/** updated by emvalac */
/* entity.c generated by valac 0.34.8, the Vala compiler
 * generated from entity.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_rect.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_pixels.h>


#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())

#define ENTITAS_TYPE_TRANSFORM (entitas_transform_get_type ())

#define SDX_MATH_TYPE_VECTOR2 (sdx_math_vector2_get_type ())
typedef struct _sdxmathVector2 sdxmathVector2;
typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _entitasTransform entitasTransform;

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _entitasBackground entitasBackground;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _entitasBullet entitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _entitasEnemy1 entitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _entitasEnemy2 entitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _entitasEnemy3 entitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _entitasExpires entitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _entitasHealth entitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _entitasHud entitasHud;

#define ENTITAS_TYPE_INDEX (entitas_index_get_type ())
typedef struct _entitasIndex entitasIndex;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _entitasLayer entitasLayer;

#define ENTITAS_TYPE_SOUND (entitas_sound_get_type ())
typedef struct _sdxaudioSound sdxaudioSound;
typedef struct _entitasSound entitasSound;

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef sdxgraphicsSprite sdxgraphicsSpriteTextSprite;
typedef struct _entitasText entitasText;

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _entitasTint entitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _entitasTween entitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _entitasVelocity entitasVelocity;
typedef struct _entitasEntity entitasEntity;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _entitas_background_free0(var) ((var == NULL) ? NULL : (var = (entitas_background_free (var), NULL)))
#define _entitas_bullet_free0(var) ((var == NULL) ? NULL : (var = (entitas_bullet_free (var), NULL)))
#define _entitas_enemy1_free0(var) ((var == NULL) ? NULL : (var = (entitas_enemy1_free (var), NULL)))
#define _entitas_enemy2_free0(var) ((var == NULL) ? NULL : (var = (entitas_enemy2_free (var), NULL)))
#define _entitas_enemy3_free0(var) ((var == NULL) ? NULL : (var = (entitas_enemy3_free (var), NULL)))
#define _entitas_expires_free0(var) ((var == NULL) ? NULL : (var = (entitas_expires_free (var), NULL)))
#define _entitas_health_free0(var) ((var == NULL) ? NULL : (var = (entitas_health_free (var), NULL)))
#define _entitas_hud_free0(var) ((var == NULL) ? NULL : (var = (entitas_hud_free (var), NULL)))
#define _entitas_index_free0(var) ((var == NULL) ? NULL : (var = (entitas_index_free (var), NULL)))
#define _entitas_layer_free0(var) ((var == NULL) ? NULL : (var = (entitas_layer_free (var), NULL)))
#define _entitas_sound_free0(var) ((var == NULL) ? NULL : (var = (entitas_sound_free (var), NULL)))
#define _entitas_text_free0(var) ((var == NULL) ? NULL : (var = (entitas_text_free (var), NULL)))
#define _entitas_tint_free0(var) ((var == NULL) ? NULL : (var = (entitas_tint_free (var), NULL)))
#define _entitas_tween_free0(var) ((var == NULL) ? NULL : (var = (entitas_tween_free (var), NULL)))
#define _entitas_velocity_free0(var) ((var == NULL) ? NULL : (var = (entitas_velocity_free (var), NULL)))

#define SDX_GRAPHICS_TYPE_SCALE (sdx_graphics_scale_get_type ())
typedef struct _sdxgraphicsScale sdxgraphicsScale;

#define SDX_GRAPHICS_SPRITE_TYPE_KIND (sdx_graphics_sprite_kind_get_type ())

#define ENTITAS_TYPE_COMPONENTS (entitas_components_get_type ())
void sdx_audio_sound_release (sdxaudioSound* self);
void sdx_audio_sound_free (sdxaudioSound* self);
sdxaudioSound* sdx_audio_sound_retain (sdxaudioSound* self);
#define _sdx_audio_sound_release0(var) ((var == NULL) ? NULL : (var = (sdx_audio_sound_release (var), NULL)))
void sdx_graphics_sprite_release (sdxgraphicsSprite* self);
void sdx_graphics_sprite_free (sdxgraphicsSprite* self);
sdxgraphicsSprite* sdx_graphics_sprite_retain (sdxgraphicsSprite* self);
#define _sdx_graphics_sprite_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_sprite_release (var), NULL)))

struct _sdxmathVector2 {
	gfloat x;
	gfloat y;
};

struct _entitasTransform {
	sdxmathVector2* scale;
	sdxmathVector2* position;
	SDL_Rect* aabb;
	sdxgraphicsSprite* sprite;
};

struct _entitasBackground {
	gboolean active;
};

struct _entitasBullet {
	gboolean active;
};

struct _entitasEnemy1 {
	gboolean active;
};

struct _entitasEnemy2 {
	gboolean active;
};

struct _entitasEnemy3 {
	gboolean active;
};

struct _entitasExpires {
	gfloat value;
};

struct _entitasHealth {
	gfloat current;
	gfloat maximum;
};

struct _entitasHud {
	gboolean active;
};

struct _entitasIndex {
	gint value;
	gint limit;
	gboolean vertical;
};

struct _entitasLayer {
	gint value;
};

struct _entitasSound {
	sdxaudioSound* sound;
};

struct _entitasText {
	gchar* text;
	sdxgraphicsSpriteTextSprite* sprite;
};

struct _entitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _entitasTween {
	gfloat min;
	gfloat max;
	gfloat speed;
	gboolean repeat;
	gboolean active;
};

struct _entitasVelocity {
	gfloat x;
	gfloat y;
};

struct _entitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	entitasTransform transform;
	entitasBackground* background;
	entitasBullet* bullet;
	entitasEnemy1* enemy1;
	entitasEnemy2* enemy2;
	entitasEnemy3* enemy3;
	entitasExpires* expires;
	entitasHealth* health;
	entitasHud* hud;
	entitasIndex* index;
	entitasLayer* layer;
	entitasSound* sound;
	entitasText* text;
	entitasTint* tint;
	entitasTween* tween;
	entitasVelocity* velocity;
};

struct _sdxgraphicsScale {
	gfloat x;
	gfloat y;
};

typedef enum  {
	SDX_GRAPHICS_SPRITE_KIND_AnimatedSprite,
	SDX_GRAPHICS_SPRITE_KIND_TextureSprite,
	SDX_GRAPHICS_SPRITE_KIND_AtlasSprite,
	SDX_GRAPHICS_SPRITE_KIND_CompositeSprite,
	SDX_GRAPHICS_SPRITE_KIND_TextSprite
} sdxgraphicsSpriteKind;

struct _sdxgraphicsSprite {
	gint _retainCount;
	gint id;
	SDL_Texture* texture;
	gint width;
	gint height;
	gint x;
	gint y;
	gint index;
	gint frame;
	sdxgraphicsScale scale;
	SDL_Color color;
	gboolean centered;
	gint layer;
	gchar* path;
	sdxgraphicsSpriteKind kind;
};

typedef enum  {
	ENTITAS_COMPONENTS_UnknownComponent,
	ENTITAS_COMPONENTS_BackgroundComponent,
	ENTITAS_COMPONENTS_BulletComponent,
	ENTITAS_COMPONENTS_Enemy1Component,
	ENTITAS_COMPONENTS_Enemy2Component,
	ENTITAS_COMPONENTS_Enemy3Component,
	ENTITAS_COMPONENTS_ExpiresComponent,
	ENTITAS_COMPONENTS_HealthComponent,
	ENTITAS_COMPONENTS_HudComponent,
	ENTITAS_COMPONENTS_IndexComponent,
	ENTITAS_COMPONENTS_LayerComponent,
	ENTITAS_COMPONENTS_SoundComponent,
	ENTITAS_COMPONENTS_TextComponent,
	ENTITAS_COMPONENTS_TintComponent,
	ENTITAS_COMPONENTS_TweenComponent,
	ENTITAS_COMPONENTS_VelocityComponent
} entitasComponents;

typedef enum  {
	ENTITAS_EXCEPTION_EntityIsNotEnabled,
	ENTITAS_EXCEPTION_EntityAlreadyHasComponent,
	ENTITAS_EXCEPTION_EntityDoesNotHaveComponent,
	ENTITAS_EXCEPTION_InvalidMatcherExpression,
	ENTITAS_EXCEPTION_EntityIsAlreadyReleased,
	ENTITAS_EXCEPTION_SingleEntity,
	ENTITAS_EXCEPTION_WorldDoesNotContainEntity
} entitasException;
#define ENTITAS_EXCEPTION entitas_exception_quark ()


GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_transform_get_type (void) G_GNUC_CONST;
GType sdx_math_vector2_get_type (void) G_GNUC_CONST;
sdxmathVector2* sdx_math_vector2_dup (const sdxmathVector2* self);
void sdx_math_vector2_free (sdxmathVector2* self);
void sdx_graphics_sprite_free (sdxgraphicsSprite* self);
entitasTransform* entitas_transform_dup (const entitasTransform* self);
void entitas_transform_free (entitasTransform* self);
void entitas_transform_copy (const entitasTransform* self, entitasTransform* dest);
void entitas_transform_destroy (entitasTransform* self);
GType entitas_background_get_type (void) G_GNUC_CONST;
entitasBackground* entitas_background_dup (const entitasBackground* self);
void entitas_background_free (entitasBackground* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
entitasBullet* entitas_bullet_dup (const entitasBullet* self);
void entitas_bullet_free (entitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self);
void entitas_enemy1_free (entitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self);
void entitas_enemy2_free (entitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self);
void entitas_enemy3_free (entitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
entitasExpires* entitas_expires_dup (const entitasExpires* self);
void entitas_expires_free (entitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
entitasHealth* entitas_health_dup (const entitasHealth* self);
void entitas_health_free (entitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
entitasHud* entitas_hud_dup (const entitasHud* self);
void entitas_hud_free (entitasHud* self);
GType entitas_index_get_type (void) G_GNUC_CONST;
entitasIndex* entitas_index_dup (const entitasIndex* self);
void entitas_index_free (entitasIndex* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
entitasLayer* entitas_layer_dup (const entitasLayer* self);
void entitas_layer_free (entitasLayer* self);
GType entitas_sound_get_type (void) G_GNUC_CONST;
void sdx_audio_sound_free (sdxaudioSound* self);
entitasSound* entitas_sound_dup (const entitasSound* self);
void entitas_sound_free (entitasSound* self);
void entitas_sound_copy (const entitasSound* self, entitasSound* dest);
void entitas_sound_destroy (entitasSound* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
entitasText* entitas_text_dup (const entitasText* self);
void entitas_text_free (entitasText* self);
void entitas_text_copy (const entitasText* self, entitasText* dest);
void entitas_text_destroy (entitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
entitasTint* entitas_tint_dup (const entitasTint* self);
void entitas_tint_free (entitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
entitasTween* entitas_tween_dup (const entitasTween* self);
void entitas_tween_free (entitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
entitasVelocity* entitas_velocity_dup (const entitasVelocity* self);
void entitas_velocity_free (entitasVelocity* self);
entitasEntity* entitas_entity_dup (const entitasEntity* self);
void entitas_entity_free (entitasEntity* self);
void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest);
void entitas_entity_destroy (entitasEntity* self);
gboolean entitas_entity_hasAnyComponent (entitasEntity *self, gint* indices, int indices_length1);
gboolean entitas_entity_hasComponent (entitasEntity *self, gint index);
gboolean entitas_entity_hasComponents (entitasEntity *self, gint* indices, int indices_length1);
gboolean entitas_entity_isActive (entitasEntity *self);
#define ENTITAS_ACTIVE ((guint64) 0x8000000000000000LL)
entitasEntity* entitas_entity_setId (entitasEntity *self, gint id);
entitasEntity* entitas_entity_setName (entitasEntity *self, const gchar* name);
entitasEntity* entitas_entity_setActive (entitasEntity *self, gboolean active);
entitasEntity* entitas_entity_setBounds (entitasEntity *self, gint x, gint y, gint w, gint h);
entitasEntity* entitas_entity_setPool (entitasEntity *self, gint pool);
entitasEntity* entitas_entity_setPosition (entitasEntity *self, gfloat x, gfloat y);
GType sdx_graphics_scale_get_type (void) G_GNUC_CONST;
sdxgraphicsScale* sdx_graphics_scale_dup (const sdxgraphicsScale* self);
void sdx_graphics_scale_free (sdxgraphicsScale* self);
GType sdx_graphics_sprite_kind_get_type (void) G_GNUC_CONST;
entitasEntity* entitas_entity_setScale (entitasEntity *self, gfloat x, gfloat y);
entitasEntity* entitas_entity_setTransform (entitasEntity *self, sdxgraphicsSprite* sprite);
void entitas_transform_init (entitasTransform *self, sdxgraphicsSprite* sprite);
gchar* entitas_entity_toString (entitasEntity *self);
entitasEntity* entitas_entity_setBackground (entitasEntity *self, gboolean value);
#define ENTITAS_BACKGROUND ((guint64) 0x00001)
gboolean entitas_entity_isBackground (entitasEntity *self);
entitasEntity* entitas_entity_setBullet (entitasEntity *self, gboolean value);
#define ENTITAS_BULLET ((guint64) 0x00002)
GType entitas_components_get_type (void) G_GNUC_CONST;
void entitas_world_onComponentAdded (entitasEntity* e, entitasComponents c);
void entitas_world_onComponentRemoved (entitasEntity* e, entitasComponents c);
gboolean entitas_entity_isBullet (entitasEntity *self);
entitasEntity* entitas_entity_setEnemy1 (entitasEntity *self, gboolean value);
#define ENTITAS_ENEMY1 ((guint64) 0x00004)
gboolean entitas_entity_isEnemy1 (entitasEntity *self);
entitasEntity* entitas_entity_setEnemy2 (entitasEntity *self, gboolean value);
#define ENTITAS_ENEMY2 ((guint64) 0x00008)
gboolean entitas_entity_isEnemy2 (entitasEntity *self);
entitasEntity* entitas_entity_setEnemy3 (entitasEntity *self, gboolean value);
#define ENTITAS_ENEMY3 ((guint64) 0x00010)
gboolean entitas_entity_isEnemy3 (entitasEntity *self);
gboolean entitas_entity_hasExpires (entitasEntity *self);
#define ENTITAS_EXPIRES ((guint64) 0x00020)
entitasEntity* entitas_entity_addExpires (entitasEntity *self, gfloat value);
GQuark entitas_exception_quark (void);
entitasEntity* entitas_entity_setExpires (entitasEntity *self, gfloat value);
entitasEntity* entitas_entity_removeExpires (entitasEntity *self);
gboolean entitas_entity_hasHealth (entitasEntity *self);
#define ENTITAS_HEALTH ((guint64) 0x00040)
entitasEntity* entitas_entity_addHealth (entitasEntity *self, gfloat current, gfloat maximum);
entitasEntity* entitas_entity_setHealth (entitasEntity *self, gfloat current, gfloat maximum);
entitasEntity* entitas_entity_removeHealth (entitasEntity *self);
entitasEntity* entitas_entity_setHud (entitasEntity *self, gboolean value);
#define ENTITAS_HUD ((guint64) 0x00080)
gboolean entitas_entity_isHud (entitasEntity *self);
gboolean entitas_entity_hasIndex (entitasEntity *self);
#define ENTITAS_INDEX ((guint64) 0x00100)
entitasEntity* entitas_entity_addIndex (entitasEntity *self, gint value, gint limit, gboolean vertical);
entitasEntity* entitas_entity_setIndex (entitasEntity *self, gint value, gint limit, gboolean vertical);
entitasEntity* entitas_entity_removeIndex (entitasEntity *self);
gboolean entitas_entity_hasLayer (entitasEntity *self);
#define ENTITAS_LAYER ((guint64) 0x00200)
entitasEntity* entitas_entity_addLayer (entitasEntity *self, gint value);
entitasEntity* entitas_entity_setLayer (entitasEntity *self, gint value);
entitasEntity* entitas_entity_removeLayer (entitasEntity *self);
gboolean entitas_entity_hasSound (entitasEntity *self);
#define ENTITAS_SOUND ((guint64) 0x00400)
entitasEntity* entitas_entity_addSound (entitasEntity *self, sdxaudioSound* sound);
entitasEntity* entitas_entity_setSound (entitasEntity *self, sdxaudioSound* sound);
entitasEntity* entitas_entity_removeSound (entitasEntity *self);
gboolean entitas_entity_hasText (entitasEntity *self);
#define ENTITAS_TEXT ((guint64) 0x00800)
entitasEntity* entitas_entity_addText (entitasEntity *self, const gchar* text, sdxgraphicsSpriteTextSprite* texture);
entitasEntity* entitas_entity_setText (entitasEntity *self, const gchar* text, sdxgraphicsSpriteTextSprite* texture);
entitasEntity* entitas_entity_removeText (entitasEntity *self);
gboolean entitas_entity_hasTint (entitasEntity *self);
#define ENTITAS_TINT ((guint64) 0x01000)
entitasEntity* entitas_entity_addTint (entitasEntity *self, gint r, gint g, gint b, gint a);
entitasEntity* entitas_entity_setTint (entitasEntity *self, gint r, gint g, gint b, gint a);
entitasEntity* entitas_entity_removeTint (entitasEntity *self);
gboolean entitas_entity_hasTween (entitasEntity *self);
#define ENTITAS_TWEEN ((guint64) 0x02000)
entitasEntity* entitas_entity_addTween (entitasEntity *self, gfloat min, gfloat max, gfloat speed, gboolean repeat, gboolean active);
entitasEntity* entitas_entity_setTween (entitasEntity *self, gfloat min, gfloat max, gfloat speed, gboolean repeat, gboolean active);
entitasEntity* entitas_entity_removeTween (entitasEntity *self);
gboolean entitas_entity_hasVelocity (entitasEntity *self);
#define ENTITAS_VELOCITY ((guint64) 0x04000)
entitasEntity* entitas_entity_addVelocity (entitasEntity *self, gfloat x, gfloat y);
entitasEntity* entitas_entity_setVelocity (entitasEntity *self, gfloat x, gfloat y);
entitasEntity* entitas_entity_removeVelocity (entitasEntity *self);

extern const guint64 ENTITAS_POW2[65];
extern const gchar* ENTITAS_ComponentString[16];

gboolean entitas_entity_hasAnyComponent (entitasEntity *self, gint* indices, int indices_length1) {
	gboolean result = FALSE;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	_tmp0_ = indices;
	_tmp0__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp0_;
		index_collection_length1 = _tmp0__length1;
		for (index_it = 0; index_it < _tmp0__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				gint _tmp1_ = 0;
				guint64 _tmp2_ = 0ULL;
				guint64 _tmp3_ = 0ULL;
				_tmp1_ = index;
				_tmp2_ = ENTITAS_POW2[_tmp1_];
				_tmp3_ = (*self).mask;
				if ((_tmp2_ & _tmp3_) != ((guint64) 0)) {
					result = TRUE;
					return result;
				}
			}
		}
	}
	result = FALSE;
	return result;
}


gboolean entitas_entity_hasComponent (entitasEntity *self, gint index) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	guint64 _tmp1_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	_tmp0_ = index;
	_tmp1_ = ENTITAS_POW2[_tmp0_];
	_tmp2_ = (*self).mask;
	result = (_tmp1_ & _tmp2_) != ((guint64) 0);
	return result;
}


gboolean entitas_entity_hasComponents (entitasEntity *self, gint* indices, int indices_length1) {
	gboolean result = FALSE;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	_tmp0_ = indices;
	_tmp0__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp0_;
		index_collection_length1 = _tmp0__length1;
		for (index_it = 0; index_it < _tmp0__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				gint _tmp1_ = 0;
				guint64 _tmp2_ = 0ULL;
				guint64 _tmp3_ = 0ULL;
				_tmp1_ = index;
				_tmp2_ = ENTITAS_POW2[_tmp1_];
				_tmp3_ = (*self).mask;
				if ((_tmp2_ & _tmp3_) == ((guint64) 0)) {
					result = FALSE;
					return result;
				}
			}
		}
	}
	result = TRUE;
	return result;
}


gboolean entitas_entity_isActive (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_ACTIVE) == ENTITAS_ACTIVE;
	return result;
}


entitasEntity* entitas_entity_setId (entitasEntity *self, gint id) {
	entitasEntity* result = NULL;
	gint _tmp0_ = 0;
	_tmp0_ = id;
	(*self).id = _tmp0_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setName (entitasEntity *self, const gchar* name) {
	entitasEntity* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*self).name);
	(*self).name = _tmp1_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setActive (entitasEntity *self, gboolean active) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	_tmp0_ = (*self).mask;
	_tmp1_ = active;
	if (((_tmp0_ & ENTITAS_ACTIVE) == ENTITAS_ACTIVE) == _tmp1_) {
		result = &(*self);
		return result;
	}
	_tmp2_ = active;
	if (_tmp2_) {
		guint64 _tmp3_ = 0ULL;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_ACTIVE;
	} else {
		guint64 _tmp4_ = 0ULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_ACTIVE;
	}
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setBounds (entitasEntity *self, gint x, gint y, gint w, gint h) {
	entitasEntity* result = NULL;
	entitasTransform _tmp0_ = {0};
	SDL_Rect* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	entitasTransform _tmp3_ = {0};
	SDL_Rect* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	entitasTransform _tmp6_ = {0};
	SDL_Rect* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	entitasTransform _tmp9_ = {0};
	SDL_Rect* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	_tmp0_ = (*self).transform;
	_tmp1_ = _tmp0_.aabb;
	_tmp2_ = x;
	(*_tmp1_).x = _tmp2_;
	_tmp3_ = (*self).transform;
	_tmp4_ = _tmp3_.aabb;
	_tmp5_ = y;
	(*_tmp4_).y = _tmp5_;
	_tmp6_ = (*self).transform;
	_tmp7_ = _tmp6_.aabb;
	_tmp8_ = w;
	(*_tmp7_).w = (guint) _tmp8_;
	_tmp9_ = (*self).transform;
	_tmp10_ = _tmp9_.aabb;
	_tmp11_ = h;
	(*_tmp10_).h = (guint) _tmp11_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setPool (entitasEntity *self, gint pool) {
	entitasEntity* result = NULL;
	gint _tmp0_ = 0;
	_tmp0_ = pool;
	(*self).pool = _tmp0_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setPosition (entitasEntity *self, gfloat x, gfloat y) {
	entitasEntity* result = NULL;
	entitasTransform _tmp0_ = {0};
	sdxmathVector2* _tmp1_ = NULL;
	gfloat _tmp2_ = 0.0F;
	entitasTransform _tmp3_ = {0};
	sdxmathVector2* _tmp4_ = NULL;
	gfloat _tmp5_ = 0.0F;
	entitasTransform _tmp6_ = {0};
	sdxgraphicsSprite* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	_tmp0_ = (*self).transform;
	_tmp1_ = _tmp0_.position;
	_tmp2_ = x;
	(*_tmp1_).x = _tmp2_;
	_tmp3_ = (*self).transform;
	_tmp4_ = _tmp3_.position;
	_tmp5_ = y;
	(*_tmp4_).y = _tmp5_;
	_tmp6_ = (*self).transform;
	_tmp7_ = _tmp6_.sprite;
	_tmp8_ = _tmp7_->centered;
	if (_tmp8_) {
		entitasTransform _tmp9_ = {0};
		SDL_Rect* _tmp10_ = NULL;
		gfloat _tmp11_ = 0.0F;
		entitasTransform _tmp12_ = {0};
		SDL_Rect* _tmp13_ = NULL;
		guint _tmp14_ = 0U;
		entitasTransform _tmp15_ = {0};
		SDL_Rect* _tmp16_ = NULL;
		gfloat _tmp17_ = 0.0F;
		entitasTransform _tmp18_ = {0};
		SDL_Rect* _tmp19_ = NULL;
		guint _tmp20_ = 0U;
		_tmp9_ = (*self).transform;
		_tmp10_ = _tmp9_.aabb;
		_tmp11_ = x;
		_tmp12_ = (*self).transform;
		_tmp13_ = _tmp12_.aabb;
		_tmp14_ = (*_tmp13_).w;
		(*_tmp10_).x = (gint) (_tmp11_ - (_tmp14_ / 2));
		_tmp15_ = (*self).transform;
		_tmp16_ = _tmp15_.aabb;
		_tmp17_ = y;
		_tmp18_ = (*self).transform;
		_tmp19_ = _tmp18_.aabb;
		_tmp20_ = (*_tmp19_).h;
		(*_tmp16_).y = (gint) (_tmp17_ - (_tmp20_ / 2));
	} else {
		entitasTransform _tmp21_ = {0};
		SDL_Rect* _tmp22_ = NULL;
		gfloat _tmp23_ = 0.0F;
		entitasTransform _tmp24_ = {0};
		SDL_Rect* _tmp25_ = NULL;
		gfloat _tmp26_ = 0.0F;
		_tmp21_ = (*self).transform;
		_tmp22_ = _tmp21_.aabb;
		_tmp23_ = x;
		(*_tmp22_).x = (gint) _tmp23_;
		_tmp24_ = (*self).transform;
		_tmp25_ = _tmp24_.aabb;
		_tmp26_ = y;
		(*_tmp25_).y = (gint) _tmp26_;
	}
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setScale (entitasEntity *self, gfloat x, gfloat y) {
	entitasEntity* result = NULL;
	entitasTransform _tmp0_ = {0};
	sdxmathVector2* _tmp1_ = NULL;
	gfloat _tmp2_ = 0.0F;
	entitasTransform _tmp3_ = {0};
	sdxmathVector2* _tmp4_ = NULL;
	gfloat _tmp5_ = 0.0F;
	_tmp0_ = (*self).transform;
	_tmp1_ = _tmp0_.scale;
	_tmp2_ = x;
	(*_tmp1_).x = _tmp2_;
	_tmp3_ = (*self).transform;
	_tmp4_ = _tmp3_.scale;
	_tmp5_ = y;
	(*_tmp4_).y = _tmp5_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setTransform (entitasEntity *self, sdxgraphicsSprite* sprite) {
	entitasEntity* result = NULL;
	sdxgraphicsSprite* _tmp0_ = NULL;
	g_return_val_if_fail (sprite != NULL, NULL);
	_tmp0_ = sprite;
	entitas_transform_destroy (&(*self).transform);
	entitas_transform_init (&(*self).transform, _tmp0_);
	result = &(*self);
	return result;
}


gchar* entitas_entity_toString (entitasEntity *self) {
	gchar* result = NULL;
	gchar* sb = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gboolean seperator = FALSE;
	_tmp0_ = g_strdup ("");
	sb = _tmp0_;
	_tmp1_ = sb;
	_tmp2_ = (*self).id;
	_tmp3_ = g_strdup_printf ("%i", _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat (_tmp1_, _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strconcat (_tmp6_, "(", NULL);
	_tmp8_ = _tmp7_;
	_tmp9_ = (*self).name;
	_tmp10_ = g_strconcat (_tmp8_, _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, ")", NULL);
	_g_free0 (sb);
	sb = _tmp12_;
	_g_free0 (_tmp11_);
	_g_free0 (_tmp8_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	seperator = FALSE;
	{
		gint i = 0;
		i = 1;
		{
			gboolean _tmp13_ = FALSE;
			_tmp13_ = TRUE;
			while (TRUE) {
				gint _tmp15_ = 0;
				gint _tmp16_ = 0;
				gboolean _tmp17_ = FALSE;
				if (!_tmp13_) {
					gint _tmp14_ = 0;
					_tmp14_ = i;
					i = _tmp14_ + 1;
				}
				_tmp13_ = FALSE;
				_tmp15_ = i;
				if (!(_tmp15_ <= G_N_ELEMENTS (ENTITAS_ComponentString))) {
					break;
				}
				_tmp16_ = i;
				_tmp17_ = entitas_entity_hasComponent (&(*self), _tmp16_);
				if (_tmp17_) {
					gboolean _tmp18_ = FALSE;
					const gchar* _tmp21_ = NULL;
					gint _tmp22_ = 0;
					const gchar* _tmp23_ = NULL;
					gchar* _tmp24_ = NULL;
					_tmp18_ = seperator;
					if (_tmp18_) {
						const gchar* _tmp19_ = NULL;
						gchar* _tmp20_ = NULL;
						_tmp19_ = sb;
						_tmp20_ = g_strconcat (_tmp19_, ", ", NULL);
						_g_free0 (sb);
						sb = _tmp20_;
					}
					_tmp21_ = sb;
					_tmp22_ = i;
					_tmp23_ = ENTITAS_ComponentString[_tmp22_];
					_tmp24_ = g_strconcat (_tmp21_, _tmp23_, NULL);
					_g_free0 (sb);
					sb = _tmp24_;
					seperator = TRUE;
				}
			}
		}
	}
	result = sb;
	return result;
}


/**
 * Components:
 */
static gpointer _entitas_background_dup0 (gpointer self) {
	return self ? entitas_background_dup (self) : NULL;
}


entitasEntity* entitas_entity_setBackground (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasBackground _tmp1_ = {0};
		entitasBackground* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_background_dup0 (&_tmp1_);
		_entitas_background_free0 ((*self).background);
		(*self).background = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_BACKGROUND;
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_background_free0 ((*self).background);
		(*self).background = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_BACKGROUND;
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isBackground (entitasEntity *self) {
	gboolean result = FALSE;
	entitasBackground* _tmp0_ = NULL;
	_tmp0_ = (*self).background;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		result = TRUE;
		return result;
	}
}


static gpointer _entitas_bullet_dup0 (gpointer self) {
	return self ? entitas_bullet_dup (self) : NULL;
}


entitasEntity* entitas_entity_setBullet (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasBullet _tmp1_ = {0};
		entitasBullet* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_bullet_dup0 (&_tmp1_);
		_entitas_bullet_free0 ((*self).bullet);
		(*self).bullet = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_BULLET;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_BulletComponent);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_bullet_free0 ((*self).bullet);
		(*self).bullet = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_BULLET;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_BulletComponent);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isBullet (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_BULLET) != ((guint64) 0);
	return result;
}


static gpointer _entitas_enemy1_dup0 (gpointer self) {
	return self ? entitas_enemy1_dup (self) : NULL;
}


entitasEntity* entitas_entity_setEnemy1 (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasEnemy1 _tmp1_ = {0};
		entitasEnemy1* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_enemy1_dup0 (&_tmp1_);
		_entitas_enemy1_free0 ((*self).enemy1);
		(*self).enemy1 = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_ENEMY1;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_Enemy1Component);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_enemy1_free0 ((*self).enemy1);
		(*self).enemy1 = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_ENEMY1;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_Enemy1Component);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isEnemy1 (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_ENEMY1) != ((guint64) 0);
	return result;
}


static gpointer _entitas_enemy2_dup0 (gpointer self) {
	return self ? entitas_enemy2_dup (self) : NULL;
}


entitasEntity* entitas_entity_setEnemy2 (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasEnemy2 _tmp1_ = {0};
		entitasEnemy2* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_enemy2_dup0 (&_tmp1_);
		_entitas_enemy2_free0 ((*self).enemy2);
		(*self).enemy2 = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_ENEMY2;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_Enemy2Component);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_enemy2_free0 ((*self).enemy2);
		(*self).enemy2 = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_ENEMY2;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_Enemy2Component);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isEnemy2 (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_ENEMY2) != ((guint64) 0);
	return result;
}


static gpointer _entitas_enemy3_dup0 (gpointer self) {
	return self ? entitas_enemy3_dup (self) : NULL;
}


entitasEntity* entitas_entity_setEnemy3 (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasEnemy3 _tmp1_ = {0};
		entitasEnemy3* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_enemy3_dup0 (&_tmp1_);
		_entitas_enemy3_free0 ((*self).enemy3);
		(*self).enemy3 = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_ENEMY3;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_Enemy3Component);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_enemy3_free0 ((*self).enemy3);
		(*self).enemy3 = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_ENEMY3;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_Enemy3Component);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isEnemy3 (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_ENEMY3) != ((guint64) 0);
	return result;
}


gboolean entitas_entity_hasExpires (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_EXPIRES) != ((guint64) 0);
	return result;
}


static gpointer _entitas_expires_dup0 (gpointer self) {
	return self ? entitas_expires_dup (self) : NULL;
}


entitasEntity* entitas_entity_addExpires (entitasEntity *self, gfloat value) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gfloat _tmp2_ = 0.0F;
	entitasExpires _tmp3_ = {0};
	entitasExpires* _tmp4_ = NULL;
	guint64 _tmp5_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_EXPIRES) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Expires");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = value;
	_tmp3_.value = _tmp2_;
	_tmp4_ = _entitas_expires_dup0 (&_tmp3_);
	_entitas_expires_free0 ((*self).expires);
	(*self).expires = _tmp4_;
	_tmp5_ = (*self).mask;
	(*self).mask = _tmp5_ | ENTITAS_EXPIRES;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_ExpiresComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setExpires (entitasEntity *self, gfloat value) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasExpires* _tmp2_ = NULL;
	gfloat _tmp3_ = 0.0F;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_EXPIRES) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Expires");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).expires;
	_tmp3_ = value;
	(*_tmp2_).value = _tmp3_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeExpires (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_EXPIRES) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Expires");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_expires_free0 ((*self).expires);
	(*self).expires = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_EXPIRES;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_ExpiresComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasHealth (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_HEALTH) != ((guint64) 0);
	return result;
}


static gpointer _entitas_health_dup0 (gpointer self) {
	return self ? entitas_health_dup (self) : NULL;
}


entitasEntity* entitas_entity_addHealth (entitasEntity *self, gfloat current, gfloat maximum) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gfloat _tmp2_ = 0.0F;
	gfloat _tmp3_ = 0.0F;
	entitasHealth _tmp4_ = {0};
	entitasHealth* _tmp5_ = NULL;
	guint64 _tmp6_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_HEALTH) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Health");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = current;
	_tmp3_ = maximum;
	_tmp4_.current = _tmp2_;
	_tmp4_.maximum = _tmp3_;
	_tmp5_ = _entitas_health_dup0 (&_tmp4_);
	_entitas_health_free0 ((*self).health);
	(*self).health = _tmp5_;
	_tmp6_ = (*self).mask;
	(*self).mask = _tmp6_ | ENTITAS_HEALTH;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_HealthComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setHealth (entitasEntity *self, gfloat current, gfloat maximum) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasHealth* _tmp2_ = NULL;
	gfloat _tmp3_ = 0.0F;
	entitasHealth* _tmp4_ = NULL;
	gfloat _tmp5_ = 0.0F;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_HEALTH) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Health");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).health;
	_tmp3_ = current;
	(*_tmp2_).current = _tmp3_;
	_tmp4_ = (*self).health;
	_tmp5_ = maximum;
	(*_tmp4_).maximum = _tmp5_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeHealth (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_HEALTH) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Health");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_health_free0 ((*self).health);
	(*self).health = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_HEALTH;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_HealthComponent);
	result = &(*self);
	return result;
}


static gpointer _entitas_hud_dup0 (gpointer self) {
	return self ? entitas_hud_dup (self) : NULL;
}


entitasEntity* entitas_entity_setHud (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasHud _tmp1_ = {0};
		entitasHud* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_hud_dup0 (&_tmp1_);
		_entitas_hud_free0 ((*self).hud);
		(*self).hud = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_HUD;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_HudComponent);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_hud_free0 ((*self).hud);
		(*self).hud = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_HUD;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_HudComponent);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isHud (entitasEntity *self) {
	gboolean result = FALSE;
	entitasHud* _tmp0_ = NULL;
	_tmp0_ = (*self).hud;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		result = TRUE;
		return result;
	}
}


gboolean entitas_entity_hasIndex (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_INDEX) != ((guint64) 0);
	return result;
}


static gpointer _entitas_index_dup0 (gpointer self) {
	return self ? entitas_index_dup (self) : NULL;
}


entitasEntity* entitas_entity_addIndex (entitasEntity *self, gint value, gint limit, gboolean vertical) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gboolean _tmp4_ = FALSE;
	entitasIndex _tmp5_ = {0};
	entitasIndex* _tmp6_ = NULL;
	guint64 _tmp7_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_INDEX) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Index");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = value;
	_tmp3_ = limit;
	_tmp4_ = vertical;
	_tmp5_.value = _tmp2_;
	_tmp5_.limit = _tmp3_;
	_tmp5_.vertical = _tmp4_;
	_tmp6_ = _entitas_index_dup0 (&_tmp5_);
	_entitas_index_free0 ((*self).index);
	(*self).index = _tmp6_;
	_tmp7_ = (*self).mask;
	(*self).mask = _tmp7_ | ENTITAS_INDEX;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_IndexComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setIndex (entitasEntity *self, gint value, gint limit, gboolean vertical) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasIndex* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	entitasIndex* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	entitasIndex* _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_INDEX) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Index");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).index;
	_tmp3_ = value;
	(*_tmp2_).value = _tmp3_;
	_tmp4_ = (*self).index;
	_tmp5_ = value;
	(*_tmp4_).limit = _tmp5_;
	_tmp6_ = (*self).index;
	_tmp7_ = vertical;
	(*_tmp6_).vertical = _tmp7_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeIndex (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_INDEX) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Index");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_index_free0 ((*self).index);
	(*self).index = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_INDEX;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_IndexComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasLayer (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_LAYER) != ((guint64) 0);
	return result;
}


static gpointer _entitas_layer_dup0 (gpointer self) {
	return self ? entitas_layer_dup (self) : NULL;
}


entitasEntity* entitas_entity_addLayer (entitasEntity *self, gint value) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gint _tmp2_ = 0;
	entitasLayer _tmp3_ = {0};
	entitasLayer* _tmp4_ = NULL;
	guint64 _tmp5_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_LAYER) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Layer");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = value;
	_tmp3_.value = _tmp2_;
	_tmp4_ = _entitas_layer_dup0 (&_tmp3_);
	_entitas_layer_free0 ((*self).layer);
	(*self).layer = _tmp4_;
	_tmp5_ = (*self).mask;
	(*self).mask = _tmp5_ | ENTITAS_LAYER;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_LayerComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setLayer (entitasEntity *self, gint value) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasLayer* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_LAYER) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Layer");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).layer;
	_tmp3_ = value;
	(*_tmp2_).value = _tmp3_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeLayer (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_LAYER) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Layer");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_layer_free0 ((*self).layer);
	(*self).layer = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_LAYER;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_LayerComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasSound (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_SOUND) != ((guint64) 0);
	return result;
}


static gpointer _sdx_audio_sound_retain0 (gpointer self) {
	return self ? sdx_audio_sound_retain (self) : NULL;
}


static gpointer _entitas_sound_dup0 (gpointer self) {
	return self ? entitas_sound_dup (self) : NULL;
}


entitasEntity* entitas_entity_addSound (entitasEntity *self, sdxaudioSound* sound) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	sdxaudioSound* _tmp2_ = NULL;
	sdxaudioSound* _tmp3_ = NULL;
	entitasSound _tmp4_ = {0};
	entitasSound _tmp5_ = {0};
	entitasSound* _tmp6_ = NULL;
	guint64 _tmp7_ = 0ULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (sound != NULL, NULL);
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SOUND) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Sound");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = sound;
	_tmp3_ = _sdx_audio_sound_retain0 (_tmp2_);
	_sdx_audio_sound_release0 (_tmp4_.sound);
	_tmp4_.sound = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp6_ = _entitas_sound_dup0 (&_tmp5_);
	_entitas_sound_free0 ((*self).sound);
	(*self).sound = _tmp6_;
	entitas_sound_destroy (&_tmp5_);
	_tmp7_ = (*self).mask;
	(*self).mask = _tmp7_ | ENTITAS_SOUND;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_SoundComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setSound (entitasEntity *self, sdxaudioSound* sound) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasSound* _tmp2_ = NULL;
	sdxaudioSound* _tmp3_ = NULL;
	sdxaudioSound* _tmp4_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (sound != NULL, NULL);
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SOUND) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Sound");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).sound;
	_tmp3_ = sound;
	_tmp4_ = _sdx_audio_sound_retain0 (_tmp3_);
	_sdx_audio_sound_release0 ((*_tmp2_).sound);
	(*_tmp2_).sound = _tmp4_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeSound (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SOUND) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Sound");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_sound_free0 ((*self).sound);
	(*self).sound = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_SOUND;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_SoundComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasText (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_TEXT) != ((guint64) 0);
	return result;
}


static gpointer _sdx_graphics_sprite_retain0 (gpointer self) {
	return self ? sdx_graphics_sprite_retain (self) : NULL;
}


static gpointer _entitas_text_dup0 (gpointer self) {
	return self ? entitas_text_dup (self) : NULL;
}


entitasEntity* entitas_entity_addText (entitasEntity *self, const gchar* text, sdxgraphicsSpriteTextSprite* texture) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp4_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp5_ = NULL;
	entitasText _tmp6_ = {0};
	entitasText _tmp7_ = {0};
	entitasText* _tmp8_ = NULL;
	guint64 _tmp9_ = 0ULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (texture != NULL, NULL);
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TEXT) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Text");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = text;
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = texture;
	_tmp5_ = _sdx_graphics_sprite_retain0 (_tmp4_);
	_g_free0 (_tmp6_.text);
	_tmp6_.text = _tmp3_;
	_sdx_graphics_sprite_release0 (_tmp6_.sprite);
	_tmp6_.sprite = _tmp5_;
	_tmp7_ = _tmp6_;
	_tmp8_ = _entitas_text_dup0 (&_tmp7_);
	_entitas_text_free0 ((*self).text);
	(*self).text = _tmp8_;
	entitas_text_destroy (&_tmp7_);
	_tmp9_ = (*self).mask;
	(*self).mask = _tmp9_ | ENTITAS_TEXT;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_TextComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setText (entitasEntity *self, const gchar* text, sdxgraphicsSpriteTextSprite* texture) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasText* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	entitasText* _tmp5_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp6_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp7_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (texture != NULL, NULL);
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TEXT) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Text");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).text;
	_tmp3_ = text;
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 ((*_tmp2_).text);
	(*_tmp2_).text = _tmp4_;
	_tmp5_ = (*self).text;
	_tmp6_ = texture;
	_tmp7_ = _sdx_graphics_sprite_retain0 (_tmp6_);
	_sdx_graphics_sprite_release0 ((*_tmp5_).sprite);
	(*_tmp5_).sprite = _tmp7_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeText (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TEXT) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Text");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_text_free0 ((*self).text);
	(*self).text = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_TEXT;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_TextComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasTint (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_TINT) != ((guint64) 0);
	return result;
}


static gpointer _entitas_tint_dup0 (gpointer self) {
	return self ? entitas_tint_dup (self) : NULL;
}


entitasEntity* entitas_entity_addTint (entitasEntity *self, gint r, gint g, gint b, gint a) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	entitasTint _tmp6_ = {0};
	entitasTint* _tmp7_ = NULL;
	guint64 _tmp8_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TINT) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Tint");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = r;
	_tmp3_ = g;
	_tmp4_ = b;
	_tmp5_ = a;
	_tmp6_.r = _tmp2_;
	_tmp6_.g = _tmp3_;
	_tmp6_.b = _tmp4_;
	_tmp6_.a = _tmp5_;
	_tmp7_ = _entitas_tint_dup0 (&_tmp6_);
	_entitas_tint_free0 ((*self).tint);
	(*self).tint = _tmp7_;
	_tmp8_ = (*self).mask;
	(*self).mask = _tmp8_ | ENTITAS_TINT;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_TintComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setTint (entitasEntity *self, gint r, gint g, gint b, gint a) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasTint* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	entitasTint* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	entitasTint* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	entitasTint* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TINT) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Tint");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).tint;
	_tmp3_ = r;
	(*_tmp2_).r = _tmp3_;
	_tmp4_ = (*self).tint;
	_tmp5_ = g;
	(*_tmp4_).g = _tmp5_;
	_tmp6_ = (*self).tint;
	_tmp7_ = b;
	(*_tmp6_).b = _tmp7_;
	_tmp8_ = (*self).tint;
	_tmp9_ = a;
	(*_tmp8_).a = _tmp9_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeTint (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TINT) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Tint");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_tint_free0 ((*self).tint);
	(*self).tint = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_TINT;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_TintComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasTween (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_TWEEN) != ((guint64) 0);
	return result;
}


static gpointer _entitas_tween_dup0 (gpointer self) {
	return self ? entitas_tween_dup (self) : NULL;
}


entitasEntity* entitas_entity_addTween (entitasEntity *self, gfloat min, gfloat max, gfloat speed, gboolean repeat, gboolean active) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gfloat _tmp2_ = 0.0F;
	gfloat _tmp3_ = 0.0F;
	gfloat _tmp4_ = 0.0F;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp6_ = FALSE;
	entitasTween _tmp7_ = {0};
	entitasTween* _tmp8_ = NULL;
	guint64 _tmp9_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TWEEN) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Tween");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = min;
	_tmp3_ = max;
	_tmp4_ = speed;
	_tmp5_ = repeat;
	_tmp6_ = active;
	_tmp7_.min = _tmp2_;
	_tmp7_.max = _tmp3_;
	_tmp7_.speed = _tmp4_;
	_tmp7_.repeat = _tmp5_;
	_tmp7_.active = _tmp6_;
	_tmp8_ = _entitas_tween_dup0 (&_tmp7_);
	_entitas_tween_free0 ((*self).tween);
	(*self).tween = _tmp8_;
	_tmp9_ = (*self).mask;
	(*self).mask = _tmp9_ | ENTITAS_TWEEN;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_TweenComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setTween (entitasEntity *self, gfloat min, gfloat max, gfloat speed, gboolean repeat, gboolean active) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasTween* _tmp2_ = NULL;
	gfloat _tmp3_ = 0.0F;
	entitasTween* _tmp4_ = NULL;
	gfloat _tmp5_ = 0.0F;
	entitasTween* _tmp6_ = NULL;
	gfloat _tmp7_ = 0.0F;
	entitasTween* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	entitasTween* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TWEEN) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Tween");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).tween;
	_tmp3_ = min;
	(*_tmp2_).min = _tmp3_;
	_tmp4_ = (*self).tween;
	_tmp5_ = max;
	(*_tmp4_).max = _tmp5_;
	_tmp6_ = (*self).tween;
	_tmp7_ = speed;
	(*_tmp6_).speed = _tmp7_;
	_tmp8_ = (*self).tween;
	_tmp9_ = repeat;
	(*_tmp8_).repeat = _tmp9_;
	_tmp10_ = (*self).tween;
	_tmp11_ = active;
	(*_tmp10_).active = _tmp11_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeTween (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TWEEN) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Tween");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_tween_free0 ((*self).tween);
	(*self).tween = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_TWEEN;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_TweenComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasVelocity (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_VELOCITY) != ((guint64) 0);
	return result;
}


static gpointer _entitas_velocity_dup0 (gpointer self) {
	return self ? entitas_velocity_dup (self) : NULL;
}


entitasEntity* entitas_entity_addVelocity (entitasEntity *self, gfloat x, gfloat y) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gfloat _tmp2_ = 0.0F;
	gfloat _tmp3_ = 0.0F;
	entitasVelocity _tmp4_ = {0};
	entitasVelocity* _tmp5_ = NULL;
	guint64 _tmp6_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_VELOCITY) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Velocity");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = x;
	_tmp3_ = y;
	_tmp4_.x = _tmp2_;
	_tmp4_.y = _tmp3_;
	_tmp5_ = _entitas_velocity_dup0 (&_tmp4_);
	_entitas_velocity_free0 ((*self).velocity);
	(*self).velocity = _tmp5_;
	_tmp6_ = (*self).mask;
	(*self).mask = _tmp6_ | ENTITAS_VELOCITY;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_VelocityComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setVelocity (entitasEntity *self, gfloat x, gfloat y) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasVelocity* _tmp2_ = NULL;
	gfloat _tmp3_ = 0.0F;
	entitasVelocity* _tmp4_ = NULL;
	gfloat _tmp5_ = 0.0F;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_VELOCITY) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Velocity");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).velocity;
	_tmp3_ = x;
	(*_tmp2_).x = _tmp3_;
	_tmp4_ = (*self).velocity;
	_tmp5_ = y;
	(*_tmp4_).y = _tmp5_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeVelocity (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_VELOCITY) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Velocity");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_velocity_free0 ((*self).velocity);
	(*self).velocity = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_VELOCITY;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_VelocityComponent);
	result = &(*self);
	return result;
}


void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest) {
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	guint64 _tmp4_ = 0ULL;
	entitasTransform _tmp5_ = {0};
	entitasTransform _tmp6_ = {0};
	entitasBackground* _tmp7_ = NULL;
	entitasBackground* _tmp8_ = NULL;
	entitasBullet* _tmp9_ = NULL;
	entitasBullet* _tmp10_ = NULL;
	entitasEnemy1* _tmp11_ = NULL;
	entitasEnemy1* _tmp12_ = NULL;
	entitasEnemy2* _tmp13_ = NULL;
	entitasEnemy2* _tmp14_ = NULL;
	entitasEnemy3* _tmp15_ = NULL;
	entitasEnemy3* _tmp16_ = NULL;
	entitasExpires* _tmp17_ = NULL;
	entitasExpires* _tmp18_ = NULL;
	entitasHealth* _tmp19_ = NULL;
	entitasHealth* _tmp20_ = NULL;
	entitasHud* _tmp21_ = NULL;
	entitasHud* _tmp22_ = NULL;
	entitasIndex* _tmp23_ = NULL;
	entitasIndex* _tmp24_ = NULL;
	entitasLayer* _tmp25_ = NULL;
	entitasLayer* _tmp26_ = NULL;
	entitasSound* _tmp27_ = NULL;
	entitasSound* _tmp28_ = NULL;
	entitasText* _tmp29_ = NULL;
	entitasText* _tmp30_ = NULL;
	entitasTint* _tmp31_ = NULL;
	entitasTint* _tmp32_ = NULL;
	entitasTween* _tmp33_ = NULL;
	entitasTween* _tmp34_ = NULL;
	entitasVelocity* _tmp35_ = NULL;
	entitasVelocity* _tmp36_ = NULL;
	_tmp0_ = (*self).id;
	(*dest).id = _tmp0_;
	_tmp1_ = (*self).name;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp2_;
	_tmp3_ = (*self).pool;
	(*dest).pool = _tmp3_;
	_tmp4_ = (*self).mask;
	(*dest).mask = _tmp4_;
	_tmp5_ = (*self).transform;
	entitas_transform_copy (&_tmp5_, &_tmp6_);
	entitas_transform_destroy (&(*dest).transform);
	(*dest).transform = _tmp6_;
	_tmp7_ = (*self).background;
	_tmp8_ = _entitas_background_dup0 (_tmp7_);
	_entitas_background_free0 ((*dest).background);
	(*dest).background = _tmp8_;
	_tmp9_ = (*self).bullet;
	_tmp10_ = _entitas_bullet_dup0 (_tmp9_);
	_entitas_bullet_free0 ((*dest).bullet);
	(*dest).bullet = _tmp10_;
	_tmp11_ = (*self).enemy1;
	_tmp12_ = _entitas_enemy1_dup0 (_tmp11_);
	_entitas_enemy1_free0 ((*dest).enemy1);
	(*dest).enemy1 = _tmp12_;
	_tmp13_ = (*self).enemy2;
	_tmp14_ = _entitas_enemy2_dup0 (_tmp13_);
	_entitas_enemy2_free0 ((*dest).enemy2);
	(*dest).enemy2 = _tmp14_;
	_tmp15_ = (*self).enemy3;
	_tmp16_ = _entitas_enemy3_dup0 (_tmp15_);
	_entitas_enemy3_free0 ((*dest).enemy3);
	(*dest).enemy3 = _tmp16_;
	_tmp17_ = (*self).expires;
	_tmp18_ = _entitas_expires_dup0 (_tmp17_);
	_entitas_expires_free0 ((*dest).expires);
	(*dest).expires = _tmp18_;
	_tmp19_ = (*self).health;
	_tmp20_ = _entitas_health_dup0 (_tmp19_);
	_entitas_health_free0 ((*dest).health);
	(*dest).health = _tmp20_;
	_tmp21_ = (*self).hud;
	_tmp22_ = _entitas_hud_dup0 (_tmp21_);
	_entitas_hud_free0 ((*dest).hud);
	(*dest).hud = _tmp22_;
	_tmp23_ = (*self).index;
	_tmp24_ = _entitas_index_dup0 (_tmp23_);
	_entitas_index_free0 ((*dest).index);
	(*dest).index = _tmp24_;
	_tmp25_ = (*self).layer;
	_tmp26_ = _entitas_layer_dup0 (_tmp25_);
	_entitas_layer_free0 ((*dest).layer);
	(*dest).layer = _tmp26_;
	_tmp27_ = (*self).sound;
	_tmp28_ = _entitas_sound_dup0 (_tmp27_);
	_entitas_sound_free0 ((*dest).sound);
	(*dest).sound = _tmp28_;
	_tmp29_ = (*self).text;
	_tmp30_ = _entitas_text_dup0 (_tmp29_);
	_entitas_text_free0 ((*dest).text);
	(*dest).text = _tmp30_;
	_tmp31_ = (*self).tint;
	_tmp32_ = _entitas_tint_dup0 (_tmp31_);
	_entitas_tint_free0 ((*dest).tint);
	(*dest).tint = _tmp32_;
	_tmp33_ = (*self).tween;
	_tmp34_ = _entitas_tween_dup0 (_tmp33_);
	_entitas_tween_free0 ((*dest).tween);
	(*dest).tween = _tmp34_;
	_tmp35_ = (*self).velocity;
	_tmp36_ = _entitas_velocity_dup0 (_tmp35_);
	_entitas_velocity_free0 ((*dest).velocity);
	(*dest).velocity = _tmp36_;
}


void entitas_entity_destroy (entitasEntity* self) {
	_g_free0 ((*self).name);
	entitas_transform_destroy (&(*self).transform);
	_entitas_background_free0 ((*self).background);
	_entitas_bullet_free0 ((*self).bullet);
	_entitas_enemy1_free0 ((*self).enemy1);
	_entitas_enemy2_free0 ((*self).enemy2);
	_entitas_enemy3_free0 ((*self).enemy3);
	_entitas_expires_free0 ((*self).expires);
	_entitas_health_free0 ((*self).health);
	_entitas_hud_free0 ((*self).hud);
	_entitas_index_free0 ((*self).index);
	_entitas_layer_free0 ((*self).layer);
	_entitas_sound_free0 ((*self).sound);
	_entitas_text_free0 ((*self).text);
	_entitas_tint_free0 ((*self).tint);
	_entitas_tween_free0 ((*self).tween);
	_entitas_velocity_free0 ((*self).velocity);
}


entitasEntity* entitas_entity_dup (const entitasEntity* self) {
	entitasEntity* dup;
	dup = g_new0 (entitasEntity, 1);
	entitas_entity_copy (self, dup);
	return dup;
}


void entitas_entity_free (entitasEntity* self) {
	entitas_entity_destroy (self);
	g_free (self);
}


GType entitas_entity_get_type (void) {
	static volatile gsize entitas_entity_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_entity_type_id__volatile)) {
		GType entitas_entity_type_id;
		entitas_entity_type_id = g_boxed_type_register_static ("entitasEntity", (GBoxedCopyFunc) entitas_entity_dup, (GBoxedFreeFunc) entitas_entity_free);
		g_once_init_leave (&entitas_entity_type_id__volatile, entitas_entity_type_id);
	}
	return entitas_entity_type_id__volatile;
}



