/** updated by emvalac */
/* Factory.c generated by valac 0.34.8, the Vala compiler
 * generated from Factory.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_rect.h>
#include <SDL2/SDL_pixels.h>
#include <stdio.h>


#define TYPE_POOL (pool_get_type ())
typedef struct _entitasWorld entitasWorld;
typedef struct _entitasGroup entitasGroup;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())

#define ENTITAS_TYPE_TRANSFORM (entitas_transform_get_type ())

#define SDX_MATH_TYPE_VECTOR2 (sdx_math_vector2_get_type ())
typedef struct _sdxmathVector2 sdxmathVector2;
typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _entitasTransform entitasTransform;

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _entitasBackground entitasBackground;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _entitasBullet entitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _entitasEnemy1 entitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _entitasEnemy2 entitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _entitasEnemy3 entitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _entitasExpires entitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _entitasHealth entitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _entitasHud entitasHud;

#define ENTITAS_TYPE_INDEX (entitas_index_get_type ())
typedef struct _entitasIndex entitasIndex;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _entitasLayer entitasLayer;

#define ENTITAS_TYPE_SOUND (entitas_sound_get_type ())
typedef struct _sdxaudioSound sdxaudioSound;
typedef struct _entitasSound entitasSound;

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef sdxgraphicsSprite sdxgraphicsSpriteTextSprite;
typedef struct _entitasText entitasText;

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _entitasTint entitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _entitasTween entitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _entitasVelocity entitasVelocity;
typedef struct _entitasEntity entitasEntity;
typedef struct _entitasEntityCache entitasEntityCache;

#define ENTITAS_TYPE_ISYSTEM (entitas_isystem_get_type ())
typedef struct _entitasISystem entitasISystem;
typedef entitasWorld Factory;
typedef struct _sdxgraphicsTextureAtlas sdxgraphicsTextureAtlas;
typedef struct _sdxfilesFileHandle sdxfilesFileHandle;
void sdx_graphics_texture_atlas_release (sdxgraphicsTextureAtlas* self);
void sdx_graphics_texture_atlas_free (sdxgraphicsTextureAtlas* self);
sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_retain (sdxgraphicsTextureAtlas* self);
#define _sdx_graphics_texture_atlas_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_texture_atlas_release (var), NULL)))
void sdx_files_file_handle_release (sdxfilesFileHandle* self);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxfilesFileHandle* sdx_files_file_handle_retain (sdxfilesFileHandle* self);
#define _sdx_files_file_handle_release0(var) ((var == NULL) ? NULL : (var = (sdx_files_file_handle_release (var), NULL)))

#define ENTITAS_TYPE_BUFFER (entitas_buffer_get_type ())
typedef struct _entitasBuffer entitasBuffer;
typedef struct _systemsDisplaySystem systemsDisplaySystem;
void sdx_graphics_sprite_release (sdxgraphicsSprite* self);
void sdx_graphics_sprite_free (sdxgraphicsSprite* self);
sdxgraphicsSprite* sdx_graphics_sprite_retain (sdxgraphicsSprite* self);
#define _sdx_graphics_sprite_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_sprite_release (var), NULL)))
typedef struct _sdxFont sdxFont;

typedef enum  {
	POOL_BACKGROUND,
	POOL_ENEMY1,
	POOL_ENEMY2,
	POOL_ENEMY3,
	POOL_PLAYER,
	POOL_BULLET,
	POOL_EXPLOSION,
	POOL_BANG,
	POOL_PARTICLE,
	POOL_HUD,
	POOL_Count
} Pool;

struct _sdxmathVector2 {
	gfloat x;
	gfloat y;
};

struct _entitasTransform {
	sdxmathVector2* scale;
	sdxmathVector2* position;
	SDL_Rect* aabb;
	sdxgraphicsSprite* sprite;
};

struct _entitasBackground {
	gboolean active;
};

struct _entitasBullet {
	gboolean active;
};

struct _entitasEnemy1 {
	gboolean active;
};

struct _entitasEnemy2 {
	gboolean active;
};

struct _entitasEnemy3 {
	gboolean active;
};

struct _entitasExpires {
	gfloat value;
};

struct _entitasHealth {
	gfloat current;
	gfloat maximum;
};

struct _entitasHud {
	gboolean active;
};

struct _entitasIndex {
	gint value;
	gint limit;
	gboolean vertical;
};

struct _entitasLayer {
	gint value;
};

struct _entitasSound {
	sdxaudioSound* sound;
};

struct _entitasText {
	gchar* text;
	sdxgraphicsSpriteTextSprite* sprite;
};

struct _entitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _entitasTween {
	gfloat min;
	gfloat max;
	gfloat speed;
	gboolean repeat;
	gboolean active;
};

struct _entitasVelocity {
	gfloat x;
	gfloat y;
};

struct _entitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	entitasTransform transform;
	entitasBackground* background;
	entitasBullet* bullet;
	entitasEnemy1* enemy1;
	entitasEnemy2* enemy2;
	entitasEnemy3* enemy3;
	entitasExpires* expires;
	entitasHealth* health;
	entitasHud* hud;
	entitasIndex* index;
	entitasLayer* layer;
	entitasSound* sound;
	entitasText* text;
	entitasTint* tint;
	entitasTween* tween;
	entitasVelocity* velocity;
};

typedef void (*entitasSystemInitialize) (void* user_data);
typedef void (*entitasSystemExecute) (gfloat delta, void* user_data);
struct _entitasISystem {
	entitasSystemInitialize initialize;
	gpointer initialize_target;
	entitasSystemExecute execute;
	gpointer execute_target;
};

typedef entitasEntity* (*entitasEntityRemovedListener) (entitasEntity* e, void* user_data);
struct _entitasWorld {
	gint _retainCount;
	GList* groups;
	entitasEntity* pool;
	gint pool_length1;
	entitasEntityCache** cache;
	gint cache_length1;
	gint id;
	entitasISystem** systems;
	gint systems_length1;
	gint count;
	entitasEntityRemovedListener entityRemoved;
	gpointer entityRemoved_target;
	GDestroyNotify entityRemoved_target_destroy_notify;
};

typedef entitasEntity* (*entitasFactory) (void* user_data);
struct _entitasBuffer {
	gint pool;
	gint size;
	entitasFactory factory;
	gpointer factory_target;
	GDestroyNotify factory_target_destroy_notify;
};


extern sdxgraphicsTextureAtlas* factory_atlas;
sdxgraphicsTextureAtlas* factory_atlas = NULL;
extern systemsDisplaySystem* systems_display_system_instance;
extern sdxFont* sdx_smallFont;

#define TAU (2.0 * G_PI)
GType pool_get_type (void) G_GNUC_CONST;
void entitas_world_free (entitasWorld* self);
void entitas_group_free (entitasGroup* self);
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_transform_get_type (void) G_GNUC_CONST;
GType sdx_math_vector2_get_type (void) G_GNUC_CONST;
sdxmathVector2* sdx_math_vector2_dup (const sdxmathVector2* self);
void sdx_math_vector2_free (sdxmathVector2* self);
void sdx_graphics_sprite_free (sdxgraphicsSprite* self);
entitasTransform* entitas_transform_dup (const entitasTransform* self);
void entitas_transform_free (entitasTransform* self);
void entitas_transform_copy (const entitasTransform* self, entitasTransform* dest);
void entitas_transform_destroy (entitasTransform* self);
GType entitas_background_get_type (void) G_GNUC_CONST;
entitasBackground* entitas_background_dup (const entitasBackground* self);
void entitas_background_free (entitasBackground* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
entitasBullet* entitas_bullet_dup (const entitasBullet* self);
void entitas_bullet_free (entitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self);
void entitas_enemy1_free (entitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self);
void entitas_enemy2_free (entitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self);
void entitas_enemy3_free (entitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
entitasExpires* entitas_expires_dup (const entitasExpires* self);
void entitas_expires_free (entitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
entitasHealth* entitas_health_dup (const entitasHealth* self);
void entitas_health_free (entitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
entitasHud* entitas_hud_dup (const entitasHud* self);
void entitas_hud_free (entitasHud* self);
GType entitas_index_get_type (void) G_GNUC_CONST;
entitasIndex* entitas_index_dup (const entitasIndex* self);
void entitas_index_free (entitasIndex* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
entitasLayer* entitas_layer_dup (const entitasLayer* self);
void entitas_layer_free (entitasLayer* self);
GType entitas_sound_get_type (void) G_GNUC_CONST;
void sdx_audio_sound_free (sdxaudioSound* self);
entitasSound* entitas_sound_dup (const entitasSound* self);
void entitas_sound_free (entitasSound* self);
void entitas_sound_copy (const entitasSound* self, entitasSound* dest);
void entitas_sound_destroy (entitasSound* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
entitasText* entitas_text_dup (const entitasText* self);
void entitas_text_free (entitasText* self);
void entitas_text_copy (const entitasText* self, entitasText* dest);
void entitas_text_destroy (entitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
entitasTint* entitas_tint_dup (const entitasTint* self);
void entitas_tint_free (entitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
entitasTween* entitas_tween_dup (const entitasTween* self);
void entitas_tween_free (entitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
entitasVelocity* entitas_velocity_dup (const entitasVelocity* self);
void entitas_velocity_free (entitasVelocity* self);
entitasEntity* entitas_entity_dup (const entitasEntity* self);
void entitas_entity_free (entitasEntity* self);
void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest);
void entitas_entity_destroy (entitasEntity* self);
void entitas_entity_cache_free (entitasEntityCache* self);
GType entitas_isystem_get_type (void) G_GNUC_CONST;
entitasISystem* entitas_isystem_dup (const entitasISystem* self);
void entitas_isystem_free (entitasISystem* self);
void sdx_graphics_texture_atlas_free (sdxgraphicsTextureAtlas* self);
Factory* factory_new (void);
entitasWorld* entitas_world_new (void);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxfilesFileHandle* sdx_files_default (const gchar* path);
sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_new (sdxfilesFileHandle* packFile, sdxfilesFileHandle* imageDir, gboolean flip);
GType entitas_buffer_get_type (void) G_GNUC_CONST;
entitasBuffer* entitas_buffer_dup (const entitasBuffer* self);
void entitas_buffer_free (entitasBuffer* self);
void entitas_buffer_copy (const entitasBuffer* self, entitasBuffer* dest);
void entitas_buffer_destroy (entitasBuffer* self);
void entitas_world_setPool (entitasWorld* self, gint size, gint count, entitasBuffer* buffers, int buffers_length1);
entitasEntity* factory_createBullet (Factory* self);
static entitasEntity* _factory_createBullet_entitas_factory (gpointer self);
void entitas_buffer_init (entitasBuffer *self, gint pool, gint size, entitasFactory factory, void* factory_target);
entitasEntity* factory_createEnemy1 (Factory* self);
static entitasEntity* _factory_createEnemy1_entitas_factory (gpointer self);
entitasEntity* factory_createEnemy2 (Factory* self);
static entitasEntity* _factory_createEnemy2_entitas_factory (gpointer self);
entitasEntity* factory_createEnemy3 (Factory* self);
static entitasEntity* _factory_createEnemy3_entitas_factory (gpointer self);
entitasEntity* factory_createExplosion (Factory* self);
static entitasEntity* _factory_createExplosion_entitas_factory (gpointer self);
entitasEntity* factory_createBang (Factory* self);
static entitasEntity* _factory_createBang_entitas_factory (gpointer self);
entitasEntity* factory_createParticle (Factory* self);
static entitasEntity* _factory_createParticle_entitas_factory (gpointer self);
static void _vala_entitasBuffer_array_free (entitasBuffer* array, gint array_length);
entitasEntity* factory_entityAdded (Factory* self, entitasEntity* e);
void systems_display_system_free (systemsDisplaySystem* self);
void systems_display_system_add (systemsDisplaySystem* self, entitasEntity* e);
entitasEntity* factory_createBase (Factory* self, const gchar* name, gint pool, gfloat scale, gboolean active, gboolean centered);
entitasEntity* entitas_world_createEntity (entitasWorld* self, const gchar* name, gint pool, gboolean active);
entitasEntity* entitas_entity_setTransform (entitasEntity *self, sdxgraphicsSprite* sprite);
sdxgraphicsSprite* sdx_graphics_texture_atlas_createSprite (sdxgraphicsTextureAtlas* self, const gchar* name, gint index);
sdxgraphicsSprite* sdx_graphics_sprite_setScale (sdxgraphicsSprite* self, gfloat x, gfloat y);
sdxgraphicsSprite* sdx_graphics_sprite_setCentered (sdxgraphicsSprite* self, gboolean value);
entitasEntity* entitas_entity_addLayer (entitasEntity *self, gint value);
entitasEntity* factory_createBackground (Factory* self);
#define SDX_pixelFactor 2
entitasEntity* entitas_entity_setBackground (entitasEntity *self, gboolean value);
entitasEntity* factory_createPlayer (Factory* self);
entitasEntity* entitas_entity_addTint (entitasEntity *self, gint r, gint g, gint b, gint a);
entitasEntity* entitas_entity_addHealth (entitasEntity *self, gfloat current, gfloat maximum);
entitasEntity* entitas_entity_addVelocity (entitasEntity *self, gfloat x, gfloat y);
entitasEntity* entitas_entity_setBullet (entitasEntity *self, gboolean value);
entitasEntity* entitas_entity_addText (entitasEntity *self, const gchar* text, sdxgraphicsSpriteTextSprite* texture);
void sdx_font_free (sdxFont* self);
sdxgraphicsSpriteTextSprite* sdx_graphics_sprite_text_sprite_new (const gchar* text, sdxFont* font, SDL_Color color);
entitasEntity* entitas_entity_setEnemy1 (entitasEntity *self, gboolean value);
entitasEntity* entitas_entity_setEnemy2 (entitasEntity *self, gboolean value);
entitasEntity* entitas_entity_setEnemy3 (entitasEntity *self, gboolean value);
entitasEntity* entitas_entity_addExpires (entitasEntity *self, gfloat value);
entitasEntity* entitas_entity_addTween (entitasEntity *self, gfloat min, gfloat max, gfloat speed, gboolean repeat, gboolean active);
entitasEntity* factory_bullet (Factory* self, gint x, gint y);
gboolean entitas_entity_cache_isEmpty (entitasEntityCache* self);
entitasEntity* entitas_entity_cache_deque (entitasEntityCache* self);
entitasEntity* entitas_entity_setPosition (entitasEntity *self, gfloat x, gfloat y);
entitasEntity* entitas_entity_setActive (entitasEntity *self, gboolean active);
entitasEntity* factory_enemy1 (Factory* self, gint x, gint y);
entitasEntity* entitas_entity_setHealth (entitasEntity *self, gfloat current, gfloat maximum);
entitasEntity* factory_enemy2 (Factory* self, gint x, gint y);
entitasEntity* factory_enemy3 (Factory* self, gint x, gint y);
entitasEntity* factory_explosion (Factory* self, gint x, gint y);
entitasEntity* entitas_entity_setBounds (entitasEntity *self, gint x, gint y, gint w, gint h);
entitasEntity* entitas_entity_setTween (entitasEntity *self, gfloat min, gfloat max, gfloat speed, gboolean repeat, gboolean active);
entitasEntity* entitas_entity_setScale (entitasEntity *self, gfloat x, gfloat y);
entitasEntity* entitas_entity_setExpires (entitasEntity *self, gfloat value);
entitasEntity* factory_bang (Factory* self, gint x, gint y);
entitasEntity* factory_particle (Factory* self, gint x, gint y);
gdouble sdx_getRandom (void);
entitasEntity* entitas_entity_setVelocity (entitasEntity *self, gfloat x, gfloat y);

extern const SDL_Color SDX_COLOR_LimeGreen;

GType pool_get_type (void) {
	static volatile gsize pool_type_id__volatile = 0;
	if (g_once_init_enter (&pool_type_id__volatile)) {
		static const GEnumValue values[] = {{POOL_BACKGROUND, "POOL_BACKGROUND", "background"}, {POOL_ENEMY1, "POOL_ENEMY1", "enemy1"}, {POOL_ENEMY2, "POOL_ENEMY2", "enemy2"}, {POOL_ENEMY3, "POOL_ENEMY3", "enemy3"}, {POOL_PLAYER, "POOL_PLAYER", "player"}, {POOL_BULLET, "POOL_BULLET", "bullet"}, {POOL_EXPLOSION, "POOL_EXPLOSION", "explosion"}, {POOL_BANG, "POOL_BANG", "bang"}, {POOL_PARTICLE, "POOL_PARTICLE", "particle"}, {POOL_HUD, "POOL_HUD", "hud"}, {POOL_Count, "POOL_Count", "count"}, {0, NULL, NULL}};
		GType pool_type_id;
		pool_type_id = g_enum_register_static ("Pool", values);
		g_once_init_leave (&pool_type_id__volatile, pool_type_id);
	}
	return pool_type_id__volatile;
}


static entitasEntity* _factory_createBullet_entitas_factory (gpointer self) {
	entitasEntity* result;
	result = factory_createBullet ((Factory*) self);
	return result;
}


static entitasEntity* _factory_createEnemy1_entitas_factory (gpointer self) {
	entitasEntity* result;
	result = factory_createEnemy1 ((Factory*) self);
	return result;
}


static entitasEntity* _factory_createEnemy2_entitas_factory (gpointer self) {
	entitasEntity* result;
	result = factory_createEnemy2 ((Factory*) self);
	return result;
}


static entitasEntity* _factory_createEnemy3_entitas_factory (gpointer self) {
	entitasEntity* result;
	result = factory_createEnemy3 ((Factory*) self);
	return result;
}


static entitasEntity* _factory_createExplosion_entitas_factory (gpointer self) {
	entitasEntity* result;
	result = factory_createExplosion ((Factory*) self);
	return result;
}


static entitasEntity* _factory_createBang_entitas_factory (gpointer self) {
	entitasEntity* result;
	result = factory_createBang ((Factory*) self);
	return result;
}


static entitasEntity* _factory_createParticle_entitas_factory (gpointer self) {
	entitasEntity* result;
	result = factory_createParticle ((Factory*) self);
	return result;
}


static void _vala_entitasBuffer_array_free (entitasBuffer* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			entitas_buffer_destroy (&array[i]);
		}
	}
	g_free (array);
}


Factory* factory_new (void) {
	Factory* self;
	sdxfilesFileHandle* _tmp0_ = NULL;
	sdxfilesFileHandle* _tmp1_ = NULL;
	sdxgraphicsTextureAtlas* _tmp2_ = NULL;
	entitasBuffer _tmp3_ = {0};
	entitasBuffer _tmp4_ = {0};
	entitasBuffer _tmp5_ = {0};
	entitasBuffer _tmp6_ = {0};
	entitasBuffer _tmp7_ = {0};
	entitasBuffer _tmp8_ = {0};
	entitasBuffer _tmp9_ = {0};
	entitasBuffer* _tmp10_ = NULL;
	entitasBuffer* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	self = (Factory*) entitas_world_new ();
	_tmp0_ = sdx_files_default ("assets/assets.atlas");
	_tmp1_ = _tmp0_;
	_tmp2_ = sdx_graphics_texture_atlas_new (_tmp1_, NULL, FALSE);
	_sdx_graphics_texture_atlas_release0 (factory_atlas);
	factory_atlas = _tmp2_;
	_sdx_files_file_handle_release0 (_tmp1_);
	entitas_buffer_init (&_tmp3_, (gint) POOL_BULLET, 20, _factory_createBullet_entitas_factory, self);
	entitas_buffer_init (&_tmp4_, (gint) POOL_ENEMY1, 15, _factory_createEnemy1_entitas_factory, self);
	entitas_buffer_init (&_tmp5_, (gint) POOL_ENEMY2, 5, _factory_createEnemy2_entitas_factory, self);
	entitas_buffer_init (&_tmp6_, (gint) POOL_ENEMY3, 4, _factory_createEnemy3_entitas_factory, self);
	entitas_buffer_init (&_tmp7_, (gint) POOL_EXPLOSION, 10, _factory_createExplosion_entitas_factory, self);
	entitas_buffer_init (&_tmp8_, (gint) POOL_BANG, 12, _factory_createBang_entitas_factory, self);
	entitas_buffer_init (&_tmp9_, (gint) POOL_PARTICLE, 100, _factory_createParticle_entitas_factory, self);
	_tmp10_ = g_new0 (entitasBuffer, 7);
	_tmp10_[0] = _tmp3_;
	_tmp10_[1] = _tmp4_;
	_tmp10_[2] = _tmp5_;
	_tmp10_[3] = _tmp6_;
	_tmp10_[4] = _tmp7_;
	_tmp10_[5] = _tmp8_;
	_tmp10_[6] = _tmp9_;
	_tmp11_ = _tmp10_;
	_tmp11__length1 = 7;
	entitas_world_setPool ((entitasWorld*) self, 256, (gint) POOL_Count, _tmp11_, 7);
	_tmp11_ = (_vala_entitasBuffer_array_free (_tmp11_, _tmp11__length1), NULL);
	return self;
}


/**
 * added to display system
 */
entitasEntity* factory_entityAdded (Factory* self, entitasEntity* e) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasTransform _tmp1_ = {0};
	sdxgraphicsSprite* _tmp2_ = NULL;
	systemsDisplaySystem* _tmp4_ = NULL;
	entitasEntity* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = e;
	_tmp1_ = (*_tmp0_).transform;
	_tmp2_ = _tmp1_.sprite;
	if (_tmp2_ == NULL) {
		entitasEntity* _tmp3_ = NULL;
		_tmp3_ = e;
		result = _tmp3_;
		return result;
	}
	_tmp4_ = systems_display_system_instance;
	_tmp5_ = e;
	systems_display_system_add (_tmp4_, _tmp5_);
	_tmp6_ = e;
	result = _tmp6_;
	return result;
}


/**
 * The stuff that all entities have
 */
entitasEntity* factory_createBase (Factory* self, const gchar* name, gint pool, gfloat scale, gboolean active, gboolean centered) {
	entitasEntity* result = NULL;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	entitasEntity* _tmp3_ = NULL;
	sdxgraphicsTextureAtlas* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	sdxgraphicsSprite* _tmp6_ = NULL;
	sdxgraphicsSprite* _tmp7_ = NULL;
	gfloat _tmp8_ = 0.0F;
	gfloat _tmp9_ = 0.0F;
	sdxgraphicsSprite* _tmp10_ = NULL;
	sdxgraphicsSprite* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	sdxgraphicsSprite* _tmp13_ = NULL;
	sdxgraphicsSprite* _tmp14_ = NULL;
	entitasEntity* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	entitasEntity* _tmp17_ = NULL;
	entitasEntity* _tmp18_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = pool;
	_tmp2_ = active;
	_tmp3_ = entitas_world_createEntity ((entitasWorld*) self, _tmp0_, _tmp1_, _tmp2_);
	_tmp4_ = factory_atlas;
	_tmp5_ = name;
	_tmp6_ = sdx_graphics_texture_atlas_createSprite (_tmp4_, _tmp5_, -1);
	_tmp7_ = _tmp6_;
	_tmp8_ = scale;
	_tmp9_ = scale;
	_tmp10_ = sdx_graphics_sprite_setScale (_tmp7_, _tmp8_, _tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = centered;
	_tmp13_ = sdx_graphics_sprite_setCentered (_tmp11_, _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = entitas_entity_setTransform (_tmp3_, _tmp14_);
	_tmp16_ = pool;
	_tmp17_ = entitas_entity_addLayer (_tmp15_, _tmp16_);
	_tmp18_ = _tmp17_;
	_sdx_graphics_sprite_release0 (_tmp14_);
	_sdx_graphics_sprite_release0 (_tmp11_);
	_sdx_graphics_sprite_release0 (_tmp7_);
	result = _tmp18_;
	return result;
}


/** 
 *	factory methods:
 */
entitasEntity* factory_createBackground (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	entitasEntity* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "background", (gint) POOL_BACKGROUND, (gfloat) (2 * SDX_pixelFactor), TRUE, FALSE);
	_tmp1_ = entitas_entity_setBackground (_tmp0_, TRUE);
	_tmp2_ = factory_entityAdded (self, _tmp1_);
	result = _tmp2_;
	return result;
}


entitasEntity* factory_createPlayer (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "spaceshipspr", (gint) POOL_PLAYER, (gfloat) (1 * SDX_pixelFactor), TRUE, TRUE);
	_tmp1_ = factory_entityAdded (self, _tmp0_);
	result = _tmp1_;
	return result;
}


entitasEntity* factory_createBullet (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	entitasEntity* _tmp2_ = NULL;
	entitasEntity* _tmp3_ = NULL;
	entitasEntity* _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "bullet", (gint) POOL_BULLET, (gfloat) (1 * SDX_pixelFactor), FALSE, TRUE);
	_tmp1_ = entitas_entity_addTint (_tmp0_, 0xd2, 0xfa, 0, 0xfa);
	_tmp2_ = entitas_entity_addHealth (_tmp1_, (gfloat) 2, (gfloat) 2);
	_tmp3_ = entitas_entity_addVelocity (_tmp2_, (gfloat) 0, (gfloat) (-800 * SDX_pixelFactor));
	_tmp4_ = entitas_entity_setBullet (_tmp3_, TRUE);
	result = _tmp4_;
	return result;
}


entitasEntity* factory_createEnemy1 (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	entitasEntity* _tmp2_ = NULL;
	sdxFont* _tmp3_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp4_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	entitasEntity* _tmp7_ = NULL;
	entitasEntity* _tmp8_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "enemy1", (gint) POOL_ENEMY1, (gfloat) (1 * SDX_pixelFactor), FALSE, TRUE);
	_tmp1_ = entitas_entity_addHealth (_tmp0_, (gfloat) 10, (gfloat) 10);
	_tmp2_ = entitas_entity_addVelocity (_tmp1_, (gfloat) 0, (gfloat) 40);
	_tmp3_ = sdx_smallFont;
	_tmp4_ = sdx_graphics_sprite_text_sprite_new ("100%", _tmp3_, SDX_COLOR_LimeGreen);
	_tmp5_ = _tmp4_;
	_tmp6_ = entitas_entity_addText (_tmp2_, "100%", _tmp5_);
	_tmp7_ = entitas_entity_setEnemy1 (_tmp6_, TRUE);
	_tmp8_ = _tmp7_;
	_sdx_graphics_sprite_release0 (_tmp5_);
	result = _tmp8_;
	return result;
}


entitasEntity* factory_createEnemy2 (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	entitasEntity* _tmp2_ = NULL;
	sdxFont* _tmp3_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp4_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	entitasEntity* _tmp7_ = NULL;
	entitasEntity* _tmp8_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "enemy2", (gint) POOL_ENEMY2, (gfloat) (1 * SDX_pixelFactor), FALSE, TRUE);
	_tmp1_ = entitas_entity_addHealth (_tmp0_, (gfloat) 20, (gfloat) 20);
	_tmp2_ = entitas_entity_addVelocity (_tmp1_, (gfloat) 0, (gfloat) 30);
	_tmp3_ = sdx_smallFont;
	_tmp4_ = sdx_graphics_sprite_text_sprite_new ("100%", _tmp3_, SDX_COLOR_LimeGreen);
	_tmp5_ = _tmp4_;
	_tmp6_ = entitas_entity_addText (_tmp2_, "100%", _tmp5_);
	_tmp7_ = entitas_entity_setEnemy2 (_tmp6_, TRUE);
	_tmp8_ = _tmp7_;
	_sdx_graphics_sprite_release0 (_tmp5_);
	result = _tmp8_;
	return result;
}


entitasEntity* factory_createEnemy3 (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	entitasEntity* _tmp2_ = NULL;
	sdxFont* _tmp3_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp4_ = NULL;
	sdxgraphicsSpriteTextSprite* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	entitasEntity* _tmp7_ = NULL;
	entitasEntity* _tmp8_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "enemy3", (gint) POOL_ENEMY3, (gfloat) (1 * SDX_pixelFactor), FALSE, TRUE);
	_tmp1_ = entitas_entity_addHealth (_tmp0_, (gfloat) 60, (gfloat) 60);
	_tmp2_ = entitas_entity_addVelocity (_tmp1_, (gfloat) 0, (gfloat) 20);
	_tmp3_ = sdx_smallFont;
	_tmp4_ = sdx_graphics_sprite_text_sprite_new ("100%", _tmp3_, SDX_COLOR_LimeGreen);
	_tmp5_ = _tmp4_;
	_tmp6_ = entitas_entity_addText (_tmp2_, "100%", _tmp5_);
	_tmp7_ = entitas_entity_setEnemy3 (_tmp6_, TRUE);
	_tmp8_ = _tmp7_;
	_sdx_graphics_sprite_release0 (_tmp5_);
	result = _tmp8_;
	return result;
}


entitasEntity* factory_createExplosion (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	entitasEntity* _tmp2_ = NULL;
	entitasEntity* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "explosion", (gint) POOL_EXPLOSION, 0.6f, FALSE, TRUE);
	_tmp1_ = entitas_entity_addTint (_tmp0_, 0xd2, 0xfa, 0xd2, 0x7f);
	_tmp2_ = entitas_entity_addExpires (_tmp1_, 0.2f);
	_tmp3_ = entitas_entity_addTween (_tmp2_, 0.006f, 0.6f, -3.f, FALSE, TRUE);
	result = _tmp3_;
	return result;
}


entitasEntity* factory_createBang (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	entitasEntity* _tmp2_ = NULL;
	entitasEntity* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "explosion", (gint) POOL_BANG, 0.1f, FALSE, TRUE);
	_tmp1_ = entitas_entity_addTint (_tmp0_, 0xd2, 0xfa, 0xd2, 0x9f);
	_tmp2_ = entitas_entity_addExpires (_tmp1_, 0.2f);
	_tmp3_ = entitas_entity_addTween (_tmp2_, 0.001f, 0.1f, -3.f, FALSE, TRUE);
	result = _tmp3_;
	return result;
}


entitasEntity* factory_createParticle (Factory* self) {
	entitasEntity* result = NULL;
	entitasEntity* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	entitasEntity* _tmp2_ = NULL;
	entitasEntity* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = factory_createBase (self, "star", (gint) POOL_PARTICLE, (gfloat) (1 * SDX_pixelFactor), FALSE, TRUE);
	_tmp1_ = entitas_entity_addTint (_tmp0_, 0xd2, 0xfa, 0xd2, 0xfa);
	_tmp2_ = entitas_entity_addExpires (_tmp1_, 0.75f);
	_tmp3_ = entitas_entity_addVelocity (_tmp2_, (gfloat) 0, (gfloat) 0);
	result = _tmp3_;
	return result;
}


/**
 * Get entity from the pool
 */
entitasEntity* factory_bullet (Factory* self, gint x, gint y) {
	entitasEntity* result = NULL;
	entitasEntityCache** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	entitasEntityCache* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	entitasEntityCache** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	entitasEntityCache* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	entitasEntity* _tmp9_ = NULL;
	entitasEntity* _tmp10_ = NULL;
	entitasEntity* _tmp11_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((entitasWorld*) self)->cache;
	_tmp0__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp1_ = _tmp0_[POOL_BULLET];
	_tmp2_ = entitas_entity_cache_isEmpty (_tmp1_);
	if (_tmp2_) {
		FILE* _tmp3_ = NULL;
		_tmp3_ = stdout;
		fprintf (_tmp3_, "out of bullets\n");
		result = NULL;
		return result;
	}
	_tmp4_ = ((entitasWorld*) self)->cache;
	_tmp4__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp5_ = _tmp4_[POOL_BULLET];
	_tmp6_ = entitas_entity_cache_deque (_tmp5_);
	_tmp7_ = x;
	_tmp8_ = y;
	_tmp9_ = entitas_entity_setPosition (_tmp6_, (gfloat) _tmp7_, (gfloat) _tmp8_);
	_tmp10_ = entitas_entity_setActive (_tmp9_, TRUE);
	_tmp11_ = factory_entityAdded (self, _tmp10_);
	result = _tmp11_;
	return result;
}


entitasEntity* factory_enemy1 (Factory* self, gint x, gint y) {
	entitasEntity* result = NULL;
	entitasEntityCache** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	entitasEntityCache* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	entitasEntityCache** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	entitasEntityCache* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	entitasEntity* _tmp9_ = NULL;
	entitasEntity* _tmp10_ = NULL;
	entitasEntity* _tmp11_ = NULL;
	entitasEntity* _tmp12_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((entitasWorld*) self)->cache;
	_tmp0__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp1_ = _tmp0_[POOL_ENEMY1];
	_tmp2_ = entitas_entity_cache_isEmpty (_tmp1_);
	if (_tmp2_) {
		FILE* _tmp3_ = NULL;
		_tmp3_ = stdout;
		fprintf (_tmp3_, "out of enemy1\n");
		result = NULL;
		return result;
	}
	_tmp4_ = ((entitasWorld*) self)->cache;
	_tmp4__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp5_ = _tmp4_[POOL_ENEMY1];
	_tmp6_ = entitas_entity_cache_deque (_tmp5_);
	_tmp7_ = x;
	_tmp8_ = y;
	_tmp9_ = entitas_entity_setPosition (_tmp6_, (gfloat) _tmp7_, (gfloat) _tmp8_);
	_tmp10_ = entitas_entity_setHealth (_tmp9_, (gfloat) 10, (gfloat) 10);
	_tmp11_ = entitas_entity_setActive (_tmp10_, TRUE);
	_tmp12_ = factory_entityAdded (self, _tmp11_);
	result = _tmp12_;
	return result;
}


entitasEntity* factory_enemy2 (Factory* self, gint x, gint y) {
	entitasEntity* result = NULL;
	entitasEntityCache** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	entitasEntityCache* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	entitasEntityCache** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	entitasEntityCache* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	entitasEntity* _tmp9_ = NULL;
	entitasEntity* _tmp10_ = NULL;
	entitasEntity* _tmp11_ = NULL;
	entitasEntity* _tmp12_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((entitasWorld*) self)->cache;
	_tmp0__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp1_ = _tmp0_[POOL_ENEMY2];
	_tmp2_ = entitas_entity_cache_isEmpty (_tmp1_);
	if (_tmp2_) {
		FILE* _tmp3_ = NULL;
		_tmp3_ = stdout;
		fprintf (_tmp3_, "out of enemy2\n");
		result = NULL;
		return result;
	}
	_tmp4_ = ((entitasWorld*) self)->cache;
	_tmp4__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp5_ = _tmp4_[POOL_ENEMY2];
	_tmp6_ = entitas_entity_cache_deque (_tmp5_);
	_tmp7_ = x;
	_tmp8_ = y;
	_tmp9_ = entitas_entity_setPosition (_tmp6_, (gfloat) _tmp7_, (gfloat) _tmp8_);
	_tmp10_ = entitas_entity_setHealth (_tmp9_, (gfloat) 20, (gfloat) 20);
	_tmp11_ = entitas_entity_setActive (_tmp10_, TRUE);
	_tmp12_ = factory_entityAdded (self, _tmp11_);
	result = _tmp12_;
	return result;
}


entitasEntity* factory_enemy3 (Factory* self, gint x, gint y) {
	entitasEntity* result = NULL;
	entitasEntityCache** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	entitasEntityCache* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	entitasEntityCache** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	entitasEntityCache* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	entitasEntity* _tmp9_ = NULL;
	entitasEntity* _tmp10_ = NULL;
	entitasEntity* _tmp11_ = NULL;
	entitasEntity* _tmp12_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((entitasWorld*) self)->cache;
	_tmp0__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp1_ = _tmp0_[POOL_ENEMY3];
	_tmp2_ = entitas_entity_cache_isEmpty (_tmp1_);
	if (_tmp2_) {
		FILE* _tmp3_ = NULL;
		_tmp3_ = stdout;
		fprintf (_tmp3_, "out of enemy3\n");
		result = NULL;
		return result;
	}
	_tmp4_ = ((entitasWorld*) self)->cache;
	_tmp4__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp5_ = _tmp4_[POOL_ENEMY3];
	_tmp6_ = entitas_entity_cache_deque (_tmp5_);
	_tmp7_ = x;
	_tmp8_ = y;
	_tmp9_ = entitas_entity_setPosition (_tmp6_, (gfloat) _tmp7_, (gfloat) _tmp8_);
	_tmp10_ = entitas_entity_setHealth (_tmp9_, (gfloat) 60, (gfloat) 60);
	_tmp11_ = entitas_entity_setActive (_tmp10_, TRUE);
	_tmp12_ = factory_entityAdded (self, _tmp11_);
	result = _tmp12_;
	return result;
}


entitasEntity* factory_explosion (Factory* self, gint x, gint y) {
	entitasEntity* result = NULL;
	entitasEntityCache** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	entitasEntityCache* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	entitasEntity* entity = NULL;
	entitasEntityCache** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	entitasEntityCache* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	entitasEntity* _tmp9_ = NULL;
	entitasTransform _tmp10_ = {0};
	SDL_Rect* _tmp11_ = NULL;
	guint _tmp12_ = 0U;
	entitasEntity* _tmp13_ = NULL;
	entitasTransform _tmp14_ = {0};
	SDL_Rect* _tmp15_ = NULL;
	guint _tmp16_ = 0U;
	entitasEntity* _tmp17_ = NULL;
	entitasEntity* _tmp18_ = NULL;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	entitasEntity* _tmp21_ = NULL;
	entitasEntity* _tmp22_ = NULL;
	entitasEntity* _tmp23_ = NULL;
	entitasEntity* _tmp24_ = NULL;
	entitasEntity* _tmp25_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((entitasWorld*) self)->cache;
	_tmp0__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp1_ = _tmp0_[POOL_EXPLOSION];
	_tmp2_ = entitas_entity_cache_isEmpty (_tmp1_);
	if (_tmp2_) {
		FILE* _tmp3_ = NULL;
		_tmp3_ = stdout;
		fprintf (_tmp3_, "out of explosions\n");
		result = NULL;
		return result;
	}
	_tmp4_ = ((entitasWorld*) self)->cache;
	_tmp4__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp5_ = _tmp4_[POOL_EXPLOSION];
	_tmp6_ = entitas_entity_cache_deque (_tmp5_);
	entity = _tmp6_;
	_tmp7_ = x;
	_tmp8_ = y;
	_tmp9_ = entity;
	_tmp10_ = (*_tmp9_).transform;
	_tmp11_ = _tmp10_.aabb;
	_tmp12_ = (*_tmp11_).w;
	_tmp13_ = entity;
	_tmp14_ = (*_tmp13_).transform;
	_tmp15_ = _tmp14_.aabb;
	_tmp16_ = (*_tmp15_).h;
	_tmp17_ = entitas_entity_setBounds (entity, _tmp7_, _tmp8_, (gint) _tmp12_, (gint) _tmp16_);
	_tmp18_ = entitas_entity_setTween (_tmp17_, 0.006f, 0.6f, -3.f, FALSE, TRUE);
	_tmp19_ = x;
	_tmp20_ = y;
	_tmp21_ = entitas_entity_setPosition (_tmp18_, (gfloat) _tmp19_, (gfloat) _tmp20_);
	_tmp22_ = entitas_entity_setScale (_tmp21_, 0.6f * SDX_pixelFactor, 0.6f * SDX_pixelFactor);
	_tmp23_ = entitas_entity_setExpires (_tmp22_, 0.2f);
	_tmp24_ = entitas_entity_setActive (_tmp23_, TRUE);
	factory_entityAdded (self, _tmp24_);
	_tmp25_ = entity;
	result = _tmp25_;
	return result;
}


entitasEntity* factory_bang (Factory* self, gint x, gint y) {
	entitasEntity* result = NULL;
	entitasEntityCache** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	entitasEntityCache* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	entitasEntity* entity = NULL;
	entitasEntityCache** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	entitasEntityCache* _tmp5_ = NULL;
	entitasEntity* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	entitasEntity* _tmp9_ = NULL;
	entitasTransform _tmp10_ = {0};
	SDL_Rect* _tmp11_ = NULL;
	guint _tmp12_ = 0U;
	entitasEntity* _tmp13_ = NULL;
	entitasTransform _tmp14_ = {0};
	SDL_Rect* _tmp15_ = NULL;
	guint _tmp16_ = 0U;
	entitasEntity* _tmp17_ = NULL;
	entitasEntity* _tmp18_ = NULL;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	entitasEntity* _tmp21_ = NULL;
	entitasEntity* _tmp22_ = NULL;
	entitasEntity* _tmp23_ = NULL;
	entitasEntity* _tmp24_ = NULL;
	entitasEntity* _tmp25_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((entitasWorld*) self)->cache;
	_tmp0__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp1_ = _tmp0_[POOL_BANG];
	_tmp2_ = entitas_entity_cache_isEmpty (_tmp1_);
	if (_tmp2_) {
		FILE* _tmp3_ = NULL;
		_tmp3_ = stdout;
		fprintf (_tmp3_, "out of bang\n");
		result = NULL;
		return result;
	}
	_tmp4_ = ((entitasWorld*) self)->cache;
	_tmp4__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp5_ = _tmp4_[POOL_BANG];
	_tmp6_ = entitas_entity_cache_deque (_tmp5_);
	entity = _tmp6_;
	_tmp7_ = x;
	_tmp8_ = y;
	_tmp9_ = entity;
	_tmp10_ = (*_tmp9_).transform;
	_tmp11_ = _tmp10_.aabb;
	_tmp12_ = (*_tmp11_).w;
	_tmp13_ = entity;
	_tmp14_ = (*_tmp13_).transform;
	_tmp15_ = _tmp14_.aabb;
	_tmp16_ = (*_tmp15_).h;
	_tmp17_ = entitas_entity_setBounds (entity, _tmp7_, _tmp8_, (gint) _tmp12_, (gint) _tmp16_);
	_tmp18_ = entitas_entity_setTween (_tmp17_, 0.003f, 0.3f, -3.f, FALSE, TRUE);
	_tmp19_ = x;
	_tmp20_ = y;
	_tmp21_ = entitas_entity_setPosition (_tmp18_, (gfloat) _tmp19_, (gfloat) _tmp20_);
	_tmp22_ = entitas_entity_setScale (_tmp21_, 0.3f * SDX_pixelFactor, 0.3f * SDX_pixelFactor);
	_tmp23_ = entitas_entity_setExpires (_tmp22_, 0.2f);
	_tmp24_ = entitas_entity_setActive (_tmp23_, TRUE);
	factory_entityAdded (self, _tmp24_);
	_tmp25_ = entity;
	result = _tmp25_;
	return result;
}


entitasEntity* factory_particle (Factory* self, gint x, gint y) {
	entitasEntity* result = NULL;
	entitasEntityCache** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	entitasEntityCache* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gdouble radians = 0.0;
	gdouble _tmp4_ = 0.0;
	gdouble magnitude = 0.0;
	gdouble _tmp5_ = 0.0;
	gdouble velocityX = 0.0;
	gdouble _tmp6_ = 0.0;
	gdouble _tmp7_ = 0.0;
	gdouble _tmp8_ = 0.0;
	gdouble velocityY = 0.0;
	gdouble _tmp9_ = 0.0;
	gdouble _tmp10_ = 0.0;
	gdouble _tmp11_ = 0.0;
	gfloat scale = 0.0F;
	gdouble _tmp12_ = 0.0;
	entitasEntity* entity = NULL;
	entitasEntityCache** _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	entitasEntityCache* _tmp14_ = NULL;
	entitasEntity* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	entitasEntity* _tmp18_ = NULL;
	entitasTransform _tmp19_ = {0};
	SDL_Rect* _tmp20_ = NULL;
	guint _tmp21_ = 0U;
	entitasEntity* _tmp22_ = NULL;
	entitasTransform _tmp23_ = {0};
	SDL_Rect* _tmp24_ = NULL;
	guint _tmp25_ = 0U;
	entitasEntity* _tmp26_ = NULL;
	gint _tmp27_ = 0;
	gint _tmp28_ = 0;
	entitasEntity* _tmp29_ = NULL;
	gfloat _tmp30_ = 0.0F;
	gfloat _tmp31_ = 0.0F;
	entitasEntity* _tmp32_ = NULL;
	gdouble _tmp33_ = 0.0;
	gdouble _tmp34_ = 0.0;
	entitasEntity* _tmp35_ = NULL;
	entitasEntity* _tmp36_ = NULL;
	entitasEntity* _tmp37_ = NULL;
	entitasEntity* _tmp38_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((entitasWorld*) self)->cache;
	_tmp0__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp1_ = _tmp0_[POOL_PARTICLE];
	_tmp2_ = entitas_entity_cache_isEmpty (_tmp1_);
	if (_tmp2_) {
		FILE* _tmp3_ = NULL;
		_tmp3_ = stdout;
		fprintf (_tmp3_, "out of particles\n");
		result = NULL;
		return result;
	}
	_tmp4_ = sdx_getRandom ();
	radians = _tmp4_ * TAU;
	_tmp5_ = sdx_getRandom ();
	magnitude = _tmp5_ * 200;
	_tmp6_ = magnitude;
	_tmp7_ = radians;
	_tmp8_ = cos (_tmp7_);
	velocityX = _tmp6_ * _tmp8_;
	_tmp9_ = magnitude;
	_tmp10_ = radians;
	_tmp11_ = sin (_tmp10_);
	velocityY = _tmp9_ * _tmp11_;
	_tmp12_ = sdx_getRandom ();
	scale = (gfloat) _tmp12_;
	_tmp13_ = ((entitasWorld*) self)->cache;
	_tmp13__length1 = ((entitasWorld*) self)->cache_length1;
	_tmp14_ = _tmp13_[POOL_PARTICLE];
	_tmp15_ = entitas_entity_cache_deque (_tmp14_);
	entity = _tmp15_;
	_tmp16_ = x;
	_tmp17_ = y;
	_tmp18_ = entity;
	_tmp19_ = (*_tmp18_).transform;
	_tmp20_ = _tmp19_.aabb;
	_tmp21_ = (*_tmp20_).w;
	_tmp22_ = entity;
	_tmp23_ = (*_tmp22_).transform;
	_tmp24_ = _tmp23_.aabb;
	_tmp25_ = (*_tmp24_).h;
	_tmp26_ = entitas_entity_setBounds (entity, _tmp16_, _tmp17_, (gint) _tmp21_, (gint) _tmp25_);
	_tmp27_ = x;
	_tmp28_ = y;
	_tmp29_ = entitas_entity_setPosition (_tmp26_, (gfloat) _tmp27_, (gfloat) _tmp28_);
	_tmp30_ = scale;
	_tmp31_ = scale;
	_tmp32_ = entitas_entity_setScale (_tmp29_, _tmp30_ * SDX_pixelFactor, _tmp31_ * SDX_pixelFactor);
	_tmp33_ = velocityX;
	_tmp34_ = velocityY;
	_tmp35_ = entitas_entity_setVelocity (_tmp32_, (gfloat) _tmp33_, (gfloat) _tmp34_);
	_tmp36_ = entitas_entity_setExpires (_tmp35_, 0.75f);
	_tmp37_ = entitas_entity_setActive (_tmp36_, TRUE);
	factory_entityAdded (self, _tmp37_);
	_tmp38_ = entity;
	result = _tmp38_;
	return result;
}



