/** updated by adriac */
/* Sprite.c generated by valac 0.34.9, the Vala compiler
 * generated from Sprite.vala, do not modify */

/* ******************************************************************************
 * Copyright 2017 darkoverlordofdata.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_render.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_pixels.h>
#include <SDL2/SDL_rect.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_surface.h>
#include <SDL2/SDL_video.h>

typedef struct _SdxGraphicsSprite SdxGraphicsSprite;
typedef struct _Class Class;

#define SDX_GRAPHICS_SPRITE_TYPE_KIND (sdx_graphics_sprite_kind_get_type ())

#define SDX_MATH_TYPE_SCALE (sdx_math_scale_get_type ())
typedef struct _SdxMathScale SdxMathScale;
#define _SDL_DestroyTexture0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyTexture (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef SdxGraphicsSprite SdxGraphicsSpriteAnimatedSprite;
typedef struct _SdxGraphicsSurface SdxGraphicsSurface;
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
typedef SdxGraphicsSprite SdxGraphicsSpriteTextureSprite;
typedef SdxGraphicsSprite SdxGraphicsSpriteAtlasSprite;
typedef struct _SdxGraphicsTextureRegion SdxGraphicsTextureRegion;
typedef SdxGraphicsTextureRegion SdxGraphicsTextureRegionFromTexture;
typedef SdxGraphicsTextureRegionFromTexture SdxGraphicsAtlasRegion;
typedef SdxGraphicsSurface SdxGraphicsSurfaceTextureSurface;
typedef SdxGraphicsSprite SdxGraphicsSpriteCompositeSprite;

#define SDX_GRAPHICS_TYPE_BLIT (sdx_graphics_blit_get_type ())
typedef struct _SdxGraphicsBlit SdxGraphicsBlit;
typedef SdxGraphicsSprite SdxGraphicsSpriteNineSliceSprite;
typedef struct _SdxGraphicsNinePatch SdxGraphicsNinePatch;
typedef SdxGraphicsSprite SdxGraphicsSpriteUISprite;
typedef struct _SdxFont SdxFont;
typedef SdxGraphicsSprite SdxGraphicsSpriteTextSprite;

typedef enum  {
	SDX_GRAPHICS_SPRITE_KIND_AnimatedSprite,
	SDX_GRAPHICS_SPRITE_KIND_TextureSprite,
	SDX_GRAPHICS_SPRITE_KIND_AtlasSprite,
	SDX_GRAPHICS_SPRITE_KIND_NineSliceSprite,
	SDX_GRAPHICS_SPRITE_KIND_CompositeSprite,
	SDX_GRAPHICS_SPRITE_KIND_TextSprite
} SdxGraphicsSpriteKind;

struct _SdxMathScale {
	gfloat x;
	gfloat y;
};

struct _SdxGraphicsSprite {
	gint ref_count;
	Class* klass;
	SdxGraphicsSpriteKind kind;
	gint id;
	SDL_Texture* texture;
	gint width;
	gint height;
	gint x;
	gint y;
	gint index;
	gint frame;
	gdouble angle;
	SdxMathScale scale;
	SDL_Color color;
	SDL_RendererFlip flip;
	SDL_Point center;
	gboolean centered;
	gint layer;
	gchar* path;
};

struct _SdxGraphicsSurface {
	gint ref_count;
	SDL_Surface* surface;
	gint id;
	gchar* path;
};

typedef enum  {
	SDX_SDL_EXCEPTION_Initialization,
	SDX_SDL_EXCEPTION_ImageInitialization,
	SDX_SDL_EXCEPTION_TtfInitialization,
	SDX_SDL_EXCEPTION_TextureFilteringNotEnabled,
	SDX_SDL_EXCEPTION_OpenWindow,
	SDX_SDL_EXCEPTION_CreateRenderer,
	SDX_SDL_EXCEPTION_InvalidForPlatform,
	SDX_SDL_EXCEPTION_UnableToLoadResource,
	SDX_SDL_EXCEPTION_UnableToLoadSurface,
	SDX_SDL_EXCEPTION_UnableToLoadTexture,
	SDX_SDL_EXCEPTION_NullPointer,
	SDX_SDL_EXCEPTION_NoSuchElement,
	SDX_SDL_EXCEPTION_IllegalStateException,
	SDX_SDL_EXCEPTION_IllegalArgumentException,
	SDX_SDL_EXCEPTION_RuntimeException,
	SDX_SDL_EXCEPTION_NotReached
} SdxSdlException;
#define SDX_SDL_EXCEPTION sdx_sdl_exception_quark ()
struct _SdxGraphicsTextureRegion {
	gint ref_count;
	SdxGraphicsSurfaceTextureSurface* texture;
	gint top;
	gint left;
	gint width;
	gint height;
	gint regionWidth;
	gint regionHeight;
	gfloat u;
	gfloat v;
	gfloat u2;
	gfloat v2;
	gint index;
	gchar* name;
	gint offsetX;
	gint offsetY;
	gint packedWidth;
	gint packedHeight;
	gint originalWidth;
	gint originalHeight;
	gboolean rotate;
	gint* splits;
	gint splits_length1;
	gint* pads;
	gint pads_length1;
};

struct _SdxGraphicsBlit {
	SDL_Rect source;
	SDL_Rect dest;
	SDL_RendererFlip flip;
};

typedef SdxGraphicsBlit* (*SdxGraphicsCompositor) (gint x, gint y, int* result_length1, void* user_data);
struct _SdxGraphicsNinePatch {
	gint ref_count;
	SdxGraphicsSurfaceTextureSurface* texture;
	gint bottomLeft;
	gint bottomCenter;
	gint bottomRight;
	gint middleLeft;
	gint middleCenter;
	gint middleRight;
	gint topLeft;
	gint topCenter;
	gint topRight;
	gint top;
	gint left;
	gint right;
	gint bottom;
	gfloat leftWidth;
	gfloat rightWidth;
	gfloat middleWidth;
	gfloat middleHeight;
	gfloat topHeight;
	gfloat bottomHeight;
	SdxGraphicsBlit slice[9];
	gint idx;
	SDL_Color color;
	gfloat padLeft;
	gfloat padRight;
	gfloat padTop;
	gfloat padBottom;
	gint sourceTop;
	gint sourceLeft;
};


extern gint sdx_graphics_sprite_uniqueId;
gint sdx_graphics_sprite_uniqueId = 0;
extern SDL_Renderer* sdx_renderer;
extern SdxGraphicsSurface** sdx_graphics_surface_cached_surface_cache;
extern gint sdx_graphics_surface_cached_surface_cache_length1;

void sdx_graphics_sprite_free (SdxGraphicsSprite* self);
void class_free (Class* self);
GType sdx_graphics_sprite_kind_get_type (void) G_GNUC_CONST;
GType sdx_math_scale_get_type (void) G_GNUC_CONST;
SdxMathScale* sdx_math_scale_dup (const SdxMathScale* self);
void sdx_math_scale_free (SdxMathScale* self);
static void sdx_graphics_sprite_instance_init (SdxGraphicsSprite * self);
Class* class_Register (const gchar* name, const gchar* guid);
SdxGraphicsSprite* sdx_graphics_sprite_retain (SdxGraphicsSprite* self);
void sdx_graphics_sprite_release (SdxGraphicsSprite* self);
void sdx_graphics_sprite_free (SdxGraphicsSprite* self);
void sdx_graphics_sprite_Render (SdxGraphicsSprite* self, gint x, gint y, SDL_Rect* clip);
void sdx_graphics_sprite_Copy (SdxGraphicsSprite* self, SDL_Rect* src, SDL_Rect* dest);
SdxGraphicsSprite* sdx_graphics_sprite_SetColor (SdxGraphicsSprite* self, SDL_Color color);
SdxGraphicsSprite* sdx_graphics_sprite_SetScale (SdxGraphicsSprite* self, gfloat x, gfloat y);
SdxGraphicsSprite* sdx_graphics_sprite_SetPosition (SdxGraphicsSprite* self, gint x, gint y);
SdxGraphicsSprite* sdx_graphics_sprite_SetCentered (SdxGraphicsSprite* self, gboolean value);
// symtbl.3 SdxGraphicsSprite / sdx_graphics_sprite
SdxGraphicsSprite* sdx_graphics_sprite_retain (SdxGraphicsSprite* self);
void sdx_graphics_sprite_release (SdxGraphicsSprite* self);
SdxGraphicsSprite* sdx_graphics_sprite_new (void);
gint sdx_graphics_sprite_get_Width (SdxGraphicsSprite* self);
void sdx_graphics_sprite_set_Width (SdxGraphicsSprite* self, gint value);
// symtbl.3 SdxGraphicsSpriteAnimatedSprite / sdx_graphics_sprite_animated_sprite
SdxGraphicsSpriteAnimatedSprite* sdx_graphics_sprite_animated_sprite_new (const gchar* path, gint width, gint height);
gint sdx_graphics_surface_cached_surface_IndexOfPath (const gchar* path);
void sdx_graphics_sprite_animated_sprite_SetFrame (SdxGraphicsSpriteAnimatedSprite* self, gint frame);
void sdx_graphics_surface_free (SdxGraphicsSurface* self);
// symtbl.3 SdxGraphicsSpriteTextureSprite / sdx_graphics_sprite_texture_sprite
SdxGraphicsSpriteTextureSprite* sdx_graphics_sprite_texture_sprite_new (const gchar* path);
GQuark sdx_sdl_exception_quark (void);
gint sdx_graphics_surface_get_width (SdxGraphicsSurface* self);
gint sdx_graphics_surface_get_height (SdxGraphicsSurface* self);
void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion* self);
// symtbl.3 SdxGraphicsSpriteAtlasSprite / sdx_graphics_sprite_atlas_sprite
SdxGraphicsSpriteAtlasSprite* sdx_graphics_sprite_atlas_sprite_new (SdxGraphicsAtlasRegion* region);
GType sdx_graphics_blit_get_type (void) G_GNUC_CONST;
SdxGraphicsBlit* sdx_graphics_blit_dup (const SdxGraphicsBlit* self);
void sdx_graphics_blit_free (SdxGraphicsBlit* self);
// symtbl.3 SdxGraphicsSpriteCompositeSprite / sdx_graphics_sprite_composite_sprite
SdxGraphicsSpriteCompositeSprite* sdx_graphics_sprite_composite_sprite_new (const gchar* path, SdxGraphicsCompositor builder, void* builder_target, gint x, gint y);
void sdx_graphics_nine_patch_free (SdxGraphicsNinePatch* self);
// symtbl.3 SdxGraphicsSpriteNineSliceSprite / sdx_graphics_sprite_nine_slice_sprite
SdxGraphicsSpriteNineSliceSprite* sdx_graphics_sprite_nine_slice_sprite_new (SdxGraphicsNinePatch* patch, gint width, gint height);
gfloat sdx_graphics_nine_patch_GetTotalWidth (SdxGraphicsNinePatch* self);
gfloat sdx_graphics_nine_patch_GetTotalHeight (SdxGraphicsNinePatch* self);
void sdx_font_free (SdxFont* self);
// symtbl.3 SdxGraphicsSpriteUISprite / sdx_graphics_sprite_ui_sprite
SdxGraphicsSpriteUISprite* sdx_graphics_sprite_ui_sprite_new (SdxGraphicsNinePatch* patch, const gchar* text, SdxFont* font, SDL_Color color, gint width, gint height);
SDL_Surface* sdx_font_Render (SdxFont* self, const gchar* text, SDL_Color fg, SDL_Color* bg);
// symtbl.3 SdxGraphicsSpriteTextSprite / sdx_graphics_sprite_text_sprite
SdxGraphicsSpriteTextSprite* sdx_graphics_sprite_text_sprite_new (const gchar* text, SdxFont* font, SDL_Color fg, SDL_Color* bg);
void sdx_graphics_sprite_text_sprite_SetText (SdxGraphicsSpriteTextSprite* self, const gchar* text, SdxFont* font, SDL_Color fg, SDL_Color* bg);

extern const SDL_Color SDX_COLOR_White;

GType sdx_graphics_sprite_kind_get_type (void) {
	static volatile gsize sdx_graphics_sprite_kind_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_graphics_sprite_kind_type_id__volatile)) {
		static const GEnumValue values[] = {{SDX_GRAPHICS_SPRITE_KIND_AnimatedSprite, "SDX_GRAPHICS_SPRITE_KIND_AnimatedSprite", "animatedsprite"}, {SDX_GRAPHICS_SPRITE_KIND_TextureSprite, "SDX_GRAPHICS_SPRITE_KIND_TextureSprite", "texturesprite"}, {SDX_GRAPHICS_SPRITE_KIND_AtlasSprite, "SDX_GRAPHICS_SPRITE_KIND_AtlasSprite", "atlassprite"}, {SDX_GRAPHICS_SPRITE_KIND_NineSliceSprite, "SDX_GRAPHICS_SPRITE_KIND_NineSliceSprite", "nineslicesprite"}, {SDX_GRAPHICS_SPRITE_KIND_CompositeSprite, "SDX_GRAPHICS_SPRITE_KIND_CompositeSprite", "compositesprite"}, {SDX_GRAPHICS_SPRITE_KIND_TextSprite, "SDX_GRAPHICS_SPRITE_KIND_TextSprite", "textsprite"}, {0, NULL, NULL}};
		GType sdx_graphics_sprite_kind_type_id;
		sdx_graphics_sprite_kind_type_id = g_enum_register_static ("SdxGraphicsSpriteKind", values);
		g_once_init_leave (&sdx_graphics_sprite_kind_type_id__volatile, sdx_graphics_sprite_kind_type_id);
	}
	return sdx_graphics_sprite_kind_type_id__volatile;
}


SdxGraphicsSprite* sdx_graphics_sprite_retain (SdxGraphicsSprite* self) {
	SdxGraphicsSprite* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void sdx_graphics_sprite_release (SdxGraphicsSprite* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		sdx_graphics_sprite_free (self);
	}
}


/**
 *  Render the sprite on the Video.Renderer context
 *
 * @param x display coordinate
 * @param y display coordinate
 * @param clip optional clipping rectangle
 */
void sdx_graphics_sprite_Render (SdxGraphicsSprite* self, gint x, gint y, SDL_Rect* clip) {
	guint _tmp0_ = 0U;
	SDL_Rect* _tmp1_ = NULL;
	gint w = 0;
	SdxMathScale _tmp5_ = {0};
	gfloat _tmp6_ = 0.0F;
	guint _tmp7_ = 0U;
	SDL_Rect* _tmp8_ = NULL;
	gint h = 0;
	SdxMathScale _tmp12_ = {0};
	gfloat _tmp13_ = 0.0F;
	gint _tmp14_ = 0;
	gboolean _tmp15_ = FALSE;
	gint _tmp19_ = 0;
	gboolean _tmp20_ = FALSE;
	SDL_Texture* _tmp24_ = NULL;
	SDL_Color _tmp25_ = {0};
	guint8 _tmp26_ = 0U;
	SDL_Color _tmp27_ = {0};
	guint8 _tmp28_ = 0U;
	SDL_Color _tmp29_ = {0};
	guint8 _tmp30_ = 0U;
	SDL_Texture* _tmp31_ = NULL;
	SDL_Color _tmp32_ = {0};
	guint8 _tmp33_ = 0U;
	SDL_Renderer* _tmp34_ = NULL;
	SDL_Texture* _tmp35_ = NULL;
	SDL_Rect* _tmp36_ = NULL;
	gint _tmp37_ = 0;
	gint _tmp38_ = 0;
	gint _tmp39_ = 0;
	gint _tmp40_ = 0;
	SDL_Rect _tmp41_ = {0};
	gdouble _tmp42_ = 0.0;
	SDL_Point _tmp43_ = {0};
	SDL_RendererFlip _tmp44_ = 0;
	g_return_if_fail (self != NULL);
	_tmp1_ = clip;
	if (_tmp1_ == NULL) {
		gint _tmp2_ = 0;
		_tmp2_ = self->width;
		_tmp0_ = (guint) _tmp2_;
	} else {
		SDL_Rect* _tmp3_ = NULL;
		guint _tmp4_ = 0U;
		_tmp3_ = clip;
		_tmp4_ = (*_tmp3_).w;
		_tmp0_ = _tmp4_;
	}
	_tmp5_ = self->scale;
	_tmp6_ = _tmp5_.x;
	w = (gint) (_tmp0_ * _tmp6_);
	_tmp8_ = clip;
	if (_tmp8_ == NULL) {
		gint _tmp9_ = 0;
		_tmp9_ = self->height;
		_tmp7_ = (guint) _tmp9_;
	} else {
		SDL_Rect* _tmp10_ = NULL;
		guint _tmp11_ = 0U;
		_tmp10_ = clip;
		_tmp11_ = (*_tmp10_).h;
		_tmp7_ = _tmp11_;
	}
	_tmp12_ = self->scale;
	_tmp13_ = _tmp12_.y;
	h = (gint) (_tmp7_ * _tmp13_);
	_tmp15_ = self->centered;
	if (_tmp15_) {
		gint _tmp16_ = 0;
		gint _tmp17_ = 0;
		_tmp16_ = x;
		_tmp17_ = w;
		_tmp14_ = _tmp16_ - (_tmp17_ / 2);
	} else {
		gint _tmp18_ = 0;
		_tmp18_ = x;
		_tmp14_ = _tmp18_;
	}
	x = _tmp14_;
	_tmp20_ = self->centered;
	if (_tmp20_) {
		gint _tmp21_ = 0;
		gint _tmp22_ = 0;
		_tmp21_ = y;
		_tmp22_ = h;
		_tmp19_ = _tmp21_ - (_tmp22_ / 2);
	} else {
		gint _tmp23_ = 0;
		_tmp23_ = y;
		_tmp19_ = _tmp23_;
	}
	y = _tmp19_;
	_tmp24_ = self->texture;
	_tmp25_ = self->color;
	_tmp26_ = _tmp25_.r;
	_tmp27_ = self->color;
	_tmp28_ = _tmp27_.g;
	_tmp29_ = self->color;
	_tmp30_ = _tmp29_.b;
	SDL_SetTextureColorMod (_tmp24_, _tmp26_, _tmp28_, _tmp30_);
	_tmp31_ = self->texture;
	_tmp32_ = self->color;
	_tmp33_ = _tmp32_.a;
	SDL_SetTextureAlphaMod (_tmp31_, _tmp33_);
	_tmp34_ = sdx_renderer;
	_tmp35_ = self->texture;
	_tmp36_ = clip;
	_tmp37_ = x;
	_tmp38_ = y;
	_tmp39_ = w;
	_tmp40_ = h;
	_tmp41_.x = _tmp37_;
	_tmp41_.y = _tmp38_;
	_tmp41_.w = (guint) _tmp39_;
	_tmp41_.h = (guint) _tmp40_;
	_tmp42_ = self->angle;
	_tmp43_ = self->center;
	_tmp44_ = self->flip;
	SDL_RenderCopyEx (_tmp34_, _tmp35_, _tmp36_, &_tmp41_, _tmp42_, &_tmp43_, _tmp44_);
}


void sdx_graphics_sprite_Copy (SdxGraphicsSprite* self, SDL_Rect* src, SDL_Rect* dest) {
	SDL_Renderer* _tmp0_ = NULL;
	SDL_Texture* _tmp1_ = NULL;
	SDL_Rect* _tmp2_ = NULL;
	SDL_Rect* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = sdx_renderer;
	_tmp1_ = self->texture;
	_tmp2_ = src;
	_tmp3_ = dest;
	SDL_RenderCopy (_tmp0_, _tmp1_, _tmp2_, _tmp3_);
}


static gpointer _sdx_graphics_sprite_retain0 (gpointer self) {
	return self ? sdx_graphics_sprite_retain (self) : NULL;
}


SdxGraphicsSprite* sdx_graphics_sprite_SetColor (SdxGraphicsSprite* self, SDL_Color color) {
	SdxGraphicsSprite* result = NULL;
	SDL_Color _tmp0_ = {0};
	SdxGraphicsSprite* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = color;
	self->color = _tmp0_;
	_tmp1_ = _sdx_graphics_sprite_retain0 (self);
	result = _tmp1_;
	return result;
}


SdxGraphicsSprite* sdx_graphics_sprite_SetScale (SdxGraphicsSprite* self, gfloat x, gfloat y) {
	SdxGraphicsSprite* result = NULL;
	gfloat _tmp0_ = 0.0F;
	gfloat _tmp1_ = 0.0F;
	SdxMathScale _tmp2_ = {0};
	SdxGraphicsSprite* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = x;
	_tmp1_ = y;
	_tmp2_.x = _tmp0_;
	_tmp2_.y = _tmp1_;
	self->scale = _tmp2_;
	_tmp3_ = _sdx_graphics_sprite_retain0 (self);
	result = _tmp3_;
	return result;
}


SdxGraphicsSprite* sdx_graphics_sprite_SetPosition (SdxGraphicsSprite* self, gint x, gint y) {
	SdxGraphicsSprite* result = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	SdxGraphicsSprite* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = x;
	self->x = _tmp0_;
	_tmp1_ = y;
	self->y = _tmp1_;
	_tmp2_ = _sdx_graphics_sprite_retain0 (self);
	result = _tmp2_;
	return result;
}


SdxGraphicsSprite* sdx_graphics_sprite_SetCentered (SdxGraphicsSprite* self, gboolean value) {
	SdxGraphicsSprite* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	SdxGraphicsSprite* _tmp6_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = value;
	self->centered = _tmp0_;
	_tmp1_ = self->centered;
	if (_tmp1_) {
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		SDL_Point _tmp4_ = {0};
		_tmp2_ = self->width;
		_tmp3_ = self->height;
		_tmp4_.x = _tmp2_ / 2;
		_tmp4_.y = _tmp3_ / 2;
		self->center = _tmp4_;
	} else {
		SDL_Point _tmp5_ = {0};
		_tmp5_.x = 0;
		_tmp5_.y = 0;
		self->center = _tmp5_;
	}
	_tmp6_ = _sdx_graphics_sprite_retain0 (self);
	result = _tmp6_;
	return result;
}


// symtbl.3 SdxGraphicsSprite / sdx_graphics_sprite
SdxGraphicsSprite* sdx_graphics_sprite_retain (SdxGraphicsSprite* self);
void sdx_graphics_sprite_release (SdxGraphicsSprite* self);
SdxGraphicsSprite* sdx_graphics_sprite_new (void) {
	SdxGraphicsSprite* self;
	self = g_slice_new0 (SdxGraphicsSprite);
	sdx_graphics_sprite_instance_init (self);
	return self;
}


gint sdx_graphics_sprite_get_Width (SdxGraphicsSprite* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->width;
	result = _tmp0_;
	return result;
}


void sdx_graphics_sprite_set_Width (SdxGraphicsSprite* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->width = _tmp0_;
}


/**
 * Animated Sprite
 * 
 * For each cell in spritesheet, draw the image from a cell
 * 
 * @param path to sprite sheet
 * @param width count of sprites horizontally on sheet
 * @param height count of sprites vertially on sheet
 */
// symtbl.3 SdxGraphicsSpriteAnimatedSprite / sdx_graphics_sprite_animated_sprite
SdxGraphicsSpriteAnimatedSprite* sdx_graphics_sprite_animated_sprite_new (const gchar* path, gint width, gint height) {
	SdxGraphicsSpriteAnimatedSprite* self;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	SDL_Point _tmp6_ = {0};
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	self = (SdxGraphicsSpriteAnimatedSprite*) sdx_graphics_sprite_new ();
	_tmp0_ = path;
	_tmp1_ = sdx_graphics_surface_cached_surface_IndexOfPath (_tmp0_);
	((SdxGraphicsSprite*) self)->index = _tmp1_;
	_tmp2_ = height;
	((SdxGraphicsSprite*) self)->height = _tmp2_;
	_tmp3_ = width;
	((SdxGraphicsSprite*) self)->width = _tmp3_;
	_tmp4_ = width;
	_tmp5_ = height;
	_tmp6_.x = _tmp4_ / 2;
	_tmp6_.y = _tmp5_ / 2;
	((SdxGraphicsSprite*) self)->center = _tmp6_;
	_tmp7_ = path;
	_tmp8_ = g_strdup (_tmp7_);
	_g_free0 (((SdxGraphicsSprite*) self)->path);
	((SdxGraphicsSprite*) self)->path = _tmp8_;
	((SdxGraphicsSprite*) self)->kind = SDX_GRAPHICS_SPRITE_KIND_AnimatedSprite;
	sdx_graphics_sprite_animated_sprite_SetFrame (self, 0);
	return self;
}


/**
 * setFrame
 * 
 * @param frame index of frame to draw
 */
void sdx_graphics_sprite_animated_sprite_SetFrame (SdxGraphicsSpriteAnimatedSprite* self, gint frame) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint32 rmask = 0U;
	guint32 gmask = 0U;
	guint32 bmask = 0U;
	guint32 amask = 0U;
	gint wf = 0;
	SdxGraphicsSurface** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	gint _tmp4_ = 0;
	SdxGraphicsSurface* _tmp5_ = NULL;
	SDL_Surface* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gint hf = 0;
	SdxGraphicsSurface** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	gint _tmp10_ = 0;
	SdxGraphicsSurface* _tmp11_ = NULL;
	SDL_Surface* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	gint _tmp18_ = 0;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	SDL_Surface* surface = NULL;
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
	guint32 _tmp23_ = 0U;
	guint32 _tmp24_ = 0U;
	guint32 _tmp25_ = 0U;
	guint32 _tmp26_ = 0U;
	SDL_Surface* _tmp27_ = NULL;
	SdxGraphicsSurface** _tmp28_ = NULL;
	gint _tmp28__length1 = 0;
	gint _tmp29_ = 0;
	SdxGraphicsSurface* _tmp30_ = NULL;
	SDL_Surface* _tmp31_ = NULL;
	gint _tmp32_ = 0;
	gint _tmp33_ = 0;
	gint _tmp34_ = 0;
	gint _tmp35_ = 0;
	SDL_Rect _tmp36_ = {0};
	SDL_Surface* _tmp37_ = NULL;
	gint _tmp38_ = 0;
	gint _tmp39_ = 0;
	SDL_Rect _tmp40_ = {0};
	SDL_Renderer* _tmp41_ = NULL;
	SDL_Surface* _tmp42_ = NULL;
	SDL_Texture* _tmp43_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = frame;
	_tmp1_ = ((SdxGraphicsSprite*) self)->frame;
	if (_tmp0_ == _tmp1_) {
		return;
	}
	_tmp2_ = frame;
	((SdxGraphicsSprite*) self)->frame = _tmp2_;
	rmask = (guint32) 0x000000ff;
	gmask = (guint32) 0x0000ff00;
	bmask = (guint32) 0x00ff0000;
	amask = (guint32) 0xff000000LL;
	_tmp3_ = sdx_graphics_surface_cached_surface_cache;
	_tmp3__length1 = sdx_graphics_surface_cached_surface_cache_length1;
	_tmp4_ = ((SdxGraphicsSprite*) self)->index;
	_tmp5_ = _tmp3_[_tmp4_];
	_tmp6_ = _tmp5_->surface;
	_tmp7_ = _tmp6_->w;
	_tmp8_ = ((SdxGraphicsSprite*) self)->width;
	wf = _tmp7_ / _tmp8_;
	_tmp9_ = sdx_graphics_surface_cached_surface_cache;
	_tmp9__length1 = sdx_graphics_surface_cached_surface_cache_length1;
	_tmp10_ = ((SdxGraphicsSprite*) self)->index;
	_tmp11_ = _tmp9_[_tmp10_];
	_tmp12_ = _tmp11_->surface;
	_tmp13_ = _tmp12_->h;
	_tmp14_ = ((SdxGraphicsSprite*) self)->height;
	hf = _tmp13_ / _tmp14_;
	_tmp15_ = frame;
	_tmp16_ = wf;
	_tmp17_ = ((SdxGraphicsSprite*) self)->width;
	((SdxGraphicsSprite*) self)->x = (_tmp15_ % _tmp16_) * _tmp17_;
	_tmp18_ = frame;
	_tmp19_ = wf;
	_tmp20_ = ((SdxGraphicsSprite*) self)->height;
	((SdxGraphicsSprite*) self)->y = ((gint) (_tmp18_ / _tmp19_)) * _tmp20_;
	_tmp21_ = ((SdxGraphicsSprite*) self)->width;
	_tmp22_ = ((SdxGraphicsSprite*) self)->height;
	_tmp23_ = rmask;
	_tmp24_ = gmask;
	_tmp25_ = bmask;
	_tmp26_ = amask;
	_tmp27_ = SDL_CreateRGBSurface ((guint32) 0, _tmp21_, _tmp22_, 32, _tmp23_, _tmp24_, _tmp25_, _tmp26_);
	surface = _tmp27_;
	_tmp28_ = sdx_graphics_surface_cached_surface_cache;
	_tmp28__length1 = sdx_graphics_surface_cached_surface_cache_length1;
	_tmp29_ = ((SdxGraphicsSprite*) self)->index;
	_tmp30_ = _tmp28_[_tmp29_];
	_tmp31_ = _tmp30_->surface;
	_tmp32_ = ((SdxGraphicsSprite*) self)->x;
	_tmp33_ = ((SdxGraphicsSprite*) self)->y;
	_tmp34_ = ((SdxGraphicsSprite*) self)->width;
	_tmp35_ = ((SdxGraphicsSprite*) self)->height;
	_tmp36_.x = _tmp32_;
	_tmp36_.y = _tmp33_;
	_tmp36_.w = (guint) _tmp34_;
	_tmp36_.h = (guint) _tmp35_;
	_tmp37_ = surface;
	_tmp38_ = ((SdxGraphicsSprite*) self)->width;
	_tmp39_ = ((SdxGraphicsSprite*) self)->height;
	_tmp40_.x = 0;
	_tmp40_.y = 0;
	_tmp40_.w = (guint) _tmp38_;
	_tmp40_.h = (guint) _tmp39_;
	SDL_BlitScaled (_tmp31_, &_tmp36_, _tmp37_, &_tmp40_);
	_tmp41_ = sdx_renderer;
	_tmp42_ = surface;
	_tmp43_ = SDL_CreateTextureFromSurface (_tmp41_, _tmp42_);
	_SDL_DestroyTexture0 (((SdxGraphicsSprite*) self)->texture);
	((SdxGraphicsSprite*) self)->texture = _tmp43_;
	_SDL_FreeSurface0 (surface);
}


/**
 * TextureSprite
 * 
 * Simple sprite, 1 image per file
 * @param path to single surface
 */
// symtbl.3 SdxGraphicsSpriteTextureSprite / sdx_graphics_sprite_texture_sprite
SdxGraphicsSpriteTextureSprite* sdx_graphics_sprite_texture_sprite_new (const gchar* path) {
	SdxGraphicsSpriteTextureSprite* self;
	gint index = 0;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	SDL_Renderer* _tmp2_ = NULL;
	SdxGraphicsSurface** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	gint _tmp4_ = 0;
	SdxGraphicsSurface* _tmp5_ = NULL;
	SDL_Surface* _tmp6_ = NULL;
	SDL_Texture* _tmp7_ = NULL;
	SDL_Texture* _tmp8_ = NULL;
	SDL_Texture* _tmp11_ = NULL;
	SdxGraphicsSurface** _tmp12_ = NULL;
	gint _tmp12__length1 = 0;
	gint _tmp13_ = 0;
	SdxGraphicsSurface* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	SdxGraphicsSurface** _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	gint _tmp18_ = 0;
	SdxGraphicsSurface* _tmp19_ = NULL;
	gint _tmp20_ = 0;
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
	gint _tmp23_ = 0;
	SDL_Point _tmp24_ = {0};
	const gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	self = (SdxGraphicsSpriteTextureSprite*) sdx_graphics_sprite_new ();
	_tmp0_ = path;
	_tmp1_ = sdx_graphics_surface_cached_surface_IndexOfPath (_tmp0_);
	index = _tmp1_;
	_tmp2_ = sdx_renderer;
	_tmp3_ = sdx_graphics_surface_cached_surface_cache;
	_tmp3__length1 = sdx_graphics_surface_cached_surface_cache_length1;
	_tmp4_ = index;
	_tmp5_ = _tmp3_[_tmp4_];
	_tmp6_ = _tmp5_->surface;
	_tmp7_ = SDL_CreateTextureFromSurface (_tmp2_, _tmp6_);
	_SDL_DestroyTexture0 (((SdxGraphicsSprite*) self)->texture);
	((SdxGraphicsSprite*) self)->texture = _tmp7_;
	_tmp8_ = ((SdxGraphicsSprite*) self)->texture;
	if (_tmp8_ == NULL) {
		const gchar* _tmp9_ = NULL;
		GError* _tmp10_ = NULL;
		_tmp9_ = path;
		_tmp10_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_UnableToLoadTexture, _tmp9_);
		_inner_error_ = _tmp10_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp11_ = ((SdxGraphicsSprite*) self)->texture;
	SDL_SetTextureBlendMode (_tmp11_, SDL_BLENDMODE_BLEND);
	_tmp12_ = sdx_graphics_surface_cached_surface_cache;
	_tmp12__length1 = sdx_graphics_surface_cached_surface_cache_length1;
	_tmp13_ = index;
	_tmp14_ = _tmp12_[_tmp13_];
	_tmp15_ = sdx_graphics_surface_get_width (_tmp14_);
	_tmp16_ = _tmp15_;
	((SdxGraphicsSprite*) self)->width = _tmp16_;
	_tmp17_ = sdx_graphics_surface_cached_surface_cache;
	_tmp17__length1 = sdx_graphics_surface_cached_surface_cache_length1;
	_tmp18_ = index;
	_tmp19_ = _tmp17_[_tmp18_];
	_tmp20_ = sdx_graphics_surface_get_height (_tmp19_);
	_tmp21_ = _tmp20_;
	((SdxGraphicsSprite*) self)->height = _tmp21_;
	_tmp22_ = ((SdxGraphicsSprite*) self)->width;
	_tmp23_ = ((SdxGraphicsSprite*) self)->height;
	_tmp24_.x = _tmp22_ / 2;
	_tmp24_.y = _tmp23_ / 2;
	((SdxGraphicsSprite*) self)->center = _tmp24_;
	_tmp25_ = path;
	_tmp26_ = g_strdup (_tmp25_);
	_g_free0 (((SdxGraphicsSprite*) self)->path);
	((SdxGraphicsSprite*) self)->path = _tmp26_;
	((SdxGraphicsSprite*) self)->kind = SDX_GRAPHICS_SPRITE_KIND_TextureSprite;
	return self;
}


/**
 * AtlasSprite
 * 
 * @param region to load sprite from
 * 
 */
// symtbl.3 SdxGraphicsSpriteAtlasSprite / sdx_graphics_sprite_atlas_sprite
SdxGraphicsSpriteAtlasSprite* sdx_graphics_sprite_atlas_sprite_new (SdxGraphicsAtlasRegion* region) {
	SdxGraphicsSpriteAtlasSprite* self;
	gchar* path = NULL;
	SdxGraphicsAtlasRegion* _tmp0_ = NULL;
	SdxGraphicsSurfaceTextureSurface* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gint index = 0;
	SdxGraphicsAtlasRegion* _tmp4_ = NULL;
	SdxGraphicsSurfaceTextureSurface* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	guint32 rmask = 0U;
	guint32 gmask = 0U;
	guint32 bmask = 0U;
	guint32 amask = 0U;
	gint x = 0;
	SdxGraphicsAtlasRegion* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint y = 0;
	SdxGraphicsAtlasRegion* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	gint w = 0;
	SdxGraphicsAtlasRegion* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint h = 0;
	SdxGraphicsAtlasRegion* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	SDL_Surface* surface = NULL;
	SDL_Surface* _tmp16_ = NULL;
	SdxGraphicsSurface** _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	SdxGraphicsSurface* _tmp18_ = NULL;
	SDL_Surface* _tmp19_ = NULL;
	SDL_Rect _tmp20_ = {0};
	SDL_Rect _tmp21_ = {0};
	SDL_Renderer* _tmp22_ = NULL;
	SDL_Texture* _tmp23_ = NULL;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	SDL_Point _tmp26_ = {0};
	SdxGraphicsAtlasRegion* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	g_return_val_if_fail (region != NULL, NULL);
	self = (SdxGraphicsSpriteAtlasSprite*) sdx_graphics_sprite_new ();
	_tmp0_ = region;
	_tmp1_ = ((SdxGraphicsTextureRegion*) _tmp0_)->texture;
	_tmp2_ = ((SdxGraphicsSurface*) _tmp1_)->path;
	_tmp3_ = g_strdup (_tmp2_);
	path = _tmp3_;
	_tmp4_ = region;
	_tmp5_ = ((SdxGraphicsTextureRegion*) _tmp4_)->texture;
	_tmp6_ = ((SdxGraphicsSurface*) _tmp5_)->path;
	_tmp7_ = sdx_graphics_surface_cached_surface_IndexOfPath (_tmp6_);
	index = _tmp7_;
	rmask = (guint32) 0x000000ff;
	gmask = (guint32) 0x0000ff00;
	bmask = (guint32) 0x00ff0000;
	amask = (guint32) 0xff000000LL;
	_tmp8_ = region;
	_tmp9_ = ((SdxGraphicsTextureRegion*) _tmp8_)->top;
	x = _tmp9_;
	_tmp10_ = region;
	_tmp11_ = ((SdxGraphicsTextureRegion*) _tmp10_)->left;
	y = _tmp11_;
	_tmp12_ = region;
	_tmp13_ = ((SdxGraphicsTextureRegion*) _tmp12_)->width;
	w = _tmp13_;
	_tmp14_ = region;
	_tmp15_ = ((SdxGraphicsTextureRegion*) _tmp14_)->height;
	h = _tmp15_;
	_tmp16_ = SDL_CreateRGBSurface ((guint32) 0, w, h, 32, rmask, gmask, bmask, amask);
	surface = _tmp16_;
	_tmp17_ = sdx_graphics_surface_cached_surface_cache;
	_tmp17__length1 = sdx_graphics_surface_cached_surface_cache_length1;
	_tmp18_ = _tmp17_[index];
	_tmp19_ = _tmp18_->surface;
	_tmp20_.x = x;
	_tmp20_.y = y;
	_tmp20_.w = (guint) w;
	_tmp20_.h = (guint) h;
	_tmp21_.x = 0;
	_tmp21_.y = 0;
	_tmp21_.w = (guint) w;
	_tmp21_.h = (guint) h;
	SDL_BlitScaled (_tmp19_, &_tmp20_, surface, &_tmp21_);
	_tmp22_ = sdx_renderer;
	_tmp23_ = SDL_CreateTextureFromSurface (_tmp22_, surface);
	_SDL_DestroyTexture0 (((SdxGraphicsSprite*) self)->texture);
	((SdxGraphicsSprite*) self)->texture = _tmp23_;
	((SdxGraphicsSprite*) self)->width = w;
	((SdxGraphicsSprite*) self)->height = h;
	_tmp24_ = ((SdxGraphicsSprite*) self)->width;
	_tmp25_ = ((SdxGraphicsSprite*) self)->height;
	_tmp26_.x = _tmp24_ / 2;
	_tmp26_.y = _tmp25_ / 2;
	((SdxGraphicsSprite*) self)->center = _tmp26_;
	_tmp27_ = region;
	_tmp28_ = ((SdxGraphicsTextureRegion*) _tmp27_)->name;
	_tmp29_ = g_strdup (_tmp28_);
	_g_free0 (((SdxGraphicsSprite*) self)->path);
	((SdxGraphicsSprite*) self)->path = _tmp29_;
	((SdxGraphicsSprite*) self)->kind = SDX_GRAPHICS_SPRITE_KIND_AtlasSprite;
	_SDL_FreeSurface0 (surface);
	_g_free0 (path);
	return self;
}


/**
 * CompositeSprite
 * 
 * @param path to custom atlas
 * @param builder factory delegate
 * @param x offset in pixels
 * @param y offset in pixels
 * 
 */
// symtbl.3 SdxGraphicsSpriteCompositeSprite / sdx_graphics_sprite_composite_sprite
SdxGraphicsSpriteCompositeSprite* sdx_graphics_sprite_composite_sprite_new (const gchar* path, SdxGraphicsCompositor builder, void* builder_target, gint x, gint y) {
	SdxGraphicsSpriteCompositeSprite* self;
	gint h = 0;
	gint w = 0;
	SdxGraphicsCompositor _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	SdxGraphicsBlit* _tmp4_ = NULL;
	gint index = 0;
	const gchar* _tmp19_ = NULL;
	gint _tmp20_ = 0;
	guint32 rmask = 0U;
	guint32 gmask = 0U;
	guint32 bmask = 0U;
	guint32 amask = 0U;
	SDL_Surface* surface = NULL;
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
	guint32 _tmp23_ = 0U;
	guint32 _tmp24_ = 0U;
	guint32 _tmp25_ = 0U;
	guint32 _tmp26_ = 0U;
	SDL_Surface* _tmp27_ = NULL;
	SdxGraphicsCompositor _tmp28_ = NULL;
	void* _tmp28__target = NULL;
	gint _tmp29_ = 0;
	gint _tmp30_ = 0;
	gint _tmp31_ = 0;
	SdxGraphicsBlit* _tmp32_ = NULL;
	SDL_Renderer* _tmp42_ = NULL;
	SDL_Surface* _tmp43_ = NULL;
	SDL_Texture* _tmp44_ = NULL;
	gint _tmp45_ = 0;
	gint _tmp46_ = 0;
	gint _tmp47_ = 0;
	gint _tmp48_ = 0;
	SDL_Point _tmp49_ = {0};
	const gchar* _tmp50_ = NULL;
	gchar* _tmp51_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	self = (SdxGraphicsSpriteCompositeSprite*) sdx_graphics_sprite_new ();
	h = 0;
	w = 0;
	_tmp0_ = builder;
	_tmp0__target = builder_target;
	_tmp1_ = x;
	_tmp2_ = y;
	_tmp4_ = _tmp0_ (_tmp1_, _tmp2_, &_tmp3_, _tmp0__target);
	{
		SdxGraphicsBlit* segment_collection = NULL;
		gint segment_collection_length1 = 0;
		gint _segment_collection_size_ = 0;
		gint segment_it = 0;
		segment_collection = _tmp4_;
		segment_collection_length1 = _tmp3_;
		for (segment_it = 0; segment_it < _tmp3_; segment_it = segment_it + 1) {
			SdxGraphicsBlit segment = {0};
			segment = segment_collection[segment_it];
			{
				SdxGraphicsBlit _tmp5_ = {0};
				SDL_Rect _tmp6_ = {0};
				guint _tmp7_ = 0U;
				gint _tmp8_ = 0;
				SdxGraphicsBlit _tmp12_ = {0};
				SDL_Rect _tmp13_ = {0};
				guint _tmp14_ = 0U;
				gint _tmp15_ = 0;
				_tmp5_ = segment;
				_tmp6_ = _tmp5_.dest;
				_tmp7_ = _tmp6_.h;
				_tmp8_ = h;
				if (_tmp7_ > ((guint) _tmp8_)) {
					SdxGraphicsBlit _tmp9_ = {0};
					SDL_Rect _tmp10_ = {0};
					guint _tmp11_ = 0U;
					_tmp9_ = segment;
					_tmp10_ = _tmp9_.dest;
					_tmp11_ = _tmp10_.h;
					h = (gint) _tmp11_;
				}
				_tmp12_ = segment;
				_tmp13_ = _tmp12_.dest;
				_tmp14_ = _tmp13_.w;
				_tmp15_ = w;
				if (_tmp14_ > ((guint) _tmp15_)) {
					SdxGraphicsBlit _tmp16_ = {0};
					SDL_Rect _tmp17_ = {0};
					guint _tmp18_ = 0U;
					_tmp16_ = segment;
					_tmp17_ = _tmp16_.dest;
					_tmp18_ = _tmp17_.w;
					w = (gint) _tmp18_;
				}
			}
		}
		segment_collection = (g_free (segment_collection), NULL);
	}
	_tmp19_ = path;
	_tmp20_ = sdx_graphics_surface_cached_surface_IndexOfPath (_tmp19_);
	index = _tmp20_;
	rmask = (guint32) 0x000000ff;
	gmask = (guint32) 0x0000ff00;
	bmask = (guint32) 0x00ff0000;
	amask = (guint32) 0xff000000LL;
	_tmp21_ = h;
	_tmp22_ = w;
	_tmp23_ = rmask;
	_tmp24_ = gmask;
	_tmp25_ = bmask;
	_tmp26_ = amask;
	_tmp27_ = SDL_CreateRGBSurface ((guint32) 0, _tmp21_, _tmp22_, 32, _tmp23_, _tmp24_, _tmp25_, _tmp26_);
	surface = _tmp27_;
	_tmp28_ = builder;
	_tmp28__target = builder_target;
	_tmp29_ = h;
	_tmp30_ = w;
	_tmp32_ = _tmp28_ (_tmp29_ / 2, _tmp30_ / 2, &_tmp31_, _tmp28__target);
	{
		SdxGraphicsBlit* segment_collection = NULL;
		gint segment_collection_length1 = 0;
		gint _segment_collection_size_ = 0;
		gint segment_it = 0;
		segment_collection = _tmp32_;
		segment_collection_length1 = _tmp31_;
		for (segment_it = 0; segment_it < _tmp31_; segment_it = segment_it + 1) {
			SdxGraphicsBlit segment = {0};
			segment = segment_collection[segment_it];
			{
				SdxGraphicsSurface** _tmp33_ = NULL;
				gint _tmp33__length1 = 0;
				gint _tmp34_ = 0;
				SdxGraphicsSurface* _tmp35_ = NULL;
				SDL_Surface* _tmp36_ = NULL;
				SdxGraphicsBlit _tmp37_ = {0};
				SDL_Rect _tmp38_ = {0};
				SDL_Surface* _tmp39_ = NULL;
				SdxGraphicsBlit _tmp40_ = {0};
				SDL_Rect _tmp41_ = {0};
				_tmp33_ = sdx_graphics_surface_cached_surface_cache;
				_tmp33__length1 = sdx_graphics_surface_cached_surface_cache_length1;
				_tmp34_ = index;
				_tmp35_ = _tmp33_[_tmp34_];
				_tmp36_ = _tmp35_->surface;
				_tmp37_ = segment;
				_tmp38_ = _tmp37_.source;
				_tmp39_ = surface;
				_tmp40_ = segment;
				_tmp41_ = _tmp40_.dest;
				SDL_BlitScaled (_tmp36_, &_tmp38_, _tmp39_, &_tmp41_);
			}
		}
		segment_collection = (g_free (segment_collection), NULL);
	}
	_tmp42_ = sdx_renderer;
	_tmp43_ = surface;
	_tmp44_ = SDL_CreateTextureFromSurface (_tmp42_, _tmp43_);
	_SDL_DestroyTexture0 (((SdxGraphicsSprite*) self)->texture);
	((SdxGraphicsSprite*) self)->texture = _tmp44_;
	_tmp45_ = w;
	((SdxGraphicsSprite*) self)->width = _tmp45_;
	_tmp46_ = h;
	((SdxGraphicsSprite*) self)->height = _tmp46_;
	_tmp47_ = ((SdxGraphicsSprite*) self)->width;
	_tmp48_ = ((SdxGraphicsSprite*) self)->height;
	_tmp49_.x = _tmp47_ / 2;
	_tmp49_.y = _tmp48_ / 2;
	((SdxGraphicsSprite*) self)->center = _tmp49_;
	_tmp50_ = path;
	_tmp51_ = g_strdup (_tmp50_);
	_g_free0 (((SdxGraphicsSprite*) self)->path);
	((SdxGraphicsSprite*) self)->path = _tmp51_;
	((SdxGraphicsSprite*) self)->kind = SDX_GRAPHICS_SPRITE_KIND_CompositeSprite;
	_SDL_FreeSurface0 (surface);
	return self;
}


/**
 * CompositeSprite
 * 
 * @param patch 9slice object
 * @param width in pixels
 * @param height in pixels
 * 
 */
// symtbl.3 SdxGraphicsSpriteNineSliceSprite / sdx_graphics_sprite_nine_slice_sprite
SdxGraphicsSpriteNineSliceSprite* sdx_graphics_sprite_nine_slice_sprite_new (SdxGraphicsNinePatch* patch, gint width, gint height) {
	SdxGraphicsSpriteNineSliceSprite* self;
	gint w = 0;
	SdxGraphicsNinePatch* _tmp0_ = NULL;
	gfloat _tmp1_ = 0.0F;
	gint _tmp2_ = 0;
	gint h = 0;
	SdxGraphicsNinePatch* _tmp3_ = NULL;
	gfloat _tmp4_ = 0.0F;
	gint _tmp5_ = 0;
	guint32 rmask = 0U;
	guint32 gmask = 0U;
	guint32 bmask = 0U;
	guint32 amask = 0U;
	SDL_Rect* dest = NULL;
	SDL_Rect* _tmp6_ = NULL;
	gint dest_length1 = 0;
	gint _dest_size_ = 0;
	SDL_Surface* surface = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	guint32 _tmp9_ = 0U;
	guint32 _tmp10_ = 0U;
	guint32 _tmp11_ = 0U;
	guint32 _tmp12_ = 0U;
	SDL_Surface* _tmp13_ = NULL;
	gint i = 0;
	guint offsetWidth = 0U;
	gint _tmp41_ = 0;
	SDL_Rect* _tmp42_ = NULL;
	gint _tmp42__length1 = 0;
	SDL_Rect _tmp43_ = {0};
	guint _tmp44_ = 0U;
	SDL_Rect* _tmp45_ = NULL;
	gint _tmp45__length1 = 0;
	SDL_Rect _tmp46_ = {0};
	guint _tmp47_ = 0U;
	SDL_Rect* _tmp48_ = NULL;
	gint _tmp48__length1 = 0;
	SDL_Rect _tmp49_ = {0};
	guint _tmp50_ = 0U;
	guint offsetHeight = 0U;
	gint _tmp51_ = 0;
	SDL_Rect* _tmp52_ = NULL;
	gint _tmp52__length1 = 0;
	SDL_Rect _tmp53_ = {0};
	guint _tmp54_ = 0U;
	SDL_Rect* _tmp55_ = NULL;
	gint _tmp55__length1 = 0;
	SDL_Rect _tmp56_ = {0};
	guint _tmp57_ = 0U;
	SDL_Rect* _tmp58_ = NULL;
	gint _tmp58__length1 = 0;
	SDL_Rect _tmp59_ = {0};
	guint _tmp60_ = 0U;
	SDL_Rect* _tmp61_ = NULL;
	gint _tmp61__length1 = 0;
	SDL_Rect* _tmp62_ = NULL;
	gint _tmp62__length1 = 0;
	guint _tmp63_ = 0U;
	guint _tmp64_ = 0U;
	SDL_Rect* _tmp65_ = NULL;
	gint _tmp65__length1 = 0;
	SDL_Rect* _tmp66_ = NULL;
	gint _tmp66__length1 = 0;
	guint _tmp67_ = 0U;
	guint _tmp68_ = 0U;
	SDL_Rect* _tmp69_ = NULL;
	gint _tmp69__length1 = 0;
	SDL_Rect* _tmp70_ = NULL;
	gint _tmp70__length1 = 0;
	guint _tmp71_ = 0U;
	guint _tmp72_ = 0U;
	SDL_Rect* _tmp73_ = NULL;
	gint _tmp73__length1 = 0;
	SDL_Rect* _tmp74_ = NULL;
	gint _tmp74__length1 = 0;
	gint _tmp75_ = 0;
	guint _tmp76_ = 0U;
	SDL_Rect* _tmp77_ = NULL;
	gint _tmp77__length1 = 0;
	SDL_Rect* _tmp78_ = NULL;
	gint _tmp78__length1 = 0;
	gint _tmp79_ = 0;
	guint _tmp80_ = 0U;
	SDL_Rect* _tmp81_ = NULL;
	gint _tmp81__length1 = 0;
	SDL_Rect* _tmp82_ = NULL;
	gint _tmp82__length1 = 0;
	gint _tmp83_ = 0;
	guint _tmp84_ = 0U;
	SDL_Rect* _tmp85_ = NULL;
	gint _tmp85__length1 = 0;
	SDL_Rect* _tmp86_ = NULL;
	gint _tmp86__length1 = 0;
	guint _tmp87_ = 0U;
	guint _tmp88_ = 0U;
	SDL_Rect* _tmp89_ = NULL;
	gint _tmp89__length1 = 0;
	SDL_Rect* _tmp90_ = NULL;
	gint _tmp90__length1 = 0;
	guint _tmp91_ = 0U;
	guint _tmp92_ = 0U;
	SDL_Rect* _tmp93_ = NULL;
	gint _tmp93__length1 = 0;
	SDL_Rect* _tmp94_ = NULL;
	gint _tmp94__length1 = 0;
	guint _tmp95_ = 0U;
	guint _tmp96_ = 0U;
	SDL_Rect* _tmp97_ = NULL;
	gint _tmp97__length1 = 0;
	SDL_Rect* _tmp98_ = NULL;
	gint _tmp98__length1 = 0;
	gint _tmp99_ = 0;
	guint _tmp100_ = 0U;
	SDL_Rect* _tmp101_ = NULL;
	gint _tmp101__length1 = 0;
	SDL_Rect* _tmp102_ = NULL;
	gint _tmp102__length1 = 0;
	gint _tmp103_ = 0;
	guint _tmp104_ = 0U;
	SDL_Rect* _tmp105_ = NULL;
	gint _tmp105__length1 = 0;
	SDL_Rect* _tmp106_ = NULL;
	gint _tmp106__length1 = 0;
	gint _tmp107_ = 0;
	guint _tmp108_ = 0U;
	SdxGraphicsNinePatch* _tmp109_ = NULL;
	SDL_Renderer* _tmp119_ = NULL;
	SDL_Surface* _tmp120_ = NULL;
	SDL_Texture* _tmp121_ = NULL;
	gint _tmp122_ = 0;
	gint _tmp123_ = 0;
	gint _tmp124_ = 0;
	gint _tmp125_ = 0;
	SDL_Point _tmp126_ = {0};
	g_return_val_if_fail (patch != NULL, NULL);
	self = (SdxGraphicsSpriteNineSliceSprite*) sdx_graphics_sprite_new ();
	_tmp0_ = patch;
	_tmp1_ = sdx_graphics_nine_patch_GetTotalWidth (_tmp0_);
	_tmp2_ = width;
	w = ((gint) _tmp1_) + _tmp2_;
	_tmp3_ = patch;
	_tmp4_ = sdx_graphics_nine_patch_GetTotalHeight (_tmp3_);
	_tmp5_ = height;
	h = ((gint) _tmp4_) + _tmp5_;
	rmask = (guint32) 0x000000ff;
	gmask = (guint32) 0x0000ff00;
	bmask = (guint32) 0x00ff0000;
	amask = (guint32) 0xff000000LL;
	_tmp6_ = g_new0 (SDL_Rect, 9);
	dest = _tmp6_;
	dest_length1 = 9;
	_dest_size_ = dest_length1;
	_tmp7_ = w;
	_tmp8_ = h;
	_tmp9_ = rmask;
	_tmp10_ = gmask;
	_tmp11_ = bmask;
	_tmp12_ = amask;
	_tmp13_ = SDL_CreateRGBSurface ((guint32) 0, _tmp7_, _tmp8_, 32, _tmp9_, _tmp10_, _tmp11_, _tmp12_);
	surface = _tmp13_;
	i = 0;
	{
		gboolean _tmp14_ = FALSE;
		i = 0;
		_tmp14_ = TRUE;
		while (TRUE) {
			gint _tmp16_ = 0;
			SDL_Rect* _tmp17_ = NULL;
			gint _tmp17__length1 = 0;
			gint _tmp18_ = 0;
			SdxGraphicsNinePatch* _tmp19_ = NULL;
			gint _tmp20_ = 0;
			SdxGraphicsBlit _tmp21_ = {0};
			SDL_Rect _tmp22_ = {0};
			gint _tmp23_ = 0;
			SdxGraphicsNinePatch* _tmp24_ = NULL;
			gint _tmp25_ = 0;
			SdxGraphicsBlit _tmp26_ = {0};
			SDL_Rect _tmp27_ = {0};
			gint _tmp28_ = 0;
			SdxGraphicsNinePatch* _tmp29_ = NULL;
			gint _tmp30_ = 0;
			SdxGraphicsBlit _tmp31_ = {0};
			SDL_Rect _tmp32_ = {0};
			guint _tmp33_ = 0U;
			SdxGraphicsNinePatch* _tmp34_ = NULL;
			gint _tmp35_ = 0;
			SdxGraphicsBlit _tmp36_ = {0};
			SDL_Rect _tmp37_ = {0};
			guint _tmp38_ = 0U;
			SDL_Rect _tmp39_ = {0};
			SDL_Rect _tmp40_ = {0};
			if (!_tmp14_) {
				gint _tmp15_ = 0;
				_tmp15_ = i;
				i = _tmp15_ + 1;
			}
			_tmp14_ = FALSE;
			_tmp16_ = i;
			if (!(_tmp16_ < 9)) {
				break;
			}
			_tmp17_ = dest;
			_tmp17__length1 = dest_length1;
			_tmp18_ = i;
			_tmp19_ = patch;
			_tmp20_ = i;
			_tmp21_ = _tmp19_->slice[_tmp20_];
			_tmp22_ = _tmp21_.dest;
			_tmp23_ = _tmp22_.x;
			_tmp24_ = patch;
			_tmp25_ = i;
			_tmp26_ = _tmp24_->slice[_tmp25_];
			_tmp27_ = _tmp26_.dest;
			_tmp28_ = _tmp27_.y;
			_tmp29_ = patch;
			_tmp30_ = i;
			_tmp31_ = _tmp29_->slice[_tmp30_];
			_tmp32_ = _tmp31_.dest;
			_tmp33_ = _tmp32_.w;
			_tmp34_ = patch;
			_tmp35_ = i;
			_tmp36_ = _tmp34_->slice[_tmp35_];
			_tmp37_ = _tmp36_.dest;
			_tmp38_ = _tmp37_.h;
			_tmp39_.x = _tmp23_;
			_tmp39_.y = _tmp28_;
			_tmp39_.w = _tmp33_;
			_tmp39_.h = _tmp38_;
			_tmp17_[_tmp18_] = _tmp39_;
			_tmp40_ = _tmp17_[_tmp18_];
		}
	}
	_tmp41_ = width;
	_tmp42_ = dest;
	_tmp42__length1 = dest_length1;
	_tmp43_ = _tmp42_[1];
	_tmp44_ = _tmp43_.w;
	_tmp45_ = dest;
	_tmp45__length1 = dest_length1;
	_tmp46_ = _tmp45_[2];
	_tmp47_ = _tmp46_.w;
	_tmp48_ = dest;
	_tmp48__length1 = dest_length1;
	_tmp49_ = _tmp48_[3];
	_tmp50_ = _tmp49_.w;
	offsetWidth = _tmp41_ - ((_tmp44_ + _tmp47_) + _tmp50_);
	_tmp51_ = height;
	_tmp52_ = dest;
	_tmp52__length1 = dest_length1;
	_tmp53_ = _tmp52_[1];
	_tmp54_ = _tmp53_.h;
	_tmp55_ = dest;
	_tmp55__length1 = dest_length1;
	_tmp56_ = _tmp55_[4];
	_tmp57_ = _tmp56_.h;
	_tmp58_ = dest;
	_tmp58__length1 = dest_length1;
	_tmp59_ = _tmp58_[7];
	_tmp60_ = _tmp59_.h;
	offsetHeight = _tmp51_ - ((_tmp54_ + _tmp57_) + _tmp60_);
	_tmp61_ = dest;
	_tmp61__length1 = dest_length1;
	_tmp62_ = dest;
	_tmp62__length1 = dest_length1;
	_tmp63_ = _tmp62_[1].w;
	_tmp64_ = offsetWidth;
	_tmp62_[1].w = _tmp63_ + _tmp64_;
	_tmp65_ = dest;
	_tmp65__length1 = dest_length1;
	_tmp66_ = dest;
	_tmp66__length1 = dest_length1;
	_tmp67_ = _tmp66_[4].w;
	_tmp68_ = offsetWidth;
	_tmp66_[4].w = _tmp67_ + _tmp68_;
	_tmp69_ = dest;
	_tmp69__length1 = dest_length1;
	_tmp70_ = dest;
	_tmp70__length1 = dest_length1;
	_tmp71_ = _tmp70_[7].w;
	_tmp72_ = offsetWidth;
	_tmp70_[7].w = _tmp71_ + _tmp72_;
	_tmp73_ = dest;
	_tmp73__length1 = dest_length1;
	_tmp74_ = dest;
	_tmp74__length1 = dest_length1;
	_tmp75_ = _tmp74_[2].x;
	_tmp76_ = offsetWidth;
	_tmp74_[2].x = _tmp75_ + ((gint) _tmp76_);
	_tmp77_ = dest;
	_tmp77__length1 = dest_length1;
	_tmp78_ = dest;
	_tmp78__length1 = dest_length1;
	_tmp79_ = _tmp78_[5].x;
	_tmp80_ = offsetWidth;
	_tmp78_[5].x = _tmp79_ + ((gint) _tmp80_);
	_tmp81_ = dest;
	_tmp81__length1 = dest_length1;
	_tmp82_ = dest;
	_tmp82__length1 = dest_length1;
	_tmp83_ = _tmp82_[8].x;
	_tmp84_ = offsetWidth;
	_tmp82_[8].x = _tmp83_ + ((gint) _tmp84_);
	_tmp85_ = dest;
	_tmp85__length1 = dest_length1;
	_tmp86_ = dest;
	_tmp86__length1 = dest_length1;
	_tmp87_ = _tmp86_[3].h;
	_tmp88_ = offsetHeight;
	_tmp86_[3].h = _tmp87_ + _tmp88_;
	_tmp89_ = dest;
	_tmp89__length1 = dest_length1;
	_tmp90_ = dest;
	_tmp90__length1 = dest_length1;
	_tmp91_ = _tmp90_[4].h;
	_tmp92_ = offsetHeight;
	_tmp90_[4].h = _tmp91_ + _tmp92_;
	_tmp93_ = dest;
	_tmp93__length1 = dest_length1;
	_tmp94_ = dest;
	_tmp94__length1 = dest_length1;
	_tmp95_ = _tmp94_[5].h;
	_tmp96_ = offsetHeight;
	_tmp94_[5].h = _tmp95_ + _tmp96_;
	_tmp97_ = dest;
	_tmp97__length1 = dest_length1;
	_tmp98_ = dest;
	_tmp98__length1 = dest_length1;
	_tmp99_ = _tmp98_[6].y;
	_tmp100_ = offsetHeight;
	_tmp98_[6].y = _tmp99_ + ((gint) _tmp100_);
	_tmp101_ = dest;
	_tmp101__length1 = dest_length1;
	_tmp102_ = dest;
	_tmp102__length1 = dest_length1;
	_tmp103_ = _tmp102_[7].y;
	_tmp104_ = offsetHeight;
	_tmp102_[7].y = _tmp103_ + ((gint) _tmp104_);
	_tmp105_ = dest;
	_tmp105__length1 = dest_length1;
	_tmp106_ = dest;
	_tmp106__length1 = dest_length1;
	_tmp107_ = _tmp106_[8].y;
	_tmp108_ = offsetHeight;
	_tmp106_[8].y = _tmp107_ + ((gint) _tmp108_);
	i = 0;
	_tmp109_ = patch;
	{
		SdxGraphicsBlit* segment_collection = NULL;
		gint segment_collection_length1 = 0;
		gint _segment_collection_size_ = 0;
		gint segment_it = 0;
		segment_collection = _tmp109_->slice;
		segment_collection_length1 = 9;
		for (segment_it = 0; segment_it < 9; segment_it = segment_it + 1) {
			SdxGraphicsBlit segment = {0};
			segment = segment_collection[segment_it];
			{
				SdxGraphicsNinePatch* _tmp110_ = NULL;
				SdxGraphicsSurfaceTextureSurface* _tmp111_ = NULL;
				SDL_Surface* _tmp112_ = NULL;
				SdxGraphicsBlit _tmp113_ = {0};
				SDL_Rect _tmp114_ = {0};
				SDL_Surface* _tmp115_ = NULL;
				SDL_Rect* _tmp116_ = NULL;
				gint _tmp116__length1 = 0;
				gint _tmp117_ = 0;
				SDL_Rect _tmp118_ = {0};
				_tmp110_ = patch;
				_tmp111_ = _tmp110_->texture;
				_tmp112_ = ((SdxGraphicsSurface*) _tmp111_)->surface;
				_tmp113_ = segment;
				_tmp114_ = _tmp113_.source;
				_tmp115_ = surface;
				_tmp116_ = dest;
				_tmp116__length1 = dest_length1;
				_tmp117_ = i;
				i = _tmp117_ + 1;
				_tmp118_ = _tmp116_[_tmp117_];
				SDL_BlitScaled (_tmp112_, &_tmp114_, _tmp115_, &_tmp118_);
			}
		}
	}
	_tmp119_ = sdx_renderer;
	_tmp120_ = surface;
	_tmp121_ = SDL_CreateTextureFromSurface (_tmp119_, _tmp120_);
	_SDL_DestroyTexture0 (((SdxGraphicsSprite*) self)->texture);
	((SdxGraphicsSprite*) self)->texture = _tmp121_;
	_tmp122_ = width;
	((SdxGraphicsSprite*) self)->width = _tmp122_;
	_tmp123_ = height;
	((SdxGraphicsSprite*) self)->height = _tmp123_;
	_tmp124_ = width;
	_tmp125_ = height;
	_tmp126_.x = _tmp124_ / 2;
	_tmp126_.y = _tmp125_ / 2;
	((SdxGraphicsSprite*) self)->center = _tmp126_;
	((SdxGraphicsSprite*) self)->kind = SDX_GRAPHICS_SPRITE_KIND_NineSliceSprite;
	_SDL_FreeSurface0 (surface);
	dest = (g_free (dest), NULL);
	return self;
}


/**
 * CompositeSprite
 * 
 * @param patch 9slice patch object
 * @param text to generate
 * @param font to use
 * @param color to use for foreground
 * @param width in pixels
 * @param height in pixels
 * 
 */
// symtbl.3 SdxGraphicsSpriteUISprite / sdx_graphics_sprite_ui_sprite
SdxGraphicsSpriteUISprite* sdx_graphics_sprite_ui_sprite_new (SdxGraphicsNinePatch* patch, const gchar* text, SdxFont* font, SDL_Color color, gint width, gint height) {
	SdxGraphicsSpriteUISprite* self;
	SDL_Surface* textSurface = NULL;
	SdxFont* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	SDL_Color _tmp2_ = {0};
	SDL_Surface* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	SDL_Surface* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gdouble _tmp7_ = 0.0;
	gint _tmp8_ = 0;
	SDL_Surface* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gdouble _tmp11_ = 0.0;
	gint w = 0;
	SdxGraphicsNinePatch* _tmp12_ = NULL;
	gfloat _tmp13_ = 0.0F;
	gint _tmp14_ = 0;
	gint h = 0;
	SdxGraphicsNinePatch* _tmp15_ = NULL;
	gfloat _tmp16_ = 0.0F;
	gint _tmp17_ = 0;
	guint32 rmask = 0U;
	guint32 gmask = 0U;
	guint32 bmask = 0U;
	guint32 amask = 0U;
	SDL_Rect* dest = NULL;
	SDL_Rect* _tmp18_ = NULL;
	gint dest_length1 = 0;
	gint _dest_size_ = 0;
	SDL_Surface* surface = NULL;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	guint32 _tmp21_ = 0U;
	guint32 _tmp22_ = 0U;
	guint32 _tmp23_ = 0U;
	guint32 _tmp24_ = 0U;
	SDL_Surface* _tmp25_ = NULL;
	gint i = 0;
	gint offsetWidth = 0;
	gint _tmp53_ = 0;
	SDL_Rect* _tmp54_ = NULL;
	gint _tmp54__length1 = 0;
	SDL_Rect _tmp55_ = {0};
	guint _tmp56_ = 0U;
	SDL_Rect* _tmp57_ = NULL;
	gint _tmp57__length1 = 0;
	SDL_Rect _tmp58_ = {0};
	guint _tmp59_ = 0U;
	SDL_Rect* _tmp60_ = NULL;
	gint _tmp60__length1 = 0;
	SDL_Rect _tmp61_ = {0};
	guint _tmp62_ = 0U;
	gdouble _tmp63_ = 0.0;
	gint offsetHeight = 0;
	gint _tmp64_ = 0;
	SDL_Rect* _tmp65_ = NULL;
	gint _tmp65__length1 = 0;
	SDL_Rect _tmp66_ = {0};
	guint _tmp67_ = 0U;
	SDL_Rect* _tmp68_ = NULL;
	gint _tmp68__length1 = 0;
	SDL_Rect _tmp69_ = {0};
	guint _tmp70_ = 0U;
	SDL_Rect* _tmp71_ = NULL;
	gint _tmp71__length1 = 0;
	SDL_Rect _tmp72_ = {0};
	guint _tmp73_ = 0U;
	gdouble _tmp74_ = 0.0;
	SDL_Rect* _tmp75_ = NULL;
	gint _tmp75__length1 = 0;
	SDL_Rect* _tmp76_ = NULL;
	gint _tmp76__length1 = 0;
	guint _tmp77_ = 0U;
	gint _tmp78_ = 0;
	SDL_Rect* _tmp79_ = NULL;
	gint _tmp79__length1 = 0;
	SDL_Rect* _tmp80_ = NULL;
	gint _tmp80__length1 = 0;
	guint _tmp81_ = 0U;
	gint _tmp82_ = 0;
	SDL_Rect* _tmp83_ = NULL;
	gint _tmp83__length1 = 0;
	SDL_Rect* _tmp84_ = NULL;
	gint _tmp84__length1 = 0;
	guint _tmp85_ = 0U;
	gint _tmp86_ = 0;
	SDL_Rect* _tmp87_ = NULL;
	gint _tmp87__length1 = 0;
	SDL_Rect* _tmp88_ = NULL;
	gint _tmp88__length1 = 0;
	gint _tmp89_ = 0;
	gint _tmp90_ = 0;
	SDL_Rect* _tmp91_ = NULL;
	gint _tmp91__length1 = 0;
	SDL_Rect* _tmp92_ = NULL;
	gint _tmp92__length1 = 0;
	gint _tmp93_ = 0;
	gint _tmp94_ = 0;
	SDL_Rect* _tmp95_ = NULL;
	gint _tmp95__length1 = 0;
	SDL_Rect* _tmp96_ = NULL;
	gint _tmp96__length1 = 0;
	gint _tmp97_ = 0;
	gint _tmp98_ = 0;
	SDL_Rect* _tmp99_ = NULL;
	gint _tmp99__length1 = 0;
	SDL_Rect* _tmp100_ = NULL;
	gint _tmp100__length1 = 0;
	guint _tmp101_ = 0U;
	gint _tmp102_ = 0;
	SDL_Rect* _tmp103_ = NULL;
	gint _tmp103__length1 = 0;
	SDL_Rect* _tmp104_ = NULL;
	gint _tmp104__length1 = 0;
	guint _tmp105_ = 0U;
	gint _tmp106_ = 0;
	SDL_Rect* _tmp107_ = NULL;
	gint _tmp107__length1 = 0;
	SDL_Rect* _tmp108_ = NULL;
	gint _tmp108__length1 = 0;
	guint _tmp109_ = 0U;
	gint _tmp110_ = 0;
	SDL_Rect* _tmp111_ = NULL;
	gint _tmp111__length1 = 0;
	SDL_Rect* _tmp112_ = NULL;
	gint _tmp112__length1 = 0;
	gint _tmp113_ = 0;
	gint _tmp114_ = 0;
	SDL_Rect* _tmp115_ = NULL;
	gint _tmp115__length1 = 0;
	SDL_Rect* _tmp116_ = NULL;
	gint _tmp116__length1 = 0;
	gint _tmp117_ = 0;
	gint _tmp118_ = 0;
	SDL_Rect* _tmp119_ = NULL;
	gint _tmp119__length1 = 0;
	SDL_Rect* _tmp120_ = NULL;
	gint _tmp120__length1 = 0;
	gint _tmp121_ = 0;
	gint _tmp122_ = 0;
	SdxGraphicsNinePatch* _tmp123_ = NULL;
	SDL_Surface* _tmp133_ = NULL;
	gint _tmp134_ = 0;
	gint _tmp135_ = 0;
	SDL_Rect _tmp136_ = {0};
	SDL_Surface* _tmp137_ = NULL;
	SdxGraphicsNinePatch* _tmp138_ = NULL;
	gint _tmp139_ = 0;
	SdxGraphicsNinePatch* _tmp140_ = NULL;
	gint _tmp141_ = 0;
	gint _tmp142_ = 0;
	gint _tmp143_ = 0;
	SDL_Rect _tmp144_ = {0};
	SDL_Renderer* _tmp145_ = NULL;
	SDL_Surface* _tmp146_ = NULL;
	SDL_Texture* _tmp147_ = NULL;
	SDL_Texture* _tmp148_ = NULL;
	gint _tmp149_ = 0;
	gint _tmp150_ = 0;
	gint _tmp151_ = 0;
	gint _tmp152_ = 0;
	SDL_Point _tmp153_ = {0};
	g_return_val_if_fail (patch != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (font != NULL, NULL);
	self = (SdxGraphicsSpriteUISprite*) sdx_graphics_sprite_new ();
	_tmp0_ = font;
	_tmp1_ = text;
	_tmp2_ = color;
	_tmp3_ = sdx_font_Render (_tmp0_, _tmp1_, _tmp2_, NULL);
	textSurface = _tmp3_;
	_tmp4_ = width;
	_tmp5_ = textSurface;
	_tmp6_ = _tmp5_->w;
	_tmp7_ = fmax ((gdouble) _tmp4_, (gdouble) _tmp6_);
	width = (gint) _tmp7_;
	_tmp8_ = height;
	_tmp9_ = textSurface;
	_tmp10_ = _tmp9_->h;
	_tmp11_ = fmax ((gdouble) _tmp8_, (gdouble) _tmp10_);
	height = (gint) _tmp11_;
	_tmp12_ = patch;
	_tmp13_ = sdx_graphics_nine_patch_GetTotalWidth (_tmp12_);
	_tmp14_ = width;
	w = ((gint) _tmp13_) + _tmp14_;
	_tmp15_ = patch;
	_tmp16_ = sdx_graphics_nine_patch_GetTotalHeight (_tmp15_);
	_tmp17_ = height;
	h = ((gint) _tmp16_) + _tmp17_;
	rmask = (guint32) 0x000000ff;
	gmask = (guint32) 0x0000ff00;
	bmask = (guint32) 0x00ff0000;
	amask = (guint32) 0xff000000LL;
	_tmp18_ = g_new0 (SDL_Rect, 9);
	dest = _tmp18_;
	dest_length1 = 9;
	_dest_size_ = dest_length1;
	_tmp19_ = w;
	_tmp20_ = h;
	_tmp21_ = rmask;
	_tmp22_ = gmask;
	_tmp23_ = bmask;
	_tmp24_ = amask;
	_tmp25_ = SDL_CreateRGBSurface ((guint32) 0, _tmp19_, _tmp20_, 32, _tmp21_, _tmp22_, _tmp23_, _tmp24_);
	surface = _tmp25_;
	i = 0;
	{
		gboolean _tmp26_ = FALSE;
		i = 0;
		_tmp26_ = TRUE;
		while (TRUE) {
			gint _tmp28_ = 0;
			SDL_Rect* _tmp29_ = NULL;
			gint _tmp29__length1 = 0;
			gint _tmp30_ = 0;
			SdxGraphicsNinePatch* _tmp31_ = NULL;
			gint _tmp32_ = 0;
			SdxGraphicsBlit _tmp33_ = {0};
			SDL_Rect _tmp34_ = {0};
			gint _tmp35_ = 0;
			SdxGraphicsNinePatch* _tmp36_ = NULL;
			gint _tmp37_ = 0;
			SdxGraphicsBlit _tmp38_ = {0};
			SDL_Rect _tmp39_ = {0};
			gint _tmp40_ = 0;
			SdxGraphicsNinePatch* _tmp41_ = NULL;
			gint _tmp42_ = 0;
			SdxGraphicsBlit _tmp43_ = {0};
			SDL_Rect _tmp44_ = {0};
			guint _tmp45_ = 0U;
			SdxGraphicsNinePatch* _tmp46_ = NULL;
			gint _tmp47_ = 0;
			SdxGraphicsBlit _tmp48_ = {0};
			SDL_Rect _tmp49_ = {0};
			guint _tmp50_ = 0U;
			SDL_Rect _tmp51_ = {0};
			SDL_Rect _tmp52_ = {0};
			if (!_tmp26_) {
				gint _tmp27_ = 0;
				_tmp27_ = i;
				i = _tmp27_ + 1;
			}
			_tmp26_ = FALSE;
			_tmp28_ = i;
			if (!(_tmp28_ < 9)) {
				break;
			}
			_tmp29_ = dest;
			_tmp29__length1 = dest_length1;
			_tmp30_ = i;
			_tmp31_ = patch;
			_tmp32_ = i;
			_tmp33_ = _tmp31_->slice[_tmp32_];
			_tmp34_ = _tmp33_.dest;
			_tmp35_ = _tmp34_.x;
			_tmp36_ = patch;
			_tmp37_ = i;
			_tmp38_ = _tmp36_->slice[_tmp37_];
			_tmp39_ = _tmp38_.dest;
			_tmp40_ = _tmp39_.y;
			_tmp41_ = patch;
			_tmp42_ = i;
			_tmp43_ = _tmp41_->slice[_tmp42_];
			_tmp44_ = _tmp43_.dest;
			_tmp45_ = _tmp44_.w;
			_tmp46_ = patch;
			_tmp47_ = i;
			_tmp48_ = _tmp46_->slice[_tmp47_];
			_tmp49_ = _tmp48_.dest;
			_tmp50_ = _tmp49_.h;
			_tmp51_.x = _tmp35_;
			_tmp51_.y = _tmp40_;
			_tmp51_.w = _tmp45_;
			_tmp51_.h = _tmp50_;
			_tmp29_[_tmp30_] = _tmp51_;
			_tmp52_ = _tmp29_[_tmp30_];
		}
	}
	_tmp53_ = width;
	_tmp54_ = dest;
	_tmp54__length1 = dest_length1;
	_tmp55_ = _tmp54_[1];
	_tmp56_ = _tmp55_.w;
	_tmp57_ = dest;
	_tmp57__length1 = dest_length1;
	_tmp58_ = _tmp57_[2];
	_tmp59_ = _tmp58_.w;
	_tmp60_ = dest;
	_tmp60__length1 = dest_length1;
	_tmp61_ = _tmp60_[3];
	_tmp62_ = _tmp61_.w;
	_tmp63_ = fmax ((gdouble) 0, (gdouble) (((gint) _tmp53_) - ((gint) ((_tmp56_ + _tmp59_) + _tmp62_))));
	offsetWidth = ((gint) _tmp63_) + 8;
	_tmp64_ = height;
	_tmp65_ = dest;
	_tmp65__length1 = dest_length1;
	_tmp66_ = _tmp65_[1];
	_tmp67_ = _tmp66_.h;
	_tmp68_ = dest;
	_tmp68__length1 = dest_length1;
	_tmp69_ = _tmp68_[4];
	_tmp70_ = _tmp69_.h;
	_tmp71_ = dest;
	_tmp71__length1 = dest_length1;
	_tmp72_ = _tmp71_[7];
	_tmp73_ = _tmp72_.h;
	_tmp74_ = fmax ((gdouble) 0, (gdouble) (((gint) _tmp64_) - ((gint) ((_tmp67_ + _tmp70_) + _tmp73_))));
	offsetHeight = (gint) _tmp74_;
	_tmp75_ = dest;
	_tmp75__length1 = dest_length1;
	_tmp76_ = dest;
	_tmp76__length1 = dest_length1;
	_tmp77_ = _tmp76_[1].w;
	_tmp78_ = offsetWidth;
	_tmp76_[1].w = _tmp77_ + _tmp78_;
	_tmp79_ = dest;
	_tmp79__length1 = dest_length1;
	_tmp80_ = dest;
	_tmp80__length1 = dest_length1;
	_tmp81_ = _tmp80_[4].w;
	_tmp82_ = offsetWidth;
	_tmp80_[4].w = _tmp81_ + _tmp82_;
	_tmp83_ = dest;
	_tmp83__length1 = dest_length1;
	_tmp84_ = dest;
	_tmp84__length1 = dest_length1;
	_tmp85_ = _tmp84_[7].w;
	_tmp86_ = offsetWidth;
	_tmp84_[7].w = _tmp85_ + _tmp86_;
	_tmp87_ = dest;
	_tmp87__length1 = dest_length1;
	_tmp88_ = dest;
	_tmp88__length1 = dest_length1;
	_tmp89_ = _tmp88_[2].x;
	_tmp90_ = offsetWidth;
	_tmp88_[2].x = _tmp89_ + ((gint) _tmp90_);
	_tmp91_ = dest;
	_tmp91__length1 = dest_length1;
	_tmp92_ = dest;
	_tmp92__length1 = dest_length1;
	_tmp93_ = _tmp92_[5].x;
	_tmp94_ = offsetWidth;
	_tmp92_[5].x = _tmp93_ + ((gint) _tmp94_);
	_tmp95_ = dest;
	_tmp95__length1 = dest_length1;
	_tmp96_ = dest;
	_tmp96__length1 = dest_length1;
	_tmp97_ = _tmp96_[8].x;
	_tmp98_ = offsetWidth;
	_tmp96_[8].x = _tmp97_ + ((gint) _tmp98_);
	_tmp99_ = dest;
	_tmp99__length1 = dest_length1;
	_tmp100_ = dest;
	_tmp100__length1 = dest_length1;
	_tmp101_ = _tmp100_[3].h;
	_tmp102_ = offsetHeight;
	_tmp100_[3].h = _tmp101_ + _tmp102_;
	_tmp103_ = dest;
	_tmp103__length1 = dest_length1;
	_tmp104_ = dest;
	_tmp104__length1 = dest_length1;
	_tmp105_ = _tmp104_[4].h;
	_tmp106_ = offsetHeight;
	_tmp104_[4].h = _tmp105_ + _tmp106_;
	_tmp107_ = dest;
	_tmp107__length1 = dest_length1;
	_tmp108_ = dest;
	_tmp108__length1 = dest_length1;
	_tmp109_ = _tmp108_[5].h;
	_tmp110_ = offsetHeight;
	_tmp108_[5].h = _tmp109_ + _tmp110_;
	_tmp111_ = dest;
	_tmp111__length1 = dest_length1;
	_tmp112_ = dest;
	_tmp112__length1 = dest_length1;
	_tmp113_ = _tmp112_[6].y;
	_tmp114_ = offsetHeight;
	_tmp112_[6].y = _tmp113_ + ((gint) _tmp114_);
	_tmp115_ = dest;
	_tmp115__length1 = dest_length1;
	_tmp116_ = dest;
	_tmp116__length1 = dest_length1;
	_tmp117_ = _tmp116_[7].y;
	_tmp118_ = offsetHeight;
	_tmp116_[7].y = _tmp117_ + ((gint) _tmp118_);
	_tmp119_ = dest;
	_tmp119__length1 = dest_length1;
	_tmp120_ = dest;
	_tmp120__length1 = dest_length1;
	_tmp121_ = _tmp120_[8].y;
	_tmp122_ = offsetHeight;
	_tmp120_[8].y = _tmp121_ + ((gint) _tmp122_);
	i = 0;
	_tmp123_ = patch;
	{
		SdxGraphicsBlit* segment_collection = NULL;
		gint segment_collection_length1 = 0;
		gint _segment_collection_size_ = 0;
		gint segment_it = 0;
		segment_collection = _tmp123_->slice;
		segment_collection_length1 = 9;
		for (segment_it = 0; segment_it < 9; segment_it = segment_it + 1) {
			SdxGraphicsBlit segment = {0};
			segment = segment_collection[segment_it];
			{
				SdxGraphicsNinePatch* _tmp124_ = NULL;
				SdxGraphicsSurfaceTextureSurface* _tmp125_ = NULL;
				SDL_Surface* _tmp126_ = NULL;
				SdxGraphicsBlit _tmp127_ = {0};
				SDL_Rect _tmp128_ = {0};
				SDL_Surface* _tmp129_ = NULL;
				SDL_Rect* _tmp130_ = NULL;
				gint _tmp130__length1 = 0;
				gint _tmp131_ = 0;
				SDL_Rect _tmp132_ = {0};
				_tmp124_ = patch;
				_tmp125_ = _tmp124_->texture;
				_tmp126_ = ((SdxGraphicsSurface*) _tmp125_)->surface;
				_tmp127_ = segment;
				_tmp128_ = _tmp127_.source;
				_tmp129_ = surface;
				_tmp130_ = dest;
				_tmp130__length1 = dest_length1;
				_tmp131_ = i;
				i = _tmp131_ + 1;
				_tmp132_ = _tmp130_[_tmp131_];
				SDL_BlitScaled (_tmp126_, &_tmp128_, _tmp129_, &_tmp132_);
			}
		}
	}
	_tmp133_ = textSurface;
	_tmp134_ = width;
	_tmp135_ = height;
	_tmp136_.x = 0;
	_tmp136_.y = 0;
	_tmp136_.w = (guint) _tmp134_;
	_tmp136_.h = (guint) _tmp135_;
	_tmp137_ = surface;
	_tmp138_ = patch;
	_tmp139_ = _tmp138_->bottom;
	_tmp140_ = patch;
	_tmp141_ = _tmp140_->right;
	_tmp142_ = width;
	_tmp143_ = height;
	_tmp144_.x = _tmp139_;
	_tmp144_.y = _tmp141_;
	_tmp144_.w = (guint) _tmp142_;
	_tmp144_.h = (guint) _tmp143_;
	SDL_BlitScaled (_tmp133_, &_tmp136_, _tmp137_, &_tmp144_);
	_tmp145_ = sdx_renderer;
	_tmp146_ = surface;
	_tmp147_ = SDL_CreateTextureFromSurface (_tmp145_, _tmp146_);
	_SDL_DestroyTexture0 (((SdxGraphicsSprite*) self)->texture);
	((SdxGraphicsSprite*) self)->texture = _tmp147_;
	_tmp148_ = ((SdxGraphicsSprite*) self)->texture;
	SDL_SetTextureBlendMode (_tmp148_, SDL_BLENDMODE_BLEND);
	_tmp149_ = width;
	((SdxGraphicsSprite*) self)->width = _tmp149_;
	_tmp150_ = height;
	((SdxGraphicsSprite*) self)->height = _tmp150_;
	_tmp151_ = width;
	_tmp152_ = height;
	_tmp153_.x = _tmp151_ / 2;
	_tmp153_.y = _tmp152_ / 2;
	((SdxGraphicsSprite*) self)->center = _tmp153_;
	((SdxGraphicsSprite*) self)->kind = SDX_GRAPHICS_SPRITE_KIND_NineSliceSprite;
	_SDL_FreeSurface0 (surface);
	dest = (g_free (dest), NULL);
	_SDL_FreeSurface0 (textSurface);
	return self;
}


/**
 * TextSprite
 * 
 * @param text string of text to generate
 * @param font used to generate text
 * @param fg foregound text color 
 * @param bg background color, null = transparent
 * 
 */
// symtbl.3 SdxGraphicsSpriteTextSprite / sdx_graphics_sprite_text_sprite
SdxGraphicsSpriteTextSprite* sdx_graphics_sprite_text_sprite_new (const gchar* text, SdxFont* font, SDL_Color fg, SDL_Color* bg) {
	SdxGraphicsSpriteTextSprite* self;
	const gchar* _tmp0_ = NULL;
	SdxFont* _tmp1_ = NULL;
	SDL_Color _tmp2_ = {0};
	SDL_Color* _tmp3_ = NULL;
	SDL_Point _tmp4_ = {0};
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (font != NULL, NULL);
	self = (SdxGraphicsSpriteTextSprite*) sdx_graphics_sprite_new ();
	_tmp0_ = text;
	_tmp1_ = font;
	_tmp2_ = fg;
	_tmp3_ = bg;
	sdx_graphics_sprite_text_sprite_SetText (self, _tmp0_, _tmp1_, _tmp2_, _tmp3_);
	((SdxGraphicsSprite*) self)->centered = FALSE;
	_tmp4_.x = 0;
	_tmp4_.y = 0;
	((SdxGraphicsSprite*) self)->center = _tmp4_;
	((SdxGraphicsSprite*) self)->kind = SDX_GRAPHICS_SPRITE_KIND_TextSprite;
	return self;
}


/**
 *  Change the text value of a Sprite.fromRenderedText
 *
 * @param text string of text to generate
 * @param font used to generate text
 * @param fg foregound text color 
 * @param bg background color, null = transparent
 */
void sdx_graphics_sprite_text_sprite_SetText (SdxGraphicsSpriteTextSprite* self, const gchar* text, SdxFont* font, SDL_Color fg, SDL_Color* bg) {
	SDL_Surface* surface = NULL;
	SdxFont* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	SDL_Color _tmp2_ = {0};
	SDL_Color* _tmp3_ = NULL;
	SDL_Surface* _tmp4_ = NULL;
	SDL_Renderer* _tmp5_ = NULL;
	SDL_Texture* _tmp6_ = NULL;
	SDL_Texture* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (text != NULL);
	g_return_if_fail (font != NULL);
	_tmp0_ = font;
	_tmp1_ = text;
	_tmp2_ = fg;
	_tmp3_ = bg;
	_tmp4_ = sdx_font_Render (_tmp0_, _tmp1_, _tmp2_, _tmp3_);
	surface = _tmp4_;
	_tmp5_ = sdx_renderer;
	_tmp6_ = SDL_CreateTextureFromSurface (_tmp5_, surface);
	_SDL_DestroyTexture0 (((SdxGraphicsSprite*) self)->texture);
	((SdxGraphicsSprite*) self)->texture = _tmp6_;
	_tmp7_ = ((SdxGraphicsSprite*) self)->texture;
	SDL_SetTextureBlendMode (_tmp7_, SDL_BLENDMODE_BLEND);
	_tmp8_ = surface->w;
	((SdxGraphicsSprite*) self)->width = _tmp8_;
	_tmp9_ = surface->h;
	((SdxGraphicsSprite*) self)->height = _tmp9_;
	_tmp10_ = text;
	_tmp11_ = g_strdup (_tmp10_);
	_g_free0 (((SdxGraphicsSprite*) self)->path);
	((SdxGraphicsSprite*) self)->path = _tmp11_;
	_SDL_FreeSurface0 (surface);
}


static void sdx_graphics_sprite_instance_init (SdxGraphicsSprite * self) {
	Class* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	SdxMathScale _tmp3_ = {0};
	self->ref_count = 1;
	_tmp0_ = class_Register ("Sdx.Graphics.Sprite", NULL);
	self->klass = _tmp0_;
	_tmp1_ = sdx_graphics_sprite_uniqueId;
	sdx_graphics_sprite_uniqueId = _tmp1_ + 1;
	_tmp2_ = sdx_graphics_sprite_uniqueId;
	self->id = _tmp2_;
	self->frame = -1;
	self->angle = 0.0;
	memset (&_tmp3_, 0, sizeof (SdxMathScale));
	_tmp3_.x = (gfloat) 1;
	_tmp3_.y = (gfloat) 1;
	self->scale = _tmp3_;
	self->color = SDX_COLOR_White;
	self->flip = SDL_FLIP_NONE;
	self->centered = TRUE;
	self->layer = 0;
}


void sdx_graphics_sprite_free (SdxGraphicsSprite* self) {
	_SDL_DestroyTexture0 (self->texture);
	_g_free0 (self->path);
	g_slice_free (SdxGraphicsSprite, self);
}



