/** updated by adriac */
/* TextureAtlas.c generated by valac 0.34.9, the Vala compiler
 * generated from TextureAtlas.vala, do not modify */

/* ******************************************************************************
 * Copyright 2017 darkoverlordofdata.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_pixels.h>

typedef struct _SdxGraphicsTextureAtlas SdxGraphicsTextureAtlas;
typedef struct _SdxGraphicsTextureRegion SdxGraphicsTextureRegion;
typedef SdxGraphicsTextureRegion SdxGraphicsTextureRegionFromTexture;
typedef SdxGraphicsTextureRegionFromTexture SdxGraphicsAtlasRegion;
// symtbl.1 _g_list_free__sdx_graphics_texture_region
#define __g_list_free__sdx_graphics_texture_region_release0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__sdx_graphics_texture_region_release0_ (var), NULL)))
typedef struct _SdxFilesFileHandle SdxFilesFileHandle;
// symtbl.1 sdx_files_file_handle
void sdx_files_file_handle_release (SdxFilesFileHandle* self);
void sdx_files_file_handle_free (SdxFilesFileHandle* self);
SdxFilesFileHandle* sdx_files_file_handle_retain (SdxFilesFileHandle* self);
#define _sdx_files_file_handle_release0(var) ((var == NULL) ? NULL : (var = (sdx_files_file_handle_release (var), NULL)))
typedef struct _SdxGraphicsTextureAtlasData SdxGraphicsTextureAtlasData;
// symtbl.1 sdx_graphics_texture_atlas_data
void sdx_graphics_texture_atlas_data_release (SdxGraphicsTextureAtlasData* self);
void sdx_graphics_texture_atlas_data_free (SdxGraphicsTextureAtlasData* self);
SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_retain (SdxGraphicsTextureAtlasData* self);
#define _sdx_graphics_texture_atlas_data_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_texture_atlas_data_release (var), NULL)))
typedef struct _SdxGraphicsSurface SdxGraphicsSurface;
typedef SdxGraphicsSurface SdxGraphicsSurfaceTextureSurface;
// symtbl.1 sdx_graphics_texture_region
void sdx_graphics_texture_region_release (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion* self);
SdxGraphicsTextureRegion* sdx_graphics_texture_region_retain (SdxGraphicsTextureRegion* self);
#define _sdx_graphics_texture_region_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_texture_region_release (var), NULL)))
typedef struct _SdxGraphicsSprite SdxGraphicsSprite;
typedef SdxGraphicsSprite SdxGraphicsSpriteAtlasSprite;
typedef struct _SdxFont SdxFont;
typedef struct _SdxGraphicsNinePatch SdxGraphicsNinePatch;
typedef SdxGraphicsSprite SdxGraphicsSpriteUISprite;
// symtbl.1 sdx_graphics_nine_patch
void sdx_graphics_nine_patch_release (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_free (SdxGraphicsNinePatch* self);
SdxGraphicsNinePatch* sdx_graphics_nine_patch_retain (SdxGraphicsNinePatch* self);
#define _sdx_graphics_nine_patch_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_nine_patch_release (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _SdxGraphicsPage SdxGraphicsPage;
typedef struct _SdxGraphicsRegion SdxGraphicsRegion;

#define SDX_GRAPHICS_TYPE_FORMAT (sdx_graphics_format_get_type ())
// symtbl.1 sdx_graphics_surface
void sdx_graphics_surface_release (SdxGraphicsSurface* self);
void sdx_graphics_surface_free (SdxGraphicsSurface* self);
SdxGraphicsSurface* sdx_graphics_surface_retain (SdxGraphicsSurface* self);
#define _sdx_graphics_surface_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_surface_release (var), NULL)))
// symtbl.1 sdx_graphics_page
void sdx_graphics_page_release (SdxGraphicsPage* self);
void sdx_graphics_page_free (SdxGraphicsPage* self);
SdxGraphicsPage* sdx_graphics_page_retain (SdxGraphicsPage* self);
#define _sdx_graphics_page_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_page_release (var), NULL)))
// symtbl.1 sdx_graphics_region
void sdx_graphics_region_release (SdxGraphicsRegion* self);
void sdx_graphics_region_free (SdxGraphicsRegion* self);
SdxGraphicsRegion* sdx_graphics_region_retain (SdxGraphicsRegion* self);
#define _sdx_graphics_region_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_region_release (var), NULL)))
// symtbl.1 _g_list_free__sdx_graphics_page
#define __g_list_free__sdx_graphics_page_release0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__sdx_graphics_page_release0_ (var), NULL)))
// symtbl.1 _g_list_free__sdx_graphics_region
#define __g_list_free__sdx_graphics_region_release0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__sdx_graphics_region_release0_ (var), NULL)))
typedef struct _SdxDataInputStream SdxDataInputStream;

#define SDX_GRAPHICS_TYPE_TEXTURE_FILTER (sdx_graphics_texture_filter_get_type ())

#define SDX_GRAPHICS_TYPE_TEXTURE_WRAP (sdx_graphics_texture_wrap_get_type ())
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
// symtbl.1 sdx_data_input_stream
void sdx_data_input_stream_release (SdxDataInputStream* self);
void sdx_data_input_stream_free (SdxDataInputStream* self);
SdxDataInputStream* sdx_data_input_stream_retain (SdxDataInputStream* self);
#define _sdx_data_input_stream_release0(var) ((var == NULL) ? NULL : (var = (sdx_data_input_stream_release (var), NULL)))

struct _SdxGraphicsTextureAtlas {
	gint ref_count;
	GList* regions;
};

struct _SdxGraphicsTextureRegion {
	gint ref_count;
	SdxGraphicsSurfaceTextureSurface* texture;
	gint top;
	gint left;
	gint width;
	gint height;
	gint regionWidth;
	gint regionHeight;
	gfloat u;
	gfloat v;
	gfloat u2;
	gfloat v2;
	gint index;
	gchar* name;
	gint offsetX;
	gint offsetY;
	gint packedWidth;
	gint packedHeight;
	gint originalWidth;
	gint originalHeight;
	gboolean rotate;
	gint* splits;
	gint splits_length1;
	gint* pads;
	gint pads_length1;
};

typedef enum  {
	SDX_SDL_EXCEPTION_Initialization,
	SDX_SDL_EXCEPTION_ImageInitialization,
	SDX_SDL_EXCEPTION_TtfInitialization,
	SDX_SDL_EXCEPTION_TextureFilteringNotEnabled,
	SDX_SDL_EXCEPTION_OpenWindow,
	SDX_SDL_EXCEPTION_CreateRenderer,
	SDX_SDL_EXCEPTION_InvalidForPlatform,
	SDX_SDL_EXCEPTION_UnableToLoadResource,
	SDX_SDL_EXCEPTION_UnableToLoadSurface,
	SDX_SDL_EXCEPTION_UnableToLoadTexture,
	SDX_SDL_EXCEPTION_NullPointer,
	SDX_SDL_EXCEPTION_NoSuchElement,
	SDX_SDL_EXCEPTION_IllegalStateException,
	SDX_SDL_EXCEPTION_IllegalArgumentException,
	SDX_SDL_EXCEPTION_RuntimeException,
	SDX_SDL_EXCEPTION_NotReached
} SdxSdlException;
#define SDX_SDL_EXCEPTION sdx_sdl_exception_quark ()
struct _SdxGraphicsTextureAtlasData {
	gint ref_count;
	GList* pages;
	GList* regions;
};

typedef enum  {
	SDX_GRAPHICS_FORMAT_Alpha,
	SDX_GRAPHICS_FORMAT_Intensity,
	SDX_GRAPHICS_FORMAT_LuminanceAlpha,
	SDX_GRAPHICS_FORMAT_RGB565,
	SDX_GRAPHICS_FORMAT_RGBA4444,
	SDX_GRAPHICS_FORMAT_RGB888,
	SDX_GRAPHICS_FORMAT_RGBA8888
} SdxGraphicsFormat;

struct _SdxGraphicsPage {
	gint ref_count;
	gint id;
	SdxFilesFileHandle* textureFile;
	SdxGraphicsSurfaceTextureSurface* texture;
	gint height;
	gint width;
	gboolean useMipMaps;
	SdxGraphicsFormat format;
	gint minFilter;
	gint magFilter;
	gint uWrap;
	gint vWrap;
};

struct _SdxGraphicsRegion {
	gint ref_count;
	SdxGraphicsPage* page;
	gint index;
	gchar* name;
	gint offsetX;
	gint offsetY;
	gint originalWidth;
	gint originalHeight;
	gboolean rotate;
	gint left;
	gint top;
	gint width;
	gint height;
	gboolean flip;
	gint* splits;
	gint splits_length1;
	gint* pads;
	gint pads_length1;
	gboolean slice9;
};

typedef enum  {
	SDX_IO_EXCEPTION_InvalidData
} SdxIOException;
#define SDX_IO_EXCEPTION sdx_io_exception_quark ()
typedef enum  {
	SDX_GRAPHICS_TEXTURE_FILTER_Nearest,
	SDX_GRAPHICS_TEXTURE_FILTER_Linear,
	SDX_GRAPHICS_TEXTURE_FILTER_MipMap,
	SDX_GRAPHICS_TEXTURE_FILTER_MipMapNearestNearest,
	SDX_GRAPHICS_TEXTURE_FILTER_MipMapLinearNearest,
	SDX_GRAPHICS_TEXTURE_FILTER_MipMapNearestLinear,
	SDX_GRAPHICS_TEXTURE_FILTER_MipMapLinearLinear
} SdxGraphicsTextureFilter;

typedef enum  {
	SDX_GRAPHICS_TEXTURE_WRAP_ClampToEdge = 1,
	SDX_GRAPHICS_TEXTURE_WRAP_Repeat = 2
} SdxGraphicsTextureWrap;


extern gint sdx_graphics_page_uniqueId;
gint sdx_graphics_page_uniqueId = 0;
extern SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_instance;
SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_instance = NULL;
extern gchar** sdx_graphics_texture_atlas_data_tuple;
extern gint sdx_graphics_texture_atlas_data_tuple_length1;
gchar** sdx_graphics_texture_atlas_data_tuple = NULL;
gint sdx_graphics_texture_atlas_data_tuple_length1 = 0;

void sdx_graphics_texture_atlas_free (SdxGraphicsTextureAtlas* self);
void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion* self);
static void sdx_graphics_texture_atlas_instance_init (SdxGraphicsTextureAtlas * self);
// symtbl.2 sdx_graphics_texture_region
void sdx_graphics_texture_region_release (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion* self);
SdxGraphicsTextureRegion* sdx_graphics_texture_region_retain (SdxGraphicsTextureRegion* self);
static void _sdx_graphics_texture_region_release0_ (gpointer var);
// symtbl.2 g_list_free__sdx_graphics_texture_region
static void _g_list_free__sdx_graphics_texture_region_release0_ (GList* self);
SdxGraphicsTextureAtlas* sdx_graphics_texture_atlas_retain (SdxGraphicsTextureAtlas* self);
void sdx_graphics_texture_atlas_release (SdxGraphicsTextureAtlas* self);
void sdx_graphics_texture_atlas_free (SdxGraphicsTextureAtlas* self);
void sdx_files_file_handle_free (SdxFilesFileHandle* self);
// symtbl.3 SdxGraphicsTextureAtlas / sdx_graphics_texture_atlas
SdxGraphicsTextureAtlas* sdx_graphics_texture_atlas_retain (SdxGraphicsTextureAtlas* self);
void sdx_graphics_texture_atlas_release (SdxGraphicsTextureAtlas* self);
SdxGraphicsTextureAtlas* sdx_graphics_texture_atlas_new (SdxFilesFileHandle* packFile, SdxFilesFileHandle* imageDir, gboolean flip);
SdxFilesFileHandle* sdx_files_file_handle_GetParent (SdxFilesFileHandle* self);
void sdx_graphics_texture_atlas_data_free (SdxGraphicsTextureAtlasData* self);
void sdx_graphics_texture_atlas_Load (SdxGraphicsTextureAtlas* self, SdxGraphicsTextureAtlasData* data);
// symtbl.3 SdxGraphicsTextureAtlasData / sdx_graphics_texture_atlas_data
SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_retain (SdxGraphicsTextureAtlasData* self);
void sdx_graphics_texture_atlas_data_release (SdxGraphicsTextureAtlasData* self);
SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_new (SdxFilesFileHandle* packFile, SdxFilesFileHandle* imagesDir, gboolean flip);
SdxGraphicsAtlasRegion* sdx_graphics_texture_atlas_FindRegion (SdxGraphicsTextureAtlas* self, const gchar* name, gint index);
void sdx_graphics_surface_free (SdxGraphicsSurface* self);
void sdx_graphics_sprite_free (SdxGraphicsSprite* self);
SdxGraphicsSprite* sdx_graphics_texture_atlas_CreateSprite (SdxGraphicsTextureAtlas* self, const gchar* name, gint index);
// symtbl.3 SdxGraphicsSpriteAtlasSprite / sdx_graphics_sprite_atlas_sprite
SdxGraphicsSpriteAtlasSprite* sdx_graphics_sprite_atlas_sprite_new (SdxGraphicsAtlasRegion* region);
void sdx_font_free (SdxFont* self);
SdxGraphicsSprite* sdx_graphics_texture_atlas_CreateUI (SdxGraphicsTextureAtlas* self, const gchar* name, const gchar* text, SdxFont* font, SDL_Color color, gint width, gint height);
void sdx_graphics_nine_patch_free (SdxGraphicsNinePatch* self);
SdxGraphicsNinePatch* sdx_graphics_texture_atlas_CreatePatch (SdxGraphicsTextureAtlas* self, const gchar* name);
// symtbl.3 SdxGraphicsSpriteUISprite / sdx_graphics_sprite_ui_sprite
SdxGraphicsSpriteUISprite* sdx_graphics_sprite_ui_sprite_new (SdxGraphicsNinePatch* patch, const gchar* text, SdxFont* font, SDL_Color color, gint width, gint height);
static gint* _vala_array_dup3 (gint* self, int length);
GQuark sdx_sdl_exception_quark (void);
// symtbl.3 SdxGraphicsNinePatch / sdx_graphics_nine_patch
SdxGraphicsNinePatch* sdx_graphics_nine_patch_retain (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_release (SdxGraphicsNinePatch* self);
SdxGraphicsNinePatch* sdx_graphics_nine_patch_new (SdxGraphicsTextureRegion* region, gint left, gint right, gint top, gint bottom);
void sdx_graphics_page_free (SdxGraphicsPage* self);
void sdx_graphics_region_free (SdxGraphicsRegion* self);
GType sdx_graphics_format_get_type (void) G_GNUC_CONST;
// symtbl.3 SdxGraphicsSurfaceTextureSurface / sdx_graphics_surface_texture_surface
SdxGraphicsSurfaceTextureSurface* sdx_graphics_surface_texture_surface_new (SdxFilesFileHandle* file);
void sdx_graphics_surface_texture_surface_SetFilter (SdxGraphicsSurfaceTextureSurface* self, gint minFilter, gint magFilter);
void sdx_graphics_surface_texture_surface_SetWrap (SdxGraphicsSurfaceTextureSurface* self, gint u, gint v);
static void _vala_array_add8 (SdxGraphicsSurfaceTextureSurface*** array, int* length, int* size, SdxGraphicsSurfaceTextureSurface* value);
// symtbl.3 SdxGraphicsAtlasRegion / sdx_graphics_atlas_region
SdxGraphicsAtlasRegion* sdx_graphics_atlas_region_retain (SdxGraphicsAtlasRegion* self);
void sdx_graphics_atlas_region_release (SdxGraphicsAtlasRegion* self);
SdxGraphicsAtlasRegion* sdx_graphics_atlas_region_new (SdxGraphicsSurfaceTextureSurface* texture, gint x, gint y, gint width, gint height);
static gint* _vala_array_dup4 (gint* self, int length);
static gint* _vala_array_dup5 (gint* self, int length);
void sdx_graphics_texture_region_Flip (SdxGraphicsTextureRegion* self, gboolean x, gboolean y);
// symtbl.3 SdxGraphicsTextureRegionFromTexture / sdx_graphics_texture_region_from_texture
SdxGraphicsTextureRegionFromTexture* sdx_graphics_texture_region_from_texture_new (SdxGraphicsSurfaceTextureSurface* texture, gint x, gint y, gint width, gint height);
static void sdx_graphics_page_instance_init (SdxGraphicsPage * self);
SdxGraphicsPage* sdx_graphics_page_retain (SdxGraphicsPage* self);
void sdx_graphics_page_release (SdxGraphicsPage* self);
void sdx_graphics_page_free (SdxGraphicsPage* self);
// symtbl.3 SdxGraphicsPage / sdx_graphics_page
SdxGraphicsPage* sdx_graphics_page_retain (SdxGraphicsPage* self);
void sdx_graphics_page_release (SdxGraphicsPage* self);
SdxGraphicsPage* sdx_graphics_page_new (SdxFilesFileHandle* handle, gint width, gint height, gboolean useMipMaps, SdxGraphicsFormat format, gint minFilter, gint magFilter, gint uWrap, gint vWrap);
static void sdx_graphics_region_instance_init (SdxGraphicsRegion * self);
SdxGraphicsRegion* sdx_graphics_region_retain (SdxGraphicsRegion* self);
void sdx_graphics_region_release (SdxGraphicsRegion* self);
void sdx_graphics_region_free (SdxGraphicsRegion* self);
// symtbl.3 SdxGraphicsRegion / sdx_graphics_region
SdxGraphicsRegion* sdx_graphics_region_retain (SdxGraphicsRegion* self);
void sdx_graphics_region_release (SdxGraphicsRegion* self);
SdxGraphicsRegion* sdx_graphics_region_new (SdxGraphicsPage* page, gint left, gint top, gint width, gint height, const gchar* name, gboolean rotatate);
static void sdx_graphics_texture_atlas_data_instance_init (SdxGraphicsTextureAtlasData * self);
// symtbl.2 sdx_graphics_page
void sdx_graphics_page_release (SdxGraphicsPage* self);
void sdx_graphics_page_free (SdxGraphicsPage* self);
SdxGraphicsPage* sdx_graphics_page_retain (SdxGraphicsPage* self);
static void _sdx_graphics_page_release0_ (gpointer var);
// symtbl.2 g_list_free__sdx_graphics_page
static void _g_list_free__sdx_graphics_page_release0_ (GList* self);
// symtbl.2 sdx_graphics_region
void sdx_graphics_region_release (SdxGraphicsRegion* self);
void sdx_graphics_region_free (SdxGraphicsRegion* self);
SdxGraphicsRegion* sdx_graphics_region_retain (SdxGraphicsRegion* self);
static void _sdx_graphics_region_release0_ (gpointer var);
// symtbl.2 g_list_free__sdx_graphics_region
static void _g_list_free__sdx_graphics_region_release0_ (GList* self);
SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_retain (SdxGraphicsTextureAtlasData* self);
void sdx_graphics_texture_atlas_data_release (SdxGraphicsTextureAtlasData* self);
void sdx_graphics_texture_atlas_data_free (SdxGraphicsTextureAtlasData* self);
void sdx_data_input_stream_free (SdxDataInputStream* self);
gint sdx_graphics_texture_atlas_data_ReadTuple (SdxDataInputStream* reader);
gchar* sdx_data_input_stream_ReadLine (SdxDataInputStream* self);
GQuark sdx_io_exception_quark (void);
gchar* sdx_graphics_texture_atlas_data_ReadValue (SdxDataInputStream* reader);
gchar* sdx_files_file_handle_Read (SdxFilesFileHandle* self);
// symtbl.3 SdxDataInputStream / sdx_data_input_stream
SdxDataInputStream* sdx_data_input_stream_retain (SdxDataInputStream* self);
void sdx_data_input_stream_release (SdxDataInputStream* self);
SdxDataInputStream* sdx_data_input_stream_new (const gchar* data);
SdxFilesFileHandle* sdx_files_file_handle_Child (SdxFilesFileHandle* self, const gchar* name);
SdxGraphicsFormat sdx_graphics_format_from (const gchar* value);
GType sdx_graphics_texture_filter_get_type (void) G_GNUC_CONST;
SdxGraphicsTextureFilter sdx_graphics_texture_filter_from (const gchar* value);
GType sdx_graphics_texture_wrap_get_type (void) G_GNUC_CONST;
gboolean sdx_graphics_texture_filter_isMipMap (SdxGraphicsTextureFilter self);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


// symtbl.2 sdx_graphics_texture_region
void sdx_graphics_texture_region_release (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion* self);
SdxGraphicsTextureRegion* sdx_graphics_texture_region_retain (SdxGraphicsTextureRegion* self);
static void _sdx_graphics_texture_region_release0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (sdx_graphics_texture_region_release (var), NULL));
}


// symtbl.2 g_list_free__sdx_graphics_texture_region
static void _g_list_free__sdx_graphics_texture_region_release0_ (GList* self) {
	g_list_foreach (self, (GFunc) _sdx_graphics_texture_region_release0_, NULL);
	g_list_free (self);
}


SdxGraphicsTextureAtlas* sdx_graphics_texture_atlas_retain (SdxGraphicsTextureAtlas* self) {
	SdxGraphicsTextureAtlas* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void sdx_graphics_texture_atlas_release (SdxGraphicsTextureAtlas* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		sdx_graphics_texture_atlas_free (self);
	}
}


/**
         * @param packFile handle
         * @param imageDir handle
         * @param flip images?
         */
static gpointer _sdx_files_file_handle_retain0 (gpointer self) {
	return self ? sdx_files_file_handle_retain (self) : NULL;
}


// symtbl.3 SdxGraphicsTextureAtlas / sdx_graphics_texture_atlas
SdxGraphicsTextureAtlas* sdx_graphics_texture_atlas_retain (SdxGraphicsTextureAtlas* self);
void sdx_graphics_texture_atlas_release (SdxGraphicsTextureAtlas* self);
SdxGraphicsTextureAtlas* sdx_graphics_texture_atlas_new (SdxFilesFileHandle* packFile, SdxFilesFileHandle* imageDir, gboolean flip) {
	SdxGraphicsTextureAtlas* self;
	SdxFilesFileHandle* _tmp0_ = NULL;
	SdxFilesFileHandle* _tmp1_ = NULL;
	SdxFilesFileHandle* _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	SdxGraphicsTextureAtlasData* _tmp8_ = NULL;
	SdxGraphicsTextureAtlasData* _tmp9_ = NULL;
	g_return_val_if_fail (packFile != NULL, NULL);
	self = g_slice_new0 (SdxGraphicsTextureAtlas);
	sdx_graphics_texture_atlas_instance_init (self);
	_tmp1_ = imageDir;
	if (_tmp1_ == NULL) {
		SdxFilesFileHandle* _tmp2_ = NULL;
		SdxFilesFileHandle* _tmp3_ = NULL;
		_tmp2_ = packFile;
		_tmp3_ = sdx_files_file_handle_GetParent (_tmp2_);
		_sdx_files_file_handle_release0 (_tmp0_);
		_tmp0_ = _tmp3_;
	} else {
		SdxFilesFileHandle* _tmp4_ = NULL;
		SdxFilesFileHandle* _tmp5_ = NULL;
		_tmp4_ = imageDir;
		_tmp5_ = _sdx_files_file_handle_retain0 (_tmp4_);
		_sdx_files_file_handle_release0 (_tmp0_);
		_tmp0_ = _tmp5_;
	}
	_tmp6_ = packFile;
	_tmp7_ = flip;
	_tmp8_ = sdx_graphics_texture_atlas_data_new (_tmp6_, _tmp0_, _tmp7_);
	_tmp9_ = _tmp8_;
	sdx_graphics_texture_atlas_Load (self, _tmp9_);
	_sdx_graphics_texture_atlas_data_release0 (_tmp9_);
	_sdx_files_file_handle_release0 (_tmp0_);
	return self;
}


static gpointer _sdx_graphics_texture_region_retain0 (gpointer self) {
	return self ? sdx_graphics_texture_region_retain (self) : NULL;
}


SdxGraphicsAtlasRegion* sdx_graphics_texture_atlas_FindRegion (SdxGraphicsTextureAtlas* self, const gchar* name, gint index) {
	SdxGraphicsAtlasRegion* result = NULL;
	GList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = self->regions;
	{
		GList* region_collection = NULL;
		GList* region_it = NULL;
		region_collection = _tmp0_;
		for (region_it = region_collection; region_it != NULL; region_it = region_it->next) {
			SdxGraphicsAtlasRegion* _tmp1_ = NULL;
			SdxGraphicsAtlasRegion* region = NULL;
			_tmp1_ = _sdx_graphics_texture_region_retain0 ((SdxGraphicsAtlasRegion*) region_it->data);
			region = _tmp1_;
			{
				gint _tmp2_ = 0;
				_tmp2_ = index;
				if (_tmp2_ == -1) {
					SdxGraphicsAtlasRegion* _tmp3_ = NULL;
					const gchar* _tmp4_ = NULL;
					const gchar* _tmp5_ = NULL;
					_tmp3_ = region;
					_tmp4_ = ((SdxGraphicsTextureRegion*) _tmp3_)->name;
					_tmp5_ = name;
					if (g_strcmp0 (_tmp4_, _tmp5_) == 0) {
						result = region;
						return result;
					}
				} else {
					gboolean _tmp6_ = FALSE;
					SdxGraphicsAtlasRegion* _tmp7_ = NULL;
					const gchar* _tmp8_ = NULL;
					const gchar* _tmp9_ = NULL;
					_tmp7_ = region;
					_tmp8_ = ((SdxGraphicsTextureRegion*) _tmp7_)->name;
					_tmp9_ = name;
					if (g_strcmp0 (_tmp8_, _tmp9_) == 0) {
						SdxGraphicsAtlasRegion* _tmp10_ = NULL;
						gint _tmp11_ = 0;
						gint _tmp12_ = 0;
						_tmp10_ = region;
						_tmp11_ = ((SdxGraphicsTextureRegion*) _tmp10_)->index;
						_tmp12_ = index;
						_tmp6_ = _tmp11_ == _tmp12_;
					} else {
						_tmp6_ = FALSE;
					}
					if (_tmp6_) {
						result = region;
						return result;
					}
				}
				_sdx_graphics_texture_region_release0 (region);
			}
		}
	}
	result = NULL;
	return result;
}


SdxGraphicsSprite* sdx_graphics_texture_atlas_CreateSprite (SdxGraphicsTextureAtlas* self, const gchar* name, gint index) {
	SdxGraphicsSprite* result = NULL;
	GList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = self->regions;
	{
		GList* region_collection = NULL;
		GList* region_it = NULL;
		region_collection = _tmp0_;
		for (region_it = region_collection; region_it != NULL; region_it = region_it->next) {
			SdxGraphicsAtlasRegion* _tmp1_ = NULL;
			SdxGraphicsAtlasRegion* region = NULL;
			_tmp1_ = _sdx_graphics_texture_region_retain0 ((SdxGraphicsAtlasRegion*) region_it->data);
			region = _tmp1_;
			{
				gint _tmp2_ = 0;
				_tmp2_ = index;
				if (_tmp2_ == -1) {
					SdxGraphicsAtlasRegion* _tmp3_ = NULL;
					const gchar* _tmp4_ = NULL;
					const gchar* _tmp5_ = NULL;
					_tmp3_ = region;
					_tmp4_ = ((SdxGraphicsTextureRegion*) _tmp3_)->name;
					_tmp5_ = name;
					if (g_strcmp0 (_tmp4_, _tmp5_) == 0) {
						SdxGraphicsAtlasRegion* _tmp6_ = NULL;
						SdxGraphicsSpriteAtlasSprite* _tmp7_ = NULL;
						_tmp6_ = region;
						_tmp7_ = sdx_graphics_sprite_atlas_sprite_new (_tmp6_);
						result = (SdxGraphicsSprite*) _tmp7_;
						_sdx_graphics_texture_region_release0 (region);
						return result;
					}
				} else {
					gboolean _tmp8_ = FALSE;
					SdxGraphicsAtlasRegion* _tmp9_ = NULL;
					const gchar* _tmp10_ = NULL;
					const gchar* _tmp11_ = NULL;
					_tmp9_ = region;
					_tmp10_ = ((SdxGraphicsTextureRegion*) _tmp9_)->name;
					_tmp11_ = name;
					if (g_strcmp0 (_tmp10_, _tmp11_) == 0) {
						SdxGraphicsAtlasRegion* _tmp12_ = NULL;
						gint _tmp13_ = 0;
						gint _tmp14_ = 0;
						_tmp12_ = region;
						_tmp13_ = ((SdxGraphicsTextureRegion*) _tmp12_)->index;
						_tmp14_ = index;
						_tmp8_ = _tmp13_ == _tmp14_;
					} else {
						_tmp8_ = FALSE;
					}
					if (_tmp8_) {
						SdxGraphicsAtlasRegion* _tmp15_ = NULL;
						SdxGraphicsSpriteAtlasSprite* _tmp16_ = NULL;
						_tmp15_ = region;
						_tmp16_ = sdx_graphics_sprite_atlas_sprite_new (_tmp15_);
						result = (SdxGraphicsSprite*) _tmp16_;
						_sdx_graphics_texture_region_release0 (region);
						return result;
					}
				}
				_sdx_graphics_texture_region_release0 (region);
			}
		}
	}
	result = NULL;
	return result;
}


SdxGraphicsSprite* sdx_graphics_texture_atlas_CreateUI (SdxGraphicsTextureAtlas* self, const gchar* name, const gchar* text, SdxFont* font, SDL_Color color, gint width, gint height) {
	SdxGraphicsSprite* result = NULL;
	const gchar* _tmp0_ = NULL;
	SdxGraphicsNinePatch* _tmp1_ = NULL;
	SdxGraphicsNinePatch* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	SdxFont* _tmp4_ = NULL;
	SDL_Color _tmp5_ = {0};
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	SdxGraphicsSpriteUISprite* _tmp8_ = NULL;
	SdxGraphicsSprite* _tmp9_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (font != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = sdx_graphics_texture_atlas_CreatePatch (self, _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = text;
	_tmp4_ = font;
	_tmp5_ = color;
	_tmp6_ = width;
	_tmp7_ = height;
	_tmp8_ = sdx_graphics_sprite_ui_sprite_new (_tmp2_, _tmp3_, _tmp4_, _tmp5_, _tmp6_, _tmp7_);
	_tmp9_ = (SdxGraphicsSprite*) _tmp8_;
	_sdx_graphics_nine_patch_release0 (_tmp2_);
	result = _tmp9_;
	return result;
}


static gint* _vala_array_dup3 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


SdxGraphicsNinePatch* sdx_graphics_texture_atlas_CreatePatch (SdxGraphicsTextureAtlas* self, const gchar* name) {
	SdxGraphicsNinePatch* result = NULL;
	GList* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = self->regions;
	{
		GList* region_collection = NULL;
		GList* region_it = NULL;
		region_collection = _tmp0_;
		for (region_it = region_collection; region_it != NULL; region_it = region_it->next) {
			SdxGraphicsAtlasRegion* _tmp1_ = NULL;
			SdxGraphicsAtlasRegion* region = NULL;
			_tmp1_ = _sdx_graphics_texture_region_retain0 ((SdxGraphicsAtlasRegion*) region_it->data);
			region = _tmp1_;
			{
				SdxGraphicsAtlasRegion* _tmp2_ = NULL;
				const gchar* _tmp3_ = NULL;
				const gchar* _tmp4_ = NULL;
				_tmp2_ = region;
				_tmp3_ = ((SdxGraphicsTextureRegion*) _tmp2_)->name;
				_tmp4_ = name;
				if (g_strcmp0 (_tmp3_, _tmp4_) == 0) {
					gint* splits = NULL;
					SdxGraphicsAtlasRegion* _tmp5_ = NULL;
					gint* _tmp6_ = NULL;
					gint _tmp6__length1 = 0;
					gint* _tmp7_ = NULL;
					gint _tmp7__length1 = 0;
					gint splits_length1 = 0;
					gint _splits_size_ = 0;
					gint* _tmp8_ = NULL;
					gint _tmp8__length1 = 0;
					SdxGraphicsNinePatch* patch = NULL;
					SdxGraphicsAtlasRegion* _tmp14_ = NULL;
					gint* _tmp15_ = NULL;
					gint _tmp15__length1 = 0;
					gint _tmp16_ = 0;
					gint* _tmp17_ = NULL;
					gint _tmp17__length1 = 0;
					gint _tmp18_ = 0;
					gint* _tmp19_ = NULL;
					gint _tmp19__length1 = 0;
					gint _tmp20_ = 0;
					gint* _tmp21_ = NULL;
					gint _tmp21__length1 = 0;
					gint _tmp22_ = 0;
					SdxGraphicsNinePatch* _tmp23_ = NULL;
					_tmp5_ = region;
					_tmp6_ = ((SdxGraphicsTextureRegion*) _tmp5_)->splits;
					_tmp6__length1 = ((SdxGraphicsTextureRegion*) _tmp5_)->splits_length1;
					_tmp7_ = (_tmp6_ != NULL) ? _vala_array_dup3 (_tmp6_, _tmp6__length1) : ((gpointer) _tmp6_);
					_tmp7__length1 = _tmp6__length1;
					splits = _tmp7_;
					splits_length1 = _tmp7__length1;
					_splits_size_ = splits_length1;
					_tmp8_ = splits;
					_tmp8__length1 = splits_length1;
					if (_tmp8_ == NULL) {
						const gchar* _tmp9_ = NULL;
						gchar* _tmp10_ = NULL;
						gchar* _tmp11_ = NULL;
						GError* _tmp12_ = NULL;
						GError* _tmp13_ = NULL;
						_tmp9_ = name;
						_tmp10_ = g_strconcat ("Region does not have ninepatch splits: ", _tmp9_, NULL);
						_tmp11_ = _tmp10_;
						_tmp12_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_IllegalArgumentException, _tmp11_);
						_tmp13_ = _tmp12_;
						_g_free0 (_tmp11_);
						_inner_error_ = _tmp13_;
						splits = (g_free (splits), NULL);
						_sdx_graphics_texture_region_release0 (region);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
					_tmp14_ = region;
					_tmp15_ = splits;
					_tmp15__length1 = splits_length1;
					_tmp16_ = _tmp15_[0];
					_tmp17_ = splits;
					_tmp17__length1 = splits_length1;
					_tmp18_ = _tmp17_[1];
					_tmp19_ = splits;
					_tmp19__length1 = splits_length1;
					_tmp20_ = _tmp19_[2];
					_tmp21_ = splits;
					_tmp21__length1 = splits_length1;
					_tmp22_ = _tmp21_[3];
					_tmp23_ = sdx_graphics_nine_patch_new ((SdxGraphicsTextureRegion*) _tmp14_, _tmp16_, _tmp18_, _tmp20_, _tmp22_);
					patch = _tmp23_;
					result = patch;
					splits = (g_free (splits), NULL);
					_sdx_graphics_texture_region_release0 (region);
					return result;
				}
				_sdx_graphics_texture_region_release0 (region);
			}
		}
	}
	result = NULL;
	return result;
}


static gpointer _sdx_graphics_page_retain0 (gpointer self) {
	return self ? sdx_graphics_page_retain (self) : NULL;
}


static gpointer _sdx_graphics_surface_retain0 (gpointer self) {
	return self ? sdx_graphics_surface_retain (self) : NULL;
}


static void _vala_array_add8 (SdxGraphicsSurfaceTextureSurface*** array, int* length, int* size, SdxGraphicsSurfaceTextureSurface* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (SdxGraphicsSurfaceTextureSurface*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static gpointer _sdx_graphics_region_retain0 (gpointer self) {
	return self ? sdx_graphics_region_retain (self) : NULL;
}


static gint* _vala_array_dup4 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


static gint* _vala_array_dup5 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


void sdx_graphics_texture_atlas_Load (SdxGraphicsTextureAtlas* self, SdxGraphicsTextureAtlasData* data) {
	SdxGraphicsSurfaceTextureSurface* texture = NULL;
	SdxGraphicsSurfaceTextureSurface** pageToTexture = NULL;
	SdxGraphicsSurfaceTextureSurface** _tmp0_ = NULL;
	gint pageToTexture_length1 = 0;
	gint _pageToTexture_size_ = 0;
	SdxGraphicsTextureAtlasData* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
	SdxGraphicsTextureAtlasData* _tmp25_ = NULL;
	GList* _tmp26_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (data != NULL);
	texture = NULL;
	_tmp0_ = g_new0 (SdxGraphicsSurfaceTextureSurface*, 0 + 1);
	pageToTexture = _tmp0_;
	pageToTexture_length1 = 0;
	_pageToTexture_size_ = pageToTexture_length1;
	_tmp1_ = data;
	_tmp2_ = _tmp1_->pages;
	{
		GList* page_collection = NULL;
		GList* page_it = NULL;
		page_collection = _tmp2_;
		for (page_it = page_collection; page_it != NULL; page_it = page_it->next) {
			SdxGraphicsPage* _tmp3_ = NULL;
			SdxGraphicsPage* page = NULL;
			_tmp3_ = _sdx_graphics_page_retain0 ((SdxGraphicsPage*) page_it->data);
			page = _tmp3_;
			{
				SdxGraphicsPage* _tmp4_ = NULL;
				SdxGraphicsSurfaceTextureSurface* _tmp5_ = NULL;
				SdxGraphicsSurfaceTextureSurface* _tmp12_ = NULL;
				SdxGraphicsPage* _tmp13_ = NULL;
				gint _tmp14_ = 0;
				SdxGraphicsPage* _tmp15_ = NULL;
				gint _tmp16_ = 0;
				SdxGraphicsSurfaceTextureSurface* _tmp17_ = NULL;
				SdxGraphicsPage* _tmp18_ = NULL;
				gint _tmp19_ = 0;
				SdxGraphicsPage* _tmp20_ = NULL;
				gint _tmp21_ = 0;
				SdxGraphicsSurfaceTextureSurface** _tmp22_ = NULL;
				gint _tmp22__length1 = 0;
				SdxGraphicsSurfaceTextureSurface* _tmp23_ = NULL;
				SdxGraphicsSurfaceTextureSurface* _tmp24_ = NULL;
				_tmp4_ = page;
				_tmp5_ = _tmp4_->texture;
				if (_tmp5_ == NULL) {
					SdxGraphicsPage* _tmp6_ = NULL;
					SdxFilesFileHandle* _tmp7_ = NULL;
					SdxGraphicsSurfaceTextureSurface* _tmp8_ = NULL;
					_tmp6_ = page;
					_tmp7_ = _tmp6_->textureFile;
					_tmp8_ = sdx_graphics_surface_texture_surface_new (_tmp7_);
					_sdx_graphics_surface_release0 (texture);
					texture = _tmp8_;
				} else {
					SdxGraphicsPage* _tmp9_ = NULL;
					SdxGraphicsSurfaceTextureSurface* _tmp10_ = NULL;
					SdxGraphicsSurfaceTextureSurface* _tmp11_ = NULL;
					_tmp9_ = page;
					_tmp10_ = _tmp9_->texture;
					_tmp11_ = _sdx_graphics_surface_retain0 (_tmp10_);
					_sdx_graphics_surface_release0 (texture);
					texture = _tmp11_;
				}
				_tmp12_ = texture;
				_tmp13_ = page;
				_tmp14_ = _tmp13_->minFilter;
				_tmp15_ = page;
				_tmp16_ = _tmp15_->magFilter;
				sdx_graphics_surface_texture_surface_SetFilter (_tmp12_, _tmp14_, _tmp16_);
				_tmp17_ = texture;
				_tmp18_ = page;
				_tmp19_ = _tmp18_->uWrap;
				_tmp20_ = page;
				_tmp21_ = _tmp20_->vWrap;
				sdx_graphics_surface_texture_surface_SetWrap (_tmp17_, _tmp19_, _tmp21_);
				_tmp22_ = pageToTexture;
				_tmp22__length1 = pageToTexture_length1;
				_tmp23_ = texture;
				_tmp24_ = _sdx_graphics_surface_retain0 (_tmp23_);
				_vala_array_add8 (&pageToTexture, &pageToTexture_length1, &_pageToTexture_size_, _tmp24_);
				_sdx_graphics_page_release0 (page);
			}
		}
	}
	_tmp25_ = data;
	_tmp26_ = _tmp25_->regions;
	{
		GList* region_collection = NULL;
		GList* region_it = NULL;
		region_collection = _tmp26_;
		for (region_it = region_collection; region_it != NULL; region_it = region_it->next) {
			SdxGraphicsRegion* _tmp27_ = NULL;
			SdxGraphicsRegion* region = NULL;
			_tmp27_ = _sdx_graphics_region_retain0 ((SdxGraphicsRegion*) region_it->data);
			region = _tmp27_;
			{
				gint width = 0;
				SdxGraphicsRegion* _tmp28_ = NULL;
				gint _tmp29_ = 0;
				gint height = 0;
				SdxGraphicsRegion* _tmp30_ = NULL;
				gint _tmp31_ = 0;
				gint _tmp32_ = 0;
				SdxGraphicsRegion* _tmp33_ = NULL;
				gboolean _tmp34_ = FALSE;
				gint _tmp37_ = 0;
				SdxGraphicsRegion* _tmp38_ = NULL;
				gboolean _tmp39_ = FALSE;
				SdxGraphicsAtlasRegion* atlasRegion = NULL;
				SdxGraphicsSurfaceTextureSurface** _tmp42_ = NULL;
				gint _tmp42__length1 = 0;
				SdxGraphicsRegion* _tmp43_ = NULL;
				SdxGraphicsPage* _tmp44_ = NULL;
				gint _tmp45_ = 0;
				SdxGraphicsSurfaceTextureSurface* _tmp46_ = NULL;
				SdxGraphicsRegion* _tmp47_ = NULL;
				gint _tmp48_ = 0;
				SdxGraphicsRegion* _tmp49_ = NULL;
				gint _tmp50_ = 0;
				SdxGraphicsAtlasRegion* _tmp51_ = NULL;
				SdxGraphicsAtlasRegion* _tmp52_ = NULL;
				SdxGraphicsRegion* _tmp53_ = NULL;
				gint _tmp54_ = 0;
				SdxGraphicsAtlasRegion* _tmp55_ = NULL;
				SdxGraphicsRegion* _tmp56_ = NULL;
				const gchar* _tmp57_ = NULL;
				gchar* _tmp58_ = NULL;
				SdxGraphicsAtlasRegion* _tmp59_ = NULL;
				SdxGraphicsRegion* _tmp60_ = NULL;
				gint _tmp61_ = 0;
				SdxGraphicsAtlasRegion* _tmp62_ = NULL;
				SdxGraphicsRegion* _tmp63_ = NULL;
				gint _tmp64_ = 0;
				SdxGraphicsAtlasRegion* _tmp65_ = NULL;
				SdxGraphicsRegion* _tmp66_ = NULL;
				gint _tmp67_ = 0;
				SdxGraphicsAtlasRegion* _tmp68_ = NULL;
				SdxGraphicsRegion* _tmp69_ = NULL;
				gint _tmp70_ = 0;
				SdxGraphicsAtlasRegion* _tmp71_ = NULL;
				SdxGraphicsRegion* _tmp72_ = NULL;
				gboolean _tmp73_ = FALSE;
				SdxGraphicsAtlasRegion* _tmp74_ = NULL;
				SdxGraphicsRegion* _tmp75_ = NULL;
				gint* _tmp76_ = NULL;
				gint _tmp76__length1 = 0;
				gint* _tmp77_ = NULL;
				gint _tmp77__length1 = 0;
				SdxGraphicsAtlasRegion* _tmp78_ = NULL;
				SdxGraphicsRegion* _tmp79_ = NULL;
				gint* _tmp80_ = NULL;
				gint _tmp80__length1 = 0;
				gint* _tmp81_ = NULL;
				gint _tmp81__length1 = 0;
				SdxGraphicsRegion* _tmp82_ = NULL;
				gboolean _tmp83_ = FALSE;
				SdxGraphicsAtlasRegion* _tmp85_ = NULL;
				SdxGraphicsAtlasRegion* _tmp86_ = NULL;
				_tmp28_ = region;
				_tmp29_ = _tmp28_->width;
				width = _tmp29_;
				_tmp30_ = region;
				_tmp31_ = _tmp30_->height;
				height = _tmp31_;
				_tmp33_ = region;
				_tmp34_ = _tmp33_->rotate;
				if (_tmp34_) {
					gint _tmp35_ = 0;
					_tmp35_ = height;
					_tmp32_ = _tmp35_;
				} else {
					gint _tmp36_ = 0;
					_tmp36_ = width;
					_tmp32_ = _tmp36_;
				}
				_tmp38_ = region;
				_tmp39_ = _tmp38_->rotate;
				if (_tmp39_) {
					gint _tmp40_ = 0;
					_tmp40_ = width;
					_tmp37_ = _tmp40_;
				} else {
					gint _tmp41_ = 0;
					_tmp41_ = height;
					_tmp37_ = _tmp41_;
				}
				_tmp42_ = pageToTexture;
				_tmp42__length1 = pageToTexture_length1;
				_tmp43_ = region;
				_tmp44_ = _tmp43_->page;
				_tmp45_ = _tmp44_->id;
				_tmp46_ = _tmp42_[_tmp45_];
				_tmp47_ = region;
				_tmp48_ = _tmp47_->left;
				_tmp49_ = region;
				_tmp50_ = _tmp49_->top;
				_tmp51_ = sdx_graphics_atlas_region_new (_tmp46_, _tmp48_, _tmp50_, _tmp32_, _tmp37_);
				atlasRegion = _tmp51_;
				_tmp52_ = atlasRegion;
				_tmp53_ = region;
				_tmp54_ = _tmp53_->index;
				((SdxGraphicsTextureRegion*) _tmp52_)->index = _tmp54_;
				_tmp55_ = atlasRegion;
				_tmp56_ = region;
				_tmp57_ = _tmp56_->name;
				_tmp58_ = g_strdup (_tmp57_);
				_g_free0 (((SdxGraphicsTextureRegion*) _tmp55_)->name);
				((SdxGraphicsTextureRegion*) _tmp55_)->name = _tmp58_;
				_tmp59_ = atlasRegion;
				_tmp60_ = region;
				_tmp61_ = _tmp60_->offsetX;
				((SdxGraphicsTextureRegion*) _tmp59_)->offsetX = _tmp61_;
				_tmp62_ = atlasRegion;
				_tmp63_ = region;
				_tmp64_ = _tmp63_->offsetY;
				((SdxGraphicsTextureRegion*) _tmp62_)->offsetY = _tmp64_;
				_tmp65_ = atlasRegion;
				_tmp66_ = region;
				_tmp67_ = _tmp66_->originalHeight;
				((SdxGraphicsTextureRegion*) _tmp65_)->originalHeight = _tmp67_;
				_tmp68_ = atlasRegion;
				_tmp69_ = region;
				_tmp70_ = _tmp69_->originalWidth;
				((SdxGraphicsTextureRegion*) _tmp68_)->originalWidth = _tmp70_;
				_tmp71_ = atlasRegion;
				_tmp72_ = region;
				_tmp73_ = _tmp72_->rotate;
				((SdxGraphicsTextureRegion*) _tmp71_)->rotate = _tmp73_;
				_tmp74_ = atlasRegion;
				_tmp75_ = region;
				_tmp76_ = _tmp75_->splits;
				_tmp76__length1 = _tmp75_->splits_length1;
				_tmp77_ = (_tmp76_ != NULL) ? _vala_array_dup4 (_tmp76_, _tmp76__length1) : ((gpointer) _tmp76_);
				_tmp77__length1 = _tmp76__length1;
				((SdxGraphicsTextureRegion*) _tmp74_)->splits = (g_free (((SdxGraphicsTextureRegion*) _tmp74_)->splits), NULL);
				((SdxGraphicsTextureRegion*) _tmp74_)->splits = _tmp77_;
				((SdxGraphicsTextureRegion*) _tmp74_)->splits_length1 = _tmp77__length1;
				_tmp78_ = atlasRegion;
				_tmp79_ = region;
				_tmp80_ = _tmp79_->pads;
				_tmp80__length1 = _tmp79_->pads_length1;
				_tmp81_ = (_tmp80_ != NULL) ? _vala_array_dup5 (_tmp80_, _tmp80__length1) : ((gpointer) _tmp80_);
				_tmp81__length1 = _tmp80__length1;
				((SdxGraphicsTextureRegion*) _tmp78_)->pads = (g_free (((SdxGraphicsTextureRegion*) _tmp78_)->pads), NULL);
				((SdxGraphicsTextureRegion*) _tmp78_)->pads = _tmp81_;
				((SdxGraphicsTextureRegion*) _tmp78_)->pads_length1 = _tmp81__length1;
				_tmp82_ = region;
				_tmp83_ = _tmp82_->flip;
				if (_tmp83_) {
					SdxGraphicsAtlasRegion* _tmp84_ = NULL;
					_tmp84_ = atlasRegion;
					sdx_graphics_texture_region_Flip ((SdxGraphicsTextureRegion*) _tmp84_, FALSE, TRUE);
				}
				_tmp85_ = atlasRegion;
				_tmp86_ = _sdx_graphics_texture_region_retain0 (_tmp85_);
				self->regions = g_list_append (self->regions, _tmp86_);
				_sdx_graphics_texture_region_release0 (atlasRegion);
				_sdx_graphics_region_release0 (region);
			}
		}
	}
	pageToTexture = (_vala_array_free (pageToTexture, pageToTexture_length1, (GDestroyNotify) sdx_graphics_surface_release), NULL);
	_sdx_graphics_surface_release0 (texture);
}


static void sdx_graphics_texture_atlas_instance_init (SdxGraphicsTextureAtlas * self) {
	self->ref_count = 1;
	self->regions = NULL;
}


void sdx_graphics_texture_atlas_free (SdxGraphicsTextureAtlas* self) {
	__g_list_free__sdx_graphics_texture_region_release0_0 (self->regions);
	g_slice_free (SdxGraphicsTextureAtlas, self);
}


/** 
         * The number at the end of the original image file name, or -1 if none.
         * 
         * When sprites are packed, if the original file name ends with a number, it is stored as the index and is not considered as
         * part of the sprite's name. This is useful for keeping animation frames in order.
         * @see TextureAtlas.FindRegion
         */
// symtbl.3 SdxGraphicsAtlasRegion / sdx_graphics_atlas_region
SdxGraphicsAtlasRegion* sdx_graphics_atlas_region_retain (SdxGraphicsAtlasRegion* self);
void sdx_graphics_atlas_region_release (SdxGraphicsAtlasRegion* self);
SdxGraphicsAtlasRegion* sdx_graphics_atlas_region_new (SdxGraphicsSurfaceTextureSurface* texture, gint x, gint y, gint width, gint height) {
	SdxGraphicsAtlasRegion* self;
	SdxGraphicsSurfaceTextureSurface* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	g_return_val_if_fail (texture != NULL, NULL);
	_tmp0_ = texture;
	_tmp1_ = x;
	_tmp2_ = y;
	_tmp3_ = width;
	_tmp4_ = height;
	self = (SdxGraphicsAtlasRegion*) sdx_graphics_texture_region_from_texture_new (_tmp0_, _tmp1_, _tmp2_, _tmp3_, _tmp4_);
	return self;
}


SdxGraphicsPage* sdx_graphics_page_retain (SdxGraphicsPage* self) {
	SdxGraphicsPage* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void sdx_graphics_page_release (SdxGraphicsPage* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		sdx_graphics_page_free (self);
	}
}


// symtbl.3 SdxGraphicsPage / sdx_graphics_page
SdxGraphicsPage* sdx_graphics_page_retain (SdxGraphicsPage* self);
void sdx_graphics_page_release (SdxGraphicsPage* self);
SdxGraphicsPage* sdx_graphics_page_new (SdxFilesFileHandle* handle, gint width, gint height, gboolean useMipMaps, SdxGraphicsFormat format, gint minFilter, gint magFilter, gint uWrap, gint vWrap) {
	SdxGraphicsPage* self;
	gint _tmp0_ = 0;
	SdxFilesFileHandle* _tmp1_ = NULL;
	SdxFilesFileHandle* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gboolean _tmp5_ = FALSE;
	SdxGraphicsFormat _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	g_return_val_if_fail (handle != NULL, NULL);
	self = g_slice_new0 (SdxGraphicsPage);
	sdx_graphics_page_instance_init (self);
	_tmp0_ = sdx_graphics_page_uniqueId;
	sdx_graphics_page_uniqueId = _tmp0_ + 1;
	self->id = _tmp0_;
	_tmp1_ = handle;
	_tmp2_ = _sdx_files_file_handle_retain0 (_tmp1_);
	_sdx_files_file_handle_release0 (self->textureFile);
	self->textureFile = _tmp2_;
	_tmp3_ = height;
	self->height = _tmp3_;
	_tmp4_ = width;
	self->width = _tmp4_;
	_tmp5_ = useMipMaps;
	self->useMipMaps = _tmp5_;
	_tmp6_ = format;
	self->format = _tmp6_;
	_tmp7_ = minFilter;
	self->minFilter = _tmp7_;
	_tmp8_ = magFilter;
	self->magFilter = _tmp8_;
	_tmp9_ = uWrap;
	self->uWrap = _tmp9_;
	_tmp10_ = vWrap;
	self->vWrap = _tmp10_;
	return self;
}


static void sdx_graphics_page_instance_init (SdxGraphicsPage * self) {
	self->ref_count = 1;
}


void sdx_graphics_page_free (SdxGraphicsPage* self) {
	_sdx_files_file_handle_release0 (self->textureFile);
	_sdx_graphics_surface_release0 (self->texture);
	g_slice_free (SdxGraphicsPage, self);
}


SdxGraphicsRegion* sdx_graphics_region_retain (SdxGraphicsRegion* self) {
	SdxGraphicsRegion* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void sdx_graphics_region_release (SdxGraphicsRegion* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		sdx_graphics_region_free (self);
	}
}


// symtbl.3 SdxGraphicsRegion / sdx_graphics_region
SdxGraphicsRegion* sdx_graphics_region_retain (SdxGraphicsRegion* self);
void sdx_graphics_region_release (SdxGraphicsRegion* self);
SdxGraphicsRegion* sdx_graphics_region_new (SdxGraphicsPage* page, gint left, gint top, gint width, gint height, const gchar* name, gboolean rotatate) {
	SdxGraphicsRegion* self;
	SdxGraphicsPage* _tmp0_ = NULL;
	SdxGraphicsPage* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	g_return_val_if_fail (page != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	self = g_slice_new0 (SdxGraphicsRegion);
	sdx_graphics_region_instance_init (self);
	_tmp0_ = page;
	_tmp1_ = _sdx_graphics_page_retain0 (_tmp0_);
	_sdx_graphics_page_release0 (self->page);
	self->page = _tmp1_;
	_tmp2_ = left;
	self->left = _tmp2_;
	_tmp3_ = top;
	self->top = _tmp3_;
	_tmp4_ = width;
	self->width = _tmp4_;
	_tmp5_ = height;
	self->height = _tmp5_;
	_tmp6_ = name;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (self->name);
	self->name = _tmp7_;
	_tmp8_ = self->rotate;
	self->rotate = _tmp8_;
	self->slice9 = FALSE;
	return self;
}


static void sdx_graphics_region_instance_init (SdxGraphicsRegion * self) {
	self->ref_count = 1;
}


void sdx_graphics_region_free (SdxGraphicsRegion* self) {
	_sdx_graphics_page_release0 (self->page);
	_g_free0 (self->name);
	self->splits = (g_free (self->splits), NULL);
	self->pads = (g_free (self->pads), NULL);
	g_slice_free (SdxGraphicsRegion, self);
}


// symtbl.2 sdx_graphics_page
void sdx_graphics_page_release (SdxGraphicsPage* self);
void sdx_graphics_page_free (SdxGraphicsPage* self);
SdxGraphicsPage* sdx_graphics_page_retain (SdxGraphicsPage* self);
static void _sdx_graphics_page_release0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (sdx_graphics_page_release (var), NULL));
}


// symtbl.2 g_list_free__sdx_graphics_page
static void _g_list_free__sdx_graphics_page_release0_ (GList* self) {
	g_list_foreach (self, (GFunc) _sdx_graphics_page_release0_, NULL);
	g_list_free (self);
}


// symtbl.2 sdx_graphics_region
void sdx_graphics_region_release (SdxGraphicsRegion* self);
void sdx_graphics_region_free (SdxGraphicsRegion* self);
SdxGraphicsRegion* sdx_graphics_region_retain (SdxGraphicsRegion* self);
static void _sdx_graphics_region_release0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (sdx_graphics_region_release (var), NULL));
}


// symtbl.2 g_list_free__sdx_graphics_region
static void _g_list_free__sdx_graphics_region_release0_ (GList* self) {
	g_list_foreach (self, (GFunc) _sdx_graphics_region_release0_, NULL);
	g_list_free (self);
}


SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_retain (SdxGraphicsTextureAtlasData* self) {
	SdxGraphicsTextureAtlasData* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void sdx_graphics_texture_atlas_data_release (SdxGraphicsTextureAtlasData* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		sdx_graphics_texture_atlas_data_free (self);
	}
}


/** 
         * Returns the number of tuple values read (1, 2 or 4). 
         */
gint sdx_graphics_texture_atlas_data_ReadTuple (SdxDataInputStream* reader) {
	gint result = 0;
	gchar* line = NULL;
	SdxDataInputStream* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar** ts = NULL;
	const gchar* _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gchar** _tmp4_ = NULL;
	gint ts_length1 = 0;
	gint _ts_size_ = 0;
	gchar** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gchar** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	const gchar* _tmp10_ = NULL;
	gchar** _tmp11_ = NULL;
	gchar** _tmp12_ = NULL;
	gchar** _tmp24_ = NULL;
	gint _tmp24__length1 = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (reader != NULL, 0);
	_tmp0_ = reader;
	_tmp1_ = sdx_data_input_stream_ReadLine (_tmp0_);
	line = _tmp1_;
	_tmp2_ = line;
	_tmp4_ = _tmp3_ = g_strsplit (_tmp2_, ":", 0);
	ts = _tmp4_;
	ts_length1 = _vala_array_length (_tmp3_);
	_ts_size_ = ts_length1;
	_tmp5_ = ts;
	_tmp5__length1 = ts_length1;
	if (_tmp5__length1 == 0) {
		const gchar* _tmp6_ = NULL;
		GError* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		_tmp6_ = line;
		_tmp7_ = g_error_new (SDX_IO_EXCEPTION, SDX_IO_EXCEPTION_InvalidData, "invalid line: %s", _tmp6_);
		_inner_error_ = _tmp7_;
		ts = (_vala_array_free (ts, ts_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (line);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp8_;
	}
	_tmp9_ = ts;
	_tmp9__length1 = ts_length1;
	_tmp10_ = _tmp9_[1];
	_tmp12_ = _tmp11_ = g_strsplit (_tmp10_, ",", 0);
	sdx_graphics_texture_atlas_data_tuple = (_vala_array_free (sdx_graphics_texture_atlas_data_tuple, sdx_graphics_texture_atlas_data_tuple_length1, (GDestroyNotify) g_free), NULL);
	sdx_graphics_texture_atlas_data_tuple = _tmp12_;
	sdx_graphics_texture_atlas_data_tuple_length1 = _vala_array_length (_tmp11_);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp13_ = FALSE;
			_tmp13_ = TRUE;
			while (TRUE) {
				gint _tmp15_ = 0;
				gchar** _tmp16_ = NULL;
				gint _tmp16__length1 = 0;
				gchar** _tmp17_ = NULL;
				gint _tmp17__length1 = 0;
				gint _tmp18_ = 0;
				gchar** _tmp19_ = NULL;
				gint _tmp19__length1 = 0;
				gint _tmp20_ = 0;
				const gchar* _tmp21_ = NULL;
				gchar* _tmp22_ = NULL;
				gchar* _tmp23_ = NULL;
				if (!_tmp13_) {
					gint _tmp14_ = 0;
					_tmp14_ = i;
					i = _tmp14_ + 1;
				}
				_tmp13_ = FALSE;
				_tmp15_ = i;
				_tmp16_ = sdx_graphics_texture_atlas_data_tuple;
				_tmp16__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
				if (!(_tmp15_ < _tmp16__length1)) {
					break;
				}
				_tmp17_ = sdx_graphics_texture_atlas_data_tuple;
				_tmp17__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
				_tmp18_ = i;
				_tmp19_ = sdx_graphics_texture_atlas_data_tuple;
				_tmp19__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
				_tmp20_ = i;
				_tmp21_ = _tmp19_[_tmp20_];
				_tmp22_ = g_strdup (_tmp21_);
				_g_free0 (_tmp17_[_tmp18_]);
				_tmp17_[_tmp18_] = _tmp22_;
				_tmp23_ = _tmp17_[_tmp18_];
			}
		}
	}
	_tmp24_ = sdx_graphics_texture_atlas_data_tuple;
	_tmp24__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
	result = _tmp24__length1;
	ts = (_vala_array_free (ts, ts_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (line);
	return result;
}


/** 
         * Returns the single value 
         */
gchar* sdx_graphics_texture_atlas_data_ReadValue (SdxDataInputStream* reader) {
	gchar* result = NULL;
	gchar* line = NULL;
	SdxDataInputStream* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar** ts = NULL;
	const gchar* _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gchar** _tmp4_ = NULL;
	gint ts_length1 = 0;
	gint _ts_size_ = 0;
	gchar** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (reader != NULL, NULL);
	_tmp0_ = reader;
	_tmp1_ = sdx_data_input_stream_ReadLine (_tmp0_);
	line = _tmp1_;
	_tmp2_ = line;
	_tmp4_ = _tmp3_ = g_strsplit (_tmp2_, ":", 0);
	ts = _tmp4_;
	ts_length1 = _vala_array_length (_tmp3_);
	_ts_size_ = ts_length1;
	_tmp5_ = ts;
	_tmp5__length1 = ts_length1;
	if (_tmp5__length1 == 0) {
		const gchar* _tmp6_ = NULL;
		GError* _tmp7_ = NULL;
		_tmp6_ = line;
		_tmp7_ = g_error_new (SDX_IO_EXCEPTION, SDX_IO_EXCEPTION_InvalidData, "invalid line: %s ", _tmp6_);
		_inner_error_ = _tmp7_;
		ts = (_vala_array_free (ts, ts_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (line);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp8_ = ts;
	_tmp8__length1 = ts_length1;
	_tmp9_ = _tmp8_[1];
	_tmp10_ = g_strdup (_tmp9_);
	result = _tmp10_;
	ts = (_vala_array_free (ts, ts_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (line);
	return result;
}


/**
         * @param packFile the atlas file
         * @param imagesDir for the bitmap(s)
         * @param flip vert|horz|none
         */
static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


static gboolean bool_Parse (const gchar* str) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (str != NULL, FALSE);
	_tmp0_ = str;
	if (g_strcmp0 (_tmp0_, "true") == 0) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}


// symtbl.3 SdxGraphicsTextureAtlasData / sdx_graphics_texture_atlas_data
SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_retain (SdxGraphicsTextureAtlasData* self);
void sdx_graphics_texture_atlas_data_release (SdxGraphicsTextureAtlasData* self);
SdxGraphicsTextureAtlasData* sdx_graphics_texture_atlas_data_new (SdxFilesFileHandle* packFile, SdxFilesFileHandle* imagesDir, gboolean flip) {
	SdxGraphicsTextureAtlasData* self;
	SdxDataInputStream* reader = NULL;
	SdxFilesFileHandle* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	SdxDataInputStream* _tmp3_ = NULL;
	SdxDataInputStream* _tmp4_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (packFile != NULL, NULL);
	g_return_val_if_fail (imagesDir != NULL, NULL);
	self = g_slice_new0 (SdxGraphicsTextureAtlasData);
	sdx_graphics_texture_atlas_data_instance_init (self);
	__g_list_free__sdx_graphics_page_release0_0 (self->pages);
	self->pages = NULL;
	__g_list_free__sdx_graphics_region_release0_0 (self->regions);
	self->regions = NULL;
	_tmp0_ = packFile;
	_tmp1_ = sdx_files_file_handle_Read (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = sdx_data_input_stream_new (_tmp2_);
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	reader = _tmp4_;
	{
		SdxGraphicsPage* pageImage = NULL;
		pageImage = NULL;
		while (TRUE) {
			gchar* line = NULL;
			SdxDataInputStream* _tmp5_ = NULL;
			gchar* _tmp6_ = NULL;
			const gchar* _tmp7_ = NULL;
			const gchar* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gint _tmp10_ = 0;
			_tmp5_ = reader;
			_tmp6_ = sdx_data_input_stream_ReadLine (_tmp5_);
			line = _tmp6_;
			_tmp7_ = line;
			if (_tmp7_ == NULL) {
				_g_free0 (line);
				break;
			}
			_tmp8_ = line;
			_tmp9_ = strlen (_tmp8_);
			_tmp10_ = _tmp9_;
			if (_tmp10_ == 0) {
				_sdx_graphics_page_release0 (pageImage);
				pageImage = NULL;
			} else {
				SdxGraphicsPage* _tmp11_ = NULL;
				_tmp11_ = pageImage;
				if (_tmp11_ == NULL) {
					SdxFilesFileHandle* file = NULL;
					SdxFilesFileHandle* _tmp12_ = NULL;
					const gchar* _tmp13_ = NULL;
					SdxFilesFileHandle* _tmp14_ = NULL;
					gint width = 0;
					gint height = 0;
					SdxDataInputStream* _tmp15_ = NULL;
					gint _tmp16_ = 0;
					SdxGraphicsFormat format = 0;
					gchar** _tmp24_ = NULL;
					gint _tmp24__length1 = 0;
					const gchar* _tmp25_ = NULL;
					gchar* _tmp26_ = NULL;
					gchar* _tmp27_ = NULL;
					SdxGraphicsFormat _tmp28_ = 0;
					SdxGraphicsFormat _tmp29_ = 0;
					SdxDataInputStream* _tmp30_ = NULL;
					SdxGraphicsTextureFilter min = 0;
					gchar** _tmp31_ = NULL;
					gint _tmp31__length1 = 0;
					const gchar* _tmp32_ = NULL;
					gchar* _tmp33_ = NULL;
					gchar* _tmp34_ = NULL;
					SdxGraphicsTextureFilter _tmp35_ = 0;
					SdxGraphicsTextureFilter _tmp36_ = 0;
					SdxGraphicsTextureFilter max = 0;
					gchar** _tmp37_ = NULL;
					gint _tmp37__length1 = 0;
					const gchar* _tmp38_ = NULL;
					gchar* _tmp39_ = NULL;
					gchar* _tmp40_ = NULL;
					SdxGraphicsTextureFilter _tmp41_ = 0;
					SdxGraphicsTextureFilter _tmp42_ = 0;
					gchar* direction = NULL;
					SdxDataInputStream* _tmp43_ = NULL;
					gchar* _tmp44_ = NULL;
					SdxGraphicsTextureWrap repeatX = 0;
					SdxGraphicsTextureWrap repeatY = 0;
					const gchar* _tmp45_ = NULL;
					SdxFilesFileHandle* _tmp48_ = NULL;
					gint _tmp49_ = 0;
					gint _tmp50_ = 0;
					SdxGraphicsTextureFilter _tmp51_ = 0;
					gboolean _tmp52_ = FALSE;
					SdxGraphicsFormat _tmp53_ = 0;
					SdxGraphicsTextureFilter _tmp54_ = 0;
					SdxGraphicsTextureFilter _tmp55_ = 0;
					SdxGraphicsTextureWrap _tmp56_ = 0;
					SdxGraphicsTextureWrap _tmp57_ = 0;
					SdxGraphicsPage* _tmp58_ = NULL;
					SdxGraphicsPage* _tmp59_ = NULL;
					SdxGraphicsPage* _tmp60_ = NULL;
					_tmp12_ = imagesDir;
					_tmp13_ = line;
					_tmp14_ = sdx_files_file_handle_Child (_tmp12_, _tmp13_);
					file = _tmp14_;
					width = 0;
					height = 0;
					_tmp15_ = reader;
					_tmp16_ = sdx_graphics_texture_atlas_data_ReadTuple (_tmp15_);
					if (_tmp16_ == 2) {
						gchar** _tmp17_ = NULL;
						gint _tmp17__length1 = 0;
						const gchar* _tmp18_ = NULL;
						gint _tmp19_ = 0;
						gchar** _tmp20_ = NULL;
						gint _tmp20__length1 = 0;
						const gchar* _tmp21_ = NULL;
						gint _tmp22_ = 0;
						SdxDataInputStream* _tmp23_ = NULL;
						_tmp17_ = sdx_graphics_texture_atlas_data_tuple;
						_tmp17__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
						_tmp18_ = _tmp17_[0];
						_tmp19_ = atoi (_tmp18_);
						width = _tmp19_;
						_tmp20_ = sdx_graphics_texture_atlas_data_tuple;
						_tmp20__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
						_tmp21_ = _tmp20_[1];
						_tmp22_ = atoi (_tmp21_);
						height = _tmp22_;
						_tmp23_ = reader;
						sdx_graphics_texture_atlas_data_ReadTuple (_tmp23_);
					}
					_tmp24_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp24__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp25_ = _tmp24_[0];
					_tmp26_ = string_strip (_tmp25_);
					_tmp27_ = _tmp26_;
					_tmp28_ = sdx_graphics_format_from (_tmp27_);
					_tmp29_ = _tmp28_;
					_g_free0 (_tmp27_);
					format = _tmp29_;
					_tmp30_ = reader;
					sdx_graphics_texture_atlas_data_ReadTuple (_tmp30_);
					_tmp31_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp31__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp32_ = _tmp31_[0];
					_tmp33_ = string_strip (_tmp32_);
					_tmp34_ = _tmp33_;
					_tmp35_ = sdx_graphics_texture_filter_from (_tmp34_);
					_tmp36_ = _tmp35_;
					_g_free0 (_tmp34_);
					min = _tmp36_;
					_tmp37_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp37__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp38_ = _tmp37_[1];
					_tmp39_ = string_strip (_tmp38_);
					_tmp40_ = _tmp39_;
					_tmp41_ = sdx_graphics_texture_filter_from (_tmp40_);
					_tmp42_ = _tmp41_;
					_g_free0 (_tmp40_);
					max = _tmp42_;
					_tmp43_ = reader;
					_tmp44_ = sdx_graphics_texture_atlas_data_ReadValue (_tmp43_);
					direction = _tmp44_;
					repeatX = SDX_GRAPHICS_TEXTURE_WRAP_ClampToEdge;
					repeatY = SDX_GRAPHICS_TEXTURE_WRAP_ClampToEdge;
					_tmp45_ = direction;
					if (g_strcmp0 (_tmp45_, "x") == 0) {
						repeatX = SDX_GRAPHICS_TEXTURE_WRAP_Repeat;
					} else {
						const gchar* _tmp46_ = NULL;
						_tmp46_ = direction;
						if (g_strcmp0 (_tmp46_, "y") == 0) {
							repeatY = SDX_GRAPHICS_TEXTURE_WRAP_Repeat;
						} else {
							const gchar* _tmp47_ = NULL;
							_tmp47_ = direction;
							if (g_strcmp0 (_tmp47_, "xy") == 0) {
								repeatX = SDX_GRAPHICS_TEXTURE_WRAP_Repeat;
								repeatY = SDX_GRAPHICS_TEXTURE_WRAP_Repeat;
							}
						}
					}
					_tmp48_ = file;
					_tmp49_ = width;
					_tmp50_ = height;
					_tmp51_ = min;
					_tmp52_ = sdx_graphics_texture_filter_isMipMap (_tmp51_);
					_tmp53_ = format;
					_tmp54_ = min;
					_tmp55_ = max;
					_tmp56_ = repeatX;
					_tmp57_ = repeatY;
					_tmp58_ = sdx_graphics_page_new (_tmp48_, _tmp49_, _tmp50_, _tmp52_, _tmp53_, (gint) _tmp54_, (gint) _tmp55_, (gint) _tmp56_, (gint) _tmp57_);
					_sdx_graphics_page_release0 (pageImage);
					pageImage = _tmp58_;
					_tmp59_ = pageImage;
					_tmp60_ = _sdx_graphics_page_retain0 (_tmp59_);
					self->pages = g_list_append (self->pages, _tmp60_);
					_g_free0 (direction);
					_sdx_files_file_handle_release0 (file);
				} else {
					gboolean rotate = FALSE;
					SdxDataInputStream* _tmp61_ = NULL;
					gchar* _tmp62_ = NULL;
					gchar* _tmp63_ = NULL;
					gboolean _tmp64_ = FALSE;
					gboolean _tmp65_ = FALSE;
					SdxDataInputStream* _tmp66_ = NULL;
					gint left = 0;
					gchar** _tmp67_ = NULL;
					gint _tmp67__length1 = 0;
					const gchar* _tmp68_ = NULL;
					gint _tmp69_ = 0;
					gint top = 0;
					gchar** _tmp70_ = NULL;
					gint _tmp70__length1 = 0;
					const gchar* _tmp71_ = NULL;
					gint _tmp72_ = 0;
					SdxDataInputStream* _tmp73_ = NULL;
					gint width = 0;
					gchar** _tmp74_ = NULL;
					gint _tmp74__length1 = 0;
					const gchar* _tmp75_ = NULL;
					gint _tmp76_ = 0;
					gint height = 0;
					gchar** _tmp77_ = NULL;
					gint _tmp77__length1 = 0;
					const gchar* _tmp78_ = NULL;
					gint _tmp79_ = 0;
					SdxGraphicsRegion* region = NULL;
					SdxGraphicsPage* _tmp80_ = NULL;
					gint _tmp81_ = 0;
					gint _tmp82_ = 0;
					gint _tmp83_ = 0;
					gint _tmp84_ = 0;
					const gchar* _tmp85_ = NULL;
					gboolean _tmp86_ = FALSE;
					SdxGraphicsRegion* _tmp87_ = NULL;
					SdxDataInputStream* _tmp88_ = NULL;
					gint _tmp89_ = 0;
					SdxGraphicsRegion* _tmp122_ = NULL;
					gchar** _tmp123_ = NULL;
					gint _tmp123__length1 = 0;
					const gchar* _tmp124_ = NULL;
					gint _tmp125_ = 0;
					SdxGraphicsRegion* _tmp126_ = NULL;
					gchar** _tmp127_ = NULL;
					gint _tmp127__length1 = 0;
					const gchar* _tmp128_ = NULL;
					gint _tmp129_ = 0;
					SdxDataInputStream* _tmp130_ = NULL;
					SdxGraphicsRegion* _tmp131_ = NULL;
					gchar** _tmp132_ = NULL;
					gint _tmp132__length1 = 0;
					const gchar* _tmp133_ = NULL;
					gint _tmp134_ = 0;
					SdxGraphicsRegion* _tmp135_ = NULL;
					gchar** _tmp136_ = NULL;
					gint _tmp136__length1 = 0;
					const gchar* _tmp137_ = NULL;
					gint _tmp138_ = 0;
					SdxGraphicsRegion* _tmp139_ = NULL;
					SdxDataInputStream* _tmp140_ = NULL;
					gchar* _tmp141_ = NULL;
					gchar* _tmp142_ = NULL;
					gint _tmp143_ = 0;
					gboolean _tmp144_ = FALSE;
					SdxGraphicsRegion* _tmp146_ = NULL;
					SdxGraphicsRegion* _tmp147_ = NULL;
					_tmp61_ = reader;
					_tmp62_ = sdx_graphics_texture_atlas_data_ReadValue (_tmp61_);
					_tmp63_ = _tmp62_;
					_tmp64_ = bool_Parse (_tmp63_);
					_tmp65_ = _tmp64_;
					_g_free0 (_tmp63_);
					rotate = _tmp65_;
					_tmp66_ = reader;
					sdx_graphics_texture_atlas_data_ReadTuple (_tmp66_);
					_tmp67_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp67__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp68_ = _tmp67_[0];
					_tmp69_ = atoi (_tmp68_);
					left = _tmp69_;
					_tmp70_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp70__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp71_ = _tmp70_[1];
					_tmp72_ = atoi (_tmp71_);
					top = _tmp72_;
					_tmp73_ = reader;
					sdx_graphics_texture_atlas_data_ReadTuple (_tmp73_);
					_tmp74_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp74__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp75_ = _tmp74_[0];
					_tmp76_ = atoi (_tmp75_);
					width = _tmp76_;
					_tmp77_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp77__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp78_ = _tmp77_[1];
					_tmp79_ = atoi (_tmp78_);
					height = _tmp79_;
					_tmp80_ = pageImage;
					_tmp81_ = left;
					_tmp82_ = top;
					_tmp83_ = width;
					_tmp84_ = height;
					_tmp85_ = line;
					_tmp86_ = rotate;
					_tmp87_ = sdx_graphics_region_new (_tmp80_, _tmp81_, _tmp82_, _tmp83_, _tmp84_, _tmp85_, _tmp86_);
					region = _tmp87_;
					_tmp88_ = reader;
					_tmp89_ = sdx_graphics_texture_atlas_data_ReadTuple (_tmp88_);
					if (_tmp89_ == 4) {
						SdxGraphicsRegion* _tmp90_ = NULL;
						SdxGraphicsRegion* _tmp91_ = NULL;
						gchar** _tmp92_ = NULL;
						gint _tmp92__length1 = 0;
						const gchar* _tmp93_ = NULL;
						gint _tmp94_ = 0;
						gchar** _tmp95_ = NULL;
						gint _tmp95__length1 = 0;
						const gchar* _tmp96_ = NULL;
						gint _tmp97_ = 0;
						gchar** _tmp98_ = NULL;
						gint _tmp98__length1 = 0;
						const gchar* _tmp99_ = NULL;
						gint _tmp100_ = 0;
						gchar** _tmp101_ = NULL;
						gint _tmp101__length1 = 0;
						const gchar* _tmp102_ = NULL;
						gint _tmp103_ = 0;
						gint* _tmp104_ = NULL;
						SdxDataInputStream* _tmp105_ = NULL;
						gint _tmp106_ = 0;
						_tmp90_ = region;
						_tmp90_->slice9 = TRUE;
						_tmp91_ = region;
						_tmp92_ = sdx_graphics_texture_atlas_data_tuple;
						_tmp92__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
						_tmp93_ = _tmp92_[0];
						_tmp94_ = atoi (_tmp93_);
						_tmp95_ = sdx_graphics_texture_atlas_data_tuple;
						_tmp95__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
						_tmp96_ = _tmp95_[1];
						_tmp97_ = atoi (_tmp96_);
						_tmp98_ = sdx_graphics_texture_atlas_data_tuple;
						_tmp98__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
						_tmp99_ = _tmp98_[2];
						_tmp100_ = atoi (_tmp99_);
						_tmp101_ = sdx_graphics_texture_atlas_data_tuple;
						_tmp101__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
						_tmp102_ = _tmp101_[3];
						_tmp103_ = atoi (_tmp102_);
						_tmp104_ = g_new0 (gint, 4);
						_tmp104_[0] = _tmp94_;
						_tmp104_[1] = _tmp97_;
						_tmp104_[2] = _tmp100_;
						_tmp104_[3] = _tmp103_;
						_tmp91_->splits = (g_free (_tmp91_->splits), NULL);
						_tmp91_->splits = _tmp104_;
						_tmp91_->splits_length1 = 4;
						_tmp105_ = reader;
						_tmp106_ = sdx_graphics_texture_atlas_data_ReadTuple (_tmp105_);
						if (_tmp106_ == 4) {
							SdxGraphicsRegion* _tmp107_ = NULL;
							gchar** _tmp108_ = NULL;
							gint _tmp108__length1 = 0;
							const gchar* _tmp109_ = NULL;
							gint _tmp110_ = 0;
							gchar** _tmp111_ = NULL;
							gint _tmp111__length1 = 0;
							const gchar* _tmp112_ = NULL;
							gint _tmp113_ = 0;
							gchar** _tmp114_ = NULL;
							gint _tmp114__length1 = 0;
							const gchar* _tmp115_ = NULL;
							gint _tmp116_ = 0;
							gchar** _tmp117_ = NULL;
							gint _tmp117__length1 = 0;
							const gchar* _tmp118_ = NULL;
							gint _tmp119_ = 0;
							gint* _tmp120_ = NULL;
							SdxDataInputStream* _tmp121_ = NULL;
							_tmp107_ = region;
							_tmp108_ = sdx_graphics_texture_atlas_data_tuple;
							_tmp108__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
							_tmp109_ = _tmp108_[0];
							_tmp110_ = atoi (_tmp109_);
							_tmp111_ = sdx_graphics_texture_atlas_data_tuple;
							_tmp111__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
							_tmp112_ = _tmp111_[1];
							_tmp113_ = atoi (_tmp112_);
							_tmp114_ = sdx_graphics_texture_atlas_data_tuple;
							_tmp114__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
							_tmp115_ = _tmp114_[2];
							_tmp116_ = atoi (_tmp115_);
							_tmp117_ = sdx_graphics_texture_atlas_data_tuple;
							_tmp117__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
							_tmp118_ = _tmp117_[3];
							_tmp119_ = atoi (_tmp118_);
							_tmp120_ = g_new0 (gint, 4);
							_tmp120_[0] = _tmp110_;
							_tmp120_[1] = _tmp113_;
							_tmp120_[2] = _tmp116_;
							_tmp120_[3] = _tmp119_;
							_tmp107_->pads = (g_free (_tmp107_->pads), NULL);
							_tmp107_->pads = _tmp120_;
							_tmp107_->pads_length1 = 4;
							_tmp121_ = reader;
							sdx_graphics_texture_atlas_data_ReadTuple (_tmp121_);
						}
					}
					_tmp122_ = region;
					_tmp123_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp123__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp124_ = _tmp123_[0];
					_tmp125_ = atoi (_tmp124_);
					_tmp122_->originalWidth = _tmp125_;
					_tmp126_ = region;
					_tmp127_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp127__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp128_ = _tmp127_[1];
					_tmp129_ = atoi (_tmp128_);
					_tmp126_->originalHeight = _tmp129_;
					_tmp130_ = reader;
					sdx_graphics_texture_atlas_data_ReadTuple (_tmp130_);
					_tmp131_ = region;
					_tmp132_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp132__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp133_ = _tmp132_[0];
					_tmp134_ = atoi (_tmp133_);
					_tmp131_->offsetX = _tmp134_;
					_tmp135_ = region;
					_tmp136_ = sdx_graphics_texture_atlas_data_tuple;
					_tmp136__length1 = sdx_graphics_texture_atlas_data_tuple_length1;
					_tmp137_ = _tmp136_[1];
					_tmp138_ = atoi (_tmp137_);
					_tmp135_->offsetY = _tmp138_;
					_tmp139_ = region;
					_tmp140_ = reader;
					_tmp141_ = sdx_graphics_texture_atlas_data_ReadValue (_tmp140_);
					_tmp142_ = _tmp141_;
					_tmp143_ = atoi (_tmp142_);
					_tmp139_->index = _tmp143_;
					_g_free0 (_tmp142_);
					_tmp144_ = flip;
					if (_tmp144_) {
						SdxGraphicsRegion* _tmp145_ = NULL;
						_tmp145_ = region;
						_tmp145_->flip = TRUE;
					}
					_tmp146_ = region;
					_tmp147_ = _sdx_graphics_region_retain0 (_tmp146_);
					self->regions = g_list_append (self->regions, _tmp147_);
					_sdx_graphics_region_release0 (region);
				}
			}
			_g_free0 (line);
		}
		_sdx_graphics_page_release0 (pageImage);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp148_ = NULL;
		const gchar* _tmp149_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp148_ = e;
		_tmp149_ = _tmp148_->message;
		g_print ("%s", _tmp149_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_sdx_data_input_stream_release0 (reader);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_sdx_data_input_stream_release0 (reader);
	return self;
}


static void sdx_graphics_texture_atlas_data_instance_init (SdxGraphicsTextureAtlasData * self) {
	self->ref_count = 1;
}


void sdx_graphics_texture_atlas_data_free (SdxGraphicsTextureAtlasData* self) {
	__g_list_free__sdx_graphics_page_release0_0 (self->pages);
	__g_list_free__sdx_graphics_region_release0_0 (self->regions);
	g_slice_free (SdxGraphicsTextureAtlasData, self);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



