/** updated by emvalac */
/* CollisionSystem.c generated by valac 0.34.8, the Vala compiler
 * generated from CollisionSystem.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_rect.h>

typedef struct _entitasSystem entitasSystem;
typedef entitasSystem systemsCollisionSystem;
typedef struct _sdxAbstractGame sdxAbstractGame;
typedef sdxAbstractGame Game;
typedef struct _entitasWorld entitasWorld;
typedef entitasWorld Factory;
typedef struct _entitasGroup entitasGroup;
void entitas_world_release (entitasWorld* self);
void entitas_world_free (entitasWorld* self);
entitasWorld* entitas_world_retain (entitasWorld* self);
#define _entitas_world_release0(var) ((var == NULL) ? NULL : (var = (entitas_world_release (var), NULL)))
typedef struct _Block3Data Block3Data;
void entitas_group_release (entitasGroup* self);
void entitas_group_free (entitasGroup* self);
entitasGroup* entitas_group_retain (entitasGroup* self);
#define _entitas_group_release0(var) ((var == NULL) ? NULL : (var = (entitas_group_release (var), NULL)))
void entitas_system_release (entitasSystem* self);
void entitas_system_free (entitasSystem* self);
entitasSystem* entitas_system_retain (entitasSystem* self);
#define _entitas_system_release0(var) ((var == NULL) ? NULL : (var = (entitas_system_release (var), NULL)))
typedef struct _entitasMatcher entitasMatcher;

#define ENTITAS_TYPE_COMPONENTS (entitas_components_get_type ())
void entitas_matcher_release (entitasMatcher* self);
void entitas_matcher_free (entitasMatcher* self);
entitasMatcher* entitas_matcher_retain (entitasMatcher* self);
#define _entitas_matcher_release0(var) ((var == NULL) ? NULL : (var = (entitas_matcher_release (var), NULL)))

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())

#define ENTITAS_TYPE_TRANSFORM (entitas_transform_get_type ())

#define SDX_MATH_TYPE_VECTOR2 (sdx_math_vector2_get_type ())
typedef struct _sdxmathVector2 sdxmathVector2;
typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _entitasTransform entitasTransform;

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _entitasBackground entitasBackground;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _entitasBullet entitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _entitasEnemy1 entitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _entitasEnemy2 entitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _entitasEnemy3 entitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _entitasExpires entitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _entitasHealth entitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _entitasHud entitasHud;

#define ENTITAS_TYPE_INDEX (entitas_index_get_type ())
typedef struct _entitasIndex entitasIndex;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _entitasLayer entitasLayer;

#define ENTITAS_TYPE_SOUND (entitas_sound_get_type ())
typedef struct _sdxaudioSound sdxaudioSound;
typedef struct _entitasSound entitasSound;

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef sdxgraphicsSprite sdxgraphicsSpriteTextSprite;
typedef struct _entitasText entitasText;

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _entitasTint entitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _entitasTween entitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _entitasVelocity entitasVelocity;
typedef struct _entitasEntity entitasEntity;

typedef void (*entitasSystemInitialize) (void* user_data);
typedef void (*entitasSystemExecute) (gfloat delta, void* user_data);
struct _entitasSystem {
	gint _retainCount;
	entitasSystemInitialize initialize;
	gpointer initialize_target;
	GDestroyNotify initialize_target_destroy_notify;
	entitasSystemExecute execute;
	gpointer execute_target;
	GDestroyNotify execute_target_destroy_notify;
};

struct _Block3Data {
	int _ref_count_;
	systemsCollisionSystem* self;
	entitasGroup* bullets;
	entitasGroup* enemies;
	Factory* world;
};

typedef enum  {
	ENTITAS_COMPONENTS_UnknownComponent,
	ENTITAS_COMPONENTS_BackgroundComponent,
	ENTITAS_COMPONENTS_BulletComponent,
	ENTITAS_COMPONENTS_Enemy1Component,
	ENTITAS_COMPONENTS_Enemy2Component,
	ENTITAS_COMPONENTS_Enemy3Component,
	ENTITAS_COMPONENTS_ExpiresComponent,
	ENTITAS_COMPONENTS_HealthComponent,
	ENTITAS_COMPONENTS_HudComponent,
	ENTITAS_COMPONENTS_IndexComponent,
	ENTITAS_COMPONENTS_LayerComponent,
	ENTITAS_COMPONENTS_SoundComponent,
	ENTITAS_COMPONENTS_TextComponent,
	ENTITAS_COMPONENTS_TintComponent,
	ENTITAS_COMPONENTS_TweenComponent,
	ENTITAS_COMPONENTS_VelocityComponent
} entitasComponents;

struct _sdxmathVector2 {
	gfloat x;
	gfloat y;
};

struct _entitasTransform {
	sdxmathVector2* scale;
	sdxmathVector2* position;
	SDL_Rect* aabb;
	sdxgraphicsSprite* sprite;
};

struct _entitasBackground {
	gboolean active;
};

struct _entitasBullet {
	gboolean active;
};

struct _entitasEnemy1 {
	gboolean active;
};

struct _entitasEnemy2 {
	gboolean active;
};

struct _entitasEnemy3 {
	gboolean active;
};

struct _entitasExpires {
	gfloat value;
};

struct _entitasHealth {
	gfloat current;
	gfloat maximum;
};

struct _entitasHud {
	gboolean active;
};

struct _entitasIndex {
	gint value;
	gint limit;
	gboolean vertical;
};

struct _entitasLayer {
	gint value;
};

struct _entitasSound {
	sdxaudioSound* sound;
};

struct _entitasText {
	gchar* text;
	sdxgraphicsSpriteTextSprite* sprite;
};

struct _entitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _entitasTween {
	gfloat min;
	gfloat max;
	gfloat speed;
	gboolean repeat;
	gboolean active;
};

struct _entitasVelocity {
	gfloat x;
	gfloat y;
};

struct _entitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	entitasTransform transform;
	entitasBackground* background;
	entitasBullet* bullet;
	entitasEnemy1* enemy1;
	entitasEnemy2* enemy2;
	entitasEnemy3* enemy3;
	entitasExpires* expires;
	entitasHealth* health;
	entitasHud* hud;
	entitasIndex* index;
	entitasLayer* layer;
	entitasSound* sound;
	entitasText* text;
	entitasTint* tint;
	entitasTween* tween;
	entitasVelocity* velocity;
};

struct _entitasGroup {
	gint _retainCount;
	entitasMatcher* matcher;
	GList* entities;
};



void entitas_system_free (entitasSystem* self);
void sdx_abstract_game_free (sdxAbstractGame* self);
void entitas_world_free (entitasWorld* self);
systemsCollisionSystem* systems_collision_system_new (Game* game, Factory* world);
void entitas_group_free (entitasGroup* self);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
entitasSystem* entitas_system_new (void);
void entitas_matcher_free (entitasMatcher* self);
entitasGroup* entitas_world_getGroup (entitasWorld* self, entitasMatcher* matcher);
entitasMatcher* entitas_matcher_AllOf (gint* args, int args_length1);
GType entitas_components_get_type (void) G_GNUC_CONST;
entitasMatcher* entitas_matcher_AnyOf (gint* args, int args_length1);
static void __lambda12_ (Block3Data* _data3_, gfloat delta);
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_transform_get_type (void) G_GNUC_CONST;
GType sdx_math_vector2_get_type (void) G_GNUC_CONST;
sdxmathVector2* sdx_math_vector2_dup (const sdxmathVector2* self);
void sdx_math_vector2_free (sdxmathVector2* self);
void sdx_graphics_sprite_free (sdxgraphicsSprite* self);
entitasTransform* entitas_transform_dup (const entitasTransform* self);
void entitas_transform_free (entitasTransform* self);
void entitas_transform_copy (const entitasTransform* self, entitasTransform* dest);
void entitas_transform_destroy (entitasTransform* self);
GType entitas_background_get_type (void) G_GNUC_CONST;
entitasBackground* entitas_background_dup (const entitasBackground* self);
void entitas_background_free (entitasBackground* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
entitasBullet* entitas_bullet_dup (const entitasBullet* self);
void entitas_bullet_free (entitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self);
void entitas_enemy1_free (entitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self);
void entitas_enemy2_free (entitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self);
void entitas_enemy3_free (entitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
entitasExpires* entitas_expires_dup (const entitasExpires* self);
void entitas_expires_free (entitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
entitasHealth* entitas_health_dup (const entitasHealth* self);
void entitas_health_free (entitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
entitasHud* entitas_hud_dup (const entitasHud* self);
void entitas_hud_free (entitasHud* self);
GType entitas_index_get_type (void) G_GNUC_CONST;
entitasIndex* entitas_index_dup (const entitasIndex* self);
void entitas_index_free (entitasIndex* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
entitasLayer* entitas_layer_dup (const entitasLayer* self);
void entitas_layer_free (entitasLayer* self);
GType entitas_sound_get_type (void) G_GNUC_CONST;
void sdx_audio_sound_free (sdxaudioSound* self);
entitasSound* entitas_sound_dup (const entitasSound* self);
void entitas_sound_free (entitasSound* self);
void entitas_sound_copy (const entitasSound* self, entitasSound* dest);
void entitas_sound_destroy (entitasSound* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
entitasText* entitas_text_dup (const entitasText* self);
void entitas_text_free (entitasText* self);
void entitas_text_copy (const entitasText* self, entitasText* dest);
void entitas_text_destroy (entitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
entitasTint* entitas_tint_dup (const entitasTint* self);
void entitas_tint_free (entitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
entitasTween* entitas_tween_dup (const entitasTween* self);
void entitas_tween_free (entitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
entitasVelocity* entitas_velocity_dup (const entitasVelocity* self);
void entitas_velocity_free (entitasVelocity* self);
entitasEntity* entitas_entity_dup (const entitasEntity* self);
void entitas_entity_free (entitasEntity* self);
void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest);
void entitas_entity_destroy (entitasEntity* self);
gboolean entitas_entity_isActive (entitasEntity *self);
entitasEntity* factory_bang (Factory* self, gint x, gint y);
void entitas_world_deleteEntity (entitasWorld* self, entitasEntity* entity);
entitasEntity* factory_particle (Factory* self, gint x, gint y);
entitasEntity* factory_explosion (Factory* self, gint x, gint y);
static void ___lambda12__entitas_system_execute (gfloat delta, gpointer self);


static gpointer _entitas_world_retain0 (gpointer self) {
	return self ? entitas_world_retain (self) : NULL;
}


static Block3Data* block3_data_ref (Block3Data* _data3_) {
	g_atomic_int_inc (&_data3_->_ref_count_);
	return _data3_;
}


static void block3_data_unref (void * _userdata_) {
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
		systemsCollisionSystem* self;
		self = _data3_->self;
		_entitas_group_release0 (_data3_->enemies);
		_entitas_group_release0 (_data3_->bullets);
		_entitas_world_release0 (_data3_->world);
		_entitas_system_release0 (self);
		g_slice_free (Block3Data, _data3_);
	}
}


static void __lambda12_ (Block3Data* _data3_, gfloat delta) {
	systemsCollisionSystem* self;
	GList* _tmp0_ = NULL;
	self = _data3_->self;
	_tmp0_ = _data3_->enemies->entities;
	{
		GList* enemy_collection = NULL;
		GList* enemy_it = NULL;
		enemy_collection = _tmp0_;
		for (enemy_it = enemy_collection; enemy_it != NULL; enemy_it = enemy_it->next) {
			entitasEntity* enemy = NULL;
			enemy = enemy_it->data;
			{
				gboolean _tmp1_ = FALSE;
				_tmp1_ = entitas_entity_isActive (enemy);
				if (_tmp1_) {
					GList* _tmp2_ = NULL;
					_tmp2_ = _data3_->bullets->entities;
					{
						GList* bullet_collection = NULL;
						GList* bullet_it = NULL;
						bullet_collection = _tmp2_;
						for (bullet_it = bullet_collection; bullet_it != NULL; bullet_it = bullet_it->next) {
							entitasEntity* bullet = NULL;
							bullet = bullet_it->data;
							{
								gboolean _tmp3_ = FALSE;
								_tmp3_ = entitas_entity_isActive (bullet);
								if (_tmp3_) {
									entitasEntity* _tmp4_ = NULL;
									entitasTransform _tmp5_ = {0};
									SDL_Rect* _tmp6_ = NULL;
									entitasEntity* _tmp7_ = NULL;
									entitasTransform _tmp8_ = {0};
									SDL_Rect* _tmp9_ = NULL;
									SDL_Rect _tmp10_ = {0};
									gboolean _tmp11_ = FALSE;
									_tmp4_ = bullet;
									_tmp5_ = (*_tmp4_).transform;
									_tmp6_ = _tmp5_.aabb;
									_tmp7_ = enemy;
									_tmp8_ = (*_tmp7_).transform;
									_tmp9_ = _tmp8_.aabb;
									_tmp10_ = *_tmp9_;
									_tmp11_ = SDL_HasIntersection (_tmp6_, &_tmp10_);
									if (_tmp11_) {
										gint x = 0;
										entitasEntity* _tmp12_ = NULL;
										entitasTransform _tmp13_ = {0};
										sdxmathVector2* _tmp14_ = NULL;
										gfloat _tmp15_ = 0.0F;
										gint y = 0;
										entitasEntity* _tmp16_ = NULL;
										entitasTransform _tmp17_ = {0};
										sdxmathVector2* _tmp18_ = NULL;
										gfloat _tmp19_ = 0.0F;
										Factory* _tmp20_ = NULL;
										gint _tmp21_ = 0;
										gint _tmp22_ = 0;
										Factory* _tmp23_ = NULL;
										entitasEntity* _tmp24_ = NULL;
										entitasEntity* _tmp31_ = NULL;
										entitasHealth* _tmp32_ = NULL;
										_tmp12_ = bullet;
										_tmp13_ = (*_tmp12_).transform;
										_tmp14_ = _tmp13_.position;
										_tmp15_ = (*_tmp14_).x;
										x = (gint) ((gfloat) _tmp15_);
										_tmp16_ = bullet;
										_tmp17_ = (*_tmp16_).transform;
										_tmp18_ = _tmp17_.position;
										_tmp19_ = (*_tmp18_).y;
										y = (gint) ((gfloat) _tmp19_);
										_tmp20_ = _data3_->world;
										_tmp21_ = x;
										_tmp22_ = y;
										factory_bang (_tmp20_, _tmp21_, _tmp22_);
										_tmp23_ = _data3_->world;
										_tmp24_ = bullet;
										entitas_world_deleteEntity ((entitasWorld*) _tmp23_, _tmp24_);
										{
											gint i = 0;
											i = 0;
											{
												gboolean _tmp25_ = FALSE;
												_tmp25_ = TRUE;
												while (TRUE) {
													gint _tmp27_ = 0;
													Factory* _tmp28_ = NULL;
													gint _tmp29_ = 0;
													gint _tmp30_ = 0;
													if (!_tmp25_) {
														gint _tmp26_ = 0;
														_tmp26_ = i;
														i = _tmp26_ + 1;
													}
													_tmp25_ = FALSE;
													_tmp27_ = i;
													if (!(_tmp27_ < 3)) {
														break;
													}
													_tmp28_ = _data3_->world;
													_tmp29_ = x;
													_tmp30_ = y;
													factory_particle (_tmp28_, _tmp29_, _tmp30_);
												}
											}
										}
										_tmp31_ = enemy;
										_tmp32_ = (*_tmp31_).health;
										if (_tmp32_ != NULL) {
											gfloat current = 0.0F;
											entitasEntity* _tmp33_ = NULL;
											entitasHealth* _tmp34_ = NULL;
											gfloat _tmp35_ = 0.0F;
											gfloat _tmp36_ = 0.0F;
											_tmp33_ = enemy;
											_tmp34_ = (*_tmp33_).health;
											_tmp35_ = (*_tmp34_).current;
											current = _tmp35_ - 2;
											_tmp36_ = current;
											if (_tmp36_ < ((gfloat) 0)) {
												Factory* _tmp37_ = NULL;
												gint _tmp38_ = 0;
												gint _tmp39_ = 0;
												Factory* _tmp40_ = NULL;
												entitasEntity* _tmp41_ = NULL;
												_tmp37_ = _data3_->world;
												_tmp38_ = x;
												_tmp39_ = y;
												factory_explosion (_tmp37_, _tmp38_, _tmp39_);
												_tmp40_ = _data3_->world;
												_tmp41_ = enemy;
												entitas_world_deleteEntity ((entitasWorld*) _tmp40_, _tmp41_);
											} else {
												entitasEntity* _tmp42_ = NULL;
												entitasHealth* _tmp43_ = NULL;
												gfloat _tmp44_ = 0.0F;
												_tmp42_ = enemy;
												_tmp43_ = (*_tmp42_).health;
												_tmp44_ = current;
												(*_tmp43_).current = _tmp44_;
											}
										}
										return;
									}
								}
							}
						}
					}
				}
			}
		}
	}
}


static void ___lambda12__entitas_system_execute (gfloat delta, gpointer self) {
	__lambda12_ (self, delta);
}


systemsCollisionSystem* systems_collision_system_new (Game* game, Factory* world) {
	systemsCollisionSystem* self;
	Block3Data* _data3_;
	Factory* _tmp0_ = NULL;
	Factory* _tmp1_ = NULL;
	Factory* _tmp2_ = NULL;
	gint* _tmp3_ = NULL;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	entitasMatcher* _tmp5_ = NULL;
	entitasMatcher* _tmp6_ = NULL;
	entitasGroup* _tmp7_ = NULL;
	entitasGroup* _tmp8_ = NULL;
	Factory* _tmp9_ = NULL;
	gint* _tmp10_ = NULL;
	gint* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	entitasMatcher* _tmp12_ = NULL;
	entitasMatcher* _tmp13_ = NULL;
	entitasGroup* _tmp14_ = NULL;
	entitasGroup* _tmp15_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	g_return_val_if_fail (world != NULL, NULL);
	_data3_ = g_slice_new0 (Block3Data);
	_data3_->_ref_count_ = 1;
	_tmp0_ = world;
	_tmp1_ = _entitas_world_retain0 (_tmp0_);
	_entitas_world_release0 (_data3_->world);
	_data3_->world = _tmp1_;
	self = (systemsCollisionSystem*) entitas_system_new ();
	_data3_->self = entitas_system_retain (self);
	_tmp2_ = _data3_->world;
	_tmp3_ = g_new0 (gint, 1);
	_tmp3_[0] = (gint) ENTITAS_COMPONENTS_BulletComponent;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = 1;
	_tmp5_ = entitas_matcher_AllOf (_tmp4_, 1);
	_tmp6_ = _tmp5_;
	_tmp7_ = entitas_world_getGroup ((entitasWorld*) _tmp2_, _tmp6_);
	_tmp8_ = _tmp7_;
	_entitas_matcher_release0 (_tmp6_);
	_tmp4_ = (g_free (_tmp4_), NULL);
	_data3_->bullets = _tmp8_;
	_tmp9_ = _data3_->world;
	_tmp10_ = g_new0 (gint, 3);
	_tmp10_[0] = (gint) ENTITAS_COMPONENTS_Enemy1Component;
	_tmp10_[1] = (gint) ENTITAS_COMPONENTS_Enemy2Component;
	_tmp10_[2] = (gint) ENTITAS_COMPONENTS_Enemy3Component;
	_tmp11_ = _tmp10_;
	_tmp11__length1 = 3;
	_tmp12_ = entitas_matcher_AnyOf (_tmp11_, 3);
	_tmp13_ = _tmp12_;
	_tmp14_ = entitas_world_getGroup ((entitasWorld*) _tmp9_, _tmp13_);
	_tmp15_ = _tmp14_;
	_entitas_matcher_release0 (_tmp13_);
	_tmp11_ = (g_free (_tmp11_), NULL);
	_data3_->enemies = _tmp15_;
	(((entitasSystem*) self)->execute_target_destroy_notify == NULL) ? NULL : (((entitasSystem*) self)->execute_target_destroy_notify (((entitasSystem*) self)->execute_target), NULL);
	((entitasSystem*) self)->execute = NULL;
	((entitasSystem*) self)->execute_target = NULL;
	((entitasSystem*) self)->execute_target_destroy_notify = NULL;
	((entitasSystem*) self)->execute = ___lambda12__entitas_system_execute;
	((entitasSystem*) self)->execute_target = block3_data_ref (_data3_);
	((entitasSystem*) self)->execute_target_destroy_notify = block3_data_unref;
	block3_data_unref (_data3_);
	_data3_ = NULL;
	return self;
}



