/** updated by emvalac */
/* DisplaySystem.c generated by valac 0.34.8, the Vala compiler
 * generated from DisplaySystem.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_rect.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_pixels.h>

typedef struct _systemsDisplaySystem systemsDisplaySystem;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())

#define ENTITAS_TYPE_TRANSFORM (entitas_transform_get_type ())

#define SDX_MATH_TYPE_VECTOR2 (sdx_math_vector2_get_type ())
typedef struct _sdxmathVector2 sdxmathVector2;
typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _entitasTransform entitasTransform;

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _entitasBackground entitasBackground;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _entitasBullet entitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _entitasEnemy1 entitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _entitasEnemy2 entitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _entitasEnemy3 entitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _entitasExpires entitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _entitasHealth entitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _entitasHud entitasHud;

#define ENTITAS_TYPE_INDEX (entitas_index_get_type ())
typedef struct _entitasIndex entitasIndex;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _entitasLayer entitasLayer;

#define ENTITAS_TYPE_SOUND (entitas_sound_get_type ())
typedef struct _sdxaudioSound sdxaudioSound;
typedef struct _entitasSound entitasSound;

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef sdxgraphicsSprite sdxgraphicsSpriteTextSprite;
typedef struct _entitasText entitasText;

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _entitasTint entitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _entitasTween entitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _entitasVelocity entitasVelocity;
typedef struct _entitasEntity entitasEntity;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
void systems_display_system_release (systemsDisplaySystem* self);
void systems_display_system_free (systemsDisplaySystem* self);
systemsDisplaySystem* systems_display_system_retain (systemsDisplaySystem* self);
#define _systems_display_system_release0(var) ((var == NULL) ? NULL : (var = (systems_display_system_release (var), NULL)))

#define SDX_GRAPHICS_TYPE_SCALE (sdx_graphics_scale_get_type ())
typedef struct _sdxgraphicsScale sdxgraphicsScale;

#define SDX_GRAPHICS_SPRITE_TYPE_KIND (sdx_graphics_sprite_kind_get_type ())
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _sdxmathVector2 {
	gfloat x;
	gfloat y;
};

struct _entitasTransform {
	sdxmathVector2* scale;
	sdxmathVector2* position;
	SDL_Rect* aabb;
	sdxgraphicsSprite* sprite;
};

struct _entitasBackground {
	gboolean active;
};

struct _entitasBullet {
	gboolean active;
};

struct _entitasEnemy1 {
	gboolean active;
};

struct _entitasEnemy2 {
	gboolean active;
};

struct _entitasEnemy3 {
	gboolean active;
};

struct _entitasExpires {
	gfloat value;
};

struct _entitasHealth {
	gfloat current;
	gfloat maximum;
};

struct _entitasHud {
	gboolean active;
};

struct _entitasIndex {
	gint value;
	gint limit;
	gboolean vertical;
};

struct _entitasLayer {
	gint value;
};

struct _entitasSound {
	sdxaudioSound* sound;
};

struct _entitasText {
	gchar* text;
	sdxgraphicsSpriteTextSprite* sprite;
};

struct _entitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _entitasTween {
	gfloat min;
	gfloat max;
	gfloat speed;
	gboolean repeat;
	gboolean active;
};

struct _entitasVelocity {
	gfloat x;
	gfloat y;
};

struct _entitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	entitasTransform transform;
	entitasBackground* background;
	entitasBullet* bullet;
	entitasEnemy1* enemy1;
	entitasEnemy2* enemy2;
	entitasEnemy3* enemy3;
	entitasExpires* expires;
	entitasHealth* health;
	entitasHud* hud;
	entitasIndex* index;
	entitasLayer* layer;
	entitasSound* sound;
	entitasText* text;
	entitasTint* tint;
	entitasTween* tween;
	entitasVelocity* velocity;
};

struct _systemsDisplaySystem {
	gint _retainCount;
	GList* sprites;
};

struct _sdxgraphicsScale {
	gfloat x;
	gfloat y;
};

typedef enum  {
	SDX_GRAPHICS_SPRITE_KIND_AnimatedSprite,
	SDX_GRAPHICS_SPRITE_KIND_TextureSprite,
	SDX_GRAPHICS_SPRITE_KIND_AtlasSprite,
	SDX_GRAPHICS_SPRITE_KIND_CompositeSprite,
	SDX_GRAPHICS_SPRITE_KIND_TextSprite
} sdxgraphicsSpriteKind;

struct _sdxgraphicsSprite {
	gint _retainCount;
	gint id;
	SDL_Texture* texture;
	gint width;
	gint height;
	gint x;
	gint y;
	gint index;
	gint frame;
	sdxgraphicsScale scale;
	SDL_Color color;
	gboolean centered;
	gint layer;
	gchar* path;
	sdxgraphicsSpriteKind kind;
};


extern systemsDisplaySystem* systems_display_system_instance;
systemsDisplaySystem* systems_display_system_instance = NULL;
extern SDL_Renderer* sdx_renderer;

void systems_display_system_free (systemsDisplaySystem* self);
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_transform_get_type (void) G_GNUC_CONST;
GType sdx_math_vector2_get_type (void) G_GNUC_CONST;
sdxmathVector2* sdx_math_vector2_dup (const sdxmathVector2* self);
void sdx_math_vector2_free (sdxmathVector2* self);
void sdx_graphics_sprite_free (sdxgraphicsSprite* self);
entitasTransform* entitas_transform_dup (const entitasTransform* self);
void entitas_transform_free (entitasTransform* self);
void entitas_transform_copy (const entitasTransform* self, entitasTransform* dest);
void entitas_transform_destroy (entitasTransform* self);
GType entitas_background_get_type (void) G_GNUC_CONST;
entitasBackground* entitas_background_dup (const entitasBackground* self);
void entitas_background_free (entitasBackground* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
entitasBullet* entitas_bullet_dup (const entitasBullet* self);
void entitas_bullet_free (entitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self);
void entitas_enemy1_free (entitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self);
void entitas_enemy2_free (entitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self);
void entitas_enemy3_free (entitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
entitasExpires* entitas_expires_dup (const entitasExpires* self);
void entitas_expires_free (entitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
entitasHealth* entitas_health_dup (const entitasHealth* self);
void entitas_health_free (entitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
entitasHud* entitas_hud_dup (const entitasHud* self);
void entitas_hud_free (entitasHud* self);
GType entitas_index_get_type (void) G_GNUC_CONST;
entitasIndex* entitas_index_dup (const entitasIndex* self);
void entitas_index_free (entitasIndex* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
entitasLayer* entitas_layer_dup (const entitasLayer* self);
void entitas_layer_free (entitasLayer* self);
GType entitas_sound_get_type (void) G_GNUC_CONST;
void sdx_audio_sound_free (sdxaudioSound* self);
entitasSound* entitas_sound_dup (const entitasSound* self);
void entitas_sound_free (entitasSound* self);
void entitas_sound_copy (const entitasSound* self, entitasSound* dest);
void entitas_sound_destroy (entitasSound* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
entitasText* entitas_text_dup (const entitasText* self);
void entitas_text_free (entitasText* self);
void entitas_text_copy (const entitasText* self, entitasText* dest);
void entitas_text_destroy (entitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
entitasTint* entitas_tint_dup (const entitasTint* self);
void entitas_tint_free (entitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
entitasTween* entitas_tween_dup (const entitasTween* self);
void entitas_tween_free (entitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
entitasVelocity* entitas_velocity_dup (const entitasVelocity* self);
void entitas_velocity_free (entitasVelocity* self);
entitasEntity* entitas_entity_dup (const entitasEntity* self);
void entitas_entity_free (entitasEntity* self);
void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest);
void entitas_entity_destroy (entitasEntity* self);
static void systems_display_system_instance_init (systemsDisplaySystem * self);
systemsDisplaySystem* systems_display_system_retain (systemsDisplaySystem* self);
void systems_display_system_release (systemsDisplaySystem* self);
void systems_display_system_free (systemsDisplaySystem* self);
systemsDisplaySystem* systems_display_system_new (void);
void systems_display_system_remove (systemsDisplaySystem* self, entitasEntity* e);
void systems_display_system_add (systemsDisplaySystem* self, entitasEntity* e);
gboolean systems_display_system_draw (systemsDisplaySystem* self, entitasEntity* e, entitasTransform* t);
GType sdx_graphics_scale_get_type (void) G_GNUC_CONST;
sdxgraphicsScale* sdx_graphics_scale_dup (const sdxgraphicsScale* self);
void sdx_graphics_scale_free (sdxgraphicsScale* self);
GType sdx_graphics_sprite_kind_get_type (void) G_GNUC_CONST;
gboolean entitas_entity_hasTint (entitasEntity *self);
gboolean entitas_entity_hasText (entitasEntity *self);


systemsDisplaySystem* systems_display_system_retain (systemsDisplaySystem* self) {
	systemsDisplaySystem* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void systems_display_system_release (systemsDisplaySystem* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		systems_display_system_free (self);
	}
}


static gpointer _systems_display_system_retain0 (gpointer self) {
	return self ? systems_display_system_retain (self) : NULL;
}


systemsDisplaySystem* systems_display_system_new (void) {
	systemsDisplaySystem* self;
	systemsDisplaySystem* _tmp0_ = NULL;
	self = g_slice_new0 (systemsDisplaySystem);
	systems_display_system_instance_init (self);
	_tmp0_ = _systems_display_system_retain0 (self);
	_systems_display_system_release0 (systems_display_system_instance);
	systems_display_system_instance = _tmp0_;
	return self;
}


void systems_display_system_remove (systemsDisplaySystem* self, entitasEntity* e) {
	entitasEntity* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = e;
	self->sprites = g_list_remove (self->sprites, _tmp0_);
}


void systems_display_system_add (systemsDisplaySystem* self, entitasEntity* e) {
	gint layer = 0;
	entitasEntity* _tmp0_ = NULL;
	entitasLayer* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GList* _tmp3_ = NULL;
	guint _tmp4_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = e;
	_tmp1_ = (*_tmp0_).layer;
	_tmp2_ = (*_tmp1_).value;
	layer = _tmp2_;
	_tmp3_ = self->sprites;
	_tmp4_ = g_list_length (_tmp3_);
	if (_tmp4_ == ((guint) 0)) {
		entitasEntity* _tmp5_ = NULL;
		_tmp5_ = e;
		self->sprites = g_list_append (self->sprites, _tmp5_);
	} else {
		gint i = 0;
		GList* _tmp6_ = NULL;
		entitasEntity* _tmp15_ = NULL;
		i = 0;
		_tmp6_ = self->sprites;
		{
			GList* s_collection = NULL;
			GList* s_it = NULL;
			s_collection = _tmp6_;
			for (s_it = s_collection; s_it != NULL; s_it = s_it->next) {
				entitasEntity* s = NULL;
				s = s_it->data;
				{
					entitasEntity* _tmp7_ = NULL;
					gint _tmp8_ = 0;
					entitasEntity* _tmp9_ = NULL;
					entitasLayer* _tmp10_ = NULL;
					gint _tmp11_ = 0;
					_tmp7_ = s;
					_vala_assert (_tmp7_ != NULL, "s != null");
					_tmp8_ = layer;
					_tmp9_ = s;
					_tmp10_ = (*_tmp9_).layer;
					_tmp11_ = (*_tmp10_).value;
					if (_tmp8_ <= _tmp11_) {
						entitasEntity* _tmp12_ = NULL;
						gint _tmp13_ = 0;
						_tmp12_ = e;
						_tmp13_ = i;
						self->sprites = g_list_insert (self->sprites, _tmp12_, _tmp13_);
						return;
					} else {
						gint _tmp14_ = 0;
						_tmp14_ = i;
						i = _tmp14_ + 1;
					}
				}
			}
		}
		_tmp15_ = e;
		self->sprites = g_list_append (self->sprites, _tmp15_);
	}
}


gboolean systems_display_system_draw (systemsDisplaySystem* self, entitasEntity* e, entitasTransform* t) {
	gboolean result = FALSE;
	entitasTransform _tmp0_ = {0};
	sdxgraphicsSprite* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (t != NULL, FALSE);
	_tmp0_ = *t;
	_tmp1_ = _tmp0_.sprite;
	if (_tmp1_ != NULL) {
		entitasTransform _tmp2_ = {0};
		SDL_Rect* _tmp3_ = NULL;
		entitasTransform _tmp4_ = {0};
		sdxgraphicsSprite* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		entitasTransform _tmp7_ = {0};
		sdxmathVector2* _tmp8_ = NULL;
		gfloat _tmp9_ = 0.0F;
		entitasTransform _tmp10_ = {0};
		SDL_Rect* _tmp11_ = NULL;
		entitasTransform _tmp12_ = {0};
		sdxgraphicsSprite* _tmp13_ = NULL;
		gint _tmp14_ = 0;
		entitasTransform _tmp15_ = {0};
		sdxmathVector2* _tmp16_ = NULL;
		gfloat _tmp17_ = 0.0F;
		entitasTransform _tmp18_ = {0};
		sdxgraphicsSprite* _tmp19_ = NULL;
		gboolean _tmp20_ = FALSE;
		gboolean _tmp37_ = FALSE;
		SDL_Renderer* _tmp56_ = NULL;
		entitasTransform _tmp57_ = {0};
		sdxgraphicsSprite* _tmp58_ = NULL;
		SDL_Texture* _tmp59_ = NULL;
		entitasTransform _tmp60_ = {0};
		SDL_Rect* _tmp61_ = NULL;
		gint _tmp62_ = 0;
		entitasTransform _tmp63_ = {0};
		SDL_Rect* _tmp64_ = NULL;
		gint _tmp65_ = 0;
		entitasTransform _tmp66_ = {0};
		SDL_Rect* _tmp67_ = NULL;
		guint _tmp68_ = 0U;
		entitasTransform _tmp69_ = {0};
		SDL_Rect* _tmp70_ = NULL;
		guint _tmp71_ = 0U;
		SDL_Rect _tmp72_ = {0};
		gboolean _tmp73_ = FALSE;
		_tmp2_ = *t;
		_tmp3_ = _tmp2_.aabb;
		_tmp4_ = *t;
		_tmp5_ = _tmp4_.sprite;
		_tmp6_ = _tmp5_->width;
		_tmp7_ = *t;
		_tmp8_ = _tmp7_.scale;
		_tmp9_ = (*_tmp8_).x;
		(*_tmp3_).w = (guint) ((gint) (((gfloat) _tmp6_) * _tmp9_));
		_tmp10_ = *t;
		_tmp11_ = _tmp10_.aabb;
		_tmp12_ = *t;
		_tmp13_ = _tmp12_.sprite;
		_tmp14_ = _tmp13_->height;
		_tmp15_ = *t;
		_tmp16_ = _tmp15_.scale;
		_tmp17_ = (*_tmp16_).y;
		(*_tmp11_).h = (guint) ((gint) (((gfloat) _tmp14_) * _tmp17_));
		_tmp18_ = *t;
		_tmp19_ = _tmp18_.sprite;
		_tmp20_ = _tmp19_->centered;
		if (_tmp20_) {
			entitasTransform _tmp21_ = {0};
			SDL_Rect* _tmp22_ = NULL;
			entitasTransform _tmp23_ = {0};
			sdxmathVector2* _tmp24_ = NULL;
			gfloat _tmp25_ = 0.0F;
			entitasTransform _tmp26_ = {0};
			SDL_Rect* _tmp27_ = NULL;
			guint _tmp28_ = 0U;
			entitasTransform _tmp29_ = {0};
			SDL_Rect* _tmp30_ = NULL;
			entitasTransform _tmp31_ = {0};
			sdxmathVector2* _tmp32_ = NULL;
			gfloat _tmp33_ = 0.0F;
			entitasTransform _tmp34_ = {0};
			SDL_Rect* _tmp35_ = NULL;
			guint _tmp36_ = 0U;
			_tmp21_ = *t;
			_tmp22_ = _tmp21_.aabb;
			_tmp23_ = *t;
			_tmp24_ = _tmp23_.position;
			_tmp25_ = (*_tmp24_).x;
			_tmp26_ = *t;
			_tmp27_ = _tmp26_.aabb;
			_tmp28_ = (*_tmp27_).w;
			(*_tmp22_).x = (gint) (((gfloat) _tmp25_) - (_tmp28_ / 2));
			_tmp29_ = *t;
			_tmp30_ = _tmp29_.aabb;
			_tmp31_ = *t;
			_tmp32_ = _tmp31_.position;
			_tmp33_ = (*_tmp32_).y;
			_tmp34_ = *t;
			_tmp35_ = _tmp34_.aabb;
			_tmp36_ = (*_tmp35_).h;
			(*_tmp30_).y = (gint) (((gfloat) _tmp33_) - (_tmp36_ / 2));
		}
		_tmp37_ = entitas_entity_hasTint (e);
		if (_tmp37_) {
			entitasTransform _tmp38_ = {0};
			sdxgraphicsSprite* _tmp39_ = NULL;
			SDL_Texture* _tmp40_ = NULL;
			entitasEntity* _tmp41_ = NULL;
			entitasTint* _tmp42_ = NULL;
			gint _tmp43_ = 0;
			entitasEntity* _tmp44_ = NULL;
			entitasTint* _tmp45_ = NULL;
			gint _tmp46_ = 0;
			entitasEntity* _tmp47_ = NULL;
			entitasTint* _tmp48_ = NULL;
			gint _tmp49_ = 0;
			entitasTransform _tmp50_ = {0};
			sdxgraphicsSprite* _tmp51_ = NULL;
			SDL_Texture* _tmp52_ = NULL;
			entitasEntity* _tmp53_ = NULL;
			entitasTint* _tmp54_ = NULL;
			gint _tmp55_ = 0;
			_tmp38_ = *t;
			_tmp39_ = _tmp38_.sprite;
			_tmp40_ = _tmp39_->texture;
			_tmp41_ = e;
			_tmp42_ = (*_tmp41_).tint;
			_tmp43_ = (*_tmp42_).r;
			_tmp44_ = e;
			_tmp45_ = (*_tmp44_).tint;
			_tmp46_ = (*_tmp45_).g;
			_tmp47_ = e;
			_tmp48_ = (*_tmp47_).tint;
			_tmp49_ = (*_tmp48_).b;
			SDL_SetTextureColorMod (_tmp40_, (guint8) _tmp43_, (guint8) _tmp46_, (guint8) _tmp49_);
			_tmp50_ = *t;
			_tmp51_ = _tmp50_.sprite;
			_tmp52_ = _tmp51_->texture;
			_tmp53_ = e;
			_tmp54_ = (*_tmp53_).tint;
			_tmp55_ = (*_tmp54_).a;
			SDL_SetTextureAlphaMod (_tmp52_, (guint8) _tmp55_);
		}
		_tmp56_ = sdx_renderer;
		_tmp57_ = *t;
		_tmp58_ = _tmp57_.sprite;
		_tmp59_ = _tmp58_->texture;
		_tmp60_ = *t;
		_tmp61_ = _tmp60_.aabb;
		_tmp62_ = (*_tmp61_).x;
		_tmp63_ = *t;
		_tmp64_ = _tmp63_.aabb;
		_tmp65_ = (*_tmp64_).y;
		_tmp66_ = *t;
		_tmp67_ = _tmp66_.aabb;
		_tmp68_ = (*_tmp67_).w;
		_tmp69_ = *t;
		_tmp70_ = _tmp69_.aabb;
		_tmp71_ = (*_tmp70_).h;
		_tmp72_.x = _tmp62_;
		_tmp72_.y = _tmp65_;
		_tmp72_.w = (guint) _tmp68_;
		_tmp72_.h = (guint) _tmp71_;
		SDL_RenderCopy (_tmp56_, _tmp59_, NULL, &_tmp72_);
		_tmp73_ = entitas_entity_hasText (e);
		if (_tmp73_) {
			SDL_Renderer* _tmp74_ = NULL;
			entitasEntity* _tmp75_ = NULL;
			entitasText* _tmp76_ = NULL;
			sdxgraphicsSpriteTextSprite* _tmp77_ = NULL;
			SDL_Texture* _tmp78_ = NULL;
			entitasTransform _tmp79_ = {0};
			sdxmathVector2* _tmp80_ = NULL;
			gfloat _tmp81_ = 0.0F;
			entitasTransform _tmp82_ = {0};
			sdxmathVector2* _tmp83_ = NULL;
			gfloat _tmp84_ = 0.0F;
			entitasEntity* _tmp85_ = NULL;
			entitasText* _tmp86_ = NULL;
			sdxgraphicsSpriteTextSprite* _tmp87_ = NULL;
			gint _tmp88_ = 0;
			entitasEntity* _tmp89_ = NULL;
			entitasText* _tmp90_ = NULL;
			sdxgraphicsSpriteTextSprite* _tmp91_ = NULL;
			gint _tmp92_ = 0;
			SDL_Rect _tmp93_ = {0};
			_tmp74_ = sdx_renderer;
			_tmp75_ = e;
			_tmp76_ = (*_tmp75_).text;
			_tmp77_ = (*_tmp76_).sprite;
			_tmp78_ = ((sdxgraphicsSprite*) _tmp77_)->texture;
			_tmp79_ = *t;
			_tmp80_ = _tmp79_.position;
			_tmp81_ = (*_tmp80_).x;
			_tmp82_ = *t;
			_tmp83_ = _tmp82_.position;
			_tmp84_ = (*_tmp83_).y;
			_tmp85_ = e;
			_tmp86_ = (*_tmp85_).text;
			_tmp87_ = (*_tmp86_).sprite;
			_tmp88_ = ((sdxgraphicsSprite*) _tmp87_)->width;
			_tmp89_ = e;
			_tmp90_ = (*_tmp89_).text;
			_tmp91_ = (*_tmp90_).sprite;
			_tmp92_ = ((sdxgraphicsSprite*) _tmp91_)->height;
			_tmp93_.x = (gint) _tmp81_;
			_tmp93_.y = (gint) _tmp84_;
			_tmp93_.w = (guint) _tmp88_;
			_tmp93_.h = (guint) _tmp92_;
			SDL_RenderCopy (_tmp74_, _tmp78_, NULL, &_tmp93_);
		}
	}
	result = TRUE;
	return result;
}


static void systems_display_system_instance_init (systemsDisplaySystem * self) {
	self->_retainCount = 1;
	self->sprites = NULL;
}


void systems_display_system_free (systemsDisplaySystem* self) {
	_g_list_free0 (self->sprites);
	g_slice_free (systemsDisplaySystem, self);
}



