/** updated by adriac */
/* Timeline.c generated by valac 0.34.9, the Vala compiler
 * generated from Timeline.vala, do not modify */

/* ******************************************************************************
 * Copyright 2017 darkoverlordofdata.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>

typedef struct _SdxMathTweenbase SdxMathTweenbase;

#define SDX_MATH_TYPE_TWEEN_KIND (sdx_math_tween_kind_get_type ())
typedef struct _Class Class;
typedef struct _SdxMathTweenAccessor SdxMathTweenAccessor;
typedef struct _SdxMathInterpolation SdxMathInterpolation;

#define SDX_MATH_TYPE_TIMELINE_MODES (sdx_math_timeline_modes_get_type ())
typedef struct _SdxMathTweenManager SdxMathTweenManager;
typedef SdxMathTweenbase SdxMathTimeline;
// symtbl.1 sdx_math_tweenbase
void sdx_math_tweenbase_release (SdxMathTweenbase* self);
void sdx_math_tweenbase_free (SdxMathTweenbase* self);
SdxMathTweenbase* sdx_math_tweenbase_retain (SdxMathTweenbase* self);
#define _sdx_math_tweenbase_release0(var) ((var == NULL) ? NULL : (var = (sdx_math_tweenbase_release (var), NULL)))
typedef SdxMathTweenbase SdxMathTween;
typedef struct _Block24Data Block24Data;
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

typedef enum  {
	SDX_MATH_TWEEN_KIND_TWEEN,
	SDX_MATH_TWEEN_KIND_TIMELINE
} SdxMathTweenKind;

typedef void (*SdxMathTweenCallbackOnEvent) (gint type, SdxMathTweenbase* source, void* user_data);
typedef enum  {
	SDX_MATH_TIMELINE_MODES_SEQUENCE,
	SDX_MATH_TIMELINE_MODES_PARALLEL
} SdxMathTimelineModes;

typedef SdxMathTweenbase* (*SdxMathTweenbaseTweenReset) (void* user_data);
typedef SdxMathTweenbase* (*SdxMathTweenbaseTweenBuild) (void* user_data);
typedef void (*SdxMathTweenbaseTweenFree) (void* user_data);
typedef SdxMathTweenbase* (*SdxMathTweenbaseTweenStart) (SdxMathTweenManager* manager, void* user_data);
typedef void (*SdxMathTweenbaseTweenForceStartValues) (void* user_data);
typedef void (*SdxMathTweenbaseTweenForceEndValues) (void* user_data);
typedef gboolean (*SdxMathTweenbaseTweenContainsTarget) (void* target, gint tweenType, void* user_data);
typedef void (*SdxMathTweenbaseTweenInitializeOverride) (void* user_data);
typedef void (*SdxMathTweenbaseTweenUpdateOverride) (gint step, gint lastStep, gboolean isIterationStep, gfloat delta, void* user_data);
struct _SdxMathTweenbase {
	gint ref_count;
	SdxMathTweenKind kind;
	gint step;
	gint repeatCnt;
	gboolean isIterationStep;
	gboolean isYoyo;
	gfloat delay;
	gfloat duration;
	gfloat repeatDelay;
	gfloat currentTime;
	gfloat deltaTime;
	gboolean isStarted;
	gboolean isInitialized;
	gboolean isFinished;
	gboolean isKilled;
	gboolean isPaused;
	SdxMathTweenCallbackOnEvent callback;
	gpointer callback_target;
	GDestroyNotify callback_target_destroy_notify;
	gint callbackTriggers;
	void* userData;
	gboolean isAutoRemoveEnabled;
	gboolean isAutoStartEnabled;
	void* target;
	Class* targetClass;
	SdxMathTweenAccessor* accessor;
	gint type;
	SdxMathInterpolation* equation;
	gboolean isFrom;
	gboolean isRelative;
	gint combinedAttrsCnt;
	gint waypointsCnt;
	gfloat* startValues;
	gint startValues_length1;
	gfloat* targetValues;
	gint targetValues_length1;
	gfloat* accessorBuffer;
	gint accessorBuffer_length1;
	GPtrArray* children;
	SdxMathTweenbase* current;
	SdxMathTweenbase* parent;
	SdxMathTimelineModes mode;
	gboolean isBuilt;
	SdxMathTweenbaseTweenReset Reset;
	gpointer Reset_target;
	GDestroyNotify Reset_target_destroy_notify;
	SdxMathTweenbaseTweenBuild Build;
	gpointer Build_target;
	GDestroyNotify Build_target_destroy_notify;
	SdxMathTweenbaseTweenFree Free;
	gpointer Free_target;
	GDestroyNotify Free_target_destroy_notify;
	SdxMathTweenbaseTweenStart Start;
	gpointer Start_target;
	GDestroyNotify Start_target_destroy_notify;
	SdxMathTweenbaseTweenForceStartValues ForceStartValues;
	gpointer ForceStartValues_target;
	GDestroyNotify ForceStartValues_target_destroy_notify;
	SdxMathTweenbaseTweenForceEndValues ForceEndValues;
	gpointer ForceEndValues_target;
	GDestroyNotify ForceEndValues_target_destroy_notify;
	SdxMathTweenbaseTweenContainsTarget ContainsTarget;
	gpointer ContainsTarget_target;
	GDestroyNotify ContainsTarget_target_destroy_notify;
	SdxMathTweenbaseTweenInitializeOverride InitializeOverride;
	gpointer InitializeOverride_target;
	GDestroyNotify InitializeOverride_target_destroy_notify;
	SdxMathTweenbaseTweenUpdateOverride UpdateOverride;
	gpointer UpdateOverride_target;
	GDestroyNotify UpdateOverride_target_destroy_notify;
};

typedef enum  {
	SDX_EXCEPTION_IllegalArgumentException,
	SDX_EXCEPTION_RuntimeException
} SdxException;
#define SDX_EXCEPTION sdx_exception_quark ()
struct _Block24Data {
	int _ref_count_;
	SdxMathTimeline* self;
	SdxMathTweenbaseTweenReset Reset_;
	gpointer Reset__target;
	GDestroyNotify Reset__target_destroy_notify;
	SdxMathTweenbaseTweenStart Start_;
	gpointer Start__target;
	GDestroyNotify Start__target_destroy_notify;
};


extern GPtrArray* sdx_math_tweenbase_pool;

void sdx_math_tweenbase_free (SdxMathTweenbase* self);
GType sdx_math_tween_kind_get_type (void) G_GNUC_CONST;
void class_free (Class* self);
void sdx_math_tween_accessor_free (SdxMathTweenAccessor* self);
void sdx_math_interpolation_free (SdxMathInterpolation* self);
GType sdx_math_timeline_modes_get_type (void) G_GNUC_CONST;
void sdx_math_tween_manager_free (SdxMathTweenManager* self);
SdxMathTimeline* sdx_math_timeline_CreateSequence (void);
// symtbl.3 SdxMathTimeline / sdx_math_timeline
SdxMathTimeline* sdx_math_timeline_retain (SdxMathTimeline* self);
void sdx_math_timeline_release (SdxMathTimeline* self);
SdxMathTimeline* sdx_math_timeline_new (void);
void sdx_math_timeline_Setup (SdxMathTimeline* self, SdxMathTimelineModes mode);
SdxMathTimeline* sdx_math_timeline_CreateParallel (void);
// symtbl.3 SdxMathTweenbase / sdx_math_tweenbase
SdxMathTweenbase* sdx_math_tweenbase_retain (SdxMathTweenbase* self);
void sdx_math_tweenbase_release (SdxMathTweenbase* self);
SdxMathTweenbase* sdx_math_tweenbase_new (void);
void sdx_math_timeline_Overrides (SdxMathTimeline* self);
SdxMathTimeline* sdx_math_timeline_Push (SdxMathTimeline* self, SdxMathTween* tween);
GQuark sdx_exception_quark (void);
SdxMathTimeline* sdx_math_timeline_PushPause (SdxMathTimeline* self, gfloat time);
SdxMathTween* sdx_math_tween_Mark (void);
SdxMathTweenbase* sdx_math_tweenbase_Delay (SdxMathTweenbase* self, gfloat delay);
SdxMathTimeline* sdx_math_timeline_BeginSequence (SdxMathTimeline* self);
SdxMathTimeline* sdx_math_timeline_BeginParallel (SdxMathTimeline* self);
SdxMathTimeline* sdx_math_timeline_End (SdxMathTimeline* self);
GPtrArray* sdx_math_timeline_GetChildren (SdxMathTimeline* self);
static Block24Data* block24_data_ref (Block24Data* _data24_);
static void block24_data_unref (void * _userdata_);
static SdxMathTweenbase* __lambda131_ (Block24Data* _data24_);
// symtbl.2 sdx_math_tweenbase
void sdx_math_tweenbase_release (SdxMathTweenbase* self);
void sdx_math_tweenbase_free (SdxMathTweenbase* self);
SdxMathTweenbase* sdx_math_tweenbase_retain (SdxMathTweenbase* self);
static void _sdx_math_tweenbase_release0_ (gpointer var);
static SdxMathTweenbase* ___lambda131__sdx_math_tweenbase_tween_reset (gpointer self);
static SdxMathTweenbase* __lambda132_ (SdxMathTimeline* self);
gint sdx_math_tweenbase_GetRepeatCount (SdxMathTweenbase* self);
gfloat sdx_math_tweenbase_GetFullDuration (SdxMathTweenbase* self);
static SdxMathTweenbase* ___lambda132__sdx_math_tweenbase_tween_build (gpointer self);
static SdxMathTweenbase* __lambda133_ (Block24Data* _data24_);
static SdxMathTweenbase* ___lambda133__sdx_math_tweenbase_tween_start (SdxMathTweenManager* manager, gpointer self);
static void __lambda134_ (SdxMathTimeline* self);
static void ___lambda134__sdx_math_tweenbase_tween_free (gpointer self);
static void __lambda135_ (SdxMathTimeline* self, gint step, gint lastStep, gboolean isIterationStep, gfloat delta);
gboolean sdx_math_tweenbase_IsReverse (SdxMathTweenbase* self, gint step);
void sdx_math_tweenbase_Update (SdxMathTweenbase* self, gfloat delta);
static void ___lambda135__sdx_math_tweenbase_tween_update_override (gint step, gint lastStep, gboolean isIterationStep, gfloat delta, gpointer self);
static void __lambda136_ (SdxMathTimeline* self);
void sdx_math_tweenbase_ForceToStart (SdxMathTweenbase* self);
static void ___lambda136__sdx_math_tweenbase_tween_force_start_values (gpointer self);
static void __lambda137_ (SdxMathTimeline* self);
void sdx_math_tweenbase_ForceToEnd (SdxMathTweenbase* self, gfloat time);
static void ___lambda137__sdx_math_tweenbase_tween_force_end_values (gpointer self);
static gboolean __lambda138_ (SdxMathTimeline* self, void* target, gint tweenType);
static gboolean ___lambda138__sdx_math_tweenbase_tween_contains_target (void* target, gint tweenType, gpointer self);


/**
         * Creates a new timeline with a 'sequence' behavior. Its children will
         * be delayed so that they are triggered one after the other.
         */
static gboolean g_ptr_array_IsEmpty (GPtrArray* self) {
	gboolean result = FALSE;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->len;
	result = _tmp0_ == ((guint) 0);
	return result;
}


static gpointer g_ptr_array_Pop (GPtrArray* self) {
	gpointer result = NULL;
	gpointer item = NULL;
	guint _tmp0_ = 0U;
	gconstpointer _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->len;
	_tmp1_ = g_ptr_array_index (self, _tmp0_ - 1);
	item = _tmp1_;
	_tmp2_ = self->len;
	g_ptr_array_remove_index (self, _tmp2_ - 1);
	result = item;
	return result;
}


static gpointer _sdx_math_tweenbase_retain0 (gpointer self) {
	return self ? sdx_math_tweenbase_retain (self) : NULL;
}


SdxMathTimeline* sdx_math_timeline_CreateSequence (void) {
	SdxMathTimeline* result = NULL;
	SdxMathTimeline* _tmp0_ = NULL;
	GPtrArray* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	SdxMathTimeline* tl = NULL;
	SdxMathTimeline* _tmp9_ = NULL;
	_tmp1_ = sdx_math_tweenbase_pool;
	_tmp2_ = g_ptr_array_IsEmpty (_tmp1_);
	if (_tmp2_) {
		SdxMathTimeline* _tmp3_ = NULL;
		_tmp3_ = sdx_math_timeline_new ();
		_sdx_math_tweenbase_release0 (_tmp0_);
		_tmp0_ = _tmp3_;
	} else {
		GPtrArray* _tmp4_ = NULL;
		gpointer _tmp5_ = NULL;
		SdxMathTweenbase* _tmp6_ = NULL;
		SdxMathTweenbaseTweenReset _tmp7_ = NULL;
		void* _tmp7__target = NULL;
		SdxMathTweenbase* _tmp8_ = NULL;
		_tmp4_ = sdx_math_tweenbase_pool;
		_tmp5_ = g_ptr_array_Pop (_tmp4_);
		_tmp6_ = (SdxMathTweenbase*) _tmp5_;
		_tmp7_ = _tmp6_->Reset;
		_tmp7__target = _tmp6_->Reset_target;
		_tmp8_ = _tmp7_ (_tmp7__target);
		_sdx_math_tweenbase_release0 (_tmp0_);
		_tmp0_ = (SdxMathTimeline*) _tmp8_;
		_sdx_math_tweenbase_release0 (_tmp6_);
	}
	_tmp9_ = _sdx_math_tweenbase_retain0 (_tmp0_);
	tl = _tmp9_;
	sdx_math_timeline_Setup (tl, SDX_MATH_TIMELINE_MODES_SEQUENCE);
	result = tl;
	_sdx_math_tweenbase_release0 (_tmp0_);
	return result;
}


/**
         * Creates a new timeline with a 'parallel' behavior. Its children will be
         * triggered all at once.
         */
SdxMathTimeline* sdx_math_timeline_CreateParallel (void) {
	SdxMathTimeline* result = NULL;
	SdxMathTimeline* _tmp0_ = NULL;
	GPtrArray* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	SdxMathTimeline* tl = NULL;
	SdxMathTimeline* _tmp9_ = NULL;
	_tmp1_ = sdx_math_tweenbase_pool;
	_tmp2_ = g_ptr_array_IsEmpty (_tmp1_);
	if (_tmp2_) {
		SdxMathTimeline* _tmp3_ = NULL;
		_tmp3_ = sdx_math_timeline_new ();
		_sdx_math_tweenbase_release0 (_tmp0_);
		_tmp0_ = _tmp3_;
	} else {
		GPtrArray* _tmp4_ = NULL;
		gpointer _tmp5_ = NULL;
		SdxMathTweenbase* _tmp6_ = NULL;
		SdxMathTweenbaseTweenReset _tmp7_ = NULL;
		void* _tmp7__target = NULL;
		SdxMathTweenbase* _tmp8_ = NULL;
		_tmp4_ = sdx_math_tweenbase_pool;
		_tmp5_ = g_ptr_array_Pop (_tmp4_);
		_tmp6_ = (SdxMathTweenbase*) _tmp5_;
		_tmp7_ = _tmp6_->Reset;
		_tmp7__target = _tmp6_->Reset_target;
		_tmp8_ = _tmp7_ (_tmp7__target);
		_sdx_math_tweenbase_release0 (_tmp0_);
		_tmp0_ = (SdxMathTimeline*) _tmp8_;
		_sdx_math_tweenbase_release0 (_tmp6_);
	}
	_tmp9_ = _sdx_math_tweenbase_retain0 (_tmp0_);
	tl = _tmp9_;
	sdx_math_timeline_Setup (tl, SDX_MATH_TIMELINE_MODES_PARALLEL);
	result = tl;
	_sdx_math_tweenbase_release0 (_tmp0_);
	return result;
}


// symtbl.3 SdxMathTimeline / sdx_math_timeline
SdxMathTimeline* sdx_math_timeline_retain (SdxMathTimeline* self);
void sdx_math_timeline_release (SdxMathTimeline* self);
SdxMathTimeline* sdx_math_timeline_new (void) {
	SdxMathTimeline* self;
	SdxMathTweenbaseTweenReset _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	SdxMathTweenbase* _tmp1_ = NULL;
	SdxMathTweenbase* _tmp2_ = NULL;
	self = (SdxMathTimeline*) sdx_math_tweenbase_new ();
	((SdxMathTweenbase*) self)->kind = SDX_MATH_TWEEN_KIND_TIMELINE;
	sdx_math_timeline_Overrides (self);
	_tmp0_ = ((SdxMathTweenbase*) self)->Reset;
	_tmp0__target = ((SdxMathTweenbase*) self)->Reset_target;
	_tmp1_ = _tmp0_ (_tmp0__target);
	_tmp2_ = _tmp1_;
	_sdx_math_tweenbase_release0 (_tmp2_);
	return self;
}


void sdx_math_timeline_Setup (SdxMathTimeline* self, SdxMathTimelineModes mode) {
	SdxMathTimelineModes _tmp0_ = 0;
	SdxMathTweenbase* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = mode;
	((SdxMathTweenbase*) self)->mode = _tmp0_;
	_tmp1_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) self);
	_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) self)->current);
	((SdxMathTweenbase*) self)->current = _tmp1_;
}


/**
         * Adds a Tween to the current timeline.
         * Nests a Timeline in the current one.
         *
         * @return The current timeline, for chaining instructions.
         */
SdxMathTimeline* sdx_math_timeline_Push (SdxMathTimeline* self, SdxMathTween* tween) {
	SdxMathTimeline* result = NULL;
	gboolean _tmp0_ = FALSE;
	SdxMathTweenKind _tmp2_ = 0;
	SdxMathTweenbase* _tmp10_ = NULL;
	GPtrArray* _tmp11_ = NULL;
	SdxMathTween* _tmp12_ = NULL;
	SdxMathTweenbase* _tmp13_ = NULL;
	SdxMathTimeline* _tmp14_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (tween != NULL, NULL);
	_tmp0_ = ((SdxMathTweenbase*) self)->isBuilt;
	if (_tmp0_) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_RuntimeException, "You can't push anything to a timeline once it is started");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = ((SdxMathTweenbase*) self)->kind;
	if (_tmp2_ == SDX_MATH_TWEEN_KIND_TIMELINE) {
		SdxMathTween* _tmp3_ = NULL;
		SdxMathTweenbase* _tmp4_ = NULL;
		SdxMathTween* _tmp5_ = NULL;
		SdxMathTween* _tmp7_ = NULL;
		SdxMathTweenbase* _tmp8_ = NULL;
		SdxMathTweenbase* _tmp9_ = NULL;
		_tmp3_ = tween;
		_tmp4_ = ((SdxMathTweenbase*) _tmp3_)->current;
		_tmp5_ = tween;
		if (_tmp4_ != _tmp5_) {
			GError* _tmp6_ = NULL;
			_tmp6_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_RuntimeException, "You forgot to call a few 'end()' statements in your pushed timeline");
			_inner_error_ = _tmp6_;
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp7_ = tween;
		_tmp8_ = ((SdxMathTweenbase*) self)->current;
		_tmp9_ = _sdx_math_tweenbase_retain0 (_tmp8_);
		_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) _tmp7_)->parent);
		((SdxMathTweenbase*) _tmp7_)->parent = _tmp9_;
	}
	_tmp10_ = ((SdxMathTweenbase*) self)->current;
	_tmp11_ = _tmp10_->children;
	_tmp12_ = tween;
	_tmp13_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) _tmp12_);
	g_ptr_array_add (_tmp11_, _tmp13_);
	_tmp14_ = _sdx_math_tweenbase_retain0 (self);
	result = _tmp14_;
	return result;
}


/**
         * Adds a pause to the timeline. The pause may be negative if you want to
         * overlap the preceding and following children.
         *
         * @param time A positive or negative duration.
         * @return The current timeline, for chaining instructions.
         */
SdxMathTimeline* sdx_math_timeline_PushPause (SdxMathTimeline* self, gfloat time) {
	SdxMathTimeline* result = NULL;
	gboolean _tmp0_ = FALSE;
	SdxMathTweenbase* _tmp2_ = NULL;
	GPtrArray* _tmp3_ = NULL;
	SdxMathTween* _tmp4_ = NULL;
	SdxMathTween* _tmp5_ = NULL;
	gfloat _tmp6_ = 0.0F;
	SdxMathTweenbase* _tmp7_ = NULL;
	SdxMathTimeline* _tmp8_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((SdxMathTweenbase*) self)->isBuilt;
	if (_tmp0_) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_RuntimeException, "You can't push anything to a timeline once it is started");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = ((SdxMathTweenbase*) self)->current;
	_tmp3_ = _tmp2_->children;
	_tmp4_ = sdx_math_tween_Mark ();
	_tmp5_ = _tmp4_;
	_tmp6_ = time;
	_tmp7_ = sdx_math_tweenbase_Delay ((SdxMathTweenbase*) _tmp5_, _tmp6_);
	g_ptr_array_add (_tmp3_, _tmp7_);
	_sdx_math_tweenbase_release0 (_tmp5_);
	_tmp8_ = _sdx_math_tweenbase_retain0 (self);
	result = _tmp8_;
	return result;
}


/**
         * Starts a nested timeline with a 'sequence' behavior. Don't forget to
         * call {@link End} to close this nested timeline.
         *
         * @return The current timeline, for chaining instructions.
         */
SdxMathTimeline* sdx_math_timeline_BeginSequence (SdxMathTimeline* self) {
	SdxMathTimeline* result = NULL;
	gboolean _tmp0_ = FALSE;
	SdxMathTimeline* _tmp2_ = NULL;
	GPtrArray* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	SdxMathTimeline* tl = NULL;
	SdxMathTimeline* _tmp11_ = NULL;
	SdxMathTweenbase* _tmp12_ = NULL;
	SdxMathTweenbase* _tmp13_ = NULL;
	SdxMathTweenbase* _tmp14_ = NULL;
	GPtrArray* _tmp15_ = NULL;
	SdxMathTweenbase* _tmp16_ = NULL;
	SdxMathTweenbase* _tmp17_ = NULL;
	SdxMathTimeline* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((SdxMathTweenbase*) self)->isBuilt;
	if (_tmp0_) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_RuntimeException, "You can't push anything to a timeline once it is started");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp3_ = sdx_math_tweenbase_pool;
	_tmp4_ = g_ptr_array_IsEmpty (_tmp3_);
	if (_tmp4_) {
		SdxMathTimeline* _tmp5_ = NULL;
		_tmp5_ = sdx_math_timeline_new ();
		_sdx_math_tweenbase_release0 (_tmp2_);
		_tmp2_ = _tmp5_;
	} else {
		GPtrArray* _tmp6_ = NULL;
		gpointer _tmp7_ = NULL;
		SdxMathTweenbase* _tmp8_ = NULL;
		SdxMathTweenbaseTweenReset _tmp9_ = NULL;
		void* _tmp9__target = NULL;
		SdxMathTweenbase* _tmp10_ = NULL;
		_tmp6_ = sdx_math_tweenbase_pool;
		_tmp7_ = g_ptr_array_Pop (_tmp6_);
		_tmp8_ = (SdxMathTweenbase*) _tmp7_;
		_tmp9_ = _tmp8_->Reset;
		_tmp9__target = _tmp8_->Reset_target;
		_tmp10_ = _tmp9_ (_tmp9__target);
		_sdx_math_tweenbase_release0 (_tmp2_);
		_tmp2_ = (SdxMathTimeline*) _tmp10_;
		_sdx_math_tweenbase_release0 (_tmp8_);
	}
	_tmp11_ = _sdx_math_tweenbase_retain0 (_tmp2_);
	tl = _tmp11_;
	_tmp12_ = ((SdxMathTweenbase*) self)->current;
	_tmp13_ = _sdx_math_tweenbase_retain0 (_tmp12_);
	_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) tl)->parent);
	((SdxMathTweenbase*) tl)->parent = _tmp13_;
	((SdxMathTweenbase*) tl)->mode = SDX_MATH_TIMELINE_MODES_SEQUENCE;
	_tmp14_ = ((SdxMathTweenbase*) self)->current;
	_tmp15_ = _tmp14_->children;
	_tmp16_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) tl);
	g_ptr_array_add (_tmp15_, _tmp16_);
	_tmp17_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) tl);
	_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) self)->current);
	((SdxMathTweenbase*) self)->current = _tmp17_;
	_tmp18_ = _sdx_math_tweenbase_retain0 (self);
	result = _tmp18_;
	_sdx_math_tweenbase_release0 (tl);
	_sdx_math_tweenbase_release0 (_tmp2_);
	return result;
}


/**
         * Starts a nested timeline with a 'parallel' behavior. Don't forget to
         * call {@link End} to close this nested timeline.
         *
         * @return The current timeline, for chaining instructions.
         */
SdxMathTimeline* sdx_math_timeline_BeginParallel (SdxMathTimeline* self) {
	SdxMathTimeline* result = NULL;
	gboolean _tmp0_ = FALSE;
	SdxMathTimeline* _tmp2_ = NULL;
	GPtrArray* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	SdxMathTimeline* tl = NULL;
	SdxMathTimeline* _tmp11_ = NULL;
	SdxMathTweenbase* _tmp12_ = NULL;
	SdxMathTweenbase* _tmp13_ = NULL;
	SdxMathTweenbase* _tmp14_ = NULL;
	GPtrArray* _tmp15_ = NULL;
	SdxMathTweenbase* _tmp16_ = NULL;
	SdxMathTweenbase* _tmp17_ = NULL;
	SdxMathTimeline* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((SdxMathTweenbase*) self)->isBuilt;
	if (_tmp0_) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_RuntimeException, "You can't push anything to a timeline once it is started");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp3_ = sdx_math_tweenbase_pool;
	_tmp4_ = g_ptr_array_IsEmpty (_tmp3_);
	if (_tmp4_) {
		SdxMathTimeline* _tmp5_ = NULL;
		_tmp5_ = sdx_math_timeline_new ();
		_sdx_math_tweenbase_release0 (_tmp2_);
		_tmp2_ = _tmp5_;
	} else {
		GPtrArray* _tmp6_ = NULL;
		gpointer _tmp7_ = NULL;
		SdxMathTweenbase* _tmp8_ = NULL;
		SdxMathTweenbaseTweenReset _tmp9_ = NULL;
		void* _tmp9__target = NULL;
		SdxMathTweenbase* _tmp10_ = NULL;
		_tmp6_ = sdx_math_tweenbase_pool;
		_tmp7_ = g_ptr_array_Pop (_tmp6_);
		_tmp8_ = (SdxMathTweenbase*) _tmp7_;
		_tmp9_ = _tmp8_->Reset;
		_tmp9__target = _tmp8_->Reset_target;
		_tmp10_ = _tmp9_ (_tmp9__target);
		_sdx_math_tweenbase_release0 (_tmp2_);
		_tmp2_ = (SdxMathTimeline*) _tmp10_;
		_sdx_math_tweenbase_release0 (_tmp8_);
	}
	_tmp11_ = _sdx_math_tweenbase_retain0 (_tmp2_);
	tl = _tmp11_;
	_tmp12_ = ((SdxMathTweenbase*) self)->current;
	_tmp13_ = _sdx_math_tweenbase_retain0 (_tmp12_);
	_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) tl)->parent);
	((SdxMathTweenbase*) tl)->parent = _tmp13_;
	((SdxMathTweenbase*) tl)->mode = SDX_MATH_TIMELINE_MODES_PARALLEL;
	_tmp14_ = ((SdxMathTweenbase*) self)->current;
	_tmp15_ = _tmp14_->children;
	_tmp16_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) tl);
	g_ptr_array_add (_tmp15_, _tmp16_);
	_tmp17_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) tl);
	_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) self)->current);
	((SdxMathTweenbase*) self)->current = _tmp17_;
	_tmp18_ = _sdx_math_tweenbase_retain0 (self);
	result = _tmp18_;
	_sdx_math_tweenbase_release0 (tl);
	_sdx_math_tweenbase_release0 (_tmp2_);
	return result;
}


/**
         * Closes the last nested timeline.
         *
         * @return The current timeline, for chaining instructions.
         */
SdxMathTimeline* sdx_math_timeline_End (SdxMathTimeline* self) {
	SdxMathTimeline* result = NULL;
	gboolean _tmp0_ = FALSE;
	SdxMathTweenbase* _tmp2_ = NULL;
	SdxMathTweenbase* _tmp4_ = NULL;
	SdxMathTweenbase* _tmp5_ = NULL;
	SdxMathTweenbase* _tmp6_ = NULL;
	SdxMathTimeline* _tmp7_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((SdxMathTweenbase*) self)->isBuilt;
	if (_tmp0_) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_RuntimeException, "You can't push anything to a timeline once it is started");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = ((SdxMathTweenbase*) self)->current;
	if (_tmp2_ == self) {
		GError* _tmp3_ = NULL;
		_tmp3_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_RuntimeException, "Nothing to end...");
		_inner_error_ = _tmp3_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp4_ = ((SdxMathTweenbase*) self)->current;
	_tmp5_ = _tmp4_->parent;
	_tmp6_ = _sdx_math_tweenbase_retain0 (_tmp5_);
	_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) self)->current);
	((SdxMathTweenbase*) self)->current = _tmp6_;
	_tmp7_ = _sdx_math_tweenbase_retain0 (self);
	result = _tmp7_;
	return result;
}


/**
         * Gets a list of the timeline children. If the timeline is started, the
         * list will be immutable.
         */
static gpointer _g_ptr_array_ref0 (gpointer self) {
	return self ? g_ptr_array_ref (self) : NULL;
}


GPtrArray* sdx_math_timeline_GetChildren (SdxMathTimeline* self) {
	GPtrArray* result = NULL;
	SdxMathTweenbase* _tmp0_ = NULL;
	GPtrArray* _tmp1_ = NULL;
	GPtrArray* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((SdxMathTweenbase*) self)->current;
	_tmp1_ = _tmp0_->children;
	_tmp2_ = _g_ptr_array_ref0 (_tmp1_);
	result = _tmp2_;
	return result;
}


static Block24Data* block24_data_ref (Block24Data* _data24_) {
	g_atomic_int_inc (&_data24_->_ref_count_);
	return _data24_;
}


static void block24_data_unref (void * _userdata_) {
	Block24Data* _data24_;
	_data24_ = (Block24Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data24_->_ref_count_)) {
		SdxMathTimeline* self;
		self = _data24_->self;
		(_data24_->Start__target_destroy_notify == NULL) ? NULL : (_data24_->Start__target_destroy_notify (_data24_->Start__target), NULL);
		_data24_->Start_ = NULL;
		_data24_->Start__target = NULL;
		_data24_->Start__target_destroy_notify = NULL;
		(_data24_->Reset__target_destroy_notify == NULL) ? NULL : (_data24_->Reset__target_destroy_notify (_data24_->Reset__target), NULL);
		_data24_->Reset_ = NULL;
		_data24_->Reset__target = NULL;
		_data24_->Reset__target_destroy_notify = NULL;
		_sdx_math_tweenbase_release0 (self);
		g_slice_free (Block24Data, _data24_);
	}
}


// symtbl.2 sdx_math_tweenbase
void sdx_math_tweenbase_release (SdxMathTweenbase* self);
void sdx_math_tweenbase_free (SdxMathTweenbase* self);
SdxMathTweenbase* sdx_math_tweenbase_retain (SdxMathTweenbase* self);
static void _sdx_math_tweenbase_release0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (sdx_math_tweenbase_release (var), NULL));
}


static SdxMathTweenbase* __lambda131_ (Block24Data* _data24_) {
	SdxMathTimeline* self;
	SdxMathTweenbase* result = NULL;
	SdxMathTweenbase* _tmp0_ = NULL;
	SdxMathTweenbase* _tmp1_ = NULL;
	GPtrArray* _tmp2_ = NULL;
	SdxMathTweenbase* _tmp3_ = NULL;
	SdxMathTweenbase* _tmp4_ = NULL;
	SdxMathTweenbase* _tmp5_ = NULL;
	self = _data24_->self;
	_tmp0_ = _data24_->Reset_ (_data24_->Reset__target);
	_tmp1_ = _tmp0_;
	_sdx_math_tweenbase_release0 (_tmp1_);
	_tmp2_ = g_ptr_array_new_full ((guint) 0, _sdx_math_tweenbase_release0_);
	_g_ptr_array_unref0 (((SdxMathTweenbase*) self)->children);
	((SdxMathTweenbase*) self)->children = _tmp2_;
	_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) self)->parent);
	((SdxMathTweenbase*) self)->parent = NULL;
	_tmp3_ = ((SdxMathTweenbase*) self)->parent;
	_tmp4_ = _sdx_math_tweenbase_retain0 (_tmp3_);
	_sdx_math_tweenbase_release0 (((SdxMathTweenbase*) self)->current);
	((SdxMathTweenbase*) self)->current = _tmp4_;
	((SdxMathTweenbase*) self)->isBuilt = FALSE;
	_tmp5_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) self);
	result = _tmp5_;
	return result;
}


static SdxMathTweenbase* ___lambda131__sdx_math_tweenbase_tween_reset (gpointer self) {
	SdxMathTweenbase* result;
	result = __lambda131_ (self);
	return result;
}


static gint g_ptr_array_get_length (GPtrArray* self) {
	gint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->len;
	result = (gint) _tmp0_;
	return result;
}


static void g_ptr_array_set_length (GPtrArray* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	g_ptr_array_set_size (self, _tmp0_);
}


static SdxMathTweenbase* __lambda132_ (SdxMathTimeline* self) {
	SdxMathTweenbase* result = NULL;
	gboolean _tmp0_ = FALSE;
	SdxMathTweenbase* _tmp32_ = NULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = ((SdxMathTweenbase*) self)->isBuilt;
	if (_tmp0_) {
		SdxMathTweenbase* _tmp1_ = NULL;
		_tmp1_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) self);
		result = _tmp1_;
		return result;
	}
	((SdxMathTweenbase*) self)->duration = (gfloat) 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gint _tmp4_ = 0;
				GPtrArray* _tmp5_ = NULL;
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				SdxMathTweenbase* obj = NULL;
				GPtrArray* _tmp8_ = NULL;
				gint _tmp9_ = 0;
				gconstpointer _tmp10_ = NULL;
				SdxMathTweenbase* _tmp11_ = NULL;
				SdxMathTweenbase* _tmp12_ = NULL;
				gint _tmp13_ = 0;
				SdxMathTweenbase* _tmp15_ = NULL;
				SdxMathTweenbaseTweenBuild _tmp16_ = NULL;
				void* _tmp16__target = NULL;
				SdxMathTweenbase* _tmp17_ = NULL;
				SdxMathTweenbase* _tmp18_ = NULL;
				SdxMathTimelineModes _tmp19_ = 0;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = ((SdxMathTweenbase*) self)->children;
				_tmp6_ = g_ptr_array_get_length (_tmp5_);
				_tmp7_ = _tmp6_;
				if (!(_tmp4_ < _tmp7_)) {
					break;
				}
				_tmp8_ = ((SdxMathTweenbase*) self)->children;
				_tmp9_ = i;
				_tmp10_ = g_ptr_array_index (_tmp8_, (guint) _tmp9_);
				_tmp11_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) _tmp10_);
				obj = _tmp11_;
				_tmp12_ = obj;
				_tmp13_ = sdx_math_tweenbase_GetRepeatCount (_tmp12_);
				if (_tmp13_ < 0) {
					GError* _tmp14_ = NULL;
					_tmp14_ = g_error_new_literal (SDX_EXCEPTION, SDX_EXCEPTION_RuntimeException, "You can't push an object with infinite repetitions in a timeline");
					_inner_error_ = _tmp14_;
					_sdx_math_tweenbase_release0 (obj);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return NULL;
				}
				_tmp15_ = obj;
				_tmp16_ = _tmp15_->Build;
				_tmp16__target = _tmp15_->Build_target;
				_tmp17_ = _tmp16_ (_tmp16__target);
				_tmp18_ = _tmp17_;
				_sdx_math_tweenbase_release0 (_tmp18_);
				_tmp19_ = ((SdxMathTweenbase*) self)->mode;
				switch (_tmp19_) {
					case SDX_MATH_TIMELINE_MODES_SEQUENCE:
					{
						gfloat tDelay = 0.0F;
						gfloat _tmp20_ = 0.0F;
						gfloat _tmp21_ = 0.0F;
						SdxMathTweenbase* _tmp22_ = NULL;
						gfloat _tmp23_ = 0.0F;
						SdxMathTweenbase* _tmp24_ = NULL;
						SdxMathTweenbase* _tmp25_ = NULL;
						gfloat _tmp26_ = 0.0F;
						gfloat _tmp27_ = 0.0F;
						_tmp20_ = ((SdxMathTweenbase*) self)->duration;
						tDelay = _tmp20_;
						_tmp21_ = ((SdxMathTweenbase*) self)->duration;
						_tmp22_ = obj;
						_tmp23_ = sdx_math_tweenbase_GetFullDuration (_tmp22_);
						((SdxMathTweenbase*) self)->duration = _tmp21_ + _tmp23_;
						_tmp24_ = obj;
						_tmp25_ = obj;
						_tmp26_ = _tmp25_->delay;
						_tmp27_ = tDelay;
						_tmp25_->delay = _tmp26_ + _tmp27_;
						break;
					}
					case SDX_MATH_TIMELINE_MODES_PARALLEL:
					{
						gfloat _tmp28_ = 0.0F;
						SdxMathTweenbase* _tmp29_ = NULL;
						gfloat _tmp30_ = 0.0F;
						gfloat _tmp31_ = 0.0F;
						_tmp28_ = ((SdxMathTweenbase*) self)->duration;
						_tmp29_ = obj;
						_tmp30_ = sdx_math_tweenbase_GetFullDuration (_tmp29_);
						_tmp31_ = fmaxf (_tmp28_, _tmp30_);
						((SdxMathTweenbase*) self)->duration = _tmp31_;
						break;
					}
					default:
					break;
				}
				_sdx_math_tweenbase_release0 (obj);
			}
		}
	}
	((SdxMathTweenbase*) self)->isBuilt = TRUE;
	_tmp32_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) self);
	result = _tmp32_;
	return result;
}


static SdxMathTweenbase* ___lambda132__sdx_math_tweenbase_tween_build (gpointer self) {
	SdxMathTweenbase* result;
	result = __lambda132_ ((SdxMathTimeline*) self);
	return result;
}


static SdxMathTweenbase* __lambda133_ (Block24Data* _data24_) {
	SdxMathTimeline* self;
	SdxMathTweenbase* result = NULL;
	SdxMathTweenbase* _tmp0_ = NULL;
	SdxMathTweenbase* _tmp1_ = NULL;
	SdxMathTweenbase* _tmp16_ = NULL;
	self = _data24_->self;
	_tmp0_ = _data24_->Start_ (NULL, _data24_->Start__target);
	_tmp1_ = _tmp0_;
	_sdx_math_tweenbase_release0 (_tmp1_);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gint _tmp4_ = 0;
				GPtrArray* _tmp5_ = NULL;
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				SdxMathTweenbase* obj = NULL;
				GPtrArray* _tmp8_ = NULL;
				gint _tmp9_ = 0;
				gconstpointer _tmp10_ = NULL;
				SdxMathTweenbase* _tmp11_ = NULL;
				SdxMathTweenbase* _tmp12_ = NULL;
				SdxMathTweenbaseTweenStart _tmp13_ = NULL;
				void* _tmp13__target = NULL;
				SdxMathTweenbase* _tmp14_ = NULL;
				SdxMathTweenbase* _tmp15_ = NULL;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = ((SdxMathTweenbase*) self)->children;
				_tmp6_ = g_ptr_array_get_length (_tmp5_);
				_tmp7_ = _tmp6_;
				if (!(_tmp4_ < _tmp7_)) {
					break;
				}
				_tmp8_ = ((SdxMathTweenbase*) self)->children;
				_tmp9_ = i;
				_tmp10_ = g_ptr_array_index (_tmp8_, (guint) _tmp9_);
				_tmp11_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) _tmp10_);
				obj = _tmp11_;
				_tmp12_ = obj;
				_tmp13_ = _tmp12_->Start;
				_tmp13__target = _tmp12_->Start_target;
				_tmp14_ = _tmp13_ (NULL, _tmp13__target);
				_tmp15_ = _tmp14_;
				_sdx_math_tweenbase_release0 (_tmp15_);
				_sdx_math_tweenbase_release0 (obj);
			}
		}
	}
	_tmp16_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) self);
	result = _tmp16_;
	return result;
}


static SdxMathTweenbase* ___lambda133__sdx_math_tweenbase_tween_start (SdxMathTweenManager* manager, gpointer self) {
	SdxMathTweenbase* result;
	result = __lambda133_ (self);
	return result;
}


static void __lambda134_ (SdxMathTimeline* self) {
	{
		gint i = 0;
		GPtrArray* _tmp0_ = NULL;
		gint _tmp1_ = 0;
		gint _tmp2_ = 0;
		_tmp0_ = ((SdxMathTweenbase*) self)->children;
		_tmp1_ = g_ptr_array_get_length (_tmp0_);
		_tmp2_ = _tmp1_;
		i = _tmp2_ - 1;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				gint _tmp5_ = 0;
				SdxMathTweenbase* obj = NULL;
				GPtrArray* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				gconstpointer _tmp8_ = NULL;
				SdxMathTweenbase* _tmp9_ = NULL;
				GPtrArray* _tmp10_ = NULL;
				gint _tmp11_ = 0;
				SdxMathTweenbase* _tmp12_ = NULL;
				SdxMathTweenbaseTweenFree _tmp13_ = NULL;
				void* _tmp13__target = NULL;
				if (!_tmp3_) {
					gint _tmp4_ = 0;
					_tmp4_ = i;
					i = _tmp4_ - 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = i;
				if (!(_tmp5_ >= 0)) {
					break;
				}
				_tmp6_ = ((SdxMathTweenbase*) self)->children;
				_tmp7_ = i;
				_tmp8_ = g_ptr_array_index (_tmp6_, (guint) _tmp7_);
				_tmp9_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) _tmp8_);
				obj = _tmp9_;
				_tmp10_ = ((SdxMathTweenbase*) self)->children;
				_tmp11_ = i;
				g_ptr_array_remove_index (_tmp10_, (guint) _tmp11_);
				_tmp12_ = obj;
				_tmp13_ = _tmp12_->Free;
				_tmp13__target = _tmp12_->Free_target;
				_tmp13_ (_tmp13__target);
				_sdx_math_tweenbase_release0 (obj);
			}
		}
	}
}


static void ___lambda134__sdx_math_tweenbase_tween_free (gpointer self) {
	__lambda134_ ((SdxMathTimeline*) self);
}


static void __lambda135_ (SdxMathTimeline* self, gint step, gint lastStep, gboolean isIterationStep, gfloat delta) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp21_ = FALSE;
	gboolean _tmp22_ = FALSE;
	gboolean _tmp41_ = FALSE;
	gint _tmp42_ = 0;
	gint _tmp43_ = 0;
	_tmp1_ = isIterationStep;
	if (!_tmp1_) {
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		_tmp2_ = step;
		_tmp3_ = lastStep;
		_tmp0_ = _tmp2_ > _tmp3_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gfloat _tmp4_ = 0.0F;
		gfloat _tmp5_ = 0.0F;
		gint _tmp6_ = 0;
		gboolean _tmp7_ = FALSE;
		gfloat dt = 0.0F;
		_tmp4_ = delta;
		_vala_assert (_tmp4_ >= ((gfloat) 0), "delta >= 0");
		_tmp6_ = lastStep;
		_tmp7_ = sdx_math_tweenbase_IsReverse ((SdxMathTweenbase*) self, _tmp6_);
		if (_tmp7_) {
			gfloat _tmp8_ = 0.0F;
			_tmp8_ = delta;
			_tmp5_ = (-_tmp8_) - 1;
		} else {
			gfloat _tmp9_ = 0.0F;
			_tmp9_ = delta;
			_tmp5_ = _tmp9_ + 1;
		}
		dt = _tmp5_;
		{
			gint i = 0;
			gint n = 0;
			GPtrArray* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			gint _tmp12_ = 0;
			i = 0;
			_tmp10_ = ((SdxMathTweenbase*) self)->children;
			_tmp11_ = g_ptr_array_get_length (_tmp10_);
			_tmp12_ = _tmp11_;
			n = _tmp12_;
			{
				gboolean _tmp13_ = FALSE;
				_tmp13_ = TRUE;
				while (TRUE) {
					gint _tmp15_ = 0;
					gint _tmp16_ = 0;
					GPtrArray* _tmp17_ = NULL;
					gint _tmp18_ = 0;
					gconstpointer _tmp19_ = NULL;
					gfloat _tmp20_ = 0.0F;
					if (!_tmp13_) {
						gint _tmp14_ = 0;
						_tmp14_ = i;
						i = _tmp14_ + 1;
					}
					_tmp13_ = FALSE;
					_tmp15_ = i;
					_tmp16_ = n;
					if (!(_tmp15_ < _tmp16_)) {
						break;
					}
					_tmp17_ = ((SdxMathTweenbase*) self)->children;
					_tmp18_ = i;
					_tmp19_ = g_ptr_array_index (_tmp17_, (guint) _tmp18_);
					_tmp20_ = dt;
					sdx_math_tweenbase_Update ((SdxMathTweenbase*) _tmp19_, _tmp20_);
				}
			}
		}
		return;
	}
	_tmp22_ = isIterationStep;
	if (!_tmp22_) {
		gint _tmp23_ = 0;
		gint _tmp24_ = 0;
		_tmp23_ = step;
		_tmp24_ = lastStep;
		_tmp21_ = _tmp23_ < _tmp24_;
	} else {
		_tmp21_ = FALSE;
	}
	if (_tmp21_) {
		gfloat _tmp25_ = 0.0F;
		gfloat _tmp26_ = 0.0F;
		gint _tmp27_ = 0;
		gboolean _tmp28_ = FALSE;
		gfloat dt = 0.0F;
		_tmp25_ = delta;
		_vala_assert (_tmp25_ <= ((gfloat) 0), "delta <= 0");
		_tmp27_ = lastStep;
		_tmp28_ = sdx_math_tweenbase_IsReverse ((SdxMathTweenbase*) self, _tmp27_);
		if (_tmp28_) {
			gfloat _tmp29_ = 0.0F;
			_tmp29_ = delta;
			_tmp26_ = (-_tmp29_) - 1;
		} else {
			gfloat _tmp30_ = 0.0F;
			_tmp30_ = delta;
			_tmp26_ = _tmp30_ + 1;
		}
		dt = _tmp26_;
		{
			gint i = 0;
			GPtrArray* _tmp31_ = NULL;
			gint _tmp32_ = 0;
			gint _tmp33_ = 0;
			_tmp31_ = ((SdxMathTweenbase*) self)->children;
			_tmp32_ = g_ptr_array_get_length (_tmp31_);
			_tmp33_ = _tmp32_;
			i = _tmp33_ - 1;
			{
				gboolean _tmp34_ = FALSE;
				_tmp34_ = TRUE;
				while (TRUE) {
					gint _tmp36_ = 0;
					GPtrArray* _tmp37_ = NULL;
					gint _tmp38_ = 0;
					gconstpointer _tmp39_ = NULL;
					gfloat _tmp40_ = 0.0F;
					if (!_tmp34_) {
						gint _tmp35_ = 0;
						_tmp35_ = i;
						i = _tmp35_ - 1;
					}
					_tmp34_ = FALSE;
					_tmp36_ = i;
					if (!(_tmp36_ >= 0)) {
						break;
					}
					_tmp37_ = ((SdxMathTweenbase*) self)->children;
					_tmp38_ = i;
					_tmp39_ = g_ptr_array_index (_tmp37_, (guint) _tmp38_);
					_tmp40_ = dt;
					sdx_math_tweenbase_Update ((SdxMathTweenbase*) _tmp39_, _tmp40_);
				}
			}
		}
		return;
	}
	_tmp41_ = isIterationStep;
	_vala_assert (_tmp41_, "isIterationStep");
	_tmp42_ = step;
	_tmp43_ = lastStep;
	if (_tmp42_ > _tmp43_) {
		gint _tmp44_ = 0;
		gboolean _tmp45_ = FALSE;
		_tmp44_ = step;
		_tmp45_ = sdx_math_tweenbase_IsReverse ((SdxMathTweenbase*) self, _tmp44_);
		if (_tmp45_) {
			SdxMathTweenbaseTweenForceEndValues _tmp46_ = NULL;
			void* _tmp46__target = NULL;
			_tmp46_ = ((SdxMathTweenbase*) self)->ForceEndValues;
			_tmp46__target = ((SdxMathTweenbase*) self)->ForceEndValues_target;
			_tmp46_ (_tmp46__target);
			{
				gint i = 0;
				gint n = 0;
				GPtrArray* _tmp47_ = NULL;
				gint _tmp48_ = 0;
				gint _tmp49_ = 0;
				i = 0;
				_tmp47_ = ((SdxMathTweenbase*) self)->children;
				_tmp48_ = g_ptr_array_get_length (_tmp47_);
				_tmp49_ = _tmp48_;
				n = _tmp49_;
				{
					gboolean _tmp50_ = FALSE;
					_tmp50_ = TRUE;
					while (TRUE) {
						gint _tmp52_ = 0;
						gint _tmp53_ = 0;
						GPtrArray* _tmp54_ = NULL;
						gint _tmp55_ = 0;
						gconstpointer _tmp56_ = NULL;
						gfloat _tmp57_ = 0.0F;
						if (!_tmp50_) {
							gint _tmp51_ = 0;
							_tmp51_ = i;
							i = _tmp51_ + 1;
						}
						_tmp50_ = FALSE;
						_tmp52_ = i;
						_tmp53_ = n;
						if (!(_tmp52_ < _tmp53_)) {
							break;
						}
						_tmp54_ = ((SdxMathTweenbase*) self)->children;
						_tmp55_ = i;
						_tmp56_ = g_ptr_array_index (_tmp54_, (guint) _tmp55_);
						_tmp57_ = delta;
						sdx_math_tweenbase_Update ((SdxMathTweenbase*) _tmp56_, _tmp57_);
					}
				}
			}
		} else {
			SdxMathTweenbaseTweenForceStartValues _tmp58_ = NULL;
			void* _tmp58__target = NULL;
			_tmp58_ = ((SdxMathTweenbase*) self)->ForceStartValues;
			_tmp58__target = ((SdxMathTweenbase*) self)->ForceStartValues_target;
			_tmp58_ (_tmp58__target);
			{
				gint i = 0;
				gint n = 0;
				GPtrArray* _tmp59_ = NULL;
				gint _tmp60_ = 0;
				gint _tmp61_ = 0;
				i = 0;
				_tmp59_ = ((SdxMathTweenbase*) self)->children;
				_tmp60_ = g_ptr_array_get_length (_tmp59_);
				_tmp61_ = _tmp60_;
				n = _tmp61_;
				{
					gboolean _tmp62_ = FALSE;
					_tmp62_ = TRUE;
					while (TRUE) {
						gint _tmp64_ = 0;
						gint _tmp65_ = 0;
						GPtrArray* _tmp66_ = NULL;
						gint _tmp67_ = 0;
						gconstpointer _tmp68_ = NULL;
						gfloat _tmp69_ = 0.0F;
						if (!_tmp62_) {
							gint _tmp63_ = 0;
							_tmp63_ = i;
							i = _tmp63_ + 1;
						}
						_tmp62_ = FALSE;
						_tmp64_ = i;
						_tmp65_ = n;
						if (!(_tmp64_ < _tmp65_)) {
							break;
						}
						_tmp66_ = ((SdxMathTweenbase*) self)->children;
						_tmp67_ = i;
						_tmp68_ = g_ptr_array_index (_tmp66_, (guint) _tmp67_);
						_tmp69_ = delta;
						sdx_math_tweenbase_Update ((SdxMathTweenbase*) _tmp68_, _tmp69_);
					}
				}
			}
		}
	} else {
		gint _tmp70_ = 0;
		gint _tmp71_ = 0;
		_tmp70_ = step;
		_tmp71_ = lastStep;
		if (_tmp70_ < _tmp71_) {
			gint _tmp72_ = 0;
			gboolean _tmp73_ = FALSE;
			_tmp72_ = step;
			_tmp73_ = sdx_math_tweenbase_IsReverse ((SdxMathTweenbase*) self, _tmp72_);
			if (_tmp73_) {
				SdxMathTweenbaseTweenForceStartValues _tmp74_ = NULL;
				void* _tmp74__target = NULL;
				_tmp74_ = ((SdxMathTweenbase*) self)->ForceStartValues;
				_tmp74__target = ((SdxMathTweenbase*) self)->ForceStartValues_target;
				_tmp74_ (_tmp74__target);
				{
					gint i = 0;
					GPtrArray* _tmp75_ = NULL;
					gint _tmp76_ = 0;
					gint _tmp77_ = 0;
					_tmp75_ = ((SdxMathTweenbase*) self)->children;
					_tmp76_ = g_ptr_array_get_length (_tmp75_);
					_tmp77_ = _tmp76_;
					i = _tmp77_ - 1;
					{
						gboolean _tmp78_ = FALSE;
						_tmp78_ = TRUE;
						while (TRUE) {
							gint _tmp80_ = 0;
							GPtrArray* _tmp81_ = NULL;
							gint _tmp82_ = 0;
							gconstpointer _tmp83_ = NULL;
							gfloat _tmp84_ = 0.0F;
							if (!_tmp78_) {
								gint _tmp79_ = 0;
								_tmp79_ = i;
								i = _tmp79_ - 1;
							}
							_tmp78_ = FALSE;
							_tmp80_ = i;
							if (!(_tmp80_ >= 0)) {
								break;
							}
							_tmp81_ = ((SdxMathTweenbase*) self)->children;
							_tmp82_ = i;
							_tmp83_ = g_ptr_array_index (_tmp81_, (guint) _tmp82_);
							_tmp84_ = delta;
							sdx_math_tweenbase_Update ((SdxMathTweenbase*) _tmp83_, _tmp84_);
						}
					}
				}
			} else {
				SdxMathTweenbaseTweenForceEndValues _tmp85_ = NULL;
				void* _tmp85__target = NULL;
				_tmp85_ = ((SdxMathTweenbase*) self)->ForceEndValues;
				_tmp85__target = ((SdxMathTweenbase*) self)->ForceEndValues_target;
				_tmp85_ (_tmp85__target);
				{
					gint i = 0;
					GPtrArray* _tmp86_ = NULL;
					gint _tmp87_ = 0;
					gint _tmp88_ = 0;
					_tmp86_ = ((SdxMathTweenbase*) self)->children;
					_tmp87_ = g_ptr_array_get_length (_tmp86_);
					_tmp88_ = _tmp87_;
					i = _tmp88_ - 1;
					{
						gboolean _tmp89_ = FALSE;
						_tmp89_ = TRUE;
						while (TRUE) {
							gint _tmp91_ = 0;
							GPtrArray* _tmp92_ = NULL;
							gint _tmp93_ = 0;
							gconstpointer _tmp94_ = NULL;
							gfloat _tmp95_ = 0.0F;
							if (!_tmp89_) {
								gint _tmp90_ = 0;
								_tmp90_ = i;
								i = _tmp90_ - 1;
							}
							_tmp89_ = FALSE;
							_tmp91_ = i;
							if (!(_tmp91_ >= 0)) {
								break;
							}
							_tmp92_ = ((SdxMathTweenbase*) self)->children;
							_tmp93_ = i;
							_tmp94_ = g_ptr_array_index (_tmp92_, (guint) _tmp93_);
							_tmp95_ = delta;
							sdx_math_tweenbase_Update ((SdxMathTweenbase*) _tmp94_, _tmp95_);
						}
					}
				}
			}
		} else {
			gfloat _tmp96_ = 0.0F;
			gint _tmp97_ = 0;
			gboolean _tmp98_ = FALSE;
			gfloat dt = 0.0F;
			gfloat _tmp101_ = 0.0F;
			_tmp97_ = step;
			_tmp98_ = sdx_math_tweenbase_IsReverse ((SdxMathTweenbase*) self, _tmp97_);
			if (_tmp98_) {
				gfloat _tmp99_ = 0.0F;
				_tmp99_ = delta;
				_tmp96_ = -_tmp99_;
			} else {
				gfloat _tmp100_ = 0.0F;
				_tmp100_ = delta;
				_tmp96_ = _tmp100_;
			}
			dt = _tmp96_;
			_tmp101_ = delta;
			if (_tmp101_ >= ((gfloat) 0)) {
				{
					gint i = 0;
					gint n = 0;
					GPtrArray* _tmp102_ = NULL;
					gint _tmp103_ = 0;
					gint _tmp104_ = 0;
					i = 0;
					_tmp102_ = ((SdxMathTweenbase*) self)->children;
					_tmp103_ = g_ptr_array_get_length (_tmp102_);
					_tmp104_ = _tmp103_;
					n = _tmp104_;
					{
						gboolean _tmp105_ = FALSE;
						_tmp105_ = TRUE;
						while (TRUE) {
							gint _tmp107_ = 0;
							gint _tmp108_ = 0;
							GPtrArray* _tmp109_ = NULL;
							gint _tmp110_ = 0;
							gconstpointer _tmp111_ = NULL;
							gfloat _tmp112_ = 0.0F;
							if (!_tmp105_) {
								gint _tmp106_ = 0;
								_tmp106_ = i;
								i = _tmp106_ + 1;
							}
							_tmp105_ = FALSE;
							_tmp107_ = i;
							_tmp108_ = n;
							if (!(_tmp107_ < _tmp108_)) {
								break;
							}
							_tmp109_ = ((SdxMathTweenbase*) self)->children;
							_tmp110_ = i;
							_tmp111_ = g_ptr_array_index (_tmp109_, (guint) _tmp110_);
							_tmp112_ = dt;
							sdx_math_tweenbase_Update ((SdxMathTweenbase*) _tmp111_, _tmp112_);
						}
					}
				}
			} else {
				{
					gint i = 0;
					GPtrArray* _tmp113_ = NULL;
					gint _tmp114_ = 0;
					gint _tmp115_ = 0;
					_tmp113_ = ((SdxMathTweenbase*) self)->children;
					_tmp114_ = g_ptr_array_get_length (_tmp113_);
					_tmp115_ = _tmp114_;
					i = _tmp115_ - 1;
					{
						gboolean _tmp116_ = FALSE;
						_tmp116_ = TRUE;
						while (TRUE) {
							gint _tmp118_ = 0;
							GPtrArray* _tmp119_ = NULL;
							gint _tmp120_ = 0;
							gconstpointer _tmp121_ = NULL;
							gfloat _tmp122_ = 0.0F;
							if (!_tmp116_) {
								gint _tmp117_ = 0;
								_tmp117_ = i;
								i = _tmp117_ - 1;
							}
							_tmp116_ = FALSE;
							_tmp118_ = i;
							if (!(_tmp118_ >= 0)) {
								break;
							}
							_tmp119_ = ((SdxMathTweenbase*) self)->children;
							_tmp120_ = i;
							_tmp121_ = g_ptr_array_index (_tmp119_, (guint) _tmp120_);
							_tmp122_ = dt;
							sdx_math_tweenbase_Update ((SdxMathTweenbase*) _tmp121_, _tmp122_);
						}
					}
				}
			}
		}
	}
}


static void ___lambda135__sdx_math_tweenbase_tween_update_override (gint step, gint lastStep, gboolean isIterationStep, gfloat delta, gpointer self) {
	__lambda135_ ((SdxMathTimeline*) self, step, lastStep, isIterationStep, delta);
}


static void __lambda136_ (SdxMathTimeline* self) {
	{
		gint i = 0;
		GPtrArray* _tmp0_ = NULL;
		gint _tmp1_ = 0;
		gint _tmp2_ = 0;
		_tmp0_ = ((SdxMathTweenbase*) self)->children;
		_tmp1_ = g_ptr_array_get_length (_tmp0_);
		_tmp2_ = _tmp1_;
		i = _tmp2_ - 1;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				gint _tmp5_ = 0;
				SdxMathTweenbase* obj = NULL;
				GPtrArray* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				gconstpointer _tmp8_ = NULL;
				SdxMathTweenbase* _tmp9_ = NULL;
				SdxMathTweenbase* _tmp10_ = NULL;
				if (!_tmp3_) {
					gint _tmp4_ = 0;
					_tmp4_ = i;
					i = _tmp4_ - 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = i;
				if (!(_tmp5_ >= 0)) {
					break;
				}
				_tmp6_ = ((SdxMathTweenbase*) self)->children;
				_tmp7_ = i;
				_tmp8_ = g_ptr_array_index (_tmp6_, (guint) _tmp7_);
				_tmp9_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) _tmp8_);
				obj = _tmp9_;
				_tmp10_ = obj;
				sdx_math_tweenbase_ForceToStart (_tmp10_);
				_sdx_math_tweenbase_release0 (obj);
			}
		}
	}
}


static void ___lambda136__sdx_math_tweenbase_tween_force_start_values (gpointer self) {
	__lambda136_ ((SdxMathTimeline*) self);
}


static void __lambda137_ (SdxMathTimeline* self) {
	{
		gint i = 0;
		gint n = 0;
		GPtrArray* _tmp0_ = NULL;
		gint _tmp1_ = 0;
		gint _tmp2_ = 0;
		i = 0;
		_tmp0_ = ((SdxMathTweenbase*) self)->children;
		_tmp1_ = g_ptr_array_get_length (_tmp0_);
		_tmp2_ = _tmp1_;
		n = _tmp2_;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				gint _tmp5_ = 0;
				gint _tmp6_ = 0;
				SdxMathTweenbase* obj = NULL;
				GPtrArray* _tmp7_ = NULL;
				gint _tmp8_ = 0;
				gconstpointer _tmp9_ = NULL;
				SdxMathTweenbase* _tmp10_ = NULL;
				SdxMathTweenbase* _tmp11_ = NULL;
				gfloat _tmp12_ = 0.0F;
				if (!_tmp3_) {
					gint _tmp4_ = 0;
					_tmp4_ = i;
					i = _tmp4_ + 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = i;
				_tmp6_ = n;
				if (!(_tmp5_ < _tmp6_)) {
					break;
				}
				_tmp7_ = ((SdxMathTweenbase*) self)->children;
				_tmp8_ = i;
				_tmp9_ = g_ptr_array_index (_tmp7_, (guint) _tmp8_);
				_tmp10_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) _tmp9_);
				obj = _tmp10_;
				_tmp11_ = obj;
				_tmp12_ = ((SdxMathTweenbase*) self)->duration;
				sdx_math_tweenbase_ForceToEnd (_tmp11_, _tmp12_);
				_sdx_math_tweenbase_release0 (obj);
			}
		}
	}
}


static void ___lambda137__sdx_math_tweenbase_tween_force_end_values (gpointer self) {
	__lambda137_ ((SdxMathTimeline*) self);
}


static gboolean __lambda138_ (SdxMathTimeline* self, void* target, gint tweenType) {
	gboolean result = FALSE;
	{
		gint i = 0;
		gint n = 0;
		GPtrArray* _tmp0_ = NULL;
		gint _tmp1_ = 0;
		gint _tmp2_ = 0;
		i = 0;
		_tmp0_ = ((SdxMathTweenbase*) self)->children;
		_tmp1_ = g_ptr_array_get_length (_tmp0_);
		_tmp2_ = _tmp1_;
		n = _tmp2_;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				gint _tmp5_ = 0;
				gint _tmp6_ = 0;
				SdxMathTweenbase* obj = NULL;
				GPtrArray* _tmp7_ = NULL;
				gint _tmp8_ = 0;
				gconstpointer _tmp9_ = NULL;
				SdxMathTweenbase* _tmp10_ = NULL;
				SdxMathTweenbase* _tmp11_ = NULL;
				SdxMathTweenbaseTweenContainsTarget _tmp12_ = NULL;
				void* _tmp12__target = NULL;
				void* _tmp13_ = NULL;
				gint _tmp14_ = 0;
				gboolean _tmp15_ = FALSE;
				if (!_tmp3_) {
					gint _tmp4_ = 0;
					_tmp4_ = i;
					i = _tmp4_ + 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = i;
				_tmp6_ = n;
				if (!(_tmp5_ < _tmp6_)) {
					break;
				}
				_tmp7_ = ((SdxMathTweenbase*) self)->children;
				_tmp8_ = i;
				_tmp9_ = g_ptr_array_index (_tmp7_, (guint) _tmp8_);
				_tmp10_ = _sdx_math_tweenbase_retain0 ((SdxMathTweenbase*) _tmp9_);
				obj = _tmp10_;
				_tmp11_ = obj;
				_tmp12_ = _tmp11_->ContainsTarget;
				_tmp12__target = _tmp11_->ContainsTarget_target;
				_tmp13_ = target;
				_tmp14_ = tweenType;
				_tmp15_ = _tmp12_ (_tmp13_, _tmp14_, _tmp12__target);
				if (_tmp15_) {
					result = TRUE;
					_sdx_math_tweenbase_release0 (obj);
					return result;
				}
				_sdx_math_tweenbase_release0 (obj);
			}
		}
	}
	result = FALSE;
	return result;
}


static gboolean ___lambda138__sdx_math_tweenbase_tween_contains_target (void* target, gint tweenType, gpointer self) {
	gboolean result;
	result = __lambda138_ ((SdxMathTimeline*) self, target, tweenType);
	return result;
}


void sdx_math_timeline_Overrides (SdxMathTimeline* self) {
	Block24Data* _data24_;
	SdxMathTweenbaseTweenReset _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	SdxMathTweenbaseTweenStart _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	g_return_if_fail (self != NULL);
	_data24_ = g_slice_new0 (Block24Data);
	_data24_->_ref_count_ = 1;
	_data24_->self = sdx_math_tweenbase_retain (self);
	_tmp0_ = ((SdxMathTweenbase*) self)->Reset;
	_tmp0__target = ((SdxMathTweenbase*) self)->Reset_target;
	_data24_->Reset_ = _tmp0_;
	_data24_->Reset__target = _tmp0__target;
	_data24_->Reset__target_destroy_notify = NULL;
	_tmp1_ = ((SdxMathTweenbase*) self)->Start;
	_tmp1__target = ((SdxMathTweenbase*) self)->Start_target;
	_data24_->Start_ = _tmp1_;
	_data24_->Start__target = _tmp1__target;
	_data24_->Start__target_destroy_notify = NULL;
	(((SdxMathTweenbase*) self)->Reset_target_destroy_notify == NULL) ? NULL : (((SdxMathTweenbase*) self)->Reset_target_destroy_notify (((SdxMathTweenbase*) self)->Reset_target), NULL);
	((SdxMathTweenbase*) self)->Reset = NULL;
	((SdxMathTweenbase*) self)->Reset_target = NULL;
	((SdxMathTweenbase*) self)->Reset_target_destroy_notify = NULL;
	((SdxMathTweenbase*) self)->Reset = ___lambda131__sdx_math_tweenbase_tween_reset;
	((SdxMathTweenbase*) self)->Reset_target = block24_data_ref (_data24_);
	((SdxMathTweenbase*) self)->Reset_target_destroy_notify = block24_data_unref;
	(((SdxMathTweenbase*) self)->Build_target_destroy_notify == NULL) ? NULL : (((SdxMathTweenbase*) self)->Build_target_destroy_notify (((SdxMathTweenbase*) self)->Build_target), NULL);
	((SdxMathTweenbase*) self)->Build = NULL;
	((SdxMathTweenbase*) self)->Build_target = NULL;
	((SdxMathTweenbase*) self)->Build_target_destroy_notify = NULL;
	((SdxMathTweenbase*) self)->Build = ___lambda132__sdx_math_tweenbase_tween_build;
	((SdxMathTweenbase*) self)->Build_target = sdx_math_tweenbase_retain (self);
	((SdxMathTweenbase*) self)->Build_target_destroy_notify = sdx_math_tweenbase_release;
	(((SdxMathTweenbase*) self)->Start_target_destroy_notify == NULL) ? NULL : (((SdxMathTweenbase*) self)->Start_target_destroy_notify (((SdxMathTweenbase*) self)->Start_target), NULL);
	((SdxMathTweenbase*) self)->Start = NULL;
	((SdxMathTweenbase*) self)->Start_target = NULL;
	((SdxMathTweenbase*) self)->Start_target_destroy_notify = NULL;
	((SdxMathTweenbase*) self)->Start = ___lambda133__sdx_math_tweenbase_tween_start;
	((SdxMathTweenbase*) self)->Start_target = block24_data_ref (_data24_);
	((SdxMathTweenbase*) self)->Start_target_destroy_notify = block24_data_unref;
	(((SdxMathTweenbase*) self)->Free_target_destroy_notify == NULL) ? NULL : (((SdxMathTweenbase*) self)->Free_target_destroy_notify (((SdxMathTweenbase*) self)->Free_target), NULL);
	((SdxMathTweenbase*) self)->Free = NULL;
	((SdxMathTweenbase*) self)->Free_target = NULL;
	((SdxMathTweenbase*) self)->Free_target_destroy_notify = NULL;
	((SdxMathTweenbase*) self)->Free = ___lambda134__sdx_math_tweenbase_tween_free;
	((SdxMathTweenbase*) self)->Free_target = sdx_math_tweenbase_retain (self);
	((SdxMathTweenbase*) self)->Free_target_destroy_notify = sdx_math_tweenbase_release;
	(((SdxMathTweenbase*) self)->UpdateOverride_target_destroy_notify == NULL) ? NULL : (((SdxMathTweenbase*) self)->UpdateOverride_target_destroy_notify (((SdxMathTweenbase*) self)->UpdateOverride_target), NULL);
	((SdxMathTweenbase*) self)->UpdateOverride = NULL;
	((SdxMathTweenbase*) self)->UpdateOverride_target = NULL;
	((SdxMathTweenbase*) self)->UpdateOverride_target_destroy_notify = NULL;
	((SdxMathTweenbase*) self)->UpdateOverride = ___lambda135__sdx_math_tweenbase_tween_update_override;
	((SdxMathTweenbase*) self)->UpdateOverride_target = sdx_math_tweenbase_retain (self);
	((SdxMathTweenbase*) self)->UpdateOverride_target_destroy_notify = sdx_math_tweenbase_release;
	(((SdxMathTweenbase*) self)->ForceStartValues_target_destroy_notify == NULL) ? NULL : (((SdxMathTweenbase*) self)->ForceStartValues_target_destroy_notify (((SdxMathTweenbase*) self)->ForceStartValues_target), NULL);
	((SdxMathTweenbase*) self)->ForceStartValues = NULL;
	((SdxMathTweenbase*) self)->ForceStartValues_target = NULL;
	((SdxMathTweenbase*) self)->ForceStartValues_target_destroy_notify = NULL;
	((SdxMathTweenbase*) self)->ForceStartValues = ___lambda136__sdx_math_tweenbase_tween_force_start_values;
	((SdxMathTweenbase*) self)->ForceStartValues_target = sdx_math_tweenbase_retain (self);
	((SdxMathTweenbase*) self)->ForceStartValues_target_destroy_notify = sdx_math_tweenbase_release;
	(((SdxMathTweenbase*) self)->ForceEndValues_target_destroy_notify == NULL) ? NULL : (((SdxMathTweenbase*) self)->ForceEndValues_target_destroy_notify (((SdxMathTweenbase*) self)->ForceEndValues_target), NULL);
	((SdxMathTweenbase*) self)->ForceEndValues = NULL;
	((SdxMathTweenbase*) self)->ForceEndValues_target = NULL;
	((SdxMathTweenbase*) self)->ForceEndValues_target_destroy_notify = NULL;
	((SdxMathTweenbase*) self)->ForceEndValues = ___lambda137__sdx_math_tweenbase_tween_force_end_values;
	((SdxMathTweenbase*) self)->ForceEndValues_target = sdx_math_tweenbase_retain (self);
	((SdxMathTweenbase*) self)->ForceEndValues_target_destroy_notify = sdx_math_tweenbase_release;
	(((SdxMathTweenbase*) self)->ContainsTarget_target_destroy_notify == NULL) ? NULL : (((SdxMathTweenbase*) self)->ContainsTarget_target_destroy_notify (((SdxMathTweenbase*) self)->ContainsTarget_target), NULL);
	((SdxMathTweenbase*) self)->ContainsTarget = NULL;
	((SdxMathTweenbase*) self)->ContainsTarget_target = NULL;
	((SdxMathTweenbase*) self)->ContainsTarget_target_destroy_notify = NULL;
	((SdxMathTweenbase*) self)->ContainsTarget = ___lambda138__sdx_math_tweenbase_tween_contains_target;
	((SdxMathTweenbase*) self)->ContainsTarget_target = sdx_math_tweenbase_retain (self);
	((SdxMathTweenbase*) self)->ContainsTarget_target_destroy_notify = sdx_math_tweenbase_release;
	block24_data_unref (_data24_);
	_data24_ = NULL;
}



