/* Sprite.c generated by valac 0.34.8, the Vala compiler
 * generated from Sprite.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_render.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_surface.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL.h>

typedef struct _Sprite Sprite;
#define _SDL_DestroyTexture0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyTexture (var), NULL)))
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))

struct _Sprite {
	gint _retainCount;
	SDL_Texture* texture;
	guint16 w;
	guint16 h;
};



void sprite_free (Sprite* self);
static void sprite_instance_init (Sprite * self);
Sprite* sprite_retain (Sprite* self);
void sprite_release (Sprite* self);
void sprite_free (Sprite* self);
Sprite* sprite_new (const gchar* file, SDL_Renderer* renderer);


Sprite* sprite_retain (Sprite* self) {
	Sprite* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sprite_release (Sprite* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sprite_free (self);
	}
}


Sprite* sprite_new (const gchar* file, SDL_Renderer* renderer) {
	Sprite* self;
	SDL_Surface* temp = NULL;
	const gchar* _tmp0_ = NULL;
	SDL_Surface* _tmp1_ = NULL;
	SDL_Surface* _tmp2_ = NULL;
	SDL_Surface* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	SDL_Surface* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	SDL_Renderer* _tmp9_ = NULL;
	SDL_Surface* _tmp10_ = NULL;
	SDL_Texture* _tmp11_ = NULL;
	SDL_Texture* _tmp12_ = NULL;
	g_return_val_if_fail (file != NULL, NULL);
	g_return_val_if_fail (renderer != NULL, NULL);
	self = g_slice_new0 (Sprite);
	sprite_instance_init (self);
	_tmp0_ = file;
	_tmp1_ = IMG_Load (_tmp0_);
	temp = _tmp1_;
	_tmp2_ = temp;
	if (_tmp2_ == NULL) {
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		_tmp3_ = file;
		_tmp4_ = SDL_GetError ();
		g_print ("Couldn't load %s: %s\n", _tmp3_, _tmp4_);
	}
	_tmp5_ = temp;
	_tmp6_ = _tmp5_->w;
	self->w = (guint16) _tmp6_;
	_tmp7_ = temp;
	_tmp8_ = _tmp7_->h;
	self->h = (guint16) _tmp8_;
	_tmp9_ = renderer;
	_tmp10_ = temp;
	_tmp11_ = SDL_CreateTextureFromSurface (_tmp9_, _tmp10_);
	_SDL_DestroyTexture0 (self->texture);
	self->texture = _tmp11_;
	_tmp12_ = self->texture;
	if (_tmp12_ == NULL) {
		const gchar* _tmp13_ = NULL;
		_tmp13_ = SDL_GetError ();
		g_print ("Couldn't create texture: %s\n", _tmp13_);
	}
	_SDL_FreeSurface0 (temp);
	return self;
}


static void sprite_instance_init (Sprite * self) {
	self->_retainCount = 1;
}


void sprite_free (Sprite* self) {
	_SDL_DestroyTexture0 (self->texture);
	g_slice_free (Sprite, self);
}



