/* InputSystem.c generated by valac 0.34.8, the Vala compiler
 * generated from InputSystem.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_rect.h>
#include <float.h>
#include <math.h>

typedef struct _systemsInputSystem systemsInputSystem;
typedef struct _Game Game;
typedef struct _entitasWorld entitasWorld;
typedef entitasWorld Factory;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _entitasBackground entitasBackground;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _entitasBullet entitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _entitasEnemy1 entitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _entitasEnemy2 entitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _entitasEnemy3 entitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _entitasExpires entitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _entitasHealth entitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _entitasHud entitasHud;

#define ENTITAS_TYPE_INDEX (entitas_index_get_type ())
typedef struct _entitasIndex entitasIndex;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _entitasLayer entitasLayer;

#define ENTITAS_TYPE_POSITION (entitas_position_get_type ())
typedef struct _entitasPosition entitasPosition;

#define ENTITAS_TYPE_SCALE (entitas_scale_get_type ())
typedef struct _entitasScale entitasScale;

#define ENTITAS_TYPE_SPRITE (entitas_sprite_get_type ())
typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _entitasSprite entitasSprite;

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef struct _entitasText entitasText;

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _entitasTint entitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _entitasTween entitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _entitasVelocity entitasVelocity;
typedef struct _entitasEntity entitasEntity;
void game_release (Game* self);
void game_free (Game* self);
Game* game_retain (Game* self);
#define _game_release0(var) ((var == NULL) ? NULL : (var = (game_release (var), NULL)))
void entitas_world_release (entitasWorld* self);
void entitas_world_free (entitasWorld* self);
entitasWorld* entitas_world_retain (entitasWorld* self);
#define _entitas_world_release0(var) ((var == NULL) ? NULL : (var = (entitas_world_release (var), NULL)))

#define ENTITAS_TYPE_ISYSTEM (entitas_isystem_get_type ())
typedef struct _entitasISystem entitasISystem;

struct _entitasBackground {
	gboolean active;
};

struct _entitasBullet {
	gboolean active;
};

struct _entitasEnemy1 {
	gboolean active;
};

struct _entitasEnemy2 {
	gboolean active;
};

struct _entitasEnemy3 {
	gboolean active;
};

struct _entitasExpires {
	gdouble value;
};

struct _entitasHealth {
	gdouble current;
	gdouble maximum;
};

struct _entitasHud {
	gboolean active;
};

struct _entitasIndex {
	gint value;
	gint limit;
	gboolean vertical;
};

struct _entitasLayer {
	gint value;
};

struct _entitasPosition {
	gdouble x;
	gdouble y;
};

struct _entitasScale {
	gdouble x;
	gdouble y;
};

struct _entitasSprite {
	sdxgraphicsSprite* sprite;
	gint width;
	gint height;
};

struct _entitasText {
	gchar* text;
	sdxgraphicsSprite* sprite;
};

struct _entitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _entitasTween {
	gdouble min;
	gdouble max;
	gdouble speed;
	gboolean repeat;
	gboolean active;
};

struct _entitasVelocity {
	gdouble x;
	gdouble y;
};

struct _entitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	entitasBackground* background;
	SDL_Rect* bounds;
	entitasBullet* bullet;
	entitasEnemy1* enemy1;
	entitasEnemy2* enemy2;
	entitasEnemy3* enemy3;
	entitasExpires* expires;
	entitasHealth* health;
	entitasHud* hud;
	entitasIndex* index;
	entitasLayer* layer;
	entitasPosition* position;
	entitasScale* scale;
	entitasSprite* sprite;
	entitasText* text;
	entitasTint* tint;
	entitasTween* tween;
	entitasVelocity* velocity;
};

struct _systemsInputSystem {
	gint _retainCount;
	Game* game;
	Factory* world;
	entitasEntity* player;
	gdouble timeToFire;
	gboolean shoot;
};

typedef void (*entitasSystemInitialize) (void* user_data);
typedef void (*entitasSystemExecute) (gdouble delta, void* user_data);
struct _entitasISystem {
	entitasSystemInitialize initialize;
	gpointer initialize_target;
	entitasSystemExecute execute;
	gpointer execute_target;
};


extern gdouble sdx_mouseX;
extern gdouble sdx_mouseY;
extern gboolean sdx_mouseDown;
extern guint8* sdx_keys;
extern gint sdx_keys_length1;

void systems_input_system_free (systemsInputSystem* self);
void game_free (Game* self);
void entitas_world_free (entitasWorld* self);
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_background_get_type (void) G_GNUC_CONST;
entitasBackground* entitas_background_dup (const entitasBackground* self);
void entitas_background_free (entitasBackground* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
entitasBullet* entitas_bullet_dup (const entitasBullet* self);
void entitas_bullet_free (entitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self);
void entitas_enemy1_free (entitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self);
void entitas_enemy2_free (entitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self);
void entitas_enemy3_free (entitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
entitasExpires* entitas_expires_dup (const entitasExpires* self);
void entitas_expires_free (entitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
entitasHealth* entitas_health_dup (const entitasHealth* self);
void entitas_health_free (entitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
entitasHud* entitas_hud_dup (const entitasHud* self);
void entitas_hud_free (entitasHud* self);
GType entitas_index_get_type (void) G_GNUC_CONST;
entitasIndex* entitas_index_dup (const entitasIndex* self);
void entitas_index_free (entitasIndex* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
entitasLayer* entitas_layer_dup (const entitasLayer* self);
void entitas_layer_free (entitasLayer* self);
GType entitas_position_get_type (void) G_GNUC_CONST;
entitasPosition* entitas_position_dup (const entitasPosition* self);
void entitas_position_free (entitasPosition* self);
GType entitas_scale_get_type (void) G_GNUC_CONST;
entitasScale* entitas_scale_dup (const entitasScale* self);
void entitas_scale_free (entitasScale* self);
GType entitas_sprite_get_type (void) G_GNUC_CONST;
void sdx_graphics_sprite_free (sdxgraphicsSprite* self);
entitasSprite* entitas_sprite_dup (const entitasSprite* self);
void entitas_sprite_free (entitasSprite* self);
void entitas_sprite_copy (const entitasSprite* self, entitasSprite* dest);
void entitas_sprite_destroy (entitasSprite* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
entitasText* entitas_text_dup (const entitasText* self);
void entitas_text_free (entitasText* self);
void entitas_text_copy (const entitasText* self, entitasText* dest);
void entitas_text_destroy (entitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
entitasTint* entitas_tint_dup (const entitasTint* self);
void entitas_tint_free (entitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
entitasTween* entitas_tween_dup (const entitasTween* self);
void entitas_tween_free (entitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
entitasVelocity* entitas_velocity_dup (const entitasVelocity* self);
void entitas_velocity_free (entitasVelocity* self);
entitasEntity* entitas_entity_dup (const entitasEntity* self);
void entitas_entity_free (entitasEntity* self);
void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest);
void entitas_entity_destroy (entitasEntity* self);
static void systems_input_system_instance_init (systemsInputSystem * self);
#define SYSTEMS_INPUT_SYSTEM_FIRE_RATE 0.1
systemsInputSystem* systems_input_system_retain (systemsInputSystem* self);
void systems_input_system_release (systemsInputSystem* self);
void systems_input_system_free (systemsInputSystem* self);
systemsInputSystem* systems_input_system_new (Game* game, Factory* world);
void systems_input_system_initialize (systemsInputSystem* self);
entitasEntity* factory_createPlayer (Factory* self);
void systems_input_system_execute (systemsInputSystem* self, gdouble delta);
entitasEntity* entitas_entity_setPosition (entitasEntity *self, gdouble x, gdouble y);
entitasEntity* factory_bullet (Factory* self, gint x, gint y);
GType entitas_isystem_get_type (void) G_GNUC_CONST;
entitasISystem* entitas_isystem_dup (const entitasISystem* self);
void entitas_isystem_free (entitasISystem* self);
entitasISystem systems_input_system_get__ISystem (systemsInputSystem* self);
static void _systems_input_system_initialize_entitas_system_initialize (gpointer self);
static void _systems_input_system_execute_entitas_system_execute (gdouble delta, gpointer self);


systemsInputSystem* systems_input_system_retain (systemsInputSystem* self) {
	systemsInputSystem* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void systems_input_system_release (systemsInputSystem* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		systems_input_system_free (self);
	}
}


static gpointer _game_retain0 (gpointer self) {
	return self ? game_retain (self) : NULL;
}


static gpointer _entitas_world_retain0 (gpointer self) {
	return self ? entitas_world_retain (self) : NULL;
}


systemsInputSystem* systems_input_system_new (Game* game, Factory* world) {
	systemsInputSystem* self;
	Game* _tmp0_ = NULL;
	Game* _tmp1_ = NULL;
	Factory* _tmp2_ = NULL;
	Factory* _tmp3_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	g_return_val_if_fail (world != NULL, NULL);
	self = g_slice_new0 (systemsInputSystem);
	systems_input_system_instance_init (self);
	_tmp0_ = game;
	_tmp1_ = _game_retain0 (_tmp0_);
	_game_release0 (self->game);
	self->game = _tmp1_;
	_tmp2_ = world;
	_tmp3_ = _entitas_world_retain0 (_tmp2_);
	_entitas_world_release0 (self->world);
	self->world = _tmp3_;
	return self;
}


void systems_input_system_initialize (systemsInputSystem* self) {
	Factory* _tmp0_ = NULL;
	entitasEntity* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->world;
	_tmp1_ = factory_createPlayer (_tmp0_);
	self->player = _tmp1_;
}


/**
 * get player input
 */
void systems_input_system_execute (systemsInputSystem* self, gdouble delta) {
	gint x = 0;
	gdouble _tmp0_ = 0.0;
	gint y = 0;
	gdouble _tmp1_ = 0.0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	entitasEntity* _tmp4_ = NULL;
	SDL_Rect* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	entitasEntity* _tmp7_ = NULL;
	SDL_Rect* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp11_ = FALSE;
	gboolean _tmp14_ = FALSE;
	gdouble _tmp17_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = sdx_mouseX;
	x = (gint) _tmp0_;
	_tmp1_ = sdx_mouseY;
	y = (gint) _tmp1_;
	_tmp2_ = x;
	_tmp3_ = y;
	entitas_entity_setPosition (self->player, (gdouble) _tmp2_, (gdouble) _tmp3_);
	_tmp4_ = self->player;
	_tmp5_ = (*_tmp4_).bounds;
	_tmp6_ = x;
	(*_tmp5_).x = _tmp6_;
	_tmp7_ = self->player;
	_tmp8_ = (*_tmp7_).bounds;
	_tmp9_ = y;
	(*_tmp8_).y = _tmp9_;
	_tmp11_ = sdx_mouseDown;
	if (_tmp11_) {
		_tmp10_ = TRUE;
	} else {
		guint8* _tmp12_ = NULL;
		gint _tmp12__length1 = 0;
		guint8 _tmp13_ = 0U;
		_tmp12_ = sdx_keys;
		_tmp12__length1 = sdx_keys_length1;
		_tmp13_ = _tmp12_[122];
		_tmp10_ = ((gint) _tmp13_) == 1;
	}
	self->shoot = _tmp10_;
	_tmp14_ = self->shoot;
	if (_tmp14_) {
		gdouble _tmp15_ = 0.0;
		gdouble _tmp16_ = 0.0;
		_tmp15_ = self->timeToFire;
		_tmp16_ = delta;
		self->timeToFire = _tmp15_ - _tmp16_;
	}
	_tmp17_ = self->timeToFire;
	if (_tmp17_ < 0.0) {
		Factory* _tmp18_ = NULL;
		gint _tmp19_ = 0;
		gint _tmp20_ = 0;
		Factory* _tmp21_ = NULL;
		gint _tmp22_ = 0;
		gint _tmp23_ = 0;
		_tmp18_ = self->world;
		_tmp19_ = x;
		_tmp20_ = y;
		factory_bullet (_tmp18_, _tmp19_ + 27, _tmp20_ + 2);
		_tmp21_ = self->world;
		_tmp22_ = x;
		_tmp23_ = y;
		factory_bullet (_tmp21_, _tmp22_ - 27, _tmp23_ + 2);
		self->timeToFire = SYSTEMS_INPUT_SYSTEM_FIRE_RATE;
	}
}


static void _systems_input_system_initialize_entitas_system_initialize (gpointer self) {
	systems_input_system_initialize ((systemsInputSystem*) self);
}


static void _systems_input_system_execute_entitas_system_execute (gdouble delta, gpointer self) {
	systems_input_system_execute ((systemsInputSystem*) self, delta);
}


entitasISystem systems_input_system_get__ISystem (systemsInputSystem* self) {
	entitasISystem result;
	entitasISystem _tmp0_ = {0};
	_tmp0_.initialize = _systems_input_system_initialize_entitas_system_initialize;
	_tmp0_.initialize_target = self;
	_tmp0_.execute = _systems_input_system_execute_entitas_system_execute;
	_tmp0_.execute_target = self;
	result = _tmp0_;
	return result;
}


static void systems_input_system_instance_init (systemsInputSystem * self) {
	self->_retainCount = 1;
	self->timeToFire = 0.0;
}


void systems_input_system_free (systemsInputSystem* self) {
	_game_release0 (self->game);
	_entitas_world_release0 (self->world);
	g_slice_free (systemsInputSystem, self);
}



