/* graphics.c generated by valac 0.34.8, the Vala compiler
 * generated from graphics.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_rect.h>
#include <SDL2/SDL_render.h>
#include <string.h>


#define SDX_GRAPHICS_TYPE_BLIT (sdx_graphics_blit_get_type ())
typedef struct _sdxgraphicsBlit sdxgraphicsBlit;

struct _sdxgraphicsBlit {
	SDL_Rect source;
	SDL_Rect dest;
	SDL_RendererFlip flip;
};

typedef sdxgraphicsBlit* (*sdxgraphicsCompositor) (gint x, gint y, int* result_length1, void* user_data);


GType sdx_graphics_blit_get_type (void) G_GNUC_CONST;
sdxgraphicsBlit* sdx_graphics_blit_dup (const sdxgraphicsBlit* self);
void sdx_graphics_blit_free (sdxgraphicsBlit* self);


sdxgraphicsBlit* sdx_graphics_blit_dup (const sdxgraphicsBlit* self) {
	sdxgraphicsBlit* dup;
	dup = g_new0 (sdxgraphicsBlit, 1);
	memcpy (dup, self, sizeof (sdxgraphicsBlit));
	return dup;
}


void sdx_graphics_blit_free (sdxgraphicsBlit* self) {
	g_free (self);
}


GType sdx_graphics_blit_get_type (void) {
	static volatile gsize sdx_graphics_blit_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_graphics_blit_type_id__volatile)) {
		GType sdx_graphics_blit_type_id;
		sdx_graphics_blit_type_id = g_boxed_type_register_static ("sdxgraphicsBlit", (GBoxedCopyFunc) sdx_graphics_blit_dup, (GBoxedFreeFunc) sdx_graphics_blit_free);
		g_once_init_leave (&sdx_graphics_blit_type_id__volatile, sdx_graphics_blit_type_id);
	}
	return sdx_graphics_blit_type_id__volatile;
}



