/* Texture.c generated by valac 0.34.8, the Vala compiler
 * generated from Texture.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_surface.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_rwops.h>
#include <SDL2/SDL_image.h>

typedef struct _sdxgraphicsTexture sdxgraphicsTexture;
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _sdxfilesFileHandle sdxfilesFileHandle;
#define _SDL_FreeRW0(var) ((var == NULL) ? NULL : (var = (SDL_FreeRW (var), NULL)))

struct _sdxgraphicsTexture {
	gint _retainCount;
	SDL_Surface* data;
	gchar* path;
};

typedef enum  {
	SDX_SDL_EXCEPTION_Initialization,
	SDX_SDL_EXCEPTION_ImageInitialization,
	SDX_SDL_EXCEPTION_TtfInitialization,
	SDX_SDL_EXCEPTION_TextureFilteringNotEnabled,
	SDX_SDL_EXCEPTION_OpenWindow,
	SDX_SDL_EXCEPTION_CreateRenderer,
	SDX_SDL_EXCEPTION_InvalidForPlatform,
	SDX_SDL_EXCEPTION_UnableToLoadResource,
	SDX_SDL_EXCEPTION_UnableToLoadSurface,
	SDX_SDL_EXCEPTION_UnableToLoadTexture,
	SDX_SDL_EXCEPTION_NullPointer,
	SDX_SDL_EXCEPTION_NoSuchElement,
	SDX_SDL_EXCEPTION_IllegalStateException,
	SDX_SDL_EXCEPTION_RuntimeException,
	SDX_SDL_EXCEPTION_NotReached
} sdxSdlException;
#define SDX_SDL_EXCEPTION sdx_sdl_exception_quark ()


void sdx_graphics_texture_free (sdxgraphicsTexture* self);
static void sdx_graphics_texture_instance_init (sdxgraphicsTexture * self);
sdxgraphicsTexture* sdx_graphics_texture_retain (sdxgraphicsTexture* self);
void sdx_graphics_texture_release (sdxgraphicsTexture* self);
void sdx_graphics_texture_free (sdxgraphicsTexture* self);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxgraphicsTexture* sdx_graphics_texture_new (sdxfilesFileHandle* file);
gchar* sdx_files_file_handle_getPath (sdxfilesFileHandle* self);
SDL_RWops* sdx_files_file_handle_getRWops (sdxfilesFileHandle* self);
SDL_Surface* sdx_graphics_texture_getSurface (const gchar* ext, SDL_RWops* raw);
gchar* sdx_files_file_handle_getExt (sdxfilesFileHandle* self);
void sdx_graphics_texture_setFilter (sdxgraphicsTexture* self, gint minFilter, gint magFilter);
void sdx_graphics_texture_setWrap (sdxgraphicsTexture* self, gint u, gint v);
GQuark sdx_sdl_exception_quark (void);
gint sdx_graphics_texture_get_width (sdxgraphicsTexture* self);
gint sdx_graphics_texture_get_height (sdxgraphicsTexture* self);


sdxgraphicsTexture* sdx_graphics_texture_retain (sdxgraphicsTexture* self) {
	sdxgraphicsTexture* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_texture_release (sdxgraphicsTexture* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_texture_free (self);
	}
}


sdxgraphicsTexture* sdx_graphics_texture_new (sdxfilesFileHandle* file) {
	sdxgraphicsTexture* self;
	sdxfilesFileHandle* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	SDL_RWops* raw = NULL;
	sdxfilesFileHandle* _tmp2_ = NULL;
	SDL_RWops* _tmp3_ = NULL;
	sdxfilesFileHandle* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	SDL_Surface* _tmp7_ = NULL;
	g_return_val_if_fail (file != NULL, NULL);
	self = g_slice_new0 (sdxgraphicsTexture);
	sdx_graphics_texture_instance_init (self);
	_tmp0_ = file;
	_tmp1_ = sdx_files_file_handle_getPath (_tmp0_);
	_g_free0 (self->path);
	self->path = _tmp1_;
	_tmp2_ = file;
	_tmp3_ = sdx_files_file_handle_getRWops (_tmp2_);
	raw = _tmp3_;
	_tmp4_ = file;
	_tmp5_ = sdx_files_file_handle_getExt (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = sdx_graphics_texture_getSurface (_tmp6_, raw);
	_SDL_FreeSurface0 (self->data);
	self->data = _tmp7_;
	_g_free0 (_tmp6_);
	_SDL_FreeRW0 (raw);
	return self;
}


void sdx_graphics_texture_setFilter (sdxgraphicsTexture* self, gint minFilter, gint magFilter) {
	g_return_if_fail (self != NULL);
}


void sdx_graphics_texture_setWrap (sdxgraphicsTexture* self, gint u, gint v) {
	g_return_if_fail (self != NULL);
}


/**
         *  Load a Surface from raw memory
         *
         * @param ext file extension (encoding)
         * @param raw RWops memory ptr
         * @param the new Surface
         */
SDL_Surface* sdx_graphics_texture_getSurface (const gchar* ext, SDL_RWops* raw) {
	SDL_Surface* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	static GQuark _tmp2_label2 = 0;
	static GQuark _tmp2_label3 = 0;
	static GQuark _tmp2_label4 = 0;
	static GQuark _tmp2_label5 = 0;
	static GQuark _tmp2_label6 = 0;
	static GQuark _tmp2_label7 = 0;
	static GQuark _tmp2_label8 = 0;
	static GQuark _tmp2_label9 = 0;
	static GQuark _tmp2_label10 = 0;
	static GQuark _tmp2_label11 = 0;
	static GQuark _tmp2_label12 = 0;
	static GQuark _tmp2_label13 = 0;
	static GQuark _tmp2_label14 = 0;
	const gchar* _tmp34_ = NULL;
	GError* _tmp35_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (ext != NULL, NULL);
	g_return_val_if_fail (raw != NULL, NULL);
	_tmp0_ = ext;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string (".cur")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp4_ = NULL;
				SDL_Surface* _tmp5_ = NULL;
				_tmp4_ = raw;
				_tmp5_ = IMG_LoadCUR_RW (_tmp4_);
				result = _tmp5_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string (".ico")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp6_ = NULL;
				SDL_Surface* _tmp7_ = NULL;
				_tmp6_ = raw;
				_tmp7_ = IMG_LoadICO_RW (_tmp6_);
				result = _tmp7_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string (".bmp")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp8_ = NULL;
				SDL_Surface* _tmp9_ = NULL;
				_tmp8_ = raw;
				_tmp9_ = IMG_LoadBMP_RW (_tmp8_);
				result = _tmp9_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label3) ? _tmp2_label3 : (_tmp2_label3 = g_quark_from_static_string (".pnm")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp10_ = NULL;
				SDL_Surface* _tmp11_ = NULL;
				_tmp10_ = raw;
				_tmp11_ = IMG_LoadPNM_RW (_tmp10_);
				result = _tmp11_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label4) ? _tmp2_label4 : (_tmp2_label4 = g_quark_from_static_string (".xpm")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp12_ = NULL;
				SDL_Surface* _tmp13_ = NULL;
				_tmp12_ = raw;
				_tmp13_ = IMG_LoadXPM_RW (_tmp12_);
				result = _tmp13_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label5) ? _tmp2_label5 : (_tmp2_label5 = g_quark_from_static_string (".xcf")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp14_ = NULL;
				SDL_Surface* _tmp15_ = NULL;
				_tmp14_ = raw;
				_tmp15_ = IMG_LoadXCF_RW (_tmp14_);
				result = _tmp15_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label6) ? _tmp2_label6 : (_tmp2_label6 = g_quark_from_static_string (".pvx")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp16_ = NULL;
				SDL_Surface* _tmp17_ = NULL;
				_tmp16_ = raw;
				_tmp17_ = IMG_LoadPCX_RW (_tmp16_);
				result = _tmp17_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label7) ? _tmp2_label7 : (_tmp2_label7 = g_quark_from_static_string (".gif")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp18_ = NULL;
				SDL_Surface* _tmp19_ = NULL;
				_tmp18_ = raw;
				_tmp19_ = IMG_LoadGIF_RW (_tmp18_);
				result = _tmp19_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label8) ? _tmp2_label8 : (_tmp2_label8 = g_quark_from_static_string (".jpg")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp20_ = NULL;
				SDL_Surface* _tmp21_ = NULL;
				_tmp20_ = raw;
				_tmp21_ = IMG_LoadJPG_RW (_tmp20_);
				result = _tmp21_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label9) ? _tmp2_label9 : (_tmp2_label9 = g_quark_from_static_string (".tif")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp22_ = NULL;
				SDL_Surface* _tmp23_ = NULL;
				_tmp22_ = raw;
				_tmp23_ = IMG_LoadTIF_RW (_tmp22_);
				result = _tmp23_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label10) ? _tmp2_label10 : (_tmp2_label10 = g_quark_from_static_string (".png")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp24_ = NULL;
				SDL_Surface* _tmp25_ = NULL;
				_tmp24_ = raw;
				_tmp25_ = IMG_LoadPNG_RW (_tmp24_);
				result = _tmp25_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label11) ? _tmp2_label11 : (_tmp2_label11 = g_quark_from_static_string (".tga")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp26_ = NULL;
				SDL_Surface* _tmp27_ = NULL;
				_tmp26_ = raw;
				_tmp27_ = IMG_LoadTGA_RW (_tmp26_);
				result = _tmp27_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label12) ? _tmp2_label12 : (_tmp2_label12 = g_quark_from_static_string (".lbm")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp28_ = NULL;
				SDL_Surface* _tmp29_ = NULL;
				_tmp28_ = raw;
				_tmp29_ = IMG_LoadLBM_RW (_tmp28_);
				result = _tmp29_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label13) ? _tmp2_label13 : (_tmp2_label13 = g_quark_from_static_string (".xv")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp30_ = NULL;
				SDL_Surface* _tmp31_ = NULL;
				_tmp30_ = raw;
				_tmp31_ = IMG_LoadXV_RW (_tmp30_);
				result = _tmp31_;
				return result;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label14) ? _tmp2_label14 : (_tmp2_label14 = g_quark_from_static_string (".webp")))) {
		switch (0) {
			default:
			{
				SDL_RWops* _tmp32_ = NULL;
				SDL_Surface* _tmp33_ = NULL;
				_tmp32_ = raw;
				_tmp33_ = IMG_LoadWEBP_RW (_tmp32_);
				result = _tmp33_;
				return result;
			}
		}
	}
	_tmp34_ = ext;
	_tmp35_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_UnableToLoadSurface, _tmp34_);
	_inner_error_ = _tmp35_;
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
	result = NULL;
	return result;
}


gint sdx_graphics_texture_get_width (sdxgraphicsTexture* self) {
	gint result;
	SDL_Surface* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->data;
	_tmp1_ = _tmp0_->w;
	result = _tmp1_;
	return result;
}


gint sdx_graphics_texture_get_height (sdxgraphicsTexture* self) {
	gint result;
	SDL_Surface* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->data;
	_tmp1_ = _tmp0_->h;
	result = _tmp1_;
	return result;
}


static void sdx_graphics_texture_instance_init (sdxgraphicsTexture * self) {
	self->_retainCount = 1;
}


void sdx_graphics_texture_free (sdxgraphicsTexture* self) {
	_SDL_FreeSurface0 (self->data);
	_g_free0 (self->path);
	g_slice_free (sdxgraphicsTexture, self);
}



